function $(id){return document.getElementById(id)}
function txt(id,fallback="—"){return $(id)?.textContent?.trim()||fallback}
function val(id,fallback=""){return $(id)?.value?.trim()||fallback}
function esc(s=""){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function empresa(){const resumo=$("empresaContextoResumo")?.textContent?.trim();if(resumo)return resumo;const select=$("empresaContexto");if(select?.selectedOptions?.length)return[...select.selectedOptions].map(o=>o.textContent.trim()).join(", ");return"Empresa selecionada"}
function competencia(){const c=val("prestacaoCompetencia");return c?c.split("-").reverse().join("/"):"—"}
function centro(){return $("prestacaoCentro")?.selectedOptions?.[0]?.textContent?.trim()||"Consolidado"}
function dados(){const desv=[...document.querySelectorAll("#prestacaoDesvios [data-prestacao-conta]")].map(el=>{const spans=[...el.querySelectorAll(":scope > span")];return{conta:spans[0]?.innerText?.trim()||"Conta",budget:spans[1]?.innerText?.trim()||"—",real:spans[2]?.innerText?.trim()||"—",variacao:spans[3]?.innerText?.trim()||"—",comentario:el.querySelector("textarea")?.value?.trim()||"Sem comentário"}});return{empresa:empresa(),competencia:competencia(),centro:centro(),resumo:val("prestacaoResumoExecutivo","Sem comentário executivo registrado."),acoes:val("prestacaoAcoes","Sem ações registradas."),kpis:[["Receita",txt("prestacaoReceita"),txt("prestacaoReceitaVar")],["OPEX",txt("prestacaoOpex"),txt("prestacaoOpexVar")],["Resultado",txt("prestacaoResultado"),txt("prestacaoResultadoVar")],["CAPEX",txt("prestacaoCapex"),txt("prestacaoCapexVar")]],desvios:desv}}
function mensagem(t,ok=false){const el=$("prestacaoMensagem");if(!el)return;el.textContent=t;el.classList.toggle("sucesso",ok)}
function printable(d){const rows=d.desvios.length?d.desvios.map(x=>`<tr><td>${esc(x.conta)}</td><td>${esc(x.budget)}</td><td>${esc(x.real)}</td><td>${esc(x.variacao)}</td><td>${esc(x.comentario)}</td></tr>`).join(""):'<tr><td colspan="5">Sem desvios relevantes</td></tr>';const w=window.open("","_blank","noopener,noreferrer");if(!w)throw new Error("popup_blocked");w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Prestação de Contas</title><style>@page{size:A4;margin:16mm}body{font-family:Arial,sans-serif;color:#0b1f33;font-size:11px}header{border-bottom:4px solid #0c9488;padding-bottom:12px;margin-bottom:18px}h1{font-size:24px;margin:0 0 6px}h2{font-size:15px;margin:20px 0 8px}.meta{color:#667085}.kpis{display:grid;grid-template-columns:1fr 1fr;gap:8px}.card{border:1px solid #d0d5dd;border-radius:8px;padding:10px}.card strong{display:block;font-size:16px;margin:5px 0}table{width:100%;border-collapse:collapse;font-size:9px}th,td{border:1px solid #d0d5dd;padding:6px;text-align:left;vertical-align:top}th{background:#0b1f33;color:white}p{line-height:1.45;white-space:pre-wrap}</style></head><body><header><h1>PRESTAÇÃO DE CONTAS</h1><div class="meta">${esc(d.empresa)} · ${esc(d.competencia)} · ${esc(d.centro)}</div></header><div class="kpis">${d.kpis.map(k=>`<div class="card"><span>${esc(k[0])}</span><strong>${esc(k[1])}</strong><small>${esc(k[2])}</small></div>`).join("")}</div><h2>Resumo executivo</h2><p>${esc(d.resumo)}</p><h2>Principais desvios</h2><table><thead><tr><th>Conta</th><th>Budget</th><th>Realizado</th><th>Δ</th><th>Comentário</th></tr></thead><tbody>${rows}</tbody></table><h2>Ações, riscos e próximos passos</h2><p>${esc(d.acoes)}</p><script>window.onload=()=>setTimeout(()=>window.print(),200)<\/script></body></html>`);w.document.close()}
function addWrapped(doc,text,x,y,width,lineHeight=4){const lines=doc.splitTextToSize(String(text||"—"),width);for(const line of lines){if(y>282){doc.addPage();y=18}doc.text(line,x,y);y+=lineHeight}return y}
async function gerar(){const d=dados();mensagem("Gerando PDF executivo...");try{const mod=await import("https://cdn.jsdelivr.net/npm/jspdf@2.5.2/+esm");const jsPDF=mod.jsPDF||mod.default?.jsPDF||mod.default;if(!jsPDF)throw new Error("jspdf_unavailable");const doc=new jsPDF({orientation:"portrait",unit:"mm",format:"a4"});const navy=[11,31,51],teal=[12,148,136],gray=[102,112,133];doc.setFillColor(...navy);doc.rect(0,0,210,30,"F");doc.setFillColor(...teal);doc.rect(0,0,6,30,"F");doc.setTextColor(255);doc.setFont("helvetica","bold");doc.setFontSize(18);doc.text("PRESTAÇÃO DE CONTAS",14,14);doc.setFont("helvetica","normal");doc.setFontSize(9);doc.text(`${d.empresa} · ${d.competencia} · ${d.centro}`,14,22);let y=42;doc.setTextColor(...navy);for(let i=0;i<d.kpis.length;i++){const k=d.kpis[i],x=14+(i%2)*92,yy=y+Math.floor(i/2)*25;doc.setDrawColor(215,225,230);doc.roundedRect(x,yy,86,20,2,2,"S");doc.setTextColor(...gray);doc.setFontSize(7);doc.text(k[0],x+4,yy+5);doc.setTextColor(...navy);doc.setFont("helvetica","bold");doc.setFontSize(11);doc.text(k[1],x+4,yy+11);doc.setFont("helvetica","normal");doc.setFontSize(7);doc.setTextColor(...teal);doc.text(k[2],x+4,yy+16)}y+=58;doc.setTextColor(...navy);doc.setFont("helvetica","bold");doc.setFontSize(11);doc.text("Resumo executivo",14,y);y+=6;doc.setFont("helvetica","normal");doc.setFontSize(8.5);doc.setTextColor(...gray);y=addWrapped(doc,d.resumo,14,y,182,4);y+=6;doc.setTextColor(...navy);doc.setFont("helvetica","bold");doc.setFontSize(11);doc.text("Principais desvios",14,y);y+=7;doc.setFontSize(7.5);for(const x of (d.desvios.length?d.desvios:[{conta:"Sem desvios relevantes",budget:"—",real:"—",variacao:"—",comentario:"—"}])){if(y>270){doc.addPage();y=18}doc.setTextColor(...navy);doc.setFont("helvetica","bold");y=addWrapped(doc,x.conta,14,y,70,3.6);doc.setFont("helvetica","normal");doc.setTextColor(...gray);doc.text(`Budget ${x.budget} · Real ${x.real} · Δ ${x.variacao}`,14,y);y+=4;y=addWrapped(doc,x.comentario,14,y,182,3.6);y+=5;doc.setDrawColor(230,235,238);doc.line(14,y-2,196,y-2)}if(y>245){doc.addPage();y=18}doc.setTextColor(...navy);doc.setFont("helvetica","bold");doc.setFontSize(11);doc.text("Ações, riscos e próximos passos",14,y);y+=6;doc.setFont("helvetica","normal");doc.setFontSize(8.5);doc.setTextColor(...gray);addWrapped(doc,d.acoes,14,y,182,4);const nome=`prestacao_contas_${String(val("prestacaoCompetencia")||"periodo")}.pdf`;doc.save(nome);mensagem("PDF gerado.",true)}catch(e){console.warn("PDF via jsPDF indisponível; usando impressão do navegador.",e);try{printable(d);mensagem("Versão para PDF aberta. Escolha “Salvar como PDF” na impressão.",true)}catch(err){console.error(err);mensagem("Não foi possível abrir o PDF. Libere pop-ups para este site e tente novamente.")}}}
document.addEventListener("click",e=>{const b=e.target.closest?.("#btnGerarPrestacaoPdf");if(!b)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();gerar()},true);
