import { $, on, esc, norm, msg, state, permite, admin, abrirPagina } from "./core.js";
import { db, moeda, dataBr, hojeIso, competenciaAtual, grupoAtualId, preencherEmpresaSelect, listarDocumentos, criarDocumento, atualizarDocumento, emitirAlteracao, abrirBox, fecharBox, nomeEmpresa, mensagemErroDados } from "./shared.js";
import { doc, setDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";
import { confirmarAcaoAdministrativa, atualizarComAuditoria, excluirComAuditoria } from "./admin-actions.js";
import { projetarContasPagar, idBaixa, primeiroDiaCompetencia, ultimoDiaCompetencia, addMesesCompetencia, hojeLocal } from "./accounts-payable-core.js";

let fixos=[],contratos=[],baixas=[],itens=[],editId=null,itemBaixa=null,busy=false;
const podeVer=()=>permite("contasPagar","visualizar")||permite("contasPagar","cadastrar")||permite("contasPagar","editar")||permite("contasPagar","baixar");
const podeCadastrar=()=>permite("contasPagar","cadastrar")||permite("contasPagar","editar");
const podeEditar=()=>permite("contasPagar","editar");
const podeBaixar=()=>permite("contasPagar","baixar")||permite("contasPagar","editar");
const n=v=>{const x=Number(v||0);return Number.isFinite(x)?x:0};
const hoje=()=>hojeLocal();

function montar(){
  if($("pagina-contasPagar"))return;
  const main=document.querySelector("main.conteudo");if(!main)return;
  const p=document.createElement("section");p.id="pagina-contasPagar";p.className="pagina hidden";p.innerHTML=`
    <div class="pagina-cabecalho"><div><span class="eyebrow">TESOURARIA OPERACIONAL</span><h2>Contas a Pagar</h2><p>Cockpit independente para compromissos fixos, vencimentos e baixas. Não alimenta DRE, Budget ou Forecast.</p></div><div class="cp-head-actions"><button id="cpAtualizar" class="btn-secundario" type="button">Atualizar</button><button id="cpNovoFixo" class="btn-primario" type="button">+ Compromisso fixo</button></div></div>
    <div class="cp-filtros lista-card"><div class="form-grid form-grid-3"><div class="campo"><label for="cpCompetencia">Competência</label><input id="cpCompetencia" type="month"></div><div class="campo"><label for="cpFiltro">Visão</label><select id="cpFiltro"><option value="pendentes">Pendentes + vencidos</option><option value="mes">Mês selecionado</option><option value="vencidos">Somente vencidos</option><option value="proximos">Próximos 7 dias</option><option value="pagos">Pagos</option><option value="todos">Todos</option></select></div><div class="campo"><label for="cpBusca">Buscar</label><input id="cpBusca" type="search" placeholder="Fornecedor ou descrição"></div></div></div>
    <div class="kpi-grid kpi-grid-4 cp-kpis"><div class="kpi-card cp-kpi-alerta"><span>Vencidos</span><strong id="cpVencidos">—</strong><small id="cpVencidosQtd">—</small></div><div class="kpi-card"><span>Próximos 7 dias</span><strong id="cpProximos7">—</strong><small id="cpProximos7Qtd">—</small></div><div class="kpi-card"><span>Em aberto no mês</span><strong id="cpAbertoMes">—</strong><small id="cpAbertoMesQtd">—</small></div><div class="kpi-card"><span>Pagos no mês</span><strong id="cpPagosMes">—</strong><small id="cpPagosMesQtd">—</small></div></div>
    <section class="lista-card"><div class="lista-cabecalho"><div><h3>Agenda de pagamentos</h3><p id="cpResumoAgenda">Carregando...</p></div><span class="mesa-tag">Cockpit</span></div><div class="tabela-container"><table class="tabela cp-tabela"><thead><tr><th>Vencimento</th><th>Fornecedor / compromisso</th><th>Origem</th><th>Empresa</th><th>Valor</th><th>Status</th><th>Ações</th></tr></thead><tbody id="cpLista"><tr><td colspan="7">Carregando...</td></tr></tbody></table></div></section>
    <section id="cpFormFixoBox" class="form-card hidden"><div class="form-card-titulo"><div><h3 id="cpFormTitulo">Novo compromisso fixo</h3><p>Cadastre obrigações recorrentes mensais. Elas existem apenas neste cockpit.</p></div></div><form id="cpFormFixo"><div class="form-grid form-grid-3"><div class="campo"><label for="cpEmpresa">Empresa</label><select id="cpEmpresa" required></select></div><div class="campo"><label for="cpFornecedor">Fornecedor / favorecido</label><input id="cpFornecedor" required></div><div class="campo"><label for="cpCategoria">Categoria operacional</label><input id="cpCategoria" placeholder="Ex.: aluguel, internet, condomínio"></div><div class="campo campo-span-2"><label for="cpDescricao">Descrição</label><input id="cpDescricao" required placeholder="Ex.: Aluguel da unidade"></div><div class="campo"><label for="cpValor">Valor mensal</label><input id="cpValor" type="number" min="0.01" step="0.01" required></div><div class="campo"><label for="cpDia">Dia do vencimento</label><input id="cpDia" type="number" min="1" max="31" required></div><div class="campo"><label for="cpInicio">Início</label><input id="cpInicio" type="date" required></div><div class="campo"><label for="cpFim">Fim (opcional)</label><input id="cpFim" type="date"></div><div class="campo campo-span-3"><label for="cpObservacao">Observações</label><input id="cpObservacao"></div></div><div class="form-acoes"><button id="cpCancelarFixo" class="btn-secundario" type="button">Cancelar</button><button class="btn-primario" type="submit">Salvar compromisso</button></div><p id="cpMensagemFixo" class="mensagem-form"></p></form></section>
    <section class="lista-card"><div class="lista-cabecalho"><div><h3>Compromissos fixos manuais</h3><p>Cadastros próprios do Contas a Pagar. Contratos entram automaticamente quando estiverem habilitados para provisão e tiverem dia de pagamento.</p></div></div><div class="tabela-container"><table class="tabela"><thead><tr><th>Compromisso</th><th>Empresa</th><th>Valor</th><th>Dia</th><th>Vigência</th><th>Status</th><th>Ações</th></tr></thead><tbody id="cpFixosLista"><tr><td colspan="7">Carregando...</td></tr></tbody></table></div></section>
    <section id="cpBaixaBox" class="form-card hidden"><div class="form-card-titulo"><div><h3>Baixar pagamento</h3><p id="cpBaixaDescricao">—</p></div></div><form id="cpFormBaixa"><div class="form-grid form-grid-3"><div class="campo"><label for="cpDataPagamento">Data do pagamento</label><input id="cpDataPagamento" type="date" required></div><div class="campo"><label for="cpValorPago">Valor pago</label><input id="cpValorPago" type="number" min="0.01" step="0.01" required></div><div class="campo"><label for="cpBaixaObs">Observação</label><input id="cpBaixaObs" placeholder="Opcional"></div></div><div class="form-acoes"><button id="cpCancelarBaixa" class="btn-secundario" type="button">Cancelar</button><button class="btn-primario" type="submit">Confirmar baixa</button></div><p id="cpMensagemBaixa" class="mensagem-form"></p></form></section>`;
  main.appendChild(p);
  const st=document.createElement("style");st.id="sig-contas-pagar-css";st.textContent=`.cp-head-actions{display:flex;gap:8px;flex-wrap:wrap}.cp-filtros{margin-bottom:12px}.cp-kpis{margin:12px 0}.cp-kpi-alerta strong{color:#b42318}.cp-tabela td:nth-child(5){font-weight:850}.cp-status{display:inline-flex;padding:4px 8px;border-radius:999px;font-size:9px;font-weight:850}.cp-status.vencido{background:#fee4e2;color:#b42318}.cp-status.hoje{background:#fff3d6;color:#b54708}.cp-status.aberto{background:#eef4ff;color:#3448a5}.cp-status.pago{background:#dff7ec;color:#067647}.cp-origem{display:inline-flex;padding:3px 7px;border-radius:999px;background:#eef3f5;color:#475467;font-size:8px;font-weight:850}.cp-origem.contrato{background:#eaf4ff;color:#175cd3}.cp-pago-info{display:block;margin-top:3px;color:#667085;font-size:9px}@media(max-width:760px){.cp-head-actions{width:100%}.cp-head-actions button{flex:1}.cp-tabela{min-width:920px}}`;document.head.appendChild(st);
  on($("cpAtualizar"),"click",carregar);on($("cpNovoFixo"),"click",()=>abrirFixo());on($("cpCancelarFixo"),"click",fecharFixo);on($("cpFormFixo"),"submit",salvarFixo);on($("cpCancelarBaixa"),"click",fecharBaixa);on($("cpFormBaixa"),"submit",salvarBaixa);on($("cpCompetencia"),"change",render);on($("cpFiltro"),"change",render);on($("cpBusca"),"input",render);
  $("cpCompetencia").value=competenciaAtual();
}

function fonteContratoDisponivel(){return permite("contratos","visualizar")}
function origemLabel(x){return x.origem==="contrato"?'<span class="cp-origem contrato">Contrato</span>':'<span class="cp-origem">Fixo manual</span>'}
function statusLabel(x){if(x.status==="pago")return`<span class="cp-status pago">Pago</span><small class="cp-pago-info">${dataBr(x.baixa?.dataPagamento)} · ${moeda(x.baixa?.valorPago||x.valor)}</small>`;if(x.status==="vencido")return'<span class="cp-status vencido">Vencido</span>';if(x.status==="vence_hoje")return'<span class="cp-status hoje">Vence hoje</span>';return'<span class="cp-status aberto">Em aberto</span>'}
function seteDias(){const d=new Date();d.setDate(d.getDate()+7);return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function range(){const comp=$("cpCompetencia")?.value||competenciaAtual();return{comp,de:primeiroDiaCompetencia(addMesesCompetencia(comp,-2)),ate:ultimoDiaCompetencia(addMesesCompetencia(comp,1))}}

function itensFiltrados(){
  const {comp}=range(),f=$("cpFiltro")?.value||"pendentes",q=norm($("cpBusca")?.value),h=hoje(),d7=seteDias();return itens.filter(x=>{
    if(q&&!norm(`${x.fornecedor} ${x.descricao} ${x.numeroContrato||""}`).includes(q))return false;
    if(f==="mes")return x.competencia===comp;
    if(f==="vencidos")return x.status==="vencido";
    if(f==="proximos")return x.status!=="pago"&&x.vencimento>=h&&x.vencimento<=d7;
    if(f==="pagos")return x.status==="pago"&&x.competencia===comp;
    if(f==="pendentes")return x.status!=="pago"&&(x.competencia===comp||x.vencimento<h);
    return true;
  })}
function resumoCompetencia(){const {comp}=range(),h=hoje(),d7=seteDias(),soma=a=>a.reduce((s,x)=>s+n(x.valor),0),abertos=itens.filter(x=>x.status!=="pago"),v=abertos.filter(x=>x.vencimento<h),p7=abertos.filter(x=>x.vencimento>=h&&x.vencimento<=d7),mes=itens.filter(x=>x.competencia===comp),pagos=mes.filter(x=>x.status==="pago"),abMes=mes.filter(x=>x.status!=="pago");return{v,p7,pagos,abMes,soma}}

function render(){
  if(!podeVer())return;const r=resumoCompetencia(),arr=itensFiltrados();$("cpVencidos").textContent=moeda(r.soma(r.v));$("cpVencidosQtd").textContent=`${r.v.length} compromisso(s)`;$("cpProximos7").textContent=moeda(r.soma(r.p7));$("cpProximos7Qtd").textContent=`${r.p7.length} compromisso(s)`;$("cpAbertoMes").textContent=moeda(r.soma(r.abMes));$("cpAbertoMesQtd").textContent=`${r.abMes.length} compromisso(s)`;$("cpPagosMes").textContent=moeda(r.soma(r.pagos.map(x=>({...x,valor:n(x.baixa?.valorPago||x.valor)}))));$("cpPagosMesQtd").textContent=`${r.pagos.length} pagamento(s)`;$("cpResumoAgenda").textContent=`${arr.length} item(ns) na visão atual${fonteContratoDisponivel()?" · contratos habilitados entram automaticamente":" · sem acesso aos contratos neste perfil"}`;
  const tb=$("cpLista");if(!arr.length){tb.innerHTML='<tr><td colspan="7">Nenhum pagamento nesta visão.</td></tr>';return}tb.innerHTML=arr.map(x=>`<tr><td>${dataBr(x.vencimento)}</td><td class="celula-principal"><strong>${esc(x.fornecedor||"Favorecido")}</strong><span>${esc(x.descricao||"")}${x.numeroContrato?` · ${esc(x.numeroContrato)}`:""}</span></td><td>${origemLabel(x)}</td><td>${esc(nomeEmpresa(x.empresaId))}</td><td>${moeda(x.valor)}</td><td>${statusLabel(x)}</td><td><div class="acoes-tabela">${x.status!=="pago"&&podeBaixar()?`<button class="btn-acao destaque" data-cp-baixar="${esc(x.id)}" type="button">Baixar</button>`:""}${x.status==="pago"&&admin()?`<button class="btn-acao" data-cp-estornar="${esc(x.id)}" type="button">Estornar</button>`:""}</div></td></tr>`).join("");tb.querySelectorAll("[data-cp-baixar]").forEach(b=>on(b,"click",()=>abrirBaixa(itens.find(x=>x.id===b.dataset.cpBaixar))));tb.querySelectorAll("[data-cp-estornar]").forEach(b=>on(b,"click",()=>estornarBaixa(itens.find(x=>x.id===b.dataset.cpEstornar))));
  renderFixos();
}

function renderFixos(){const tb=$("cpFixosLista");if(!tb)return;const arr=[...fixos].sort((a,b)=>String(a.fornecedor||"").localeCompare(String(b.fornecedor||""),"pt-BR"));if(!arr.length){tb.innerHTML='<tr><td colspan="7">Nenhum compromisso fixo manual cadastrado.</td></tr>';return}tb.innerHTML=arr.map(x=>`<tr><td class="celula-principal"><strong>${esc(x.fornecedor||"Favorecido")}</strong><span>${esc(x.descricao||"")}</span></td><td>${esc(nomeEmpresa(x.empresaId))}</td><td>${moeda(x.valor)}</td><td>Dia ${Number(x.diaVencimento||0)}</td><td>${dataBr(x.inicio)}${x.fim?` → ${dataBr(x.fim)}`:" → contínuo"}</td><td><span class="${x.status==="inativo"?"status-inativo":"status-ativo"}">${x.status==="inativo"?"Inativo":"Ativo"}</span></td><td><div class="acoes-tabela">${podeEditar()?`<button class="btn-acao destaque" data-cpf-edit="${x.id}" type="button">Editar</button><button class="btn-acao" data-cpf-status="${x.id}" type="button">${x.status==="inativo"?"Reativar":"Inativar"}</button>`:""}${admin()?`<button class="btn-acao" data-cpf-del="${x.id}" type="button">Excluir</button>`:""}</div></td></tr>`).join("");tb.querySelectorAll("[data-cpf-edit]").forEach(b=>on(b,"click",()=>abrirFixo(fixos.find(x=>x.id===b.dataset.cpfEdit))));tb.querySelectorAll("[data-cpf-status]").forEach(b=>on(b,"click",()=>alternarFixo(fixos.find(x=>x.id===b.dataset.cpfStatus))));tb.querySelectorAll("[data-cpf-del]").forEach(b=>on(b,"click",()=>excluirFixo(fixos.find(x=>x.id===b.dataset.cpfDel))));}

async function carregar(){
  if(!podeVer()||busy)return;busy=true;const tb=$("cpLista");if(tb)tb.innerHTML='<tr><td colspan="7">Atualizando cockpit...</td></tr>';
  try{const tarefas=[listarDocumentos("contasPagarFixos"),listarDocumentos("contasPagarBaixas")];if(fonteContratoDisponivel())tarefas.push(listarDocumentos("contratos"));const res=await Promise.all(tarefas);fixos=res[0]||[];baixas=res[1]||[];contratos=fonteContratoDisponivel()?(res[2]||[]):[];const {de,ate}=range();itens=projetarContasPagar({fixos,contratos,baixas,de,ate,hoje:hoje()});render()}catch(e){console.error(e);if(tb)tb.innerHTML=`<tr><td colspan="7">${esc(mensagemErroDados(e,"o Contas a Pagar"))}</td></tr>`}finally{busy=false}}

async function abrirFixo(x=null){if(!(x?podeEditar():podeCadastrar()))return;editId=x?.id||null;$("cpFormFixo")?.reset();await preencherEmpresaSelect($("cpEmpresa"),{valorAtual:x?.empresaId||state.usuario?.empresaId});$("cpFormTitulo").textContent=x?"Editar compromisso fixo":"Novo compromisso fixo";$("cpFornecedor").value=x?.fornecedor||"";$("cpCategoria").value=x?.categoria||"";$("cpDescricao").value=x?.descricao||"";$("cpValor").value=x?.valor||"";$("cpDia").value=x?.diaVencimento||"";$("cpInicio").value=x?.inicio||hojeIso();$("cpFim").value=x?.fim||"";$("cpObservacao").value=x?.observacao||"";msg($("cpMensagemFixo"),"");abrirBox($("cpFormFixoBox"),$("cpFornecedor"));$("cpFormFixoBox")?.scrollIntoView({behavior:"smooth",block:"start"})}
function fecharFixo(){editId=null;fecharBox($("cpFormFixoBox"),$("cpFormFixo"),$("cpMensagemFixo"))}
async function salvarFixo(e){e.preventDefault();const d={empresaId:$("cpEmpresa").value,fornecedor:$("cpFornecedor").value.trim(),categoria:$("cpCategoria").value.trim(),descricao:$("cpDescricao").value.trim(),valor:n($("cpValor").value),diaVencimento:n($("cpDia").value),inicio:$("cpInicio").value,fim:$("cpFim").value,observacao:$("cpObservacao").value.trim(),status:fixos.find(x=>x.id===editId)?.status||"ativo"};if(!d.empresaId||!d.fornecedor||!d.descricao||!d.valor||d.diaVencimento<1||d.diaVencimento>31||!d.inicio)return msg($("cpMensagemFixo"),"Preencha empresa, favorecido, descrição, valor, início e dia de vencimento.");if(d.fim&&d.fim<d.inicio)return msg($("cpMensagemFixo"),"A data final não pode ser anterior ao início.");try{msg($("cpMensagemFixo"),"Salvando...");if(editId)await atualizarDocumento("contasPagarFixos",editId,d);else await criarDocumento("contasPagarFixos",d);msg($("cpMensagemFixo"),"Compromisso salvo.",true);emitirAlteracao("contasPagar");await carregar();setTimeout(fecharFixo,400)}catch(err){console.error(err);msg($("cpMensagemFixo"),"Não foi possível salvar o compromisso.")}}
async function alternarFixo(x){if(!x||!podeEditar())return;const status=x.status==="inativo"?"ativo":"inativo";if(!confirm(`${status==="inativo"?"Inativar":"Reativar"} ${x.descricao||x.fornecedor}?`))return;await atualizarDocumento("contasPagarFixos",x.id,{status});emitirAlteracao("contasPagar");await carregar()}
async function excluirFixo(x){if(!x||!admin())return;const possui=baixas.some(b=>b.origem==="fixo"&&b.origemId===x.id&&b.status==="pago");if(possui)return alert("Este compromisso possui histórico de pagamentos. Inative-o para preservar a rastreabilidade.");const conf=await confirmarAcaoAdministrativa({titulo:"Excluir compromisso fixo",descricao:"Exclusão física é excepcional e ficará registrada na auditoria administrativa.",confirmarTexto:"Excluir definitivamente",perigosa:true});if(!conf)return;await excluirComAuditoria({colecao:"contasPagarFixos",id:x.id,empresaId:x.empresaId,modulo:"contasPagar",motivo:conf.motivo,resumo:`Exclusão de compromisso fixo: ${x.descricao||x.fornecedor}`,snapshotAntes:x});emitirAlteracao("contasPagar");await carregar()}

function abrirBaixa(x){if(!x||!podeBaixar())return;itemBaixa=x;$("cpFormBaixa")?.reset();$("cpBaixaDescricao").textContent=`${x.fornecedor} · ${x.descricao} · vencimento ${dataBr(x.vencimento)}`;$("cpDataPagamento").value=hojeIso();$("cpValorPago").value=n(x.valor).toFixed(2);msg($("cpMensagemBaixa"),"");abrirBox($("cpBaixaBox"),$("cpDataPagamento"));$("cpBaixaBox")?.scrollIntoView({behavior:"smooth",block:"start"})}
function fecharBaixa(){itemBaixa=null;fecharBox($("cpBaixaBox"),$("cpFormBaixa"),$("cpMensagemBaixa"))}
async function salvarBaixa(e){e.preventDefault();const x=itemBaixa;if(!x)return;const valorPago=n($("cpValorPago").value),dataPagamento=$("cpDataPagamento").value;if(!valorPago||!dataPagamento)return msg($("cpMensagemBaixa"),"Informe data e valor do pagamento.");const id=idBaixa({origem:x.origem,origemId:x.origemId,competencia:x.competencia}),anterior=baixas.find(b=>b.id===id);const payload={grupoId:grupoAtualId(),empresaId:x.empresaId,origem:x.origem,origemId:x.origemId,competencia:x.competencia,vencimento:x.vencimento,fornecedor:x.fornecedor,descricao:x.descricao,valorPrevisto:x.valor,valorPago,dataPagamento,status:"pago",observacao:$("cpBaixaObs").value.trim(),automatico:x.automatico===true,atualizadoEm:serverTimestamp()};if(!anterior){payload.criadoPor=state.usuario.id;payload.criadoEm=serverTimestamp()}try{msg($("cpMensagemBaixa"),"Registrando baixa...");await setDoc(doc(db,"contasPagarBaixas",id),payload,{merge:true});emitirAlteracao("contasPagar");msg($("cpMensagemBaixa"),"Pagamento baixado.",true);await carregar();setTimeout(fecharBaixa,350)}catch(err){console.error(err);msg($("cpMensagemBaixa"),"Não foi possível registrar a baixa.")}}
async function estornarBaixa(x){if(!x?.baixa||!admin())return;const conf=await confirmarAcaoAdministrativa({titulo:"Estornar baixa",descricao:`O pagamento de ${x.fornecedor} em ${x.competencia} voltará a ficar em aberto. O histórico será preservado.`,confirmarTexto:"Estornar pagamento",perigosa:true});if(!conf)return;await atualizarComAuditoria({colecao:"contasPagarBaixas",id:x.baixa.id||x.id,empresaId:x.empresaId,modulo:"contasPagar",acao:"estorno_pagamento",motivo:conf.motivo,resumo:`Estorno de baixa: ${x.fornecedor} · ${x.competencia}`,snapshotAntes:x.baixa,alteracoes:{status:"estornado",motivoEstorno:conf.motivo,estornadoPor:state.usuario.id,estornadoPorNome:state.usuario.nome||"Administrador",estornadoEm:serverTimestamp()}});emitirAlteracao("contasPagar");await carregar()}

function exibirMenu(){const b=$("menuContasPagar");if(b)b.classList.toggle("hidden",!podeVer());$("cpNovoFixo")?.classList.toggle("hidden",!podeCadastrar())}
window.addEventListener("sig:ready",()=>{exibirMenu();if(podeVer())carregar()});window.addEventListener("sig:page",e=>{if(e.detail?.pagina==="contasPagar")carregar()});window.addEventListener("sig:empresa-changed",()=>{if(!$("pagina-contasPagar")?.classList.contains("hidden"))carregar()});window.addEventListener("sig:data-changed",e=>{if(["contasPagar","contratos"].includes(e.detail?.modulo)&&!$("pagina-contasPagar")?.classList.contains("hidden"))carregar()});

montar();exibirMenu();
export { carregar as carregarContasPagar };
