import { $, on, esc, msg, permite, moeda, dataBr, empresaAtualId, listarDocumentos, criarDocumento, atualizarDocumento } from "./shared.js";
import { exportarTabelaPdf, exportarTabelaXls } from "./export-utils.js";

const pagina=$("pagina-controladoria");
let contas=[],lancamentos=[],fixos=[],centros=[],editConta=null,editLanc=null,editFixo=null,carregadoEmpresa="";
const hoje=()=>new Date().toISOString().slice(0,10);
const numero=v=>{const x=Number(v||0);return Number.isFinite(x)?x:0};
const sinal=l=>l.natureza==="entrada"?1:-1;
const ativo=l=>l.status!=="cancelado";
const addDias=(iso,dias)=>{const [a,m,d]=iso.split("-").map(Number),x=new Date(Date.UTC(a,m-1,d));x.setUTCDate(x.getUTCDate()+dias);return x.toISOString().slice(0,10)};
const competencia=iso=>String(iso||"").slice(0,7);
function dataMensal(ano,mes,dia){const ultimo=new Date(Date.UTC(ano,mes,0)).getUTCDate();return `${ano}-${String(mes).padStart(2,"0")}-${String(Math.min(Math.max(1,dia),ultimo)).padStart(2,"0")}`}

function montarTela(){
  const tabs=pagina?.querySelector(".fpa-tabs");if(!tabs||$("tabFluxoCaixa"))return;
  const tab=document.createElement("button");tab.id="tabFluxoCaixa";tab.className="fpa-tab";tab.dataset.fpaTab="caixa";tab.type="button";tab.textContent="Fluxo de Caixa";tabs.appendChild(tab);
  const s=document.createElement("section");s.className="fpa-view hidden";s.dataset.fpaView="caixa";s.innerHTML=`
    <div class="pagina-cabecalho interno"><div><h3>Fluxo de Caixa</h3><p>Posição bancária, provisões, compromissos fixos e projeção financeira da empresa ativa.</p></div><div class="acoes-cabecalho"><button id="btnContaBancaria" class="btn-secundario" type="button">Contas bancárias</button><button id="btnNovoFixo" class="btn-secundario" type="button">+ Compromisso fixo</button><button id="btnNovaProvisao" class="btn-secundario" type="button">+ Provisão</button><button id="btnNovoLancamentoCaixa" class="btn-primario" type="button">+ Lançamento</button></div></div>
    <div class="caixa-kpis"><div class="kpi-card"><span>Saldo liquidado hoje</span><strong id="caixaSaldoHoje">—</strong></div><div class="kpi-card"><span>Saldo projetado D+30</span><strong id="caixaD30">—</strong></div><div class="kpi-card"><span>Saldo projetado D+60</span><strong id="caixaD60">—</strong></div><div class="kpi-card"><span>Saldo projetado D+90</span><strong id="caixaD90">—</strong></div></div>
    <div id="caixaAlertas" class="caixa-alertas"></div>
    <section id="formContaCaixaContainer" class="form-card hidden"><div class="form-card-titulo"><div><h3 id="tituloContaCaixa">Conta bancária</h3><p>Cadastre a posição inicial usada na projeção.</p></div></div><form id="formContaCaixa"><div class="form-grid form-grid-3"><div class="campo"><label for="contaCaixaNome">Apelido / identificação</label><input id="contaCaixaNome" required placeholder="Ex.: Conta movimento"></div><div class="campo"><label for="contaCaixaBanco">Banco</label><input id="contaCaixaBanco" required></div><div class="campo"><label for="contaCaixaAgencia">Agência</label><input id="contaCaixaAgencia"></div><div class="campo"><label for="contaCaixaNumero">Conta</label><input id="contaCaixaNumero"></div><div class="campo"><label for="contaCaixaSaldoAbertura">Saldo de abertura</label><input id="contaCaixaSaldoAbertura" type="number" step="0.01"></div><div class="campo"><label for="contaCaixaStatus">Status</label><select id="contaCaixaStatus"><option value="ativo">Ativa</option><option value="inativo">Inativa</option></select></div></div><div class="form-acoes"><button id="btnCancelarContaCaixa" class="btn-secundario" type="button">Cancelar</button><button class="btn-primario" type="submit">Salvar conta</button></div><p id="mensagemContaCaixa" class="mensagem-form"></p></form><div id="listaContasCaixa" class="caixa-contas-lista"></div></section>
    <section id="formLancamentoCaixaContainer" class="form-card hidden"><div class="form-card-titulo"><div><h3 id="tituloLancamentoCaixa">Novo lançamento</h3><p>Entradas e saídas previstas, confirmadas ou liquidadas.</p></div></div><form id="formLancamentoCaixa"><div class="form-grid form-grid-3"><div class="campo"><label for="caixaData">Data</label><input id="caixaData" type="date" required></div><div class="campo"><label for="caixaNatureza">Natureza</label><select id="caixaNatureza"><option value="saida">Saída</option><option value="entrada">Entrada</option></select></div><div class="campo"><label for="caixaStatus">Status</label><select id="caixaStatus"><option value="provisao">Provisão</option><option value="previsto">Previsto</option><option value="confirmado">Confirmado</option><option value="liquidado">Liquidado</option><option value="cancelado">Cancelado</option></select></div><div class="campo"><label for="caixaContaBanco">Conta bancária</label><select id="caixaContaBanco"></select></div><div class="campo"><label for="caixaClasse">Classe</label><select id="caixaClasse"><option value="operacional">Operacional / OPEX</option><option value="capex">CAPEX</option><option value="financeiro">Financeiro</option><option value="tributos">Tributos</option><option value="pessoal">Pessoal</option></select></div><div class="campo"><label for="caixaCentro">Centro de custo</label><select id="caixaCentro"></select></div><div class="campo"><label for="caixaCategoria">Categoria</label><input id="caixaCategoria" placeholder="Ex.: fornecedores"></div><div class="campo campo-span-2"><label for="caixaDescricao">Descrição</label><input id="caixaDescricao" required></div><div class="campo"><label for="caixaValor">Valor</label><input id="caixaValor" type="number" min="0" step="0.01" required></div><div class="campo campo-span-2"><label for="caixaObservacao">Observação</label><input id="caixaObservacao"></div></div><div class="form-acoes"><button id="btnCancelarLancamentoCaixa" class="btn-secundario" type="button">Cancelar</button><button class="btn-primario" type="submit">Salvar lançamento</button></div><p id="mensagemLancamentoCaixa" class="mensagem-form"></p></form></section>
    <section id="formFixoCaixaContainer" class="form-card hidden"><div class="form-card-titulo"><div><h3 id="tituloFixoCaixa">Compromisso fixo</h3><p>Use para contratos, aluguéis, folhas, serviços recorrentes e demais compromissos mensais.</p></div></div><form id="formFixoCaixa"><div class="form-grid form-grid-3"><div class="campo campo-span-2"><label for="fixoDescricao">Descrição</label><input id="fixoDescricao" required></div><div class="campo"><label for="fixoNatureza">Natureza</label><select id="fixoNatureza"><option value="saida">Saída</option><option value="entrada">Entrada</option></select></div><div class="campo"><label for="fixoValor">Valor mensal</label><input id="fixoValor" type="number" min="0" step="0.01" required></div><div class="campo"><label for="fixoDia">Dia do vencimento</label><input id="fixoDia" type="number" min="1" max="31" value="10"></div><div class="campo"><label for="fixoContaBanco">Conta bancária</label><select id="fixoContaBanco"></select></div><div class="campo"><label for="fixoCentro">Centro de custo</label><select id="fixoCentro"></select></div><div class="campo"><label for="fixoCategoria">Categoria</label><input id="fixoCategoria"></div><div class="campo"><label for="fixoContrato">Contrato / referência</label><input id="fixoContrato"></div><div class="campo"><label for="fixoInicio">Início</label><input id="fixoInicio" type="date" required></div><div class="campo"><label for="fixoFim">Fim</label><input id="fixoFim" type="date"></div><div class="campo"><label for="fixoStatus">Status</label><select id="fixoStatus"><option value="ativo">Ativo</option><option value="inativo">Inativo</option></select></div></div><div class="form-acoes"><button id="btnCancelarFixoCaixa" class="btn-secundario" type="button">Cancelar</button><button class="btn-primario" type="submit">Salvar compromisso</button></div><p id="mensagemFixoCaixa" class="mensagem-form"></p></form><div class="caixa-fixos-cab"><strong>Compromissos cadastrados</strong><button id="btnGerarProvisoesFixas" class="btn-secundario" type="button">Gerar provisões D+90</button></div><div id="listaFixosCaixa" class="caixa-fixos-lista"></div></section>
    <div class="fpa-toolbar caixa-toolbar"><div class="campo"><label for="caixaFiltroInicio">De</label><input id="caixaFiltroInicio" type="date"></div><div class="campo"><label for="caixaFiltroFim">Até</label><input id="caixaFiltroFim" type="date"></div><div class="campo"><label for="caixaFiltroConta">Conta bancária</label><select id="caixaFiltroConta"></select></div><div class="campo"><label for="caixaFiltroStatus">Status</label><select id="caixaFiltroStatus"><option value="">Todos</option><option value="provisao">Provisão</option><option value="previsto">Previsto</option><option value="confirmado">Confirmado</option><option value="liquidado">Liquidado</option></select></div><button id="btnExportarCaixaXls" class="btn-secundario" type="button">Exportar XLS</button><button id="btnExportarCaixaPdf" class="btn-secundario" type="button">Exportar PDF</button></div>
    <section class="lista-card"><div class="lista-cabecalho"><div><h3>Visão projetada</h3><p id="caixaResumoPeriodo">Carregando...</p></div></div><div class="tabela-container"><table id="tabelaFluxoCaixa" class="tabela caixa-tabela"><thead><tr><th>Data</th><th>Conta</th><th>Descrição</th><th>Classe</th><th>Status</th><th>Entrada</th><th>Saída</th><th>Saldo projetado</th><th class="nao-exportar">Ações</th></tr></thead><tbody id="listaFluxoCaixa"></tbody></table></div></section>`;
  pagina.appendChild(s);
  on(tab,"click",()=>{document.querySelectorAll(".fpa-tab").forEach(b=>b.classList.toggle("ativo",b===tab));document.querySelectorAll(".fpa-view").forEach(v=>v.classList.toggle("hidden",v!==s));carregarCaixa()});
}

function optsContas(valor="",todos=false){return`${todos?'<option value="">Todas as contas</option>':'<option value="">Sem conta definida</option>'}${contas.filter(x=>x.status!=="inativo").map(x=>`<option value="${esc(x.id)}" ${x.id===valor?"selected":""}>${esc(x.nome)} · ${esc(x.banco)}</option>`).join("")}`}
function optsCentros(valor=""){return'<option value="">Sem centro específico</option>'+centros.filter(x=>x.status!=="inativo").map(x=>`<option value="${esc(x.id)}" ${x.id===valor?"selected":""}>${esc(x.codigo)} · ${esc(x.nome)}</option>`).join("")}
function preencherSelects(){[
  ["caixaContaBanco",false],["fixoContaBanco",false],["caixaFiltroConta",true]
].forEach(([id,todos])=>{const s=$(id);if(!s)return;const v=s.value;s.innerHTML=optsContas(v,todos);if([...s.options].some(o=>o.value===v))s.value=v});["caixaCentro","fixoCentro"].forEach(id=>{const s=$(id);if(!s)return;const v=s.value;s.innerHTML=optsCentros(v);if([...s.options].some(o=>o.value===v))s.value=v})}
function nomeConta(id){const x=contas.find(c=>c.id===id);return x?`${x.nome} · ${x.banco}`:"-"}
function statusNome(v){return{provisao:"Provisão",previsto:"Previsto",confirmado:"Confirmado",liquidado:"Liquidado",cancelado:"Cancelado"}[v]||v}

function saldoAbertura(contaId=""){return contas.filter(x=>x.status!=="inativo"&&(!contaId||x.id===contaId)).reduce((s,x)=>s+numero(x.saldoAbertura),0)}
function movimentoAte(data,{contaId="",somenteLiquidado=false}={}){return lancamentos.filter(ativo).filter(x=>(!contaId||x.contaBancariaId===contaId)&&x.data<=data&&(!somenteLiquidado||x.status==="liquidado")).reduce((s,x)=>s+sinal(x)*numero(x.valor),0)}
function saldoProjetado(data,contaId=""){return saldoAbertura(contaId)+movimentoAte(data,{contaId})}
function renderKpis(){const h=hoje();$("caixaSaldoHoje").textContent=moeda(saldoAbertura()+movimentoAte(h,{somenteLiquidado:true}));$("caixaD30").textContent=moeda(saldoProjetado(addDias(h,30)));$("caixaD60").textContent=moeda(saldoProjetado(addDias(h,60)));$("caixaD90").textContent=moeda(saldoProjetado(addDias(h,90)));const venc=lancamentos.filter(x=>ativo(x)&&x.status!=="liquidado"&&x.data<h);$("caixaAlertas").innerHTML=venc.length?`<div class="modulo-aviso"><strong>${venc.length} lançamento(s) pendente(s) com data vencida.</strong> Revise provisões e confirmações para manter a projeção confiável.</div>`:""}

function renderContas(){const box=$("listaContasCaixa");if(!box)return;box.innerHTML=contas.length?contas.map(x=>`<button type="button" class="caixa-conta-card" data-edit-conta-caixa="${x.id}"><strong>${esc(x.nome)}</strong><span>${esc(x.banco)} ${esc(x.agencia||"")} ${esc(x.numeroConta||"")}</span><small>Abertura: ${moeda(x.saldoAbertura)}</small></button>`).join(""):'<div class="empty-state">Nenhuma conta bancária cadastrada.</div>';box.querySelectorAll("[data-edit-conta-caixa]").forEach(b=>on(b,"click",()=>abrirConta(contas.find(x=>x.id===b.dataset.editContaCaixa))))}
function renderFixos(){const box=$("listaFixosCaixa");if(!box)return;box.innerHTML=fixos.length?fixos.map(x=>`<button type="button" class="caixa-fixo-card" data-edit-fixo="${x.id}"><span><strong>${esc(x.descricao)}</strong><small>${esc(x.categoria||"Sem categoria")} · dia ${x.diaVencimento}</small></span><b>${x.natureza==="entrada"?"+":"−"} ${moeda(x.valor)}</b></button>`).join(""):'<div class="empty-state">Nenhum compromisso fixo cadastrado.</div>';box.querySelectorAll("[data-edit-fixo]").forEach(b=>on(b,"click",()=>abrirFixo(fixos.find(x=>x.id===b.dataset.editFixo))))}

function filtrados(){const ini=$("caixaFiltroInicio")?.value||hoje(),fim=$("caixaFiltroFim")?.value||addDias(hoje(),90),conta=$("caixaFiltroConta")?.value||"",status=$("caixaFiltroStatus")?.value||"";return lancamentos.filter(x=>x.data>=ini&&x.data<=fim&&(!conta||x.contaBancariaId===conta)&&(!status||x.status===status)).sort((a,b)=>String(a.data).localeCompare(String(b.data))||String(a.descricao||"").localeCompare(String(b.descricao||""),"pt-BR"))}
function renderTabela(){const arr=filtrados(),tbody=$("listaFluxoCaixa"),ini=$("caixaFiltroInicio")?.value||hoje(),conta=$("caixaFiltroConta")?.value||"";let saldo=saldoAbertura(conta)+lancamentos.filter(ativo).filter(x=>x.data<ini&&(!conta||x.contaBancariaId===conta)).reduce((s,x)=>s+sinal(x)*numero(x.valor),0);if($("caixaResumoPeriodo"))$("caixaResumoPeriodo").textContent=`${arr.length} lançamento(s) · ${dataBr(ini)} a ${dataBr($("caixaFiltroFim")?.value||addDias(hoje(),90))}`;if(!tbody)return;tbody.innerHTML=arr.length?arr.map(x=>{if(ativo(x))saldo+=sinal(x)*numero(x.valor);const venc=x.status!=="liquidado"&&x.status!=="cancelado"&&x.data<hoje();return`<tr class="${venc?"linha-critica":""}"><td>${dataBr(x.data)}</td><td>${esc(nomeConta(x.contaBancariaId))}</td><td class="celula-principal"><strong>${esc(x.descricao)}</strong><span>${esc(x.categoria||"")}</span></td><td>${esc(x.classe||"operacional")}</td><td><span class="fluxo-status status-${x.status==="liquidado"?"aprovada":x.status==="cancelado"?"reprovada":"solicitada"}">${esc(statusNome(x.status))}</span></td><td class="numero">${x.natureza==="entrada"?moeda(x.valor):"-"}</td><td class="numero">${x.natureza==="saida"?moeda(x.valor):"-"}</td><td class="numero"><strong>${moeda(saldo)}</strong></td><td class="nao-exportar"><button class="btn-acao destaque" type="button" data-edit-lanc-caixa="${x.id}">Editar</button></td></tr>`}).join(""):'<tr><td colspan="9">Nenhum lançamento no período.</td></tr>';tbody.querySelectorAll("[data-edit-lanc-caixa]").forEach(b=>on(b,"click",()=>abrirLancamento(lancamentos.find(x=>x.id===b.dataset.editLancCaixa))))}
function renderTudo(){preencherSelects();renderContas();renderFixos();renderKpis();renderTabela()}

async function carregarCaixa(){if(!empresaAtualId())return;try{[contas,lancamentos,fixos,centros]=await Promise.all([listarDocumentos("contasBancarias"),listarDocumentos("fluxoCaixaLancamentos"),listarDocumentos("fluxoCaixaFixos"),listarDocumentos("centrosCusto")]);carregadoEmpresa=empresaAtualId();renderTudo()}catch(e){console.error("Erro ao carregar fluxo de caixa",e);if($("caixaResumoPeriodo"))$("caixaResumoPeriodo").textContent="As regras do Firebase para o Fluxo de Caixa ainda precisam ser publicadas."}}

function abrirConta(x=null){editConta=x?.id||null;$("formContaCaixa")?.reset();$("tituloContaCaixa").textContent=x?"Editar conta bancária":"Nova conta bancária";$("contaCaixaNome").value=x?.nome||"";$("contaCaixaBanco").value=x?.banco||"";$("contaCaixaAgencia").value=x?.agencia||"";$("contaCaixaNumero").value=x?.numeroConta||"";$("contaCaixaSaldoAbertura").value=numero(x?.saldoAbertura);$("contaCaixaStatus").value=x?.status||"ativo";$("formContaCaixaContainer")?.classList.remove("hidden");renderContas()}
function abrirLancamento(x=null,{provisao=false}={}){editLanc=x?.id||null;$("formLancamentoCaixa")?.reset();$("tituloLancamentoCaixa").textContent=x?"Editar lançamento":provisao?"Nova provisão":"Novo lançamento";$("caixaData").value=x?.data||hoje();$("caixaNatureza").value=x?.natureza||"saida";$("caixaStatus").value=x?.status||(provisao?"provisao":"previsto");$("caixaContaBanco").innerHTML=optsContas(x?.contaBancariaId||"");$("caixaClasse").value=x?.classe||"operacional";$("caixaCentro").innerHTML=optsCentros(x?.centroCustoId||"");$("caixaCategoria").value=x?.categoria||"";$("caixaDescricao").value=x?.descricao||"";$("caixaValor").value=numero(x?.valor);$("caixaObservacao").value=x?.observacao||"";$("formLancamentoCaixaContainer")?.classList.remove("hidden")}
function abrirFixo(x=null){editFixo=x?.id||null;$("formFixoCaixa")?.reset();$("tituloFixoCaixa").textContent=x?"Editar compromisso fixo":"Novo compromisso fixo";$("fixoDescricao").value=x?.descricao||"";$("fixoNatureza").value=x?.natureza||"saida";$("fixoValor").value=numero(x?.valor);$("fixoDia").value=numero(x?.diaVencimento)||10;$("fixoContaBanco").innerHTML=optsContas(x?.contaBancariaId||"");$("fixoCentro").innerHTML=optsCentros(x?.centroCustoId||"");$("fixoCategoria").value=x?.categoria||"";$("fixoContrato").value=x?.contratoReferencia||"";$("fixoInicio").value=x?.inicio||hoje();$("fixoFim").value=x?.fim||"";$("fixoStatus").value=x?.status||"ativo";$("formFixoCaixaContainer")?.classList.remove("hidden");renderFixos()}

async function salvarConta(e){e.preventDefault();const d={nome:$("contaCaixaNome").value.trim(),banco:$("contaCaixaBanco").value.trim(),agencia:$("contaCaixaAgencia").value.trim(),numeroConta:$("contaCaixaNumero").value.trim(),saldoAbertura:numero($("contaCaixaSaldoAbertura").value),status:$("contaCaixaStatus").value};if(!d.nome||!d.banco)return msg($("mensagemContaCaixa"),"Informe identificação e banco.");try{if(editConta)await atualizarDocumento("contasBancarias",editConta,d);else await criarDocumento("contasBancarias",d);editConta=null;await carregarCaixa();msg($("mensagemContaCaixa"),"Conta salva.",true)}catch(err){console.error(err);msg($("mensagemContaCaixa"),"Não foi possível salvar a conta.")}}
async function salvarLancamento(e){e.preventDefault();if(!permite("controladoria","editar"))return msg($("mensagemLancamentoCaixa"),"Seu perfil não permite editar o fluxo de caixa.");const d={data:$("caixaData").value,natureza:$("caixaNatureza").value,status:$("caixaStatus").value,contaBancariaId:$("caixaContaBanco").value,classe:$("caixaClasse").value,centroCustoId:$("caixaCentro").value,categoria:$("caixaCategoria").value.trim(),descricao:$("caixaDescricao").value.trim(),valor:Math.abs(numero($("caixaValor").value)),observacao:$("caixaObservacao").value.trim(),origem:"manual"};if(!d.data||!d.descricao||!d.valor)return msg($("mensagemLancamentoCaixa"),"Informe data, descrição e valor.");try{if(editLanc)await atualizarDocumento("fluxoCaixaLancamentos",editLanc,d);else await criarDocumento("fluxoCaixaLancamentos",d);editLanc=null;$("formLancamentoCaixaContainer")?.classList.add("hidden");await carregarCaixa()}catch(err){console.error(err);msg($("mensagemLancamentoCaixa"),"Não foi possível salvar o lançamento.")}}
async function salvarFixo(e){e.preventDefault();const d={descricao:$("fixoDescricao").value.trim(),natureza:$("fixoNatureza").value,valor:Math.abs(numero($("fixoValor").value)),diaVencimento:Math.min(31,Math.max(1,numero($("fixoDia").value)||1)),contaBancariaId:$("fixoContaBanco").value,centroCustoId:$("fixoCentro").value,categoria:$("fixoCategoria").value.trim(),contratoReferencia:$("fixoContrato").value.trim(),inicio:$("fixoInicio").value,fim:$("fixoFim").value,status:$("fixoStatus").value};if(!d.descricao||!d.valor||!d.inicio)return msg($("mensagemFixoCaixa"),"Informe descrição, valor e início.");try{if(editFixo)await atualizarDocumento("fluxoCaixaFixos",editFixo,d);else await criarDocumento("fluxoCaixaFixos",d);editFixo=null;await carregarCaixa();msg($("mensagemFixoCaixa"),"Compromisso salvo.",true)}catch(err){console.error(err);msg($("mensagemFixoCaixa"),"Não foi possível salvar o compromisso.")}}

async function gerarProvisoes(){const inicio=hoje(),limite=addDias(inicio,90),ativos=fixos.filter(x=>x.status!=="inativo");let criados=0;try{for(const f of ativos){const [ai,mi]=inicio.split("-").map(Number),[af,mf]=limite.split("-").map(Number);let a=ai,m=mi;while(a<af||(a===af&&m<=mf)){const data=dataMensal(a,m,numero(f.diaVencimento)||1),comp=competencia(data);if(data>=String(f.inicio||"0000-00-00")&&(!f.fim||data<=f.fim)&&data<=limite&&!lancamentos.some(l=>l.origemFixoId===f.id&&l.competencia===comp)){await criarDocumento("fluxoCaixaLancamentos",{data,natureza:f.natureza,valor:f.valor,status:"provisao",contaBancariaId:f.contaBancariaId||"",centroCustoId:f.centroCustoId||"",classe:"operacional",categoria:f.categoria||"Compromisso fixo",descricao:f.descricao,observacao:f.contratoReferencia?`Contrato: ${f.contratoReferencia}`:"",origem:"fixo",origemFixoId:f.id,competencia:comp});criados++}m++;if(m>12){m=1;a++}}}await carregarCaixa();alert(`${criados} provisão(ões) gerada(s) até D+90.`)}catch(e){console.error(e);alert("Não foi possível gerar todas as provisões.")}}

function exportMeta(){return[document.querySelector("#empresaContexto option:checked")?.textContent||"Empresa",`${dataBr($("caixaFiltroInicio")?.value)} a ${dataBr($("caixaFiltroFim")?.value)}`]}
function bind(){
  montarTela();if(!$("caixaFiltroInicio"))return;$("caixaFiltroInicio").value=hoje();$("caixaFiltroFim").value=addDias(hoje(),90);
  on($("btnContaBancaria"),"click",()=>abrirConta());on($("btnNovoLancamentoCaixa"),"click",()=>abrirLancamento());on($("btnNovaProvisao"),"click",()=>abrirLancamento(null,{provisao:true}));on($("btnNovoFixo"),"click",()=>abrirFixo());
  on($("btnCancelarContaCaixa"),"click",()=>$("formContaCaixaContainer")?.classList.add("hidden"));on($("btnCancelarLancamentoCaixa"),"click",()=>$("formLancamentoCaixaContainer")?.classList.add("hidden"));on($("btnCancelarFixoCaixa"),"click",()=>$("formFixoCaixaContainer")?.classList.add("hidden"));
  on($("formContaCaixa"),"submit",salvarConta);on($("formLancamentoCaixa"),"submit",salvarLancamento);on($("formFixoCaixa"),"submit",salvarFixo);on($("btnGerarProvisoesFixas"),"click",gerarProvisoes);
  ["caixaFiltroInicio","caixaFiltroFim","caixaFiltroConta","caixaFiltroStatus"].forEach(id=>on($(id),"change",renderTabela));
  on($("btnExportarCaixaXls"),"click",()=>exportarTabelaXls($("tabelaFluxoCaixa"),{nome:"fluxo_caixa",titulo:"Fluxo de Caixa Projetado",meta:exportMeta()}));on($("btnExportarCaixaPdf"),"click",()=>exportarTabelaPdf($("tabelaFluxoCaixa"),{nome:"fluxo_caixa",titulo:"Fluxo de Caixa Projetado",meta:exportMeta()}));
  window.addEventListener("sig:page",e=>{if(e.detail?.pagina==="controladoria"&&carregadoEmpresa!==empresaAtualId())carregarCaixa()});window.addEventListener("sig:empresa-changed",()=>{carregadoEmpresa="";contas=[];lancamentos=[];fixos=[];centros=[];if(!$("tabFluxoCaixa")?.classList.contains("hidden"))carregarCaixa()});
}
bind();
