import { abrirPagina, state, db, admin } from "./core.js";
import { $, esc, msg, permite, listarDocumentos, criarDocumento, atualizarDocumento, empresaUnicaSelecionadaId, nomeEmpresa, dataBr } from "./shared.js";
import { collection, getDocs, query, where } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";

const PADRAO_MENSAL=[
  {id:"bancos",titulo:"Conciliações bancárias concluídas",dia:1},
  {id:"provisoes",titulo:"Provisões e contratos recorrentes revisados",dia:1},
  {id:"realizado",titulo:"Realizado importado / lançado",dia:2},
  {id:"dre",titulo:"DRE gerencial revisada",dia:3},
  {id:"desvios",titulo:"Desvios relevantes justificados",dia:4},
  {id:"capex",titulo:"CAPEX revisado",dia:4},
  {id:"forecast",titulo:"Forecast atualizado",dia:5},
  {id:"caixa",titulo:"Fluxo de caixa atualizado",dia:5},
  {id:"prestacao",titulo:"Prestação de Contas preparada",dia:6}
];
const PADRAO_ANUAL=[
  {id:"conciliacoes_patrimoniais",titulo:"Conciliações patrimoniais encerradas",dia:1},
  {id:"inventario",titulo:"Inventário físico e estoques conciliados",dia:2},
  {id:"imobilizado",titulo:"Imobilizado e depreciações revisados",dia:3},
  {id:"provisoes_anuais",titulo:"Provisões e contingências revisadas",dia:4},
  {id:"circularizacoes",titulo:"Circularizações / confirmações concluídas",dia:5},
  {id:"tributos_anuais",titulo:"Tributos e obrigações anuais revisados",dia:6},
  {id:"dre_anual",titulo:"Fechamento gerencial anual validado",dia:7},
  {id:"budget_seguinte",titulo:"Budget do exercício seguinte aprovado",dia:8}
];
let tarefas=[],cabecalhos=[],configs=[],usuarios=[],busy=false;
const pagina=()=>$("pagina-closing-v2");
const podeGerir=()=>admin()||permite("controladoria","editar")||permite("controladoria","fechamento");
const podeFechar=()=>admin()||permite("controladoria","editar")||permite("controladoria","fecharCompetencia");
const podeConfigurar=()=>admin()||permite("controladoria","editar");
const hoje=()=>new Date().toISOString().slice(0,10);
const compAtual=()=>new Date().toISOString().slice(0,7);
const n=v=>{const x=Number(v||0);return Number.isFinite(x)?x:0};
function dataDmais(comp,dia){const[a,m]=comp.split("-").map(Number),d=new Date(Date.UTC(a,m,Math.max(1,n(dia)||1)));return d.toISOString().slice(0,10)}
function empresa(){return empresaUnicaSelecionadaId()}
function configAtual(){return configs.find(x=>x.empresaId===empresa())||null}
function modo(){return $("closingV2Modo")?.value||"mensal"}
function chave(){return modo()==="mensal"?($("closingV2Comp")?.value||compAtual()):`ANUAL-${$("closingV2Ano")?.value||new Date().getFullYear()}`}
function labelChave(){return modo()==="mensal"?chave().split("-").reverse().join("/"):`Exercício ${String(chave()).replace("ANUAL-","")}`}
function modelos(tipo){const c=configAtual(),campo=tipo==="mensal"?"fechamentoModeloMensal":"fechamentoModeloAnual",salvos=Array.isArray(c?.[campo])?c[campo].filter(x=>x.ativo!==false):[];return salvos.length?salvos:(tipo==="mensal"?PADRAO_MENSAL:PADRAO_ANUAL)}
function tarefasAtuais(){return tarefas.filter(x=>x.competencia===chave()).sort((a,b)=>n(a.ordem)-n(b.ordem))}
function cabAtual(){return cabecalhos.find(x=>x.competencia===chave())}

function criarPagina(){
  if(pagina())return;const main=document.querySelector("main.conteudo");if(!main)return;const s=document.createElement("section");s.id="pagina-closing-v2";s.className="pagina hidden";s.innerHTML=`
  <div class="pagina-cabecalho"><div><span class="eyebrow">CONTROLADORIA & FP&A</span><h2>Cockpit de Fechamento</h2><p>Fechamento mensal e anual com régua replicável, responsáveis, prazos e bloqueio de competência.</p></div><button id="btnAtualizarClosingV2" class="btn-secundario" type="button">Atualizar</button></div>
  <div id="closingV2Aviso" class="modulo-aviso"></div>
  <div class="fpa-toolbar"><div class="campo"><label for="closingV2Modo">Cockpit</label><select id="closingV2Modo"><option value="mensal">Mensal</option><option value="anual">Anual</option></select></div><div id="closingV2CampoComp" class="campo"><label for="closingV2Comp">Competência</label><input id="closingV2Comp" type="month"></div><div id="closingV2CampoAno" class="campo hidden"><label for="closingV2Ano">Exercício</label><input id="closingV2Ano" type="number" min="2020" max="2100"></div><button id="btnCriarClosingV2" class="btn-secundario" type="button">Criar checklist</button><button id="btnConcluirClosingV2" class="btn-primario" type="button">Concluir fechamento</button><button id="btnConfigClosingV2" class="btn-secundario" type="button">Configurar modelo</button><span id="mensagemClosingV2" class="mensagem-form"></span></div>
  <div class="kpi-grid kpi-grid-4"><div class="kpi-card"><span>Progresso</span><strong id="closingV2Prog">—</strong><small id="closingV2Estado">—</small></div><div class="kpi-card"><span>Concluídas</span><strong id="closingV2Concl">—</strong><small>etapas concluídas</small></div><div class="kpi-card"><span>Pendentes</span><strong id="closingV2Pend">—</strong><small>etapas em aberto</small></div><div class="kpi-card"><span>Vencidas</span><strong id="closingV2Venc">—</strong><small>prazo ultrapassado</small></div></div>
  <section id="closingV2Config" class="form-card hidden"><div class="form-card-titulo"><div><h3>Modelo recorrente</h3><p>Itens cadastrados aqui serão replicados nos próximos checklists. Alterar o modelo não apaga históricos já criados.</p></div></div><form id="formClosingModelo"><div class="form-grid form-grid-3"><div class="campo"><label for="closingModeloTipo">Tipo</label><select id="closingModeloTipo"><option value="mensal">Mensal</option><option value="anual">Anual</option></select></div><div class="campo"><label for="closingModeloTitulo">Nova etapa</label><input id="closingModeloTitulo" required placeholder="Ex.: Revisar provisão de férias"></div><div class="campo"><label for="closingModeloDia">D+ / ordem</label><input id="closingModeloDia" type="number" min="1" step="1" value="1"></div></div><div class="form-acoes"><button class="btn-primario" type="submit">Adicionar ao modelo</button></div><p id="mensagemClosingModelo" class="mensagem-form"></p></form><div id="listaClosingModelos"></div></section>
  <section class="lista-card"><div class="lista-cabecalho"><div><h3 id="closingV2Titulo">Régua de fechamento</h3><p id="closingV2Resumo">—</p></div></div><div class="tabela-container"><table class="tabela"><thead><tr><th>Etapa</th><th>Responsável</th><th>Prazo</th><th>Status</th><th>Observação</th><th>Ação</th></tr></thead><tbody id="listaClosingV2"></tbody></table></div></section>`;main.appendChild(s);
  $("closingV2Comp").value=compAtual();$("closingV2Ano").value=new Date().getFullYear();$("closingV2Modo")?.addEventListener("change",()=>{trocarModo();render()});$("closingV2Comp")?.addEventListener("change",render);$("closingV2Ano")?.addEventListener("change",render);$("btnAtualizarClosingV2")?.addEventListener("click",carregar);$("btnCriarClosingV2")?.addEventListener("click",criarChecklist);$("btnConcluirClosingV2")?.addEventListener("click",alternarFechamento);$("btnConfigClosingV2")?.addEventListener("click",()=>$("closingV2Config")?.classList.toggle("hidden"));$("formClosingModelo")?.addEventListener("submit",salvarModelo);
}
function trocarModo(){const mensal=modo()==="mensal";$("closingV2CampoComp").classList.toggle("hidden",!mensal);$("closingV2CampoAno").classList.toggle("hidden",mensal);$("closingModeloTipo").value=modo();$("closingV2Titulo").textContent=mensal?"Régua de fechamento mensal":"Cockpit de fechamento anual";renderModelos()}
async function carregarUsuarios(){try{const s=await getDocs(query(collection(db,"usuarios"),where("grupoId","==",state.usuario.grupoId)));usuarios=[];s.forEach(r=>{const d=r.data();if(d.ativo===true)usuarios.push({id:r.id,...d})})}catch{usuarios=[{id:state.usuario.id,nome:state.usuario.nome||state.usuario.email||"Eu"}]}}
function optsUsuarios(id){return usuarios.map(u=>`<option value="${esc(u.id)}" ${u.id===id?"selected":""}>${esc(u.nome||u.email||u.id)}</option>`).join("")}
function renderModelos(){const box=$("listaClosingModelos");if(!box)return;const tipo=$("closingModeloTipo")?.value||modo(),arr=modelos(tipo);box.innerHTML=`<div class="tabela-container"><table class="tabela"><thead><tr><th>Etapa</th><th>D+ / ordem</th><th>Origem</th></tr></thead><tbody>${arr.map(x=>`<tr><td>${esc(x.titulo)}</td><td>${x.dia||x.ordem||1}</td><td>${Array.isArray(configAtual()?.[tipo==="mensal"?"fechamentoModeloMensal":"fechamentoModeloAnual"])?"Configurado":"Padrão SIG"}</td></tr>`).join("")}</tbody></table></div>`}
function render(){
  if(!pagina())return;const arr=tarefasAtuais(),cab=cabAtual(),fechado=cab?.status==="concluido",concl=arr.filter(x=>x.status==="concluido").length,pend=arr.length-concl,venc=modo()==="mensal"?arr.filter(x=>x.status!=="concluido"&&x.prazo&&x.prazo<hoje()).length:0,prog=arr.length?Math.round(concl/arr.length*100):0;$("closingV2Prog").textContent=`${prog}%`;$("closingV2Concl").textContent=concl;$("closingV2Pend").textContent=pend;$("closingV2Venc").textContent=venc;$("closingV2Estado").textContent=fechado?"FECHADO":"Em andamento";$("closingV2Resumo").textContent=`${nomeEmpresa(empresa()||"")} · ${labelChave()} · ${arr.length} etapa(s)`;$("closingV2Aviso").innerHTML=fechado?'<strong>Fechamento concluído.</strong> O Input Mensal desta competência fica bloqueado enquanto o fechamento estiver concluído.':modo()==="mensal"?'A conclusão deste cockpit bloqueia o Input Mensal da competência.':'O cockpit anual preserva a trilha de encerramento do exercício sem alterar os checklists mensais.';$("btnCriarClosingV2").classList.toggle("hidden",!podeGerir()||arr.length>0);$("btnConcluirClosingV2").classList.toggle("hidden",!podeFechar()||!arr.length);$("btnConcluirClosingV2").textContent=fechado?"Reabrir fechamento":"Concluir fechamento";$("btnConfigClosingV2").classList.toggle("hidden",!podeConfigurar());
  const tb=$("listaClosingV2");if(!tb)return;if(!arr.length){tb.innerHTML='<tr><td colspan="6">Nenhum checklist criado para este período.</td></tr>';renderModelos();return}tb.innerHTML=arr.map(t=>{const edit=podeGerir()&&!fechado,exec=(t.responsavelId===state.usuario.id||podeFechar())&&!fechado;return`<tr><td><strong>${esc(t.titulo)}</strong><small>${modo()==="mensal"?`D+${t.diaFechamento||"-"}`:`Ordem ${t.ordem||"-"}`}</small></td><td>${edit?`<select data-cl-resp="${t.id}">${optsUsuarios(t.responsavelId)}</select>`:esc(t.responsavelNome||"-")}</td><td>${modo()==="mensal"?(edit?`<input type="date" data-cl-prazo="${t.id}" value="${esc(t.prazo||"")}">`:dataBr(t.prazo)):"—"}</td><td>${exec||edit?`<select data-cl-status="${t.id}"><option value="aberto" ${t.status==="aberto"?"selected":""}>Aberto</option><option value="em_andamento" ${t.status==="em_andamento"?"selected":""}>Em andamento</option><option value="concluido" ${t.status==="concluido"?"selected":""}>Concluído</option></select>`:esc(t.status||"aberto")}</td><td>${exec||edit?`<input type="text" data-cl-obs="${t.id}" value="${esc(t.observacao||"")}" placeholder="Observação">`:esc(t.observacao||"-")}</td><td>${exec||edit?`<button class="btn-acao destaque" data-cl-save="${t.id}" type="button">Salvar</button>`:"—"}</td></tr>`}).join("");tb.querySelectorAll("[data-cl-save]").forEach(b=>b.addEventListener("click",()=>salvarTarefa(b.dataset.clSave)));renderModelos()
}
async function carregar(){criarPagina();if(busy||!empresa())return;busy=true;msg($("mensagemClosingV2"),"Carregando...");try{await carregarUsuarios();[tarefas,cabecalhos,configs]=await Promise.all([listarDocumentos("fechamentoTarefas"),listarDocumentos("fechamentosMensais"),listarDocumentos("configuracoesControladoria")]);trocarModo();render();msg($("mensagemClosingV2"),"")}catch(e){console.error("Cockpit:",e);msg($("mensagemClosingV2"),"Não foi possível carregar o Cockpit.")}finally{busy=false}}
async function criarChecklist(){if(!podeGerir()||tarefasAtuais().length)return;const tipo=modo(),lista=modelos(tipo),comp=chave();if(!confirm(`Criar checklist ${tipo} para ${labelChave()}?`))return;try{for(let i=0;i<lista.length;i++){const m=lista[i],u=usuarios[0]||state.usuario;await criarDocumento("fechamentoTarefas",{competencia:comp,tarefaId:m.id||`modelo_${i+1}`,titulo:m.titulo,ordem:i+1,diaFechamento:tipo==="mensal"?n(m.dia||m.diaFechamento||i+1):i+1,prazo:tipo==="mensal"?dataDmais(comp,n(m.dia||m.diaFechamento||i+1)):"",responsavelId:u.id,responsavelNome:u.nome||u.email||u.id,status:"aberto",observacao:"",tipoFechamento:tipo})}await criarDocumento("fechamentosMensais",{competencia:comp,status:"aberto",tipoFechamento:tipo});await carregar()}catch(e){console.error(e);msg($("mensagemClosingV2"),"Não foi possível criar o checklist.")}}
async function salvarTarefa(id){const t=tarefas.find(x=>x.id===id);if(!t)return;const tb=$("listaClosingV2"),resp=tb.querySelector(`[data-cl-resp="${id}"]`),prazo=tb.querySelector(`[data-cl-prazo="${id}"]`),status=tb.querySelector(`[data-cl-status="${id}"]`),obs=tb.querySelector(`[data-cl-obs="${id}"]`),rid=resp?.value||t.responsavelId,u=usuarios.find(x=>x.id===rid),d={status:status?.value||t.status,observacao:obs?.value.trim()||""};if(podeGerir()){d.responsavelId=rid;d.responsavelNome=u?.nome||u?.email||rid;if(modo()==="mensal")d.prazo=prazo?.value||t.prazo}try{await atualizarDocumento("fechamentoTarefas",id,d);await carregar()}catch(e){console.error(e);alert("Não foi possível atualizar a etapa.")}}
async function alternarFechamento(){if(!podeFechar())return;const cab=cabAtual(),arr=tarefasAtuais();if(!cab)return alert("Crie o checklist primeiro.");const fechado=cab.status==="concluido";if(!fechado&&arr.some(x=>x.status!=="concluido"))return alert("Ainda existem etapas pendentes.");if(!confirm(`${fechado?"Reabrir":"Concluir"} ${labelChave()}?`))return;try{await atualizarDocumento("fechamentosMensais",cab.id,{status:fechado?"aberto":"concluido",fechadoEm:fechado?"":new Date().toISOString(),fechadoPor:fechado?"":state.usuario.id,fechadoPorNome:fechado?"":state.usuario.nome||state.usuario.email||state.usuario.id});await carregar()}catch(e){console.error(e);alert("Não foi possível alterar o fechamento.")}}
async function salvarModelo(e){e.preventDefault();if(!podeConfigurar())return;const tipo=$("closingModeloTipo").value,titulo=$("closingModeloTitulo").value.trim(),dia=Math.max(1,n($("closingModeloDia").value)||1);if(!titulo)return;let cfg=configAtual(),campo=tipo==="mensal"?"fechamentoModeloMensal":"fechamentoModeloAnual",atual=Array.isArray(cfg?.[campo])?[...cfg[campo]]:[...(tipo==="mensal"?PADRAO_MENSAL:PADRAO_ANUAL)];atual.push({id:`custom_${Date.now()}`,titulo,dia,ativo:true});try{if(cfg)await atualizarDocumento("configuracoesControladoria",cfg.id,{[campo]:atual});else await criarDocumento("configuracoesControladoria",{[campo]:atual});$("closingModeloTitulo").value="";await carregar();msg($("mensagemClosingModelo"),"Etapa adicionada ao modelo e será replicada nos próximos checklists.",true)}catch(err){console.error(err);msg($("mensagemClosingModelo"),"Não foi possível atualizar o modelo.")}}
export function abrir(){criarPagina();abrirPagina("closing-v2");const t=$("tituloPagina");if(t)t.textContent="Cockpit de Fechamento";carregar()}
criarPagina();window.addEventListener("sig:empresa-changed",()=>{if(pagina()&&!pagina().classList.contains("hidden"))carregar()});
