import { abrirPagina, state, db, admin } from "./core.js";
import { $, esc, msg, permite, listarDocumentos, criarDocumento, atualizarDocumento, empresaUnicaSelecionadaId, grupoAtualId, nomeEmpresa, dataBr } from "./shared.js";
import { collection, getDocs, query, where, writeBatch, doc, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";

const PADRAO_MENSAL=[
  {id:"bancos",titulo:"Conciliações bancárias concluídas",dia:1},
  {id:"provisoes",titulo:"Provisões e contratos recorrentes revisados",dia:1},
  {id:"realizado",titulo:"Realizado importado / lançado",dia:2},
  {id:"dre",titulo:"DRE gerencial revisada",dia:3},
  {id:"desvios",titulo:"Desvios relevantes justificados",dia:4},
  {id:"capex",titulo:"CAPEX revisado",dia:4},
  {id:"forecast",titulo:"Forecast atualizado",dia:5},
  {id:"caixa",titulo:"Fluxo de caixa atualizado",dia:5},
  {id:"prestacao",titulo:"Prestação de Contas preparada",dia:6}
];
const PADRAO_ANUAL=[
  {id:"conciliacoes_patrimoniais",titulo:"Conciliações patrimoniais encerradas",dia:1},
  {id:"inventario",titulo:"Inventário físico e estoques conciliados",dia:2},
  {id:"imobilizado",titulo:"Imobilizado e depreciações revisados",dia:3},
  {id:"provisoes_anuais",titulo:"Provisões e contingências revisadas",dia:4},
  {id:"circularizacoes",titulo:"Circularizações / confirmações concluídas",dia:5},
  {id:"tributos_anuais",titulo:"Tributos e obrigações anuais revisados",dia:6},
  {id:"dre_anual",titulo:"Fechamento gerencial anual validado",dia:7},
  {id:"budget_seguinte",titulo:"Budget do exercício seguinte aprovado",dia:8}
];

let tarefas=[],cabecalhos=[],configs=[],usuarios=[],busy=false,criando=false,normalizando=false;
const pagina=()=>$("pagina-closing-v3");
const podeGerir=()=>admin()||permite("controladoria","editar")||permite("controladoria","fechamento");
const podeFechar=()=>admin()||permite("controladoria","editar")||permite("controladoria","fecharCompetencia");
const podeConfigurar=()=>admin()||permite("controladoria","editar");
const hoje=()=>new Date().toISOString().slice(0,10);
const compAtual=()=>new Date().toISOString().slice(0,7);
const n=v=>{const x=Number(v||0);return Number.isFinite(x)?x:0};
const idSeguro=v=>String(v||"sem").replace(/[^a-zA-Z0-9_-]/g,"_");
function dataDmais(comp,dia){const[a,m]=comp.split("-").map(Number),d=new Date(Date.UTC(a,m,Math.max(1,n(dia)||1)));return d.toISOString().slice(0,10)}
function empresa(){return empresaUnicaSelecionadaId()}
function configAtual(){return configs.find(x=>x.empresaId===empresa())||null}
function modo(){return $("closingV3Modo")?.value||"mensal"}
function chave(){return modo()==="mensal"?($("closingV3Comp")?.value||compAtual()):`ANUAL-${$("closingV3Ano")?.value||new Date().getFullYear()}`}
function refAtual(tipo=modo()){return tipo==="mensal"?($("closingV3Comp")?.value||compAtual()):String($("closingV3Ano")?.value||new Date().getFullYear())}
function refDaCompetencia(comp,tipo){return tipo==="mensal"?String(comp||""):String(comp||"").replace("ANUAL-","")}
function labelChave(){return modo()==="mensal"?chave().split("-").reverse().join("/"):`Exercício ${String(chave()).replace("ANUAL-","")}`}
function campoModelo(tipo){return tipo==="mensal"?"fechamentoModeloMensal":"fechamentoModeloAnual"}
function basePadrao(tipo){return (tipo==="mensal"?PADRAO_MENSAL:PADRAO_ANUAL).map(x=>({...x,origem:"padrao",vigencias:[{desde:tipo==="mensal"?"0000-00":"0000",ativo:true}]}))}
function todosModelos(tipo){const cfg=configAtual(),salvos=cfg?.[campoModelo(tipo)];return Array.isArray(salvos)&&salvos.length?salvos.map(x=>({...x,origem:x.origem||"configurado"})):basePadrao(tipo)}
function estadoNoPeriodo(item,tipo,ref=refAtual(tipo)){
  if(item.excluidoDesde&&String(item.excluidoDesde)<=String(ref))return{ativo:false,excluido:true};
  const ev=Array.isArray(item.vigencias)?[...item.vigencias].filter(x=>x?.desde&&String(x.desde)<=String(ref)).sort((a,b)=>String(a.desde).localeCompare(String(b.desde))):[];
  if(ev.length)return{ativo:ev[ev.length-1].ativo!==false,excluido:false};
  if(item.vigenciaInicio&&String(item.vigenciaInicio)>String(ref))return{ativo:false,excluido:false};
  return{ativo:item.ativo!==false,excluido:false};
}
function modelosAtivos(tipo,ref=refAtual(tipo)){return todosModelos(tipo).filter(x=>estadoNoPeriodo(x,tipo,ref).ativo)}
function scoreTarefa(t){return(t.status==="concluido"?8:t.status==="em_andamento"?4:0)+(t.observacao?2:0)+(t.responsavelId&&t.responsavelId!==state.usuario.id?1:0)+n(t.atualizadoEm?.seconds)/1e12}
function chaveTarefa(t){return`${t.competencia}|${t.tarefaId||t.titulo}`}
function deduplicadas(lista){const map=new Map();lista.filter(x=>x.duplicadoArquivado!==true&&x.modeloInativo!==true).forEach(t=>{const k=chaveTarefa(t),a=map.get(k);if(!a||scoreTarefa(t)>scoreTarefa(a))map.set(k,t)});return[...map.values()]}
function duplicidadesDaCompetencia(){const raw=tarefas.filter(x=>x.competencia===chave()&&x.duplicadoArquivado!==true),map=new Map(),dups=[];raw.forEach(t=>{const k=chaveTarefa(t);if(!map.has(k)){map.set(k,[t]);return}map.get(k).push(t)});map.forEach(arr=>{if(arr.length>1){const keep=[...arr].sort((a,b)=>scoreTarefa(b)-scoreTarefa(a))[0];arr.filter(x=>x.id!==keep.id).forEach(x=>dups.push(x))}});return dups}
function tarefasAtuais(){return deduplicadas(tarefas.filter(x=>x.competencia===chave())).sort((a,b)=>n(a.ordem)-n(b.ordem))}
function cabAtual(){const arr=cabecalhos.filter(x=>x.competencia===chave());return arr.sort((a,b)=>n(b.atualizadoEm?.seconds)-n(a.atualizadoEm?.seconds))[0]||null}
function tarefaIdDoc(comp,tarefaId){return`cl_${idSeguro(empresa())}_${idSeguro(comp)}_${idSeguro(tarefaId)}`}
function cabIdDoc(comp){return`fh_${idSeguro(empresa())}_${idSeguro(comp)}`}

function criarPagina(){
  if(pagina())return;const main=document.querySelector("main.conteudo");if(!main)return;const s=document.createElement("section");s.id="pagina-closing-v3";s.className="pagina hidden";s.innerHTML=`
  <div class="pagina-cabecalho"><div><span class="eyebrow">CONTROLADORIA & FP&A</span><h2>Cockpit de Fechamento</h2><p>Fechamento mensal e anual com modelo temporal, histórico preservado e geração idempotente.</p></div><button id="btnAtualizarClosingV3" class="btn-secundario" type="button">Atualizar</button></div>
  <div id="closingV3Aviso" class="modulo-aviso"></div>
  <div class="fpa-toolbar"><div class="campo"><label for="closingV3Modo">Cockpit</label><select id="closingV3Modo"><option value="mensal">Mensal</option><option value="anual">Anual</option></select></div><div id="closingV3CampoComp" class="campo"><label for="closingV3Comp">Competência</label><input id="closingV3Comp" type="month"></div><div id="closingV3CampoAno" class="campo hidden"><label for="closingV3Ano">Exercício</label><input id="closingV3Ano" type="number" min="2020" max="2100"></div><button id="btnCriarClosingV3" class="btn-secundario" type="button">Criar checklist</button><button id="btnConcluirClosingV3" class="btn-primario" type="button">Concluir fechamento</button><button id="btnConfigClosingV3" class="btn-secundario" type="button">Configurar modelo</button><button id="btnNormalizarClosingV3" class="btn-secundario hidden" type="button">Limpar duplicidades</button><span id="mensagemClosingV3" class="mensagem-form"></span></div>
  <div class="kpi-grid kpi-grid-4"><div class="kpi-card"><span>Progresso</span><strong id="closingV3Prog">—</strong><small id="closingV3Estado">—</small></div><div class="kpi-card"><span>Concluídas</span><strong id="closingV3Concl">—</strong><small>etapas concluídas</small></div><div class="kpi-card"><span>Pendentes</span><strong id="closingV3Pend">—</strong><small>etapas em aberto</small></div><div class="kpi-card"><span>Vencidas</span><strong id="closingV3Venc">—</strong><small>prazo ultrapassado</small></div></div>
  <section id="closingV3Config" class="form-card hidden"><div class="form-card-titulo"><div><h3>Modelo recorrente</h3><p>As alterações passam a valer a partir da competência/exercício selecionado. Períodos anteriores permanecem históricos.</p></div></div><form id="formClosingModeloV3"><div class="form-grid form-grid-3"><div class="campo"><label for="closingModeloTipoV3">Tipo</label><select id="closingModeloTipoV3"><option value="mensal">Mensal</option><option value="anual">Anual</option></select></div><div class="campo"><label for="closingModeloTituloV3">Nova etapa</label><input id="closingModeloTituloV3" required placeholder="Ex.: Revisar provisão de férias"></div><div class="campo"><label for="closingModeloDiaV3">D+ / ordem</label><input id="closingModeloDiaV3" type="number" min="1" step="1" value="1"></div></div><div class="form-acoes"><button class="btn-primario" type="submit">Adicionar a partir deste período</button></div><p id="mensagemClosingModeloV3" class="mensagem-form"></p></form><div id="listaClosingModelosV3"></div></section>
  <section class="lista-card"><div class="lista-cabecalho"><div><h3 id="closingV3Titulo">Régua de fechamento</h3><p id="closingV3Resumo">—</p></div></div><div class="tabela-container"><table class="tabela"><thead><tr><th>Etapa</th><th>Responsável</th><th>Prazo</th><th>Status</th><th>Observação</th><th>Ação</th></tr></thead><tbody id="listaClosingV3"></tbody></table></div></section>`;main.appendChild(s);
  $("closingV3Comp").value=compAtual();$("closingV3Ano").value=new Date().getFullYear();
  $("closingV3Modo")?.addEventListener("change",()=>{trocarModo();render()});$("closingV3Comp")?.addEventListener("change",()=>{render();renderModelos()});$("closingV3Ano")?.addEventListener("change",()=>{render();renderModelos()});
  $("btnAtualizarClosingV3")?.addEventListener("click",carregar);$("btnCriarClosingV3")?.addEventListener("click",criarChecklist);$("btnConcluirClosingV3")?.addEventListener("click",alternarFechamento);$("btnConfigClosingV3")?.addEventListener("click",()=>$("closingV3Config")?.classList.toggle("hidden"));$("btnNormalizarClosingV3")?.addEventListener("click",normalizarDuplicidades);$("formClosingModeloV3")?.addEventListener("submit",salvarModelo);
}
function trocarModo(){const mensal=modo()==="mensal";$("closingV3CampoComp").classList.toggle("hidden",!mensal);$("closingV3CampoAno").classList.toggle("hidden",mensal);$("closingModeloTipoV3").value=modo();$("closingV3Titulo").textContent=mensal?"Régua de fechamento mensal":"Cockpit de fechamento anual";renderModelos()}
async function carregarUsuarios(){try{const s=await getDocs(query(collection(db,"usuarios"),where("grupoId","==",state.usuario.grupoId)));usuarios=[];s.forEach(r=>{const d=r.data();if(d.ativo===true)usuarios.push({id:r.id,...d})})}catch{usuarios=[{id:state.usuario.id,nome:state.usuario.nome||state.usuario.email||"Eu"}]}}
function optsUsuarios(id){return usuarios.map(u=>`<option value="${esc(u.id)}" ${u.id===id?"selected":""}>${esc(u.nome||u.email||u.id)}</option>`).join("")}
function renderModelos(){const box=$("listaClosingModelosV3");if(!box)return;const tipo=$("closingModeloTipoV3")?.value||modo(),ref=refAtual(tipo),arr=todosModelos(tipo);box.innerHTML=`<div class="modulo-aviso"><strong>Vigência:</strong> ações realizadas aqui valem de ${tipo==="mensal"?ref.split("-").reverse().join("/"):ref} em diante.</div><div class="tabela-container"><table class="tabela"><thead><tr><th>Etapa</th><th>D+ / ordem</th><th>Situação neste período</th><th>Origem</th><th>Ações</th></tr></thead><tbody>${arr.map(x=>{const st=estadoNoPeriodo(x,tipo,ref),custom=x.origem==="custom"||String(x.id||"").startsWith("custom_");return`<tr><td><strong>${esc(x.titulo)}</strong></td><td>${x.dia||x.ordem||1}</td><td>${st.excluido?"Excluída daqui em diante":st.ativo?"Ativa":"Inativa"}</td><td>${custom?"Customizada":"Padrão / configurada"}</td><td>${!podeConfigurar()?"—":st.excluido?"—":`<button class="btn-acao" type="button" data-modelo-toggle="${esc(x.id)}" data-tipo="${tipo}">${st.ativo?"Inativar daqui em diante":"Ativar daqui em diante"}</button>${custom?` <button class="btn-acao" type="button" data-modelo-excluir="${esc(x.id)}" data-tipo="${tipo}">Excluir daqui em diante</button>`:""}`}</td></tr>`}).join("")}</tbody></table></div>`;box.querySelectorAll("[data-modelo-toggle]").forEach(b=>b.addEventListener("click",()=>alterarVigenciaModelo(b.dataset.modeloToggle,b.dataset.tipo)));box.querySelectorAll("[data-modelo-excluir]").forEach(b=>b.addEventListener("click",()=>excluirModelo(b.dataset.modeloExcluir,b.dataset.tipo)))}
function render(){if(!pagina())return;const arr=tarefasAtuais(),cab=cabAtual(),fechado=cab?.status==="concluido",concl=arr.filter(x=>x.status==="concluido").length,pend=arr.length-concl,venc=modo()==="mensal"?arr.filter(x=>x.status!=="concluido"&&x.prazo&&x.prazo<hoje()).length:0,prog=arr.length?Math.round(concl/arr.length*100):0,dups=duplicidadesDaCompetencia();$("closingV3Prog").textContent=`${prog}%`;$("closingV3Concl").textContent=concl;$("closingV3Pend").textContent=pend;$("closingV3Venc").textContent=venc;$("closingV3Estado").textContent=fechado?"FECHADO":"Em andamento";$("closingV3Resumo").textContent=`${nomeEmpresa(empresa()||"")} · ${labelChave()} · ${arr.length} etapa(s)`;$("closingV3Aviso").innerHTML=dups.length?`<strong>${dups.length} duplicidade(s) antiga(s) detectada(s).</strong> A grade já ignora as cópias repetidas. Use “Limpar duplicidades” para arquivá-las.`:fechado?'<strong>Fechamento concluído.</strong> O Input Mensal desta competência fica bloqueado enquanto o fechamento estiver concluído.':modo()==="mensal"?'A conclusão deste cockpit bloqueia o Input Mensal da competência.':'O cockpit anual preserva a trilha de encerramento do exercício sem alterar os checklists mensais.';$("btnCriarClosingV3").classList.toggle("hidden",!podeGerir()||arr.length>0);$("btnConcluirClosingV3").classList.toggle("hidden",!podeFechar()||!arr.length);$("btnConcluirClosingV3").textContent=fechado?"Reabrir fechamento":"Concluir fechamento";$("btnConfigClosingV3").classList.toggle("hidden",!podeConfigurar());$("btnNormalizarClosingV3").classList.toggle("hidden",!podeGerir()||!dups.length);
  const tb=$("listaClosingV3");if(!tb)return;if(!arr.length){tb.innerHTML='<tr><td colspan="6">Nenhum checklist criado para este período.</td></tr>';renderModelos();return}tb.innerHTML=arr.map(t=>{const edit=podeGerir()&&!fechado,exec=(t.responsavelId===state.usuario.id||podeFechar())&&!fechado;return`<tr><td><strong>${esc(t.titulo)}</strong><small>${modo()==="mensal"?`D+${t.diaFechamento||"-"}`:`Ordem ${t.ordem||"-"}`}</small></td><td>${edit?`<select data-cl3-resp="${t.id}">${optsUsuarios(t.responsavelId)}</select>`:esc(t.responsavelNome||"-")}</td><td>${modo()==="mensal"?(edit?`<input type="date" data-cl3-prazo="${t.id}" value="${esc(t.prazo||"")}">`:dataBr(t.prazo)):"—"}</td><td>${exec||edit?`<select data-cl3-status="${t.id}"><option value="aberto" ${t.status==="aberto"?"selected":""}>Aberto</option><option value="em_andamento" ${t.status==="em_andamento"?"selected":""}>Em andamento</option><option value="concluido" ${t.status==="concluido"?"selected":""}>Concluído</option></select>`:esc(t.status||"aberto")}</td><td>${exec||edit?`<input type="text" data-cl3-obs="${t.id}" value="${esc(t.observacao||"")}" placeholder="Observação">`:esc(t.observacao||"-")}</td><td>${exec||edit?`<button class="btn-acao destaque" data-cl3-save="${t.id}" type="button">Salvar</button>`:"—"}</td></tr>`}).join("");tb.querySelectorAll("[data-cl3-save]").forEach(b=>b.addEventListener("click",()=>salvarTarefa(b.dataset.cl3Save)));renderModelos()}

async function carregar(){criarPagina();if(busy||!empresa())return;busy=true;const b=$("btnAtualizarClosingV3");if(b){b.disabled=true;b.textContent="Atualizando..."}msg($("mensagemClosingV3"),"Carregando...");try{const up=carregarUsuarios();[tarefas,cabecalhos,configs]=await Promise.all([listarDocumentos("fechamentoTarefas"),listarDocumentos("fechamentosMensais"),listarDocumentos("configuracoesControladoria")]);await up;trocarModo();render();msg($("mensagemClosingV3"),"")}catch(e){console.error("Cockpit V3:",e);msg($("mensagemClosingV3"),"Não foi possível carregar o Cockpit.")}finally{busy=false;if(b){b.disabled=false;b.textContent="Atualizar"}}}
async function criarChecklist(){if(!podeGerir()||criando||busy||tarefasAtuais().length)return;criando=true;const b=$("btnCriarClosingV3");if(b){b.disabled=true;b.textContent="Criando..."}try{const tipo=modo(),comp=chave(),lista=modelosAtivos(tipo,refDaCompetencia(comp,tipo));if(!confirm(`Criar checklist ${tipo} para ${labelChave()}?`))return;const batch=writeBatch(db),grupoId=grupoAtualId(),emp=empresa(),u=usuarios[0]||state.usuario;for(let i=0;i<lista.length;i++){const m=lista[i],tid=m.id||`modelo_${i+1}`,ref=doc(db,"fechamentoTarefas",tarefaIdDoc(comp,tid));batch.set(ref,{grupoId,empresaId:emp,competencia:comp,tarefaId:tid,titulo:m.titulo,ordem:i+1,diaFechamento:tipo==="mensal"?n(m.dia||m.diaFechamento||i+1):i+1,prazo:tipo==="mensal"?dataDmais(comp,n(m.dia||m.diaFechamento||i+1)):"",responsavelId:u.id,responsavelNome:u.nome||u.email||u.id,status:"aberto",observacao:"",tipoFechamento:tipo,modeloInativo:false,criadoPor:state.usuario.id,criadoEm:serverTimestamp(),atualizadoEm:serverTimestamp()},{merge:true})}batch.set(doc(db,"fechamentosMensais",cabIdDoc(comp)),{grupoId,empresaId:emp,competencia:comp,status:"aberto",tipoFechamento:tipo,criadoPor:state.usuario.id,criadoEm:serverTimestamp(),atualizadoEm:serverTimestamp()},{merge:true});await batch.commit();await carregar()}catch(e){console.error(e);msg($("mensagemClosingV3"),"Não foi possível criar o checklist.")}finally{criando=false;if(b){b.disabled=false;b.textContent="Criar checklist"}}}
async function salvarTarefa(id){const t=tarefas.find(x=>x.id===id);if(!t)return;const tb=$("listaClosingV3"),resp=tb.querySelector(`[data-cl3-resp="${id}"]`),prazo=tb.querySelector(`[data-cl3-prazo="${id}"]`),status=tb.querySelector(`[data-cl3-status="${id}"]`),obs=tb.querySelector(`[data-cl3-obs="${id}"]`),rid=resp?.value||t.responsavelId,u=usuarios.find(x=>x.id===rid),d={status:status?.value||t.status,observacao:obs?.value.trim()||""};if(podeGerir()){d.responsavelId=rid;d.responsavelNome=u?.nome||u?.email||rid;if(modo()==="mensal")d.prazo=prazo?.value||t.prazo}try{await atualizarDocumento("fechamentoTarefas",id,d);await carregar()}catch(e){console.error(e);alert("Não foi possível atualizar a etapa.")}}
async function alternarFechamento(){if(!podeFechar())return;const cab=cabAtual(),arr=tarefasAtuais();if(!cab)return alert("Crie o checklist primeiro.");const fechado=cab.status==="concluido";if(!fechado&&arr.some(x=>x.status!=="concluido"))return alert("Ainda existem etapas pendentes.");if(!confirm(`${fechado?"Reabrir":"Concluir"} ${labelChave()}?`))return;try{await atualizarDocumento("fechamentosMensais",cab.id,{status:fechado?"aberto":"concluido",fechadoEm:fechado?"":new Date().toISOString(),fechadoPor:fechado?"":state.usuario.id,fechadoPorNome:fechado?"":state.usuario.nome||state.usuario.email||state.usuario.id});await carregar()}catch(e){console.error(e);alert("Não foi possível alterar o fechamento.")}}
async function normalizarDuplicidades(){if(!podeGerir()||normalizando)return;const dups=duplicidadesDaCompetencia();if(!dups.length)return;if(!confirm(`Arquivar ${dups.length} duplicidade(s) desta competência? O histórico será preservado.`))return;normalizando=true;try{const batch=writeBatch(db);dups.forEach(x=>batch.update(doc(db,"fechamentoTarefas",x.id),{duplicadoArquivado:true,arquivadoPor:state.usuario.id,arquivadoEm:serverTimestamp(),atualizadoEm:serverTimestamp()}));await batch.commit();await carregar()}catch(e){console.error(e);msg($("mensagemClosingV3"),"Não foi possível limpar as duplicidades.")}finally{normalizando=false}}
function modeloConfiguravel(tipo){const cfg=configAtual(),campo=campoModelo(tipo);return Array.isArray(cfg?.[campo])?[...cfg[campo]]:basePadrao(tipo)}
async function persistirModelo(tipo,arr,mensagem){const cfg=configAtual(),campo=campoModelo(tipo);if(cfg)await atualizarDocumento("configuracoesControladoria",cfg.id,{[campo]:arr});else await criarDocumento("configuracoesControladoria",{[campo]:arr});await carregar();msg($("mensagemClosingModeloV3"),mensagem,true)}
function compDoCab(cab){return cab?.competencia||""}
function cabDoTipo(cab,tipo){return(tipo==="mensal"&&!String(cab?.competencia||"").startsWith("ANUAL-"))||(tipo==="anual"&&String(cab?.competencia||"").startsWith("ANUAL-"))}
async function sincronizarModeloExistente(item,tipo,desde,ativo){const afetados=cabecalhos.filter(c=>cabDoTipo(c,tipo)&&String(refDaCompetencia(compDoCab(c),tipo))>=String(desde));if(!afetados.length)return;const batch=writeBatch(db),grupoId=grupoAtualId(),emp=empresa(),u=usuarios[0]||state.usuario;for(const cab of afetados){const comp=cab.competencia,existentes=tarefas.filter(t=>t.competencia===comp&&t.tarefaId===item.id&&t.duplicadoArquivado!==true);if(ativo){if(existentes.length)existentes.forEach(t=>batch.update(doc(db,"fechamentoTarefas",t.id),{modeloInativo:false,atualizadoEm:serverTimestamp()}));else{const idx=modelosAtivos(tipo,refDaCompetencia(comp,tipo)).findIndex(x=>x.id===item.id),ordem=idx>=0?idx+1:n(item.ordem||item.dia||1);batch.set(doc(db,"fechamentoTarefas",tarefaIdDoc(comp,item.id)),{grupoId,empresaId:emp,competencia:comp,tarefaId:item.id,titulo:item.titulo,ordem,diaFechamento:tipo==="mensal"?n(item.dia||ordem):ordem,prazo:tipo==="mensal"?dataDmais(comp,n(item.dia||ordem)):"",responsavelId:u.id,responsavelNome:u.nome||u.email||u.id,status:"aberto",observacao:"",tipoFechamento:tipo,modeloInativo:false,criadoPor:state.usuario.id,criadoEm:serverTimestamp(),atualizadoEm:serverTimestamp()},{merge:true})}}else existentes.forEach(t=>batch.update(doc(db,"fechamentoTarefas",t.id),{modeloInativo:true,modeloAlteradoDesde:desde,atualizadoEm:serverTimestamp()}))}await batch.commit()}
async function salvarModelo(e){e.preventDefault();if(!podeConfigurar())return;const tipo=$("closingModeloTipoV3").value,titulo=$("closingModeloTituloV3").value.trim(),dia=Math.max(1,n($("closingModeloDiaV3").value)||1),desde=refAtual(tipo);if(!titulo)return;const atual=modeloConfiguravel(tipo),item={id:`custom_${Date.now()}`,titulo,dia,ativo:true,origem:"custom",vigencias:[{desde,ativo:true}]};atual.push(item);try{await persistirModelo(tipo,atual,`Etapa adicionada a partir de ${tipo==="mensal"?desde.split("-").reverse().join("/"):desde}.`);$("closingModeloTituloV3").value="";await sincronizarModeloExistente(item,tipo,desde,true);await carregar()}catch(err){console.error(err);msg($("mensagemClosingModeloV3"),"Não foi possível atualizar o modelo.")}}
async function alterarVigenciaModelo(id,tipo){if(!podeConfigurar())return;const desde=refAtual(tipo),atual=modeloConfiguravel(tipo),i=atual.findIndex(x=>x.id===id);if(i<0)return;const st=estadoNoPeriodo(atual[i],tipo,desde),novo=!st.ativo;if(!confirm(`${novo?"Ativar":"Inativar"} “${atual[i].titulo}” a partir de ${tipo==="mensal"?desde.split("-").reverse().join("/"):desde}?`))return;atual[i]={...atual[i],vigencias:[...(Array.isArray(atual[i].vigencias)?atual[i].vigencias:[]),{desde,ativo:novo}]};try{const item=atual[i];await persistirModelo(tipo,atual,`${novo?"Ativada":"Inativada"} a partir do período selecionado.`);await sincronizarModeloExistente(item,tipo,desde,novo);await carregar()}catch(e){console.error(e);msg($("mensagemClosingModeloV3"),"Não foi possível alterar a vigência.")}}
async function excluirModelo(id,tipo){if(!podeConfigurar())return;const desde=refAtual(tipo),atual=modeloConfiguravel(tipo),i=atual.findIndex(x=>x.id===id);if(i<0)return;if(!confirm(`Excluir “${atual[i].titulo}” de ${tipo==="mensal"?desde.split("-").reverse().join("/"):desde} em diante? Períodos anteriores serão preservados.`))return;atual[i]={...atual[i],excluidoDesde:desde};try{const item=atual[i];await persistirModelo(tipo,atual,"Etapa excluída somente dos períodos atuais/futuros.");await sincronizarModeloExistente(item,tipo,desde,false);await carregar()}catch(e){console.error(e);msg($("mensagemClosingModeloV3"),"Não foi possível excluir a etapa do modelo.")}}

export function abrir(){criarPagina();abrirPagina("closing-v3");const t=$("tituloPagina");if(t)t.textContent="Cockpit de Fechamento";carregar()}
criarPagina();window.addEventListener("sig:empresa-changed",()=>{if(pagina()&&!pagina().classList.contains("hidden"))carregar()});
