import { EmailAuthProvider, reauthenticateWithCredential } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js";
import { collection, addDoc, updateDoc, deleteDoc, doc, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";
import { $, on, esc, norm, msg, auth, db, state, abrirPagina, carregarAdmin, atualizarResumo } from "./core.js";

let editId=null, excluir=null;
const form=$("formEmpresa"),box=$("formEmpresaContainer"),titulo=$("tituloFormEmpresa"),razao=$("empresaRazaoSocial"),fantasia=$("empresaNomeFantasia"),cnpj=$("empresaCnpj"),mensagem=$("mensagemEmpresa"),lista=$("listaEmpresas"),qtd=$("quantidadeEmpresas"),busca=$("buscaEmpresa"),modal=$("modalExcluirEmpresa"),nomeExcluir=$("nomeEmpresaExcluir"),formExcluir=$("formConfirmarExclusaoEmpresa"),senhaExcluir=$("senhaExclusaoEmpresa"),msgExcluir=$("mensagemExclusaoEmpresa");

function fmt(v){const n=String(v||"").replace(/\D/g,"").slice(0,14);return n.replace(/^(\d{2})(\d)/,"$1.$2").replace(/^(\d{2})\.(\d{3})(\d)/,"$1.$2.$3").replace(/\.(\d{3})(\d)/,".$1/$2").replace(/(\d{4})(\d)/,"$1-$2")}
function valido(v){const c=String(v||"").replace(/\D/g,"");if(c.length!==14||/^(\d)\1{13}$/.test(c))return false;const calc=b=>{let p=b.length-7,s=0;for(const n of b){s+=Number(n)*p--;if(p<2)p=9}const r=s%11;return r<2?0:11-r};const d1=calc(c.slice(0,12)),d2=calc(c.slice(0,12)+d1);return c===c.slice(0,12)+d1+d2}
function limpar(){editId=null;form?.reset();if(titulo)titulo.textContent="Nova empresa";msg(mensagem,"")}
function abrir(e=null){limpar();if(e){editId=e.id;if(titulo)titulo.textContent="Editar empresa";razao.value=e.razaoSocial||"";fantasia.value=e.nomeFantasia||"";cnpj.value=e.cnpj||""}box?.classList.remove("hidden");razao?.focus()}
function temVinculo(id){const vinc=[...state.usuarios.values()].some(u=>u.empresaId===id||(Array.isArray(u.empresasAcesso)&&u.empresasAcesso.includes(id)));const e=state.empresas.get(id);return vinc||e?.possuiMovimento===true||Number(e?.movimentosCount||0)>0}

export function renderEmpresas(filtro=""){const t=norm(filtro);const arr=[...state.empresas.values()].filter(e=>!t||[e.razaoSocial,e.nomeFantasia,e.cnpj].some(v=>norm(v).includes(t))).sort((a,b)=>String(a.nomeFantasia||a.razaoSocial||"").localeCompare(String(b.nomeFantasia||b.razaoSocial||""),"pt-BR"));if(qtd)qtd.textContent=`${state.empresas.size} empresa(s) cadastrada(s)`;if(!lista)return;if(!arr.length){lista.innerHTML='<tr><td colspan="4">Nenhuma empresa encontrada.</td></tr>';return}lista.innerHTML=arr.map(e=>`<tr><td class="celula-principal"><strong>${esc(e.nomeFantasia||e.razaoSocial)}</strong><span>${esc(e.razaoSocial)}</span></td><td>${esc(e.cnpj)}</td><td><span class="${e.ativo===true?"status-ativo":"status-inativo"}">${e.ativo===true?"Ativa":"Inativa"}</span></td><td><div class="acoes-tabela"><button class="btn-acao destaque" data-ee="${e.id}" type="button">Editar</button><button class="btn-acao" data-es="${e.id}" type="button">${e.ativo===true?"Inativar":"Reativar"}</button><button class="btn-acao perigo" data-ex="${e.id}" type="button">Excluir</button></div></td></tr>`).join("");document.querySelectorAll("[data-ee]").forEach(b=>on(b,"click",()=>abrir(state.empresas.get(b.dataset.ee))));document.querySelectorAll("[data-es]").forEach(b=>on(b,"click",()=>status(b.dataset.es)));document.querySelectorAll("[data-ex]").forEach(b=>on(b,"click",()=>prepararExclusao(b.dataset.ex)))}
export async function carregarEmpresas(){if(lista)lista.innerHTML='<tr><td colspan="4">Carregando empresas...</td></tr>';try{await carregarAdmin();renderEmpresas(busca?.value||"")}catch(e){console.error(e);if(lista)lista.innerHTML='<tr><td colspan="4">Não foi possível carregar as empresas.</td></tr>'}}

on($("cardEmpresas"),"click",async()=>{abrirPagina("empresas");await carregarEmpresas()});
on($("btnNovaEmpresa"),"click",()=>abrir());on($("btnCancelarEmpresa"),"click",()=>{limpar();box?.classList.add("hidden")});on(cnpj,"input",()=>{cnpj.value=fmt(cnpj.value)});on(busca,"input",()=>renderEmpresas(busca.value));
on(form,"submit",async ev=>{ev.preventDefault();const r=razao.value.trim(),f=fantasia.value.trim(),c=fmt(cnpj.value),num=c.replace(/\D/g,"");if(!valido(c))return msg(mensagem,"Informe um CNPJ válido.");if([...state.empresas.values()].some(e=>e.id!==editId&&String(e.cnpj||"").replace(/\D/g,"")===num))return msg(mensagem,"Já existe uma empresa com este CNPJ.");if(!state.usuario?.grupoId)return msg(mensagem,"Seu usuário não está vinculado a um grupo empresarial.");try{msg(mensagem,"Salvando...");const dados={razaoSocial:r,nomeFantasia:f,cnpj:c,cnpjNumeros:num,grupoId:state.usuario.grupoId,atualizadoEm:serverTimestamp()};if(editId)await updateDoc(doc(db,"empresas",editId),dados);else await addDoc(collection(db,"empresas"),{...dados,ativo:true,criadoEm:serverTimestamp()});msg(mensagem,editId?"Empresa atualizada com sucesso.":"Empresa cadastrada com sucesso.",true);await carregarEmpresas();await atualizarResumo();setTimeout(()=>{limpar();box?.classList.add("hidden")},600)}catch(e){console.error(e);msg(mensagem,"Não foi possível salvar a empresa.")}});
async function status(id){const e=state.empresas.get(id);if(!e)return;const novo=e.ativo!==true;if(!confirm(`Deseja ${novo?"reativar":"inativar"} ${e.nomeFantasia||e.razaoSocial}?`))return;try{await updateDoc(doc(db,"empresas",id),{ativo:novo,atualizadoEm:serverTimestamp()});await carregarEmpresas();await atualizarResumo()}catch(err){console.error(err);alert("Não foi possível alterar o status da empresa.")}}
async function prepararExclusao(id){await carregarAdmin();if(temVinculo(id))return alert("Esta empresa possui vínculos ou histórico e não pode ser excluída. Use Inativar.");excluir=state.empresas.get(id);if(!excluir)return;if(nomeExcluir)nomeExcluir.textContent=excluir.nomeFantasia||excluir.razaoSocial;if(senhaExcluir)senhaExcluir.value="";msg(msgExcluir,"");modal?.classList.remove("hidden")}
function fechar(){excluir=null;formExcluir?.reset();msg(msgExcluir,"");modal?.classList.add("hidden")}
on($("btnCancelarExclusaoEmpresa"),"click",fechar);on(modal,"click",e=>{if(e.target===modal)fechar()});
on(formExcluir,"submit",async ev=>{ev.preventDefault();if(!excluir||!auth.currentUser?.email)return;try{msg(msgExcluir,"Validando administrador...");await carregarAdmin();if(temVinculo(excluir.id))return msg(msgExcluir,"A empresa possui vínculo e não pode mais ser excluída.");await reauthenticateWithCredential(auth.currentUser,EmailAuthProvider.credential(auth.currentUser.email,senhaExcluir.value));await deleteDoc(doc(db,"empresas",excluir.id));fechar();await carregarEmpresas();await atualizarResumo();alert("Empresa excluída permanentemente.")}catch(e){console.error(e);msg(msgExcluir,["auth/invalid-credential","auth/wrong-password"].includes(e.code)?"Senha incorreta.":"Não foi possível concluir a exclusão.")}});
