import { $, on, esc, norm, msg, permite, state, moeda, dataBr, diasAte, preencherEmpresaSelect, listarDocumentos, criarDocumento, atualizarDocumento, excluirDocumento, emitirAlteracao, abrirBox, fecharBox, confirmar } from "./shared.js";
import { uploadArquivo } from "./storage.js";

let dados=[],centros=[],editId=null;
const box=$("formContratoContainer"),form=$("formContrato"),titulo=$("tituloFormContrato"),mensagem=$("mensagemContrato"),lista=$("listaContratos"),busca=$("buscaContrato"),qtd=$("quantidadeContratos"),empresa=$("contratoEmpresa"),numero=$("contratoNumero"),fornecedor=$("contratoFornecedor"),objeto=$("contratoObjeto"),inicio=$("contratoInicio"),fim=$("contratoFim"),valorCampo=$("contratoValor"),responsavel=$("contratoResponsavel"),status=$("contratoStatus"),reajuste=$("contratoReajuste"),obs=$("contratoObservacoes");

function montarCampos(){
  const grid=form?.querySelector(".form-grid");if(!grid||$("contratoCentroCusto"))return;
  const campoEmpresa=empresa?.closest(".campo");
  const cc=document.createElement("div");cc.className="campo";cc.innerHTML='<label for="contratoCentroCusto">Centro de custo</label><select id="contratoCentroCusto"><option value="">Sem centro específico</option></select>';
  const arq=document.createElement("div");arq.className="campo campo-span-2";arq.innerHTML='<label for="contratoArquivo">Arquivo do contrato</label><input id="contratoArquivo" type="file" accept=".pdf,.doc,.docx,.xls,.xlsx,.jpg,.jpeg,.png"><small id="contratoArquivoAtual" class="arquivo-atual"></small>';
  if(campoEmpresa){campoEmpresa.after(cc);cc.after(arq)}else{grid.prepend(arq);grid.prepend(cc)}
  const head=form.closest("section")?.nextElementSibling?.querySelector("thead tr");
  if(head)head.innerHTML="<th>Contrato</th><th>Centro de custo</th><th>Vigência</th><th>Valor mensal</th><th>Status</th><th>Ações</th>";
}
montarCampos();
const centro=()=>$("contratoCentroCusto"),arquivo=()=>$("contratoArquivo"),arquivoAtual=()=>$("contratoArquivoAtual");
function centroNome(id){const c=centros.find(x=>x.id===id);return c?`${c.codigo||""}${c.codigo?" · ":""}${c.nome||""}`:"-"}
function preencherCentros(valor=""){const el=centro();if(!el)return;el.innerHTML='<option value="">Sem centro específico</option>'+centros.filter(x=>x.status!=="inativo").sort((a,b)=>String(a.codigo||"").localeCompare(String(b.codigo||""),"pt-BR")).map(x=>`<option value="${x.id}">${esc(x.codigo||"")} · ${esc(x.nome||"")}</option>`).join("");el.value=valor||""}

function limpar(){editId=null;form?.reset();preencherCentros();if(titulo)titulo.textContent="Novo contrato";if(arquivoAtual())arquivoAtual().innerHTML="";msg(mensagem,"")}
async function abrir(item=null){limpar();await preencherEmpresaSelect(empresa,{valorAtual:item?.empresaId||state.usuario?.empresaId});if(item){editId=item.id;titulo.textContent="Editar contrato";numero.value=item.numero||"";fornecedor.value=item.fornecedor||"";objeto.value=item.objeto||"";inicio.value=item.inicio||"";fim.value=item.fim||"";valorCampo.value=Number(item.valorMensal||0);responsavel.value=item.responsavel||"";status.value=item.status||"ativo";reajuste.value=item.reajuste||"";obs.value=item.observacoes||"";empresa.value=item.empresaId||"";preencherCentros(item.centroCustoId||"");if(item.arquivoPrincipal?.url&&arquivoAtual())arquivoAtual().innerHTML=`Arquivo atual: <a href="${esc(item.arquivoPrincipal.url)}" target="_blank" rel="noopener">${esc(item.arquivoPrincipal.nome||"Abrir arquivo")}</a>`}abrirBox(box,objeto);box?.scrollIntoView({behavior:"smooth",block:"start"})}
function statusContrato(item){if(item.status==="encerrado")return'<span class="status-inativo">Encerrado</span>';if(item.status==="suspenso")return'<span class="status-aviso">Suspenso</span>';const d=diasAte(item.fim);if(d!==null&&d<0)return'<span class="status-inativo">Vencido</span>';if(d!==null&&d<=60)return'<span class="status-aviso">A vencer</span>';return'<span class="status-ativo">Ativo</span>'}
function render(filtro=""){
 const t=norm(filtro),arr=dados.filter(x=>!t||[x.numero,x.fornecedor,x.objeto,x.responsavel,centroNome(x.centroCustoId)].some(v=>norm(v).includes(t))).sort((a,b)=>String(a.fim||"9999").localeCompare(String(b.fim||"9999")));
 const ativos=dados.filter(x=>x.status==="ativo"&&((diasAte(x.fim)??1)>=0));const av=ativos.filter(x=>{const d=diasAte(x.fim);return d!==null&&d<=60});const venc=dados.filter(x=>x.status==="ativo"&&(diasAte(x.fim)??0)<0);
 $("contratosAtivos").textContent=ativos.length;$("contratosAVencer").textContent=av.length;$("contratosVencidos").textContent=venc.length;$("contratosValorMensal").textContent=moeda(ativos.reduce((s,x)=>s+Number(x.valorMensal||0),0));if(qtd)qtd.textContent=`${dados.length} contrato(s) cadastrado(s)`;
 if(!lista)return;if(!arr.length){lista.innerHTML='<tr><td colspan="6">Nenhum contrato encontrado.</td></tr>';return}
 lista.innerHTML=arr.map(x=>`<tr><td class="celula-principal"><strong>${esc(x.numero||x.fornecedor||"Contrato")}</strong><span>${esc(x.objeto||"")}</span></td><td>${esc(centroNome(x.centroCustoId))}</td><td>${dataBr(x.inicio)} → ${dataBr(x.fim)}</td><td>${moeda(x.valorMensal)}</td><td>${statusContrato(x)}</td><td><div class="acoes-tabela">${x.arquivoPrincipal?.url?`<a class="btn-acao" href="${esc(x.arquivoPrincipal.url)}" target="_blank" rel="noopener">Arquivo</a>`:""}${permite("contratos","editar")?`<button class="btn-acao destaque" data-ctr-edit="${x.id}" type="button">Editar</button>`:""}${permite("contratos","excluir")?`<button class="btn-acao perigo" data-ctr-del="${x.id}" type="button">Excluir</button>`:""}</div></td></tr>`).join("");
 document.querySelectorAll("[data-ctr-edit]").forEach(b=>on(b,"click",()=>abrir(dados.find(x=>x.id===b.dataset.ctrEdit))));document.querySelectorAll("[data-ctr-del]").forEach(b=>on(b,"click",()=>remover(b.dataset.ctrDel)));
}
export async function carregarContratos(){if(!permite("contratos"))return;if(lista)lista.innerHTML='<tr><td colspan="6">Carregando contratos...</td></tr>';try{await preencherEmpresaSelect(empresa);[dados,centros]=await Promise.all([listarDocumentos("contratos"),listarDocumentos("centrosCusto")]);preencherCentros();render(busca?.value||"")}catch(e){console.error(e);if(lista)lista.innerHTML='<tr><td colspan="6">Não foi possível carregar os contratos.</td></tr>'}}
async function remover(id){const item=dados.find(x=>x.id===id);if(!item||!confirmar(`Excluir o contrato ${item.numero||item.fornecedor}?`))return;try{await excluirDocumento("contratos",id);await carregarContratos();emitirAlteracao("contratos")}catch(e){console.error(e);alert("Não foi possível excluir o contrato.")}}

on($("btnNovoContrato"),"click",()=>abrir());on($("btnCancelarContrato"),"click",()=>{limpar();box?.classList.add("hidden")});on(busca,"input",()=>render(busca.value));
on(form,"submit",async ev=>{ev.preventDefault();const d={empresaId:empresa.value,numero:numero.value.trim(),fornecedor:fornecedor.value.trim(),objeto:objeto.value.trim(),inicio:inicio.value,fim:fim.value,valorMensal:Number(valorCampo.value||0),responsavel:responsavel.value.trim(),status:status.value,reajuste:reajuste.value,observacoes:obs.value.trim(),centroCustoId:centro()?.value||""};if(!d.empresaId||!d.fornecedor||!d.objeto||!d.inicio||!d.fim)return msg(mensagem,"Preencha fornecedor, objeto e vigência.");if(d.fim<d.inicio)return msg(mensagem,"A data de término não pode ser anterior ao início.");try{msg(mensagem,"Salvando contrato...");let id=editId;if(editId)await atualizarDocumento("contratos",editId,d);else id=await criarDocumento("contratos",d);const f=arquivo()?.files?.[0];if(f){msg(mensagem,"Enviando arquivo...");const meta=await uploadArquivo({modulo:"contratos",registroId:id,arquivo:f,pasta:"principal"});await atualizarDocumento("contratos",id,{arquivoPrincipal:meta})}msg(mensagem,"Contrato salvo com sucesso.",true);await carregarContratos();emitirAlteracao("contratos");setTimeout(()=>fecharBox(box,form,mensagem),500)}catch(e){console.error(e);msg(mensagem,e?.code?.includes("storage")?"Contrato salvo, mas o Firebase Storage ainda precisa ser habilitado para anexos.":"Não foi possível salvar o contrato.")}});
window.addEventListener("sig:page",e=>{if(e.detail?.pagina==="contratos")carregarContratos()});
window.addEventListener("sig:empresa-changed",()=>{if(!box?.classList.contains("hidden"))limpar()});
