import { $, on, esc, norm, msg, permite, state, moeda, competenciaAtual, preencherEmpresaSelect, listarDocumentos, criarDocumento, atualizarDocumento, emitirAlteracao, abrirBox, fecharBox } from "./shared.js";
let linhas=[],editId=null;
const box=$("formLinhaGerencialContainer"),form=$("formLinhaGerencial"),titulo=$("tituloFormLinhaGerencial"),mensagem=$("mensagemLinhaGerencial"),lista=$("listaLinhasGerenciais"),busca=$("buscaLinhaGerencial"),qtd=$("quantidadeLinhasGerenciais"),filtroComp=$("controladoriaCompetenciaFiltro"),filtroEmpresa=$("controladoriaEmpresaFiltro"),empresa=$("ctrlEmpresa"),comp=$("ctrlCompetencia"),grupo=$("ctrlGrupoDre"),conta=$("ctrlConta"),natureza=$("ctrlNatureza"),orcado=$("ctrlOrcado"),forecast=$("ctrlForecast"),realizado=$("ctrlRealizado"),d30=$("ctrlD30Input"),d60=$("ctrlD60Input"),d90=$("ctrlD90Input"),obs=$("ctrlObservacao");
const grupos={receita:"Receita",custos:"Custos",despesas:"Despesas Operacionais",financeiro:"Resultado Financeiro",impostos:"Impostos",outros:"Outros"};
const podeEditar=()=>permite("controladoria","editar")||permite("controladoria","budget")||permite("controladoria","forecast")||permite("controladoria","importar");
function limpar(){editId=null;form?.reset();if(titulo)titulo.textContent="Nova linha gerencial";msg(mensagem,"");comp.value=filtroComp.value||competenciaAtual()}
async function abrir(item=null){limpar();await preencherEmpresaSelect(empresa,{valorAtual:item?.empresaId||state.usuario?.empresaId});if(item){editId=item.id;titulo.textContent="Editar linha gerencial";empresa.value=item.empresaId||"";comp.value=item.competencia||competenciaAtual();grupo.value=item.grupoDre||"despesas";conta.value=item.conta||"";natureza.value=item.natureza||"despesa";orcado.value=Number(item.orcado||0);forecast.value=Number(item.forecast||0);realizado.value=Number(item.realizado||0);d30.value=Number(item.caixaD30||0);d60.value=Number(item.caixaD60||0);d90.value=Number(item.caixaD90||0);obs.value=item.observacao||""}abrirBox(box,conta);box?.scrollIntoView({behavior:"smooth",block:"start"})}
function assinada(x,campo){const n=Number(x[campo]||0);return x.natureza==="receita"?n:-n}
function filtro(){return linhas.filter(x=>(!filtroComp.value||x.competencia===filtroComp.value)&&(!filtroEmpresa.value||x.empresaId===filtroEmpresa.value))}
function pctVar(real,budget){if(!budget)return real?100:0;return((real-budget)/Math.abs(budget))*100}
function render(){const base=filtro(),t=norm(busca?.value||""),arr=base.filter(x=>!t||norm(x.conta).includes(t)).sort((a,b)=>String(a.grupoDre||"").localeCompare(String(b.grupoDre||""))||String(a.conta||"").localeCompare(String(b.conta||""),"pt-BR"));const rec=base.filter(x=>x.natureza==="receita").reduce((s,x)=>s+Number(x.realizado||0),0),desp=base.filter(x=>x.natureza!=="receita").reduce((s,x)=>s+Number(x.realizado||0),0),res=rec-desp,budgetRes=base.reduce((s,x)=>s+assinada(x,"orcado"),0),variacao=pctVar(res,budgetRes);$("ctrlReceita").textContent=moeda(rec);$("ctrlDespesa").textContent=moeda(desp);$("ctrlResultado").textContent=moeda(res);$("ctrlVariacao").textContent=`${variacao.toLocaleString("pt-BR",{maximumFractionDigits:1})}%`;$("ctrlVariacao").className=variacao<0?"desvio-negativo":"desvio-positivo";$("ctrlD30").textContent=moeda(base.reduce((s,x)=>s+assinada(x,"caixaD30"),0));$("ctrlD60").textContent=moeda(base.reduce((s,x)=>s+assinada(x,"caixaD60"),0));$("ctrlD90").textContent=moeda(base.reduce((s,x)=>s+assinada(x,"caixaD90"),0));$("ctrlResumoCompetencia").textContent=filtroComp.value?`Competência ${filtroComp.value.split("-").reverse().join("/")}`:"Todas as competências";if(qtd)qtd.textContent=`${base.length} linha(s) na visão selecionada`;
 const dre=$("ctrlDreResumo");if(dre){const linhasGrupo=Object.entries(grupos).map(([id,nome])=>{const g=base.filter(x=>x.grupoDre===id);if(!g.length)return"";const b=g.reduce((s,x)=>s+assinada(x,"orcado"),0),f=g.reduce((s,x)=>s+assinada(x,"forecast"),0),r=g.reduce((s,x)=>s+assinada(x,"realizado"),0);return`<div class="dre-linha"><strong>${esc(nome)}</strong><div class="dre-valores"><span title="Budget">B ${moeda(b)}</span><span title="Forecast">F ${moeda(f)}</span><span title="Realizado">R ${moeda(r)}</span></div></div>`}).join("");dre.innerHTML=(linhasGrupo||'<div class="empty-state">Sem dados para a competência.</div>')+`<div class="dre-linha dre-linha-total"><strong>Resultado</strong><div class="dre-valores"><span>B ${moeda(budgetRes)}</span><span>F ${moeda(base.reduce((s,x)=>s+assinada(x,"forecast"),0))}</span><span>R ${moeda(res)}</span></div></div>`}
 const desv=$("ctrlDesvios");if(desv){const d=base.map(x=>({x,p:pctVar(Number(x.realizado||0),Number(x.orcado||0))})).filter(o=>Math.abs(o.p)>=5&&Number(o.x.orcado||0)!==0).sort((a,b)=>Math.abs(b.p)-Math.abs(a.p)).slice(0,12);desv.innerHTML=d.length?d.map(({x,p})=>`<div class="desvio-item"><div class="pendencia-info"><strong>${esc(x.conta)}</strong><span>${moeda(x.realizado)} realizado · ${moeda(x.orcado)} budget</span></div><span class="${p<0?"desvio-negativo":"desvio-positivo"}">${p>0?"+":""}${p.toLocaleString("pt-BR",{maximumFractionDigits:1})}%</span></div>`).join(""):'<div class="empty-state">Nenhuma linha com desvio acima de 5%.</div>'}
 if(!lista)return;if(!arr.length){lista.innerHTML='<tr><td colspan="6">Nenhuma linha gerencial encontrada.</td></tr>';return}lista.innerHTML=arr.map(x=>{const p=pctVar(Number(x.realizado||0),Number(x.orcado||0));return`<tr><td class="celula-principal"><strong>${esc(x.conta)}</strong><span>${esc(grupos[x.grupoDre]||x.grupoDre)} · ${esc(x.competencia)}</span></td><td class="numero">${moeda(x.orcado)}</td><td class="numero">${moeda(x.forecast)}</td><td class="numero">${moeda(x.realizado)}</td><td class="numero ${p<0?"desvio-negativo":"desvio-positivo"}">${p>0?"+":""}${p.toLocaleString("pt-BR",{maximumFractionDigits:1})}%</td><td>${podeEditar()?`<button class="btn-acao destaque" data-ctrl-edit="${x.id}" type="button">Editar</button>`:""}</td></tr>`}).join("");document.querySelectorAll("[data-ctrl-edit]").forEach(b=>on(b,"click",()=>abrir(linhas.find(x=>x.id===b.dataset.ctrlEdit))))}
export async function carregarControladoria(){if(!permite("controladoria"))return;try{if(!filtroComp.value)filtroComp.value=competenciaAtual();await Promise.all([preencherEmpresaSelect(empresa),preencherEmpresaSelect(filtroEmpresa,{todas:true,valorAtual:filtroEmpresa.value})]);linhas=await listarDocumentos("planejamentoMensal");render()}catch(e){console.error(e);if(lista)lista.innerHTML='<tr><td colspan="6">Não foi possível carregar os dados gerenciais.</td></tr>'}}
on($("btnNovaLinhaGerencial"),"click",()=>abrir());on($("btnCancelarLinhaGerencial"),"click",()=>{limpar();box?.classList.add("hidden")});on(filtroComp,"change",render);on(filtroEmpresa,"change",render);on(busca,"input",render);on(grupo,"change",()=>{natureza.value=grupo.value==="receita"?"receita":"despesa"});
on(form,"submit",async ev=>{ev.preventDefault();const d={empresaId:empresa.value,competencia:comp.value,grupoDre:grupo.value,conta:conta.value.trim(),natureza:natureza.value,orcado:Number(orcado.value||0),forecast:Number(forecast.value||0),realizado:Number(realizado.value||0),caixaD30:Number(d30.value||0),caixaD60:Number(d60.value||0),caixaD90:Number(d90.value||0),observacao:obs.value.trim()};if(!d.empresaId||!d.competencia||!d.conta)return msg(mensagem,"Informe empresa, competência e conta gerencial.");try{msg(mensagem,"Salvando...");if(editId)await atualizarDocumento("planejamentoMensal",editId,d);else await criarDocumento("planejamentoMensal",d);msg(mensagem,"Linha gerencial salva.",true);filtroComp.value=d.competencia;await carregarControladoria();emitirAlteracao("controladoria");setTimeout(()=>fecharBox(box,form,mensagem),500)}catch(e){console.error(e);msg(mensagem,"Não foi possível salvar a linha gerencial.")}});window.addEventListener("sig:page",e=>{if(e.detail?.pagina==="controladoria")carregarControladoria()});
