import { initializeApp } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js";
import { getAuth, signInWithEmailAndPassword, signOut, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js";
import { getFirestore, doc, getDoc, collection, getDocs } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyDhFhXmyg44MqDkMHxgwVJ4DxEW-qqiDkU",authDomain:"gestao-de-contratos-b266b.firebaseapp.com",projectId:"gestao-de-contratos-b266b",storageBucket:"gestao-de-contratos-b266b.firebasestorage.app",messagingSenderId:"1090500586579",appId:"1:1090500586579:web:90419b7abe37540eeeeaa6"};
export const app=initializeApp(firebaseConfig);
export const auth=getAuth(app);
export const db=getFirestore(app);
export const firebaseConfigPublic=firebaseConfig;
export const state={usuario:null,perfil:null,grupo:null,empresas:new Map(),usuarios:new Map(),perfis:new Map()};
export const $=id=>document.getElementById(id);
export const on=(el,ev,fn)=>el?.addEventListener(ev,fn);
export const esc=v=>v==null?"-":String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
export const norm=v=>String(v||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim();
export function msg(el,texto,sucesso=false){if(!el)return;el.textContent=texto;el.classList.toggle("sucesso",sucesso)}
export function admin(){return state.perfil?.acessoTotal===true}
export function permite(modulo,acao="visualizar"){return admin()||state.perfil?.permissoes?.[modulo]?.[acao]===true}
export function podeAdministrar(){return admin()||permite("administracao")}

const telaLogin=$("telaLogin"),sistema=$("sistema"),formLogin=$("formLogin"),email=$("email"),senha=$("senha"),mensagemLogin=$("mensagemLogin"),nomeUsuario=$("nomeUsuario"),btnSair=$("btnSair"),tituloPagina=$("tituloPagina"),subtitulo=$("subtituloContexto"),menuDashboard=$("menuDashboard"),menuContratos=$("menuContratos"),menuAdmin=$("menuAdministracao"),btnEntrar=formLogin?.querySelector('button[type="submit"]');
let loginBusy=false;
function setBusy(v,t="Entrando..."){loginBusy=v;if(btnEntrar){btnEntrar.disabled=v;btnEntrar.textContent=v?"Entrando...":"Entrar"}if(v)msg(mensagemLogin,t)}
function erroLogin(e){return {"auth/invalid-credential":"E-mail ou senha inválidos.","auth/user-disabled":"Este acesso foi desativado.","auth/too-many-requests":"Muitas tentativas. Aguarde alguns minutos.","auth/network-request-failed":"Falha de conexão. Verifique sua internet."}[e?.code]||"Não foi possível entrar. Tente novamente."}

export function abrirPagina(nome){const p=$(`pagina-${nome}`);if(!p)return;document.querySelectorAll(".pagina").forEach(x=>x.classList.add("hidden"));p.classList.remove("hidden");document.querySelectorAll(".menu-item").forEach(x=>x.classList.remove("ativo"));const adm=["administracao","empresas","usuarios","perfis","grupo"].includes(nome);(adm?menuAdmin:document.querySelector(`.menu-item[data-pagina="${nome}"]`))?.classList.add("ativo");const tit={dashboard:"Dashboard",contratos:"Contratos",administracao:"Administração",empresas:"Empresas",usuarios:"Usuários",perfis:"Perfis de Acesso",grupo:"Grupo Empresarial"};if(tituloPagina)tituloPagina.textContent=tit[nome]||"SIG";if(subtitulo)subtitulo.textContent=state.grupo?.nome||"Sistema Integrado de Gestão";window.scrollTo({top:0,behavior:"smooth"})}
export function configurarMenus(){menuDashboard?.classList.toggle("hidden",!permite("dashboard"));menuContratos?.classList.toggle("hidden",!permite("contratos"));menuAdmin?.classList.toggle("hidden",!podeAdministrar())}
function primeira(){if(permite("dashboard"))return"dashboard";if(permite("contratos"))return"contratos";if(podeAdministrar())return"administracao";return"dashboard"}
export async function carregarGrupoAtual(){if(!state.usuario?.grupoId){state.grupo=null;return}const s=await getDoc(doc(db,"gruposEmpresariais",state.usuario.grupoId));state.grupo=s.exists()?{id:s.id,...s.data()}:null}
export async function carregarAdmin(){if(!podeAdministrar())return;const[e,u,p]=await Promise.all([getDocs(collection(db,"empresas")),getDocs(collection(db,"usuarios")),getDocs(collection(db,"perfisAcesso"))]);state.empresas=new Map();state.usuarios=new Map();state.perfis=new Map();e.forEach(r=>{const d=r.data();if(!state.usuario?.grupoId||d.grupoId===state.usuario.grupoId)state.empresas.set(r.id,{id:r.id,...d})});u.forEach(r=>{const d=r.data();if(!state.usuario?.grupoId||!d.grupoId||d.grupoId===state.usuario.grupoId)state.usuarios.set(r.id,{id:r.id,...d})});p.forEach(r=>{const d=r.data();if(d.acessoTotal===true||!d.grupoId||d.grupoId===state.usuario?.grupoId)state.perfis.set(r.id,{id:r.id,...d})})}
export async function atualizarResumo(){if(!podeAdministrar())return;try{await carregarAdmin();if($("resumoEmpresas"))$("resumoEmpresas").textContent=state.empresas.size;if($("resumoUsuarios"))$("resumoUsuarios").textContent=[...state.usuarios.values()].filter(x=>x.ativo===true).length;if($("resumoPerfis"))$("resumoPerfis").textContent=[...state.perfis.values()].filter(x=>x.ativo===true).length}catch(e){console.error(e);["resumoEmpresas","resumoUsuarios","resumoPerfis"].forEach(id=>{if($(id))$(id).textContent="—"})}}

on(formLogin,"submit",async ev=>{ev.preventDefault();if(loginBusy)return;const em=email?.value.trim(),pw=senha?.value;if(!em||!pw)return;setBusy(true);try{await signInWithEmailAndPassword(auth,em,pw);msg(mensagemLogin,"Credenciais validadas. Carregando seu acesso...")}catch(e){console.error(e);msg(mensagemLogin,erroLogin(e));setBusy(false)}});
on(btnSair,"click",()=>signOut(auth));
onAuthStateChanged(auth,async user=>{if(!user){state.usuario=state.perfil=state.grupo=null;sistema?.classList.add("hidden");telaLogin?.classList.remove("hidden");if(nomeUsuario)nomeUsuario.textContent="";setBusy(false);return}try{setBusy(true,"Validando seu acesso...");const us=await getDoc(doc(db,"usuarios",user.uid));if(!us.exists())throw new Error("usuario-nao-autorizado");const ud=us.data();if(ud.ativo!==true)throw new Error("usuario-inativo");const ps=await getDoc(doc(db,"perfisAcesso",ud.perfilId));if(!ps.exists()||ps.data().ativo!==true)throw new Error("perfil-indisponivel");state.usuario={id:user.uid,...ud};state.perfil={id:ps.id,...ps.data()};await carregarGrupoAtual();if(state.grupo?.ativo===false)throw new Error("grupo-inativo");telaLogin?.classList.add("hidden");sistema?.classList.remove("hidden");if(nomeUsuario)nomeUsuario.textContent=state.usuario.nome||user.email||"Usuário";if(senha)senha.value="";msg(mensagemLogin,"");setBusy(false);configurarMenus();abrirPagina(primeira());if(podeAdministrar())atualizarResumo()}catch(e){console.error(e);const m={"usuario-nao-autorizado":"Usuário autenticado, mas sem cadastro no SIG.","usuario-inativo":"Este usuário está desativado.","perfil-indisponivel":"Seu perfil de acesso está indisponível.","grupo-inativo":"O grupo empresarial está inativo."};msg(mensagemLogin,m[e.message]||"Não foi possível validar seu acesso.");try{await signOut(auth)}catch{}setBusy(false)}});
document.querySelectorAll(".menu-item").forEach(i=>on(i,"click",async()=>{const p=i.dataset.pagina;if(p==="administracao"&&!podeAdministrar())return;abrirPagina(p);if(p==="administracao")await atualizarResumo()}));
document.querySelectorAll("[data-voltar-admin]").forEach(b=>on(b,"click",async()=>{abrirPagina("administracao");await atualizarResumo()}));
