import { abrirPagina, state, db, admin } from "./core.js";
import { $, esc, msg, permite, listarDocumentos, empresaUnicaSelecionadaId, empresasSelecionadasIds, grupoAtualId, periodoAno, periodoChave, nomeEmpresa } from "./shared.js";
import { writeBatch, doc, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";

const MESES=[["jan","Jan"],["fev","Fev"],["mar","Mar"],["abr","Abr"],["mai","Mai"],["jun","Jun"],["jul","Jul"],["ago","Ago"],["set","Set"],["out","Out"],["nov","Nov"],["dez","Dez"]];
const GRUPOS={receita:"Receita Operacional",deducoes:"Deduções da Receita",custos:"Custos",despesas:"Despesas Operacionais",financeiro:"Resultado Financeiro",impostos:"Impostos",outros:"Outros"};
let plano=[],centros=[],realizados=[],periodos=[],fechamentos=[],config=null,busy=false,sujo=false;
const n=v=>{const x=Number(v||0);return Number.isFinite(x)?x:0};
const stamp=x=>n(x?.atualizadoEm?.seconds||x?.criadoEm?.seconds||0);
const pagina=()=>$("pagina-ctrl-input");
const podeEditar=()=>admin()||permite("controladoria","editar")||permite("controladoria","realizado")||permite("controladoria","importar");
const podeFechar=()=>admin()||permite("controladoria","editar")||permite("controladoria","fecharCompetencia");
function comp(){const p=periodoChave();if(!/^m\d{2}$/.test(p))return null;const i=Number(p.slice(1))-1;return i>=0&&i<12?{i,mes:MESES[i][0],nome:MESES[i][1],chave:`${periodoAno()}-${String(i+1).padStart(2,"0")}`}:null}
function centroDados(){const v=$("inputV2Centro")?.value||"";return v==="__legacy__"?"":v}
function docsConta(contaId,centroId,ano){return realizados.filter(x=>x.contaId===contaId&&(x.centroCustoId||"")===(centroId||"")&&Number(x.exercicio)===Number(ano))}
function valorConta(contaId,centroId,ano,mes){return docsConta(contaId,centroId,ano).reduce((s,x)=>s+n(x.valores?.[mes]),0)}
function periodoDoc(empresaId,chave){return periodos.find(x=>x.empresaId===empresaId&&x.competencia===chave)}
function fechamentoDoc(empresaId,chave){return fechamentos.find(x=>x.empresaId===empresaId&&x.competencia===chave)}
function estadoPeriodo(){const empresaId=empresaUnicaSelecionadaId(),c=comp();if(!empresaId||!c)return{fechado:true,motivo:"Contexto inválido"};const f=fechamentoDoc(empresaId,c.chave),p=periodoDoc(empresaId,c.chave);if(f?.status==="concluido")return{fechado:true,cockpit:true,motivo:"Competência concluída no Cockpit de Fechamento"};if(p?.status==="fechado")return{fechado:true,cockpit:false,motivo:"Competência bloqueada pela Controladoria"};return{fechado:false,cockpit:false,motivo:"Competência aberta para lançamento"}}
function idSeguro(v){return String(v||"sem").replace(/[^a-zA-Z0-9_-]/g,"_")}
function idRealizado(emp,ano,cc,conta){return `r_${idSeguro(emp)}_${ano}_${idSeguro(cc||"sem")}_${idSeguro(conta)}`}
function idPeriodo(emp,chave){return `periodo_${idSeguro(emp)}_${idSeguro(chave)}`}

function criarPagina(){
  if(pagina())return;const main=document.querySelector("main.conteudo");if(!main)return;const p=document.createElement("section");p.id="pagina-ctrl-input";p.className="pagina hidden";p.innerHTML=`
  <div class="pagina-cabecalho"><div><span class="eyebrow">CONTROLADORIA & FP&A</span><h2>Input Mensal</h2><p>Realizado mensal com matriz Centro × Conta, normalização de duplicidades e bloqueio de competência.</p></div><button id="btnAtualizarInputV2" class="btn-secundario" type="button">Atualizar</button></div>
  <div id="inputV2Aviso" class="modulo-aviso"></div>
  <div class="fpa-toolbar"><div class="campo"><label for="inputV2Centro">Centro de custo</label><select id="inputV2Centro"><option value="">Selecione...</option></select></div><div class="campo"><label>Competência</label><div id="inputV2Contexto" class="fpa-contexto-chip">—</div></div><div class="campo"><label>Status</label><div id="inputV2Status" class="fpa-contexto-chip">—</div></div><button id="btnAlternarPeriodoInput" class="btn-secundario" type="button">Fechar competência</button><button id="btnZerarInput" class="btn-secundario" type="button">Zerar valores exibidos</button><button id="btnSalvarInputV2" class="btn-primario" type="button">Salvar competência</button><span id="mensagemInputV2" class="mensagem-form"></span></div>
  <section class="lista-card"><div class="lista-cabecalho"><div><h3 id="inputV2Titulo">Realizado</h3><p id="inputV2Sub">Selecione um centro de custo.</p></div><span id="inputV2Duplicidades"></span></div><div class="fpa-grid-wrap"><table id="tabelaInputV2" class="fpa-grid"><tbody><tr><td>Carregando...</td></tr></tbody></table></div></section>`;main.appendChild(p);
  $("btnAtualizarInputV2")?.addEventListener("click",()=>carregar({preservarCentro:true}));$("inputV2Centro")?.addEventListener("change",render);$("btnSalvarInputV2")?.addEventListener("click",salvar);$("btnZerarInput")?.addEventListener("click",()=>document.querySelectorAll("#tabelaInputV2 [data-input-v2]").forEach(i=>{i.value="0";i.dispatchEvent(new Event("input"))}));$("btnAlternarPeriodoInput")?.addEventListener("click",alternarPeriodo);
}
function contexto(){const emp=empresaUnicaSelecionadaId(),c=comp();if(empresasSelecionadasIds().length!==1)return{ok:false,texto:"Selecione apenas uma empresa no cabeçalho para lançar o realizado."};if(!c)return{ok:false,texto:"Escolha uma competência mensal (Jan–Dez) no cabeçalho. T1/T2/T3/T4 e Total são apenas consultas."};return{ok:true,emp,c}}
function preencherCentros(preservar=""){
  const s=$("inputV2Centro");if(!s)return;const ano=periodoAno(),temLegado=realizados.some(x=>Number(x.exercicio)===ano&&!(x.centroCustoId||"")&&Object.values(x.valores||{}).some(v=>n(v)!==0));s.innerHTML='<option value="">Selecione o centro...</option>'+centros.filter(x=>x.status!=="inativo").sort((a,b)=>String(a.codigo||"").localeCompare(String(b.codigo||""),"pt-BR")).map(x=>`<option value="${esc(x.id)}">${esc(x.codigo||"")} · ${esc(x.nome||"")}</option>`).join("")+(temLegado?'<option value="__legacy__">Sem centro / lançamentos legados</option>':"");if(preservar&&[...s.options].some(o=>o.value===preservar))s.value=preservar
}
function contasVisiveis(){const v=$("inputV2Centro")?.value||"";if(!v)return[];if(v==="__legacy__"){const ids=new Set(realizados.filter(x=>Number(x.exercicio)===periodoAno()&&!(x.centroCustoId||"")).map(x=>x.contaId));return plano.filter(x=>ids.has(x.id))}const centro=centros.find(x=>x.id===v),permitidas=new Set(Array.isArray(centro?.contasPermitidas)?centro.contasPermitidas:[]);return plano.filter(x=>x.status!=="inativo"&&permitidas.has(x.id))}
function render(){
  const t=$("tabelaInputV2");if(!t)return;const cx=contexto();if(!cx.ok){t.innerHTML=`<tbody><tr><td>${esc(cx.texto)}</td></tr></tbody>`;$("inputV2Aviso").textContent=cx.texto;return}const centroV=$("inputV2Centro")?.value||"",cc=centroDados(),ep=estadoPeriodo(),contas=contasVisiveis();$("inputV2Contexto").textContent=`${nomeEmpresa(cx.emp)} · ${cx.c.nome}/${periodoAno()}`;$("inputV2Status").textContent=ep.fechado?`FECHADO · ${ep.motivo}`:"ABERTO";$("inputV2Aviso").innerHTML=ep.fechado?`<strong>Competência bloqueada.</strong> ${esc(ep.motivo)}.`:centroV==="__legacy__"?'<strong>Modo legado.</strong> Aqui aparecem lançamentos antigos sem centro de custo para correção/zeragem.':'Os valores salvos substituem a competência; não são somados ao saldo anterior.';$("btnAlternarPeriodoInput").classList.toggle("hidden",!podeFechar()||ep.cockpit);$("btnAlternarPeriodoInput").textContent=ep.fechado?"Reabrir competência":"Fechar competência";$("btnSalvarInputV2").disabled=!podeEditar()||ep.fechado||!centroV;$("btnZerarInput").disabled=ep.fechado||!centroV;
  if(!centroV){t.innerHTML='<tbody><tr><td>Selecione um centro de custo. Lançamentos antigos sem centro aparecerão como opção “Sem centro / lançamentos legados”.</td></tr></tbody>';return}if(!contas.length){t.innerHTML='<tbody><tr><td>Nenhuma conta disponível para este centro. Configure a matriz Centro × Conta.</td></tr></tbody>';return}
  let dups=0;t.innerHTML=`<thead><tr><th>Conta</th><th>Grupo</th><th>Centro</th><th class="numero">${cx.c.nome}/${periodoAno()}</th><th>Integridade</th></tr></thead><tbody>${contas.map(c=>{const ds=docsConta(c.id,cc,periodoAno()),v=valorConta(c.id,cc,periodoAno(),cx.c.mes);if(ds.length>1)dups+=ds.length-1;return`<tr><td><strong>${esc(c.codigo||"")}</strong><small>${esc(c.nome||"")}</small></td><td>${esc(GRUPOS[c.grupoDre]||c.grupoDre||"-")}</td><td>${centroV==="__legacy__"?"Sem centro / legado":esc(centros.find(x=>x.id===centroV)?.nome||"-")}</td><td class="numero"><input data-input-v2="${esc(c.id)}" data-original="${v}" type="number" step="0.01" value="${v}" ${ep.fechado?"disabled":""}></td><td>${ds.length>1?`<span class="status-atencao">${ds.length} registros · será normalizado ao salvar</span>`:"OK"}</td></tr>`}).join("")}</tbody>`;$("inputV2Titulo").textContent=centroV==="__legacy__"?"Realizado sem centro / legado":`Realizado · ${centros.find(x=>x.id===centroV)?.nome||"Centro"}`;$("inputV2Sub").textContent=`${contas.length} conta(s) · cada salvamento substitui o valor do mês`;$("inputV2Duplicidades").textContent=dups?`${dups} duplicidade(s) detectada(s)`:"Base normalizada";
}
async function carregar({preservarCentro=false}={}){
  criarPagina();if(busy)return;const cx=contexto(),atual=preservarCentro?$("inputV2Centro")?.value||"":"";if(!cx.ok){render();return}busy=true;msg($("mensagemInputV2"),"Carregando...");try{const [p,c,r,ps,fs,cfg]=await Promise.all([listarDocumentos("planoContasGerencial"),listarDocumentos("centrosCusto"),listarDocumentos("realizadoMensal"),listarDocumentos("periodosControladoria"),listarDocumentos("fechamentosMensais"),listarDocumentos("configuracoesControladoria")]);plano=p;centros=c;realizados=r;periodos=ps;fechamentos=fs;config=cfg.find(x=>x.empresaId===cx.emp)||null;preencherCentros(atual);sujo=false;render();msg($("mensagemInputV2"),"")}catch(e){console.error("Input Mensal:",e);msg($("mensagemInputV2"),"Não foi possível carregar o Input Mensal. Verifique as regras do Firebase.")}finally{busy=false}}
async function salvar(){
  const cx=contexto(),centroV=$("inputV2Centro")?.value||"",cc=centroDados(),ep=estadoPeriodo();if(!cx.ok)return msg($("mensagemInputV2"),cx.texto);if(ep.fechado)return msg($("mensagemInputV2"),"Competência fechada. Reabra antes de alterar valores.");if(!centroV)return msg($("mensagemInputV2"),"Selecione o centro de custo.");const inputs=[...document.querySelectorAll("#tabelaInputV2 [data-input-v2]")],alterados=inputs.map(i=>({contaId:i.dataset.inputV2,valor:n(i.value),original:n(i.dataset.original)})).filter(x=>x.valor!==x.original||docsConta(x.contaId,cc,periodoAno()).length>1);if(!alterados.length)return msg($("mensagemInputV2"),"Nenhuma alteração para salvar.",true);
  if(centroV==="__legacy__"&&config?.permitirLancamentoSemCentro!==true){const novos=alterados.filter(x=>!docsConta(x.contaId,"",periodoAno()).length&&x.valor!==0);if(novos.length)return msg($("mensagemInputV2"),"Modo legado não cria novos lançamentos sem centro. Use um centro de custo válido.")}
  const b=$("btnSalvarInputV2");b.disabled=true;b.textContent="Salvando...";try{const batch=writeBatch(db),grupoId=grupoAtualId(),ano=periodoAno(),mes=cx.c.mes;for(const x of alterados){const ds=docsConta(x.contaId,cc,ano).sort((a,b)=>stamp(a)-stamp(b));if(ds.length){batch.update(doc(db,"realizadoMensal",ds[0].id),{[`valores.${mes}`]:x.valor,atualizadoEm:serverTimestamp()});for(const dup of ds.slice(1))batch.update(doc(db,"realizadoMensal",dup.id),{[`valores.${mes}`]:0,atualizadoEm:serverTimestamp(),normalizadoPor:state.usuario.id})}else if(x.valor!==0){batch.set(doc(db,"realizadoMensal",idRealizado(cx.emp,ano,cc,x.contaId)),{grupoId,empresaId:cx.emp,contaId:x.contaId,centroCustoId:cc,exercicio:ano,valores:Object.fromEntries(MESES.map(([m])=>[m,m===mes?x.valor:0])),criadoPor:state.usuario.id,criadoEm:serverTimestamp(),atualizadoEm:serverTimestamp()})}}await batch.commit();msg($("mensagemInputV2"),"Competência salva e duplicidades do mês normalizadas.",true);await carregar({preservarCentro:true})}catch(e){console.error(e);msg($("mensagemInputV2"),"Não foi possível salvar a competência.")}finally{b.disabled=false;b.textContent="Salvar competência"}}
async function alternarPeriodo(){const cx=contexto(),ep=estadoPeriodo();if(!cx.ok||!podeFechar()||ep.cockpit)return;const batch=writeBatch(db),ref=doc(db,"periodosControladoria",idPeriodo(cx.emp,cx.c.chave));batch.set(ref,{grupoId:grupoAtualId(),empresaId:cx.emp,competencia:cx.c.chave,status:ep.fechado?"aberto":"fechado",alteradoPor:state.usuario.id,atualizadoEm:serverTimestamp()},{merge:true});try{await batch.commit();await carregar({preservarCentro:true})}catch(e){console.error(e);msg($("mensagemInputV2"),"Não foi possível alterar o status da competência.")}}
function marcarSujo(){if(!pagina()||pagina().classList.contains("hidden"))return;sujo=true;$("inputV2Aviso").innerHTML='<strong>Filtros do cabeçalho alterados.</strong> Clique em Atualizar para carregar o novo contexto.'}
export function abrir(){criarPagina();abrirPagina("ctrl-input");const t=$("tituloPagina");if(t)t.textContent="Input Mensal";carregar({preservarCentro:true})}
criarPagina();window.addEventListener("sig:periodo-changed",marcarSujo);window.addEventListener("sig:empresa-changed",marcarSujo);
