import { abrirPagina } from "./core.js";
import { $, esc, permite, moeda, listarDocumentos, periodoAno, periodoChave, empresasSelecionadasIds, nomeEmpresa } from "./shared.js";
import { CC_ESTATISTICO_ID, CC_ESTATISTICO_NOME, contaEstatistica, centroEstatisticoSintetico } from "./statistical-center.js";

const MESES=["jan","fev","mar","abr","mai","jun","jul","ago","set","out","nov","dez"];
const NOMES=["Jan","Fev","Mar","Abr","Mai","Jun","Jul","Ago","Set","Out","Nov","Dez"];
const PERIODOS={total:{label:"Total do exercício",indices:[0,1,2,3,4,5,6,7,8,9,10,11]},t1:{label:"T1 · Jan–Mar",indices:[0,1,2]},t2:{label:"T2 · Abr–Jun",indices:[3,4,5]},t3:{label:"T3 · Jul–Set",indices:[6,7,8]},t4:{label:"T4 · Out–Dez",indices:[9,10,11]}};
for(let i=0;i<12;i++)PERIODOS[`m${String(i+1).padStart(2,"0")}`]={label:NOMES[i],indices:[i]};
const GRUPOS=[["receita","RECEITAS"],["deducoes","DEDUÇÕES DA RECEITA"],["custos","CUSTOS INDUSTRIAIS"],["despesas","DESPESAS OPERACIONAIS"],["financeiro","RESULTADO FINANCEIRO"],["impostos","IMPOSTOS"],["outros","OUTROS"]];
let plano=[],centros=[],docs=[],realizados=[],carregando=false,sujo=false;
const expandidas=new Set();
const n=v=>{const x=Number(v||0);return Number.isFinite(x)?x:0};
const stamp=x=>n(x?.atualizadoEm?.seconds||x?.criadoEm?.seconds||0);
const pagina=()=>$("pagina-ctrl-dre-v5");
const visivel=()=>pagina()&&!pagina().classList.contains("hidden");
const ativo=x=>x?.legadoArquivado!==true&&x?.duplicadoArquivado!==true;
function periodo(){return PERIODOS[periodoChave()]||PERIODOS.total}
function idSeguro(v){return String(v||"sem").replace(/[^a-zA-Z0-9_-]/g,"_")}
function centroDoc(d,conta){return contaEstatistica(conta)?CC_ESTATISTICO_ID:(d.centroCustoId||"")}
function chaveDoc(d,conta=null){return`${d.empresaId}|${conta?centroDoc(d,conta):(d.centroCustoId||"")}|${d.contaId}`}
function versaoMaisRecente(arr,ano){const m=new Map();arr.filter(x=>Number(x.exercicio)===Number(ano)&&x.versao).forEach(x=>m.set(x.versao,Math.max(m.get(x.versao)||0,stamp(x))));return[...m.entries()].sort((a,b)=>b[1]-a[1]||String(b[0]).localeCompare(String(a[0]),"pt-BR"))[0]?.[0]||""}
function modoConteudo(){return $("dreV5Conteudo")?.value||"completa"}
function visao(){return $("dreV5Visao")?.value||"por_cc"}
function contextoTexto(){const ids=empresasSelecionadasIds(),p=periodo(),v=visao()==="consolidada"?"Consolidada por conta":"Por Centro de Custo",c=modoConteudo()==="estatisticas"?"Estatísticas":modoConteudo()==="financeira"?"Financeira":"Completa";return`${ids.length>1?`${ids.length} empresas consolidadas`:ids.length===1?nomeEmpresa(ids[0]):"Sem empresa"} · ${v} · ${c} · ${p.label} · ${periodoAno()}`}
function docsCanonicos(arr,cenario,ano,versao=""){const planoMap=new Map(plano.map(x=>[x.id,x])),map=new Map();arr.filter(x=>ativo(x)&&Number(x.exercicio)===Number(ano)&&(!versao||x.versao===versao)).forEach(x=>{const conta=planoMap.get(x.contaId),k=chaveDoc(x,conta),atual=map.get(k);let prefer=false;if(cenario==="realizado"){const cc=contaEstatistica(conta)?CC_ESTATISTICO_ID:(x.centroCustoId||"");const canon=`r_${idSeguro(x.empresaId)}_${ano}_${idSeguro(cc)}_${idSeguro(x.contaId)}`;prefer=x.id===canon||!atual||(atual.id!==canon&&stamp(x)>stamp(atual))}else prefer=!atual||stamp(x)>stamp(atual);if(prefer)map.set(k,x)});return[...map.values()]}
function criarPagina(){if(pagina())return;const main=document.querySelector("main.conteudo");if(!main)return;const s=document.createElement("section");s.id="pagina-ctrl-dre-v5";s.className="pagina hidden";s.innerHTML=`<div class="pagina-cabecalho"><div><span class="eyebrow">CONTROLADORIA & FP&A</span><h2>DRE Gerencial</h2><p>Visão financeira e estatística com a mesma estrutura de Budget e Forecast.</p></div><div class="acoes-cabecalho"><button id="btnExportarDreV5" class="btn-secundario" type="button">Exportar Excel</button><button id="btnImprimirDreV5" class="btn-secundario" type="button">Imprimir / PDF</button><button id="btnAtualizarDreV5" class="btn-primario" type="button">Atualizar</button></div></div><div id="dreV5Aviso" class="modulo-aviso hidden"></div><div class="fpa-toolbar"><div class="campo"><label for="dreV5Cenario">Cenário</label><select id="dreV5Cenario"><option value="realizado">Realizado</option><option value="budget">Budget</option><option value="forecast">Forecast</option></select></div><div class="campo"><label for="dreV5Visao">Visão</label><select id="dreV5Visao"><option value="por_cc">Por Centro de Custo</option><option value="consolidada">Consolidada por conta</option></select></div><div class="campo"><label for="dreV5Conteudo">Conteúdo</label><select id="dreV5Conteudo"><option value="completa">Completa</option><option value="financeira">Financeira</option><option value="estatisticas">Estatísticas</option></select></div><div class="campo"><label for="dreV5Centro">Centro de custo</label><select id="dreV5Centro"><option value="">Todos / consolidado</option></select></div><div class="campo"><label>Contexto</label><div id="dreV5Contexto" class="fpa-contexto-chip">—</div></div></div><section class="lista-card"><div class="lista-cabecalho"><div><h3 id="dreV5Titulo">DRE</h3><p id="dreV5Legenda">Clique em Atualizar.</p></div></div><div class="fpa-grid-wrap dre-v5-wrap"><table id="tabelaDreV5" class="fpa-grid fpa-grid-dre dre-v5-grid"><tbody><tr><td>Carregando...</td></tr></tbody></table></div></section>`;main.appendChild(s);garantirCss();$("btnAtualizarDreV5").addEventListener("click",carregar);$("btnExportarDreV5").addEventListener("click",exportarExcel);$("btnImprimirDreV5").addEventListener("click",imprimir);$("dreV5Cenario").addEventListener("change",()=>{sujo=true;marcarSujo("Cenário alterado.")});$("dreV5Visao").addEventListener("change",()=>{ajustarFiltros();render()});$("dreV5Conteudo").addEventListener("change",()=>{ajustarFiltros();render()});$("dreV5Centro").addEventListener("change",()=>{ajustarFiltros();render()})}
function garantirCss(){if($("dre-v5-css"))return;const s=document.createElement("style");s.id="dre-v5-css";s.textContent=`.dre-v5-grid th:first-child,.dre-v5-grid td:first-child{width:260px;min-width:260px;max-width:260px;white-space:normal;overflow-wrap:anywhere}.dre-v5-grid th:not(:first-child),.dre-v5-grid td:not(:first-child){min-width:96px}.dre-estat-bloco td{background:#eefaf8;font-weight:800}.dre-estat-conta td:first-child{border-left:3px solid #18a999}.dre-estat-conta td:first-child strong{font-weight:650}.dre-v5-wrap{max-width:100%;overflow:auto}@media(max-width:900px){.dre-v5-grid th:first-child,.dre-v5-grid td:first-child{width:210px;min-width:210px;max-width:210px}}`;document.head.appendChild(s)}
function marcarSujo(texto="Filtros alterados."){if(!visivel())return;const a=$("dreV5Aviso");if(a){a.classList.remove("hidden");a.innerHTML=`<strong>${esc(texto)}</strong> Clique em Atualizar para consultar o novo contexto.`}if($("dreV5Contexto"))$("dreV5Contexto").textContent=contextoTexto()}
function limparAviso(){$("dreV5Aviso")?.classList.add("hidden")}
function preencherCentros(){const sel=$("dreV5Centro");if(!sel)return;const atual=sel.value,ids=new Set(empresasSelecionadasIds()),arr=centros.filter(x=>x.status!=="inativo"&&ids.has(x.empresaId)).sort((a,b)=>String(a.codigo||"").localeCompare(String(b.codigo||""),"pt-BR"));sel.innerHTML='<option value="">Todos / consolidado</option><option value="'+CC_ESTATISTICO_ID+'">Estatísticas / Indicadores</option>'+arr.map(x=>`<option value="${esc(x.id)}">${esc(x.codigo||"")} · ${esc(x.nome||"")}${ids.size>1?` · ${esc(nomeEmpresa(x.empresaId))}`:""}</option>`).join("");if(atual&&[...sel.options].some(o=>o.value===atual))sel.value=atual}
function ajustarFiltros(){const s=$("dreV5Centro"),v=visao(),c=modoConteudo();if(v==="consolidada"){if(c==="estatisticas"){$("dreV5Visao").value="por_cc";return ajustarFiltros()}$("dreV5Conteudo").value="financeira";if(s?.value===CC_ESTATISTICO_ID)s.value=""}if(c==="estatisticas"){if($("dreV5Visao"))$("dreV5Visao").value="por_cc";if(s)s.value=CC_ESTATISTICO_ID}if(s?.value===CC_ESTATISTICO_ID){$("dreV5Visao").value="por_cc";$("dreV5Conteudo").value="estatisticas"}}
function colunas(){const chave=periodoChave(),p=periodo();if(chave==="total"){const out=[];for(let q=0;q<4;q++){for(let i=q*3;i<q*3+3;i++)out.push({label:NOMES[i],indices:[i],tipo:"mes"});out.push({label:`T${q+1}`,indices:[q*3,q*3+1,q*3+2],tipo:"tri"})}out.push({label:"Total",indices:[0,1,2,3,4,5,6,7,8,9,10,11],tipo:"total"});return out}if(/^t[1-4]$/.test(chave))return[...p.indices.map(i=>({label:NOMES[i],indices:[i],tipo:"mes"})),{label:`Total ${chave.toUpperCase()}`,indices:[...p.indices],tipo:"total"}];return[{label:p.label,indices:[...p.indices],tipo:"mes"}]}
function valorFinanceiro(vals,c){return c.indices.reduce((s,i)=>s+n(vals[i]),0)}
function valorEstatistico(vals,c,conta){const tipo=conta?.consolidacaoEstatistica||"soma",vs=c.indices.map(i=>n(vals[i]));if(tipo==="media")return vs.length?vs.reduce((a,b)=>a+b,0)/vs.length:0;if(tipo==="ultimo"){for(let i=vs.length-1;i>=0;i--)if(vs[i]!==0)return vs[i];return vs[vs.length-1]||0}return vs.reduce((a,b)=>a+b,0)}
function formatoEstat(v,conta){const u=conta?.unidadeEstatistica||"numero";if(u==="pct")return`${v.toLocaleString("pt-BR",{maximumFractionDigits:2})}%`;if(["rs_un","rs_m2","rs_m3"].includes(u))return moeda(v);const sufixo={un:" un",m2:" m²",m3:" m³",t:" t",kg:" kg",h:" h"}[u]||"";return`${v.toLocaleString("pt-BR",{maximumFractionDigits:2})}${sufixo}`}
function valoresDoc(d,cenario,realMap,conta){const out=Array(12).fill(0);if(cenario!=="forecast"){for(let i=0;i<12;i++)out[i]=n(d?.valores?.[MESES[i]]);return out}const fechado=n(d?.realizadoFechadoAte),r=realMap.get(chaveDoc(d,conta));for(let i=0;i<12;i++)out[i]=i<fechado?n(r?.valores?.[MESES[i]]):n(d?.valores?.[MESES[i]]);return out}
function somaLinhas(arr){const out=Array(12).fill(0);arr.forEach(x=>x.valores.forEach((v,i)=>out[i]+=v));return out}
function linhaFinanceira(label,vals,cols,classe,indent=0,extra=""){return`<tr class="${classe}"><td style="padding-left:${indent}px">${extra}<strong>${esc(label)}</strong></td>${cols.map(c=>`<td class="numero ${c.tipo!=="mes"?"fpa-total":""}"><strong>${moeda(valorFinanceiro(vals,c))}</strong></td>`).join("")}</tr>`}
function linhaEstat(label,vals,cols,conta,classe="dre-estat-conta",indent=24){return`<tr class="${classe}"><td style="padding-left:${indent}px"><strong>${esc(label)}</strong></td>${cols.map(c=>`<td class="numero ${c.tipo!=="mes"?"fpa-total":""}">${formatoEstat(valorEstatistico(vals,c,conta),conta)}</td>`).join("")}</tr>`}
function linhasBase(){const ano=periodoAno(),cenario=$("dreV5Cenario")?.value||"realizado",ccFiltro=$("dreV5Centro")?.value||"",versao=cenario==="realizado"?"":versaoMaisRecente(docs,ano),base=docsCanonicos(docs,cenario,ano,versao),realBase=cenario==="forecast"?docsCanonicos(realizados,"realizado",ano):[],planoMap=new Map(plano.map(x=>[x.id,x])),realMap=new Map(realBase.map(x=>{const c=planoMap.get(x.contaId);return[chaveDoc(x,c),x]})),centroMap=new Map(centros.map(x=>[x.id,x])),linhas=[];base.forEach(d=>{const c=planoMap.get(d.contaId);if(!c||c.status==="inativo")return;const estat=contaEstatistica(c),ccId=estat?CC_ESTATISTICO_ID:(d.centroCustoId||"");if(ccFiltro&&ccId!==ccFiltro)return;const cc=estat?centroEstatisticoSintetico(d.empresaId):centroMap.get(ccId);if(!cc)return;const sinal=estat?1:(c.natureza==="receita"?1:-1),vals=valoresDoc(d,cenario,realMap,c).map(v=>sinal*v);linhas.push({empresaId:d.empresaId,ccId,cc,c,estat,grupo:estat?"estatisticas":c.grupoDre||"outros",valores:vals})});return{linhas,versao,cenario}}
function renderEstatisticas(linhas,cols){const arr=linhas.filter(x=>x.estat).sort((a,b)=>n(a.c.ordem)-n(b.c.ordem)||String(a.c.codigo||"").localeCompare(String(b.c.codigo||""),"pt-BR"));if(!arr.length)return[];return[`<tr class="dre-estat-bloco"><td><strong>${esc(CC_ESTATISTICO_NOME.toUpperCase())}</strong></td>${cols.map(()=>'<td></td>').join("")}</tr>`,...arr.map(x=>linhaEstat(`${x.c.codigo||""} · ${x.c.nome||"Indicador"}`,x.valores,cols,x.c))]}
function renderPorCc(linhas,cols){const corpo=[];const conteudo=modoConteudo();if(conteudo!=="financeira")corpo.push(...renderEstatisticas(linhas,cols));if(conteudo==="estatisticas")return corpo;const fin=linhas.filter(x=>!x.estat);for(const[gid,glabel]of GRUPOS){const gp=fin.filter(x=>x.grupo===gid);if(!gp.length)continue;corpo.push(linhaFinanceira(glabel,somaLinhas(gp),cols,"dre-grupo"));const ccIds=[...new Set(gp.map(x=>x.ccId))];for(const ccId of ccIds){const cp=gp.filter(x=>x.ccId===ccId),cc=cp[0].cc,label=`${cc.codigo||""} · ${cc.nome||"Centro"}${empresasSelecionadasIds().length>1?` · ${nomeEmpresa(cp[0].empresaId)}`:""}`;corpo.push(linhaFinanceira(label,somaLinhas(cp),cols,"dre-centro",16));cp.sort((a,b)=>String(a.c.codigo||"").localeCompare(String(b.c.codigo||""),"pt-BR")).forEach(x=>corpo.push(`<tr class="dre-filha"><td style="padding-left:34px">${esc(x.c.codigo||"")} · ${esc(x.c.nome||"Conta")}</td>${cols.map(c=>`<td class="numero ${c.tipo!=="mes"?"fpa-total":""}">${moeda(valorFinanceiro(x.valores,c))}</td>`).join("")}</tr>`))}}return corpo}
function renderConsolidada(linhas,cols){const corpo=[],fin=linhas.filter(x=>!x.estat);for(const[gid,glabel]of GRUPOS){const gp=fin.filter(x=>x.grupo===gid);if(!gp.length)continue;corpo.push(linhaFinanceira(glabel,somaLinhas(gp),cols,"dre-grupo"));const contas=new Map();gp.forEach(x=>{const k=`${x.c.codigo||x.c.id}|${x.c.nome||""}`;if(!contas.has(k))contas.set(k,{codigo:x.c.codigo||"",nome:x.c.nome||"Conta",linhas:[]});contas.get(k).linhas.push(x)});for(const[k,item]of[...contas.entries()].sort((a,b)=>String(a[1].codigo).localeCompare(String(b[1].codigo),"pt-BR"))){const aberto=expandidas.has(`${gid}|${k}`),extra=`<button class="btn-mini" data-dre-expand="${esc(`${gid}|${k}`)}" type="button">${aberto?"▾":"▸"}</button> `;corpo.push(linhaFinanceira(`${item.codigo} · ${item.nome}`,somaLinhas(item.linhas),cols,"dre-filha",16,extra));if(aberto)item.linhas.sort((a,b)=>String(a.cc.codigo||"").localeCompare(String(b.cc.codigo||""),"pt-BR")).forEach(x=>corpo.push(linhaFinanceira(`${x.cc.codigo||""} · ${x.cc.nome||"Centro"}${empresasSelecionadasIds().length>1?` · ${nomeEmpresa(x.empresaId)}`:""}`,x.valores,cols,"dre-cc-detail",34))}}return corpo}
function bind(){document.querySelectorAll("#tabelaDreV5 [data-dre-expand]").forEach(b=>b.addEventListener("click",()=>{const k=b.dataset.dreExpand;expandidas.has(k)?expandidas.delete(k):expandidas.add(k);render()}))}
function render(){const t=$("tabelaDreV5");if(!t)return;ajustarFiltros();const{linhas,versao,cenario}=linhasBase(),cols=colunas(),v=visao(),conteudo=modoConteudo(),financeiras=linhas.filter(x=>!x.estat),resultado=somaLinhas(financeiras),corpo=v==="consolidada"?renderConsolidada(linhas,cols):renderPorCc(linhas,cols);if(conteudo!=="estatisticas"&&financeiras.length)corpo.push(linhaFinanceira("RESULTADO",resultado,cols,"dre-resultado"));t.innerHTML=`<thead><tr><th>DRE ${periodoAno()}</th>${cols.map(c=>`<th class="${c.tipo!=="mes"?"fpa-total":""}">${c.label}</th>`).join("")}</tr></thead><tbody>${corpo.join("")||'<tr><td>Sem dados para o contexto.</td></tr>'}</tbody>`;$("dreV5Titulo").textContent=`DRE · ${cenario==="realizado"?"Realizado":cenario==="budget"?"Budget":"Forecast"}`;$("dreV5Legenda").textContent=`${contextoTexto()}${versao?` · versão ${versao}`:""}`;$("dreV5Contexto").textContent=contextoTexto();bind()}
function nomeArquivo(ext){return`DRE_${periodoAno()}_${($("dreV5Cenario")?.value||"realizado")}_${periodoChave()}.${ext}`.replace(/[^a-zA-Z0-9_.-]/g,"_")}
function exportarExcel(){const tabela=$("tabelaDreV5");if(!tabela)return;const html=`<html><head><meta charset="utf-8"></head><body><h2>DRE Gerencial</h2><p>${esc(contextoTexto())}</p>${tabela.outerHTML}</body></html>`,blob=new Blob([html],{type:"application/vnd.ms-excel;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=nomeArquivo("xls");document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function imprimir(){const tabela=$("tabelaDreV5");if(!tabela)return;const w=window.open("","_blank","width=1200,height=800");if(!w)return alert("Permita pop-ups para imprimir a DRE.");w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>DRE Gerencial</title><style>body{font-family:Arial,sans-serif;color:#111;padding:20px}h1{font-size:20px}p{font-size:11px;color:#555}table{border-collapse:collapse;width:100%;font-size:9px}th,td{border:1px solid #bbb;padding:5px;text-align:right}th:first-child,td:first-child{text-align:left;width:240px;max-width:240px;white-space:normal}.dre-grupo td,.dre-resultado td{font-weight:bold;background:#eee}.dre-centro td{font-weight:bold;background:#f6f6f6}.dre-estat-bloco td{font-weight:bold;background:#e9f7f5}@page{size:landscape;margin:8mm}</style></head><body><h1>DRE Gerencial</h1><p>${esc(contextoTexto())}</p>${tabela.outerHTML}<script>window.onload=()=>{window.print()}<\/script></body></html>`);w.document.close()}
export async function carregar(){criarPagina();if(carregando||(!permite("controladoria","visualizar")&&!permite("controladoria")))return;if(!empresasSelecionadasIds().length){marcarSujo("Selecione ao menos uma empresa.");return}carregando=true;const b=$("btnAtualizarDreV5");if(b){b.disabled=true;b.textContent="Atualizando..."}try{const cenario=$("dreV5Cenario")?.value||"realizado",tarefas=[listarDocumentos("planoContasGerencial"),listarDocumentos("centrosCusto")];if(cenario==="realizado")tarefas.push(listarDocumentos("realizadoMensal"));if(cenario==="budget")tarefas.push(listarDocumentos("budgetLinhas"));if(cenario==="forecast")tarefas.push(listarDocumentos("forecastLinhas"),listarDocumentos("realizadoMensal"));const r=await Promise.all(tarefas);plano=r[0];centros=r[1];docs=r[2]||[];realizados=cenario==="forecast"?(r[3]||[]):[];preencherCentros();ajustarFiltros();render();sujo=false;limparAviso()}catch(e){console.error("DRE V5:",e);const a=$("dreV5Aviso");if(a){a.classList.remove("hidden");a.textContent="Não foi possível atualizar a DRE."}}finally{carregando=false;if(b){b.disabled=false;b.textContent="Atualizar"}}}
export function abrir(){criarPagina();abrirPagina("ctrl-dre-v5");const t=$("tituloPagina");if(t)t.textContent="DRE Gerencial";carregar()}
criarPagina();window.addEventListener("sig:periodo-changed",()=>{sujo=true;marcarSujo("Período alterado no cabeçalho.")});window.addEventListener("sig:empresa-changed",()=>{sujo=true;marcarSujo("Seleção de empresas alterada.")});
