import { abrirPagina } from "./core.js";
import { $, esc, permite, moeda, listarDocumentos, periodoAno, periodoChave, empresasSelecionadasIds, nomeEmpresa } from "./shared.js";

const MESES=["jan","fev","mar","abr","mai","jun","jul","ago","set","out","nov","dez"];
const NOMES=["Jan","Fev","Mar","Abr","Mai","Jun","Jul","Ago","Set","Out","Nov","Dez"];
const PERIODOS={total:{label:"Total do exercício",indices:[0,1,2,3,4,5,6,7,8,9,10,11]},t1:{label:"T1 · Jan–Mar",indices:[0,1,2]},t2:{label:"T2 · Abr–Jun",indices:[3,4,5]},t3:{label:"T3 · Jul–Set",indices:[6,7,8]},t4:{label:"T4 · Out–Dez",indices:[9,10,11]}};
for(let i=0;i<12;i++)PERIODOS[`m${String(i+1).padStart(2,"0")}`]={label:NOMES[i],indices:[i]};
const GRUPOS=[["receita","RECEITAS"],["deducoes","DEDUÇÕES DA RECEITA"],["custos","CUSTOS INDUSTRIAIS"],["despesas","DESPESAS OPERACIONAIS"],["financeiro","RESULTADO FINANCEIRO"],["impostos","IMPOSTOS"],["outros","OUTROS"],["estatisticas","INDICADORES / CONTAS ESTATÍSTICAS"]];
let plano=[],centros=[],docs=[],realizados=[],carregando=false,sujo=false;
const n=v=>{const x=Number(v||0);return Number.isFinite(x)?x:0};
const stamp=x=>n(x?.atualizadoEm?.seconds||x?.criadoEm?.seconds||0);
const pagina=()=>$("pagina-ctrl-dre-v3");
const visivel=()=>pagina()&&!pagina().classList.contains("hidden");
const ativo=x=>x?.legadoArquivado!==true&&x?.duplicadoArquivado!==true;
function periodo(){return PERIODOS[periodoChave()]||PERIODOS.total}
function grupoConta(c){return c?.tipoConta==="estatistica"||c?.grupoDre==="estatisticas"?"estatisticas":c?.grupoDre||"outros"}
function versaoMaisRecente(arr,ano){const m=new Map();arr.filter(x=>Number(x.exercicio)===Number(ano)&&x.versao).forEach(x=>m.set(x.versao,Math.max(m.get(x.versao)||0,stamp(x))));return[...m.entries()].sort((a,b)=>b[1]-a[1]||String(b[0]).localeCompare(String(a[0]),"pt-BR"))[0]?.[0]||""}
function contextoTexto(){const ids=empresasSelecionadasIds(),p=periodo();return`${ids.length>1?`${ids.length} empresas consolidadas`:ids.length===1?nomeEmpresa(ids[0]):"Sem empresa"} · ${p.label} · ${periodoAno()}`}
function idSeguro(v){return String(v||"sem").replace(/[^a-zA-Z0-9_-]/g,"_")}
function chaveDoc(d){return`${d.empresaId}|${d.centroCustoId||""}|${d.contaId}`}
function docsCanonicos(arr,cenario,ano,versao=""){const map=new Map();arr.filter(x=>ativo(x)&&Number(x.exercicio)===Number(ano)&&(!versao||x.versao===versao)).forEach(x=>{const k=chaveDoc(x),atual=map.get(k);let prefer=false;if(cenario==="realizado"){const canon=`r_${idSeguro(x.empresaId)}_${ano}_${idSeguro(x.centroCustoId||"")}_${idSeguro(x.contaId)}`;prefer=x.id===canon||(!atual)||(atual.id!==canon&&stamp(x)>stamp(atual))}else prefer=!atual||stamp(x)>stamp(atual);if(prefer)map.set(k,x)});return[...map.values()]}
function criarPagina(){if(pagina())return;const main=document.querySelector("main.conteudo");if(!main)return;const s=document.createElement("section");s.id="pagina-ctrl-dre-v3";s.className="pagina hidden";s.innerHTML=`<div class="pagina-cabecalho"><div><span class="eyebrow">CONTROLADORIA & FP&A</span><h2>DRE Gerencial</h2><p>Visão gerencial em árvore: Grupo → Centro de Custo → Conta.</p></div><button id="btnAtualizarDreV3" class="btn-primario" type="button">Atualizar</button></div><div id="dreV3Aviso" class="modulo-aviso hidden"></div><div class="fpa-toolbar"><div class="campo"><label for="dreV3Cenario">Cenário</label><select id="dreV3Cenario"><option value="realizado">Realizado</option><option value="budget">Budget</option><option value="forecast">Forecast</option></select></div><div class="campo"><label for="dreV3Centro">Centro de custo</label><select id="dreV3Centro"><option value="">Todos / consolidado</option></select></div><div class="campo"><label>Contexto</label><div id="dreV3Contexto" class="fpa-contexto-chip">—</div></div></div><section class="lista-card"><div class="lista-cabecalho"><div><h3 id="dreV3Titulo">DRE</h3><p id="dreV3Legenda">Clique em Atualizar.</p></div></div><div class="fpa-grid-wrap"><table id="tabelaDreV3" class="fpa-grid fpa-grid-dre"><tbody><tr><td>Carregando...</td></tr></tbody></table></div></section>`;main.appendChild(s);$("btnAtualizarDreV3").addEventListener("click",carregar);$("dreV3Cenario").addEventListener("change",()=>{sujo=true;marcarSujo("Cenário alterado.")});$("dreV3Centro").addEventListener("change",render)}
function marcarSujo(texto="Filtros alterados."){if(!visivel())return;const a=$("dreV3Aviso");if(a){a.classList.remove("hidden");a.innerHTML=`<strong>${esc(texto)}</strong> Clique em Atualizar para consultar o novo contexto.`}if($("dreV3Contexto"))$("dreV3Contexto").textContent=contextoTexto()}
function limparAviso(){$("dreV3Aviso")?.classList.add("hidden")}
function preencherCentros(){const sel=$("dreV3Centro");if(!sel)return;const atual=sel.value,ids=new Set(empresasSelecionadasIds()),arr=centros.filter(x=>x.status!=="inativo"&&ids.has(x.empresaId)).sort((a,b)=>String(a.codigo||"").localeCompare(String(b.codigo||""),"pt-BR"));sel.innerHTML='<option value="">Todos / consolidado</option>'+arr.map(x=>`<option value="${esc(x.id)}">${esc(x.codigo||"")} · ${esc(x.nome||"")}${ids.size>1?` · ${esc(nomeEmpresa(x.empresaId))}`:""}</option>`).join("");if(arr.some(x=>x.id===atual))sel.value=atual}
function colunas(){const chave=periodoChave(),p=periodo();if(chave==="total"){const out=[];for(let q=0;q<4;q++){for(let i=q*3;i<q*3+3;i++)out.push({label:NOMES[i],indices:[i],tipo:"mes"});out.push({label:`T${q+1}`,indices:[q*3,q*3+1,q*3+2],tipo:"tri"})}out.push({label:"Total",indices:[0,1,2,3,4,5,6,7,8,9,10,11],tipo:"total"});return out}if(/^t[1-4]$/.test(chave))return[...p.indices.map(i=>({label:NOMES[i],indices:[i],tipo:"mes"})),{label:`Total ${chave.toUpperCase()}`,indices:[...p.indices],tipo:"total"}];return[{label:p.label,indices:[...p.indices],tipo:"mes"}]}
function valorColuna(vals,c){return c.indices.reduce((s,i)=>s+n(vals[i]),0)}
function valoresDoc(d,cenario,ano,realMap){const out=Array(12).fill(0);if(cenario!=="forecast"){for(let i=0;i<12;i++)out[i]=n(d?.valores?.[MESES[i]]);return out}const fechado=n(d?.realizadoFechadoAte),r=realMap.get(chaveDoc(d));for(let i=0;i<12;i++)out[i]=i<fechado?n(r?.valores?.[MESES[i]]):n(d?.valores?.[MESES[i]]);return out}
function somaLinhas(arr){const out=Array(12).fill(0);arr.forEach(x=>x.valores.forEach((v,i)=>out[i]+=v));return out}
function linhaValores(label,vals,cols,classe,indent=0){return`<tr class="${classe}"><td style="padding-left:${indent}px"><strong>${esc(label)}</strong></td>${cols.map(c=>`<td class="numero ${c.tipo!=="mes"?"fpa-total":""}"><strong>${moeda(valorColuna(vals,c))}</strong></td>`).join("")}</tr>`}
function render(){const t=$("tabelaDreV3");if(!t)return;const ano=periodoAno(),cenario=$("dreV3Cenario")?.value||"realizado",ccFiltro=$("dreV3Centro")?.value||"",versao=cenario==="realizado"?"":versaoMaisRecente(docs,ano),base=docsCanonicos(docs,cenario,ano,versao),realBase=cenario==="forecast"?docsCanonicos(realizados,"realizado",ano):[],realMap=new Map(realBase.map(x=>[chaveDoc(x),x])),planoMap=new Map(plano.map(x=>[x.id,x])),centroMap=new Map(centros.map(x=>[x.id,x])),linhas=[];base.forEach(d=>{if(ccFiltro&&(d.centroCustoId||"")!==ccFiltro)return;const c=planoMap.get(d.contaId),cc=centroMap.get(d.centroCustoId);if(!c||c.status==="inativo"||!cc)return;const estat=grupoConta(c)==="estatisticas",sinal=estat?1:(c.natureza==="receita"?1:-1),vals=valoresDoc(d,cenario,ano,realMap).map(v=>sinal*v);linhas.push({empresaId:d.empresaId,ccId:cc.id,cc,c,grupo:grupoConta(c),estat,valores:vals})});const cols=colunas(),corpo=[],financeiras=linhas.filter(x=>!x.estat),resultado=somaLinhas(financeiras);for(const[gid,glabel]of GRUPOS){const gp=linhas.filter(x=>x.grupo===gid);if(!gp.length)continue;corpo.push(linhaValores(glabel,somaLinhas(gp),cols,"dre-grupo"));const ccIds=[...new Set(gp.map(x=>x.ccId))];for(const ccId of ccIds){const cp=gp.filter(x=>x.ccId===ccId),cc=cp[0].cc,label=`${cc.codigo||""} · ${cc.nome||"Centro"}${empresasSelecionadasIds().length>1?` · ${nomeEmpresa(cp[0].empresaId)}`:""}`;corpo.push(linhaValores(label,somaLinhas(cp),cols,"dre-centro",20));cp.sort((a,b)=>String(a.c.codigo||"").localeCompare(String(b.c.codigo||""),"pt-BR")).forEach(x=>corpo.push(`<tr class="dre-filha"><td style="padding-left:42px">${esc(x.c.codigo||"")} · ${esc(x.c.nome||"Conta")}</td>${cols.map(c=>`<td class="numero ${c.tipo!=="mes"?"fpa-total":""}">${moeda(valorColuna(x.valores,c))}</td>`).join("")}</tr>`))}}corpo.push(linhaValores("RESULTADO",resultado,cols,"dre-resultado"));t.innerHTML=`<thead><tr><th>DRE ${ano}</th>${cols.map(c=>`<th class="${c.tipo!=="mes"?"fpa-total":""}">${c.label}</th>`).join("")}</tr></thead><tbody>${corpo.join("")||'<tr><td>Sem dados para o contexto.</td></tr>'}</tbody>`;$("dreV3Titulo").textContent=`DRE · ${cenario==="realizado"?"Realizado":cenario==="budget"?"Budget":"Forecast"}`;$("dreV3Legenda").textContent=`${contextoTexto()}${versao?` · versão ${versao}`:""}`;$("dreV3Contexto").textContent=contextoTexto()}
export async function carregar(){criarPagina();if(carregando||(!permite("controladoria","visualizar")&&!permite("controladoria")))return;if(!empresasSelecionadasIds().length){marcarSujo("Selecione ao menos uma empresa.");return}carregando=true;const b=$("btnAtualizarDreV3");if(b){b.disabled=true;b.textContent="Atualizando..."}try{const cenario=$("dreV3Cenario")?.value||"realizado",tarefas=[listarDocumentos("planoContasGerencial"),listarDocumentos("centrosCusto")];if(cenario==="realizado")tarefas.push(listarDocumentos("realizadoMensal"));if(cenario==="budget")tarefas.push(listarDocumentos("budgetLinhas"));if(cenario==="forecast")tarefas.push(listarDocumentos("forecastLinhas"),listarDocumentos("realizadoMensal"));const r=await Promise.all(tarefas);plano=r[0];centros=r[1];docs=r[2]||[];realizados=cenario==="forecast"?(r[3]||[]):[];preencherCentros();render();sujo=false;limparAviso()}catch(e){console.error("DRE V3:",e);const a=$("dreV3Aviso");if(a){a.classList.remove("hidden");a.textContent="Não foi possível atualizar a DRE."}}finally{carregando=false;if(b){b.disabled=false;b.textContent="Atualizar"}}}
export function abrir(){criarPagina();abrirPagina("ctrl-dre-v3");const t=$("tituloPagina");if(t)t.textContent="DRE Gerencial";carregar()}
criarPagina();window.addEventListener("sig:periodo-changed",()=>{sujo=true;marcarSujo("Período alterado no cabeçalho.")});window.addEventListener("sig:empresa-changed",()=>{sujo=true;marcarSujo("Seleção de empresas alterada.")});
