import { abrirPagina } from "./core.js";
import { $, esc, moeda, listarDocumentos, periodoAno, periodoChave, empresasSelecionadasIds, nomeEmpresa } from "./shared.js";
import { CC_ESTATISTICO_ID, CC_ESTATISTICO_NOME, contaEstatistica, centroEstatisticoSintetico } from "./statistical-center.js";
import { contaSintetica, contaAnalitica, folhasDescendentes, arvoreParaFolhas } from "./account-tree.js";
import { contaDre } from "./account-mask.js";
import { contaAtivaNoExercicio } from "./account-validity.js";
import { exportarTabelaXls, exportarTabelaPdf } from "./export-utils.js";

const MESES=["jan","fev","mar","abr","mai","jun","jul","ago","set","out","nov","dez"];
const NOMES=["Jan","Fev","Mar","Abr","Mai","Jun","Jul","Ago","Set","Out","Nov","Dez"];
const PERIODOS={total:{label:"Total do exercício",indices:[0,1,2,3,4,5,6,7,8,9,10,11]},t1:{label:"T1 · Jan–Mar",indices:[0,1,2]},t2:{label:"T2 · Abr–Jun",indices:[3,4,5]},t3:{label:"T3 · Jul–Set",indices:[6,7,8]},t4:{label:"T4 · Out–Dez",indices:[9,10,11]}};
for(let i=0;i<12;i++)PERIODOS[`m${String(i+1).padStart(2,"0")}`]={label:NOMES[i],indices:[i]};
const GRUPOS=[["receita","RECEITAS"],["deducoes","DEDUÇÕES DA RECEITA"],["custos","CUSTOS INDUSTRIAIS"],["despesas","DESPESAS OPERACIONAIS"],["financeiro","RESULTADO FINANCEIRO"],["impostos","IMPOSTOS"],["outros","OUTROS"]];
let plano=[],centros=[],docs=[],realizados=[],carregando=false,sujo=false,versaoCarregada="";
const expandidas=new Set();
const n=v=>{const x=Number(v||0);return Number.isFinite(x)?x:0};
const stamp=x=>n(x?.atualizadoEm?.seconds||x?.criadoEm?.seconds||0);
const ativo=x=>x?.legadoArquivado!==true&&x?.duplicadoArquivado!==true;
const pagina=()=>$("pagina-ctrl-dre-v7");
const visivel=()=>pagina()&&!pagina().classList.contains("hidden");
const periodo=()=>PERIODOS[periodoChave()]||PERIODOS.total;
const modoConteudo=()=>$("dreV7Conteudo")?.value||"completa";
const visao=()=>$("dreV7Visao")?.value||"por_cc";
const cenario=()=>$("dreV7Cenario")?.value||"realizado";
const ccFiltro=()=>$("dreV7Centro")?.value||"";
const idSeguro=v=>String(v||"sem").replace(/[^a-zA-Z0-9_-]/g,"_");
const vazio=()=>Array(12).fill(0);
function somaVetores(vs){const out=vazio();for(const v of vs||[])for(let i=0;i<12;i++)out[i]+=n(v?.[i]);return out}
function grupoEfetivo(c){if(!c)return"outros";if(contaAnalitica(c)){const p=plano.find(x=>x.id===c.contaPaiId);return p?.grupoDre||c.grupoDre||"outros"}return c.grupoDre||"outros"}
function sinalConta(c){return contaEstatistica(c)?1:(c?.natureza==="receita"?1:-1)}
function centroDoc(d,c){return contaEstatistica(c)?CC_ESTATISTICO_ID:(d.centroCustoId||"")}
function chaveDoc(d,c){return`${d.empresaId}|${centroDoc(d,c)}|${d.contaId}`}
function versaoMaisRecente(arr,ano){const m=new Map();arr.filter(x=>x.tipoRegistro!=="budget_meta"&&Number(x.exercicio)===Number(ano)&&x.versao).forEach(x=>m.set(x.versao,Math.max(m.get(x.versao)||0,stamp(x))));return[...m.entries()].sort((a,b)=>b[1]-a[1]||String(b[0]).localeCompare(String(a[0]),"pt-BR"))[0]?.[0]||""}
function contextoTexto(){const ids=empresasSelecionadasIds(),v=visao()==="consolidada"?"Consolidada por conta":"Por Centro de Custo",c=modoConteudo()==="estatisticas"?"Estatísticas":modoConteudo()==="financeira"?"Financeira":"Completa",ver=versaoCarregada?` · ${versaoCarregada}`:"";return`${ids.length>1?`${ids.length} empresas consolidadas`:ids.length===1?nomeEmpresa(ids[0]):"Sem empresa"} · ${v} · ${c} · ${periodo().label} · ${periodoAno()}${ver}`}

function criarPagina(){if(pagina())return;const main=document.querySelector("main.conteudo");if(!main)return;const s=document.createElement("section");s.id="pagina-ctrl-dre-v7";s.className="pagina hidden";s.innerHTML=`
<div class="pagina-cabecalho"><div><span class="eyebrow">CONTROLADORIA & FP&A</span><h2>DRE Gerencial</h2><p>Estrutura Sintética/Analítica com vigência histórica e visão executiva ou detalhada.</p></div><div class="acoes-cabecalho"><button id="btnDreV7Recolher" class="btn-secundario" type="button">Recolher tudo</button><button id="btnDreV7Expandir" class="btn-secundario" type="button">Expandir tudo</button><button id="btnExportarDreV7" class="btn-secundario" type="button">Exportar Excel</button><button id="btnImprimirDreV7" class="btn-secundario" type="button">Imprimir / PDF</button><button id="btnAtualizarDreV7" class="btn-primario" type="button">Atualizar</button></div></div>
<div id="dreV7Aviso" class="modulo-aviso hidden"></div><div class="fpa-toolbar"><div class="campo"><label for="dreV7Cenario">Cenário</label><select id="dreV7Cenario"><option value="realizado">Realizado</option><option value="budget">Budget</option><option value="forecast">Forecast</option></select></div><div class="campo"><label for="dreV7Visao">Visão</label><select id="dreV7Visao"><option value="por_cc">Por Centro de Custo</option><option value="consolidada">Consolidada por conta</option></select></div><div class="campo"><label for="dreV7Conteudo">Conteúdo</label><select id="dreV7Conteudo"><option value="completa">Completa</option><option value="financeira">Financeira</option><option value="estatisticas">Estatísticas</option></select></div><div class="campo"><label for="dreV7Centro">Centro de custo</label><select id="dreV7Centro"><option value="">Todos</option></select></div><div class="campo"><label>Contexto</label><div id="dreV7Contexto" class="fpa-contexto-chip">—</div></div></div>
<section class="lista-card"><div class="lista-cabecalho"><div><h3 id="dreV7Titulo">DRE</h3><p id="dreV7Legenda">Clique em Atualizar.</p></div></div><div class="fpa-grid-wrap dre-v7-wrap"><table id="tabelaDreV7" class="fpa-grid fpa-grid-dre dre-v7-grid"><tbody><tr><td>Carregando...</td></tr></tbody></table></div></section>`;main.appendChild(s);garantirCss();$("btnAtualizarDreV7")?.addEventListener("click",carregar);$("btnExportarDreV7")?.addEventListener("click",exportarExcel);$("btnImprimirDreV7")?.addEventListener("click",imprimir);$("btnDreV7Expandir")?.addEventListener("click",expandirTudo);$("btnDreV7Recolher")?.addEventListener("click",recolherTudo);$("dreV7Cenario")?.addEventListener("change",()=>marcarSujo("Cenário alterado."));$("dreV7Visao")?.addEventListener("change",()=>{ajustarFiltros();render()});$("dreV7Conteudo")?.addEventListener("change",()=>{ajustarFiltros();render()});$("dreV7Centro")?.addEventListener("change",()=>{ajustarFiltros();render()})}
function garantirCss(){if($("dre-v7-css"))return;const s=document.createElement("style");s.id="dre-v7-css";s.textContent=`.dre-v7-grid th:first-child,.dre-v7-grid td:first-child{width:285px;min-width:285px;max-width:285px;white-space:normal;overflow-wrap:anywhere}.dre-v7-grid th:not(:first-child),.dre-v7-grid td:not(:first-child){min-width:96px}.dre-v7-wrap{max-width:100%;overflow:auto}.dre-v7-tree{display:flex;align-items:center;gap:6px}.dre-v7-tree.sintetica{font-weight:850}.dre-v7-tree .indent{display:inline-block;flex:0 0 auto}.dre-tree-toggle{width:18px;height:18px;border:0;background:transparent;cursor:pointer;padding:0;color:#475467}.dre-tree-toggle:before{content:'▸';font-size:11px}.dre-tree-toggle.aberta:before{content:'▾'}.dre-tree-spacer{display:inline-block;width:18px}.dre-v7-sint td{background:#f7f9fb}.dre-v7-cc td{background:#eef3f5;font-weight:850}.dre-v7-grupo td{background:#e7eef2;font-weight:900}.dre-v7-estat td{background:#eefaf8}.dre-v7-estat-bloco td{background:#dff5f1;font-weight:900}.dre-v7-resultado td{background:#0b1f33!important;color:#fff!important;font-weight:900}.dre-v7-grid small{display:block;color:#667085;font-size:8px;margin-top:2px}@media(max-width:900px){.dre-v7-grid th:first-child,.dre-v7-grid td:first-child{width:220px;min-width:220px;max-width:220px}}`;document.head.appendChild(s)}
function marcarSujo(texto="Contexto alterado."){sujo=true;if(!visivel())return;const a=$("dreV7Aviso");if(a){a.classList.remove("hidden");a.innerHTML=`<strong>${esc(texto)}</strong> Clique em Atualizar para consultar o novo contexto.`}if($("dreV7Contexto"))$("dreV7Contexto").textContent=contextoTexto()}
function limparAviso(){sujo=false;$("dreV7Aviso")?.classList.add("hidden")}
function preencherCentros(){const s=$("dreV7Centro");if(!s)return;const atual=s.value,ids=new Set(empresasSelecionadasIds()),arr=centros.filter(c=>c.status!=="inativo"&&ids.has(c.empresaId)).sort((a,b)=>String(a.codigo||"").localeCompare(String(b.codigo||""),"pt-BR"));s.innerHTML=`<option value="">Todos</option><option value="${CC_ESTATISTICO_ID}">Estatísticas / Indicadores</option>`+arr.map(c=>`<option value="${esc(c.id)}">${esc(c.codigo||"")} · ${esc(c.nome||"")}${ids.size>1?` · ${esc(nomeEmpresa(c.empresaId))}`:""}</option>`).join("");if(atual&&[...s.options].some(o=>o.value===atual))s.value=atual}
function ajustarFiltros(){const s=$("dreV7Centro");if(visao()==="consolidada"){if(modoConteudo()==="estatisticas")$("dreV7Conteudo").value="financeira";if(s?.value===CC_ESTATISTICO_ID)s.value=""}if(modoConteudo()==="estatisticas"){$("dreV7Visao").value="por_cc";if(s)s.value=CC_ESTATISTICO_ID}if(s?.value===CC_ESTATISTICO_ID){$("dreV7Visao").value="por_cc";$("dreV7Conteudo").value="estatisticas"}}
function colunas(){const chave=periodoChave(),p=periodo();if(chave==="total"){const out=[];for(let q=0;q<4;q++){for(let i=q*3;i<q*3+3;i++)out.push({label:NOMES[i],indices:[i],tipo:"mes"});out.push({label:`T${q+1}`,indices:[q*3,q*3+1,q*3+2],tipo:"tri"})}out.push({label:"Total",indices:[0,1,2,3,4,5,6,7,8,9,10,11],tipo:"total"});return out}if(/^t[1-4]$/.test(chave))return[...p.indices.map(i=>({label:NOMES[i],indices:[i],tipo:"mes"})),{label:`Total ${chave.toUpperCase()}`,indices:[...p.indices],tipo:"total"}];return[{label:p.label,indices:[...p.indices],tipo:"mes"}]}
function valorFinanceiro(vals,col){return col.indices.reduce((s,i)=>s+n(vals[i]),0)}
function valorEstatistico(vals,col,conta){const tipo=conta?.consolidacaoEstatistica||"soma",vs=col.indices.map(i=>n(vals[i]));if(tipo==="media")return vs.length?vs.reduce((a,b)=>a+b,0)/vs.length:0;if(tipo==="ultimo"){for(let i=vs.length-1;i>=0;i--)if(vs[i]!==0)return vs[i];return vs.at(-1)||0}return vs.reduce((a,b)=>a+b,0)}
function formatoEstat(v,c){const u=c?.unidadeEstatistica||"numero";if(u==="pct")return`${n(v).toLocaleString("pt-BR",{maximumFractionDigits:2})}%`;if(["rs_un","rs_m2","rs_m3"].includes(u))return moeda(v);const suf={un:" un",m2:" m²",m3:" m³",t:" t",kg:" kg",h:" h"}[u]||"";return`${n(v).toLocaleString("pt-BR",{maximumFractionDigits:2})}${suf}`}
function docsCanonicos(arr,cen,ano,versao=""){const pmap=new Map(plano.map(c=>[c.id,c])),map=new Map();arr.filter(d=>ativo(d)&&d.tipoRegistro!=="budget_meta"&&Number(d.exercicio)===Number(ano)&&(!versao||d.versao===versao)).forEach(d=>{const c=pmap.get(d.contaId);if(!c||!contaAnalitica(c)||!contaAtivaNoExercicio(c,ano)||(!contaEstatistica(c)&&!contaDre(c)))return;const k=chaveDoc(d,c),at=map.get(k);if(cen==="realizado"){const cc=centroDoc(d,c),canon=`r_${idSeguro(d.empresaId)}_${ano}_${idSeguro(cc)}_${idSeguro(d.contaId)}`;if(!at||d.id===canon||(at.id!==canon&&stamp(d)>stamp(at)))map.set(k,d)}else if(!at||stamp(d)>stamp(at))map.set(k,d)});return[...map.values()]}
function valoresDocumento(d,cen,realMap,c){const out=vazio();if(cen!=="forecast"){for(let i=0;i<12;i++)out[i]=n(d?.valores?.[MESES[i]]);return out}const fechado=Math.max(0,Math.min(12,n(d?.realizadoFechadoAte))),r=realMap.get(chaveDoc(d,c));for(let i=0;i<12;i++)out[i]=i<fechado?n(r?.valores?.[MESES[i]]):n(d?.valores?.[MESES[i]]);return out}
function linhasBase(){const ano=periodoAno(),cen=cenario(),vers=cen==="realizado"?"":versaoMaisRecente(docs,ano),base=docsCanonicos(docs,cen,ano,vers),reais=cen==="forecast"?docsCanonicos(realizados,"realizado",ano):[],pmap=new Map(plano.map(c=>[c.id,c])),rmap=new Map(reais.map(d=>{const c=pmap.get(d.contaId);return[chaveDoc(d,c),d]})),cmap=new Map(centros.map(c=>[c.id,c])),ids=new Set(empresasSelecionadasIds()),out=[];versaoCarregada=vers;base.forEach(d=>{if(ids.size&&!ids.has(d.empresaId))return;const c=pmap.get(d.contaId);if(!c)return;const stat=contaEstatistica(c),ccId=stat?CC_ESTATISTICO_ID:(d.centroCustoId||""),cc=stat?centroEstatisticoSintetico(d.empresaId):cmap.get(ccId);if(!cc)return;out.push({empresaId:d.empresaId,conta:c,ccId,cc,valores:valoresDocumento(d,cen,rmap,c).map(v=>v*sinalConta(c)),estatistica:stat})});return out}
function folhasNo(conta,permitidas){if(contaAnalitica(conta))return permitidas.has(conta.id)?[conta]:[];return folhasDescendentes(plano,conta.id).filter(c=>permitidas.has(c.id))}
function valoresNo(conta,permitidas,linhas,ccId=null){const ids=new Set(folhasNo(conta,permitidas).map(c=>c.id));return somaVetores(linhas.filter(l=>ids.has(l.conta.id)&&(!ccId||l.ccId===ccId)).map(l=>l.valores))}
function chaveExp(prefix,id){return`${prefix}|${id}`}
function arvoreVisivel(arvore,prefix){const out=[];let bloqueado=null;for(const item of arvore){if(bloqueado!==null){if(item.nivel>bloqueado)continue;bloqueado=null}out.push(item);if(contaSintetica(item.conta)&&!expandidas.has(chaveExp(prefix,item.conta.id)))bloqueado=item.nivel}return out}
function celulasFinanceiras(vals,cols,forte=true){return cols.map(c=>`<td class="numero ${c.tipo!=="mes"?"fpa-total":""}">${forte?"<strong>":""}${moeda(valorFinanceiro(vals,c))}${forte?"</strong>":""}</td>`).join("")}
function celulasEstat(vals,cols,c,sintetica=false){return cols.map(col=>`<td class="numero ${col.tipo!=="mes"?"fpa-total":""}">${sintetica?"—":formatoEstat(valorEstatistico(vals,col,c),c)}</td>`).join("")}
function rowConta(c,nivel,prefix,permitidas,linhas,ccId=null,stat=false){const sint=contaSintetica(c),key=chaveExp(prefix,c.id),vals=valoresNo(c,permitidas,linhas,ccId),btn=sint?`<button class="dre-tree-toggle ${expandidas.has(key)?"aberta":""}" data-dre-v7-toggle="${esc(key)}" type="button" aria-label="${expandidas.has(key)?"Recolher":"Expandir"}"></button>`:'<span class="dre-tree-spacer"></span>',classe=`${sint?"dre-v7-sint":""} ${stat?"dre-v7-estat":""}`;return`<tr class="${classe}"><td><div class="dre-v7-tree ${sint?"sintetica":""}"><span class="indent" style="width:${Math.min(nivel,8)*18}px"></span>${btn}<span>${esc(c.codigo||"")} · ${esc(c.nome||"")}</span></div>${sint?'<small>Σ Conta sintética</small>':""}</td>${stat?celulasEstat(vals,colunas(),c,sint):celulasFinanceiras(vals,colunas(),sint)}</tr>`}
function linhaTitulo(label,vals,cols,classe){return`<tr class="${classe}"><td><strong>${esc(label)}</strong></td>${celulasFinanceiras(vals,cols,true)}</tr>`}
function renderEstatisticas(linhas,cols,corpo){const folhas=plano.filter(c=>contaAtivaNoExercicio(c,periodoAno())&&contaEstatistica(c)&&contaAnalitica(c)).map(c=>c.id),permitidas=new Set(folhas);if(!permitidas.size)return;const arv=arvoreParaFolhas(plano,permitidas,{estatistica:true});corpo.push(`<tr class="dre-v7-estat-bloco"><td><strong>${esc(CC_ESTATISTICO_NOME.toUpperCase())}</strong></td>${cols.map(()=>'<td>—</td>').join("")}</tr>`);for(const item of arvoreVisivel(arv,"estat"))corpo.push(rowConta(item.conta,item.nivel,"estat",permitidas,linhas,CC_ESTATISTICO_ID,true))}
function centrosFinanceiros(){const ids=new Set(empresasSelecionadasIds()),arr=centros.filter(c=>c.status!=="inativo"&&ids.has(c.empresaId)).sort((a,b)=>String(a.codigo||"").localeCompare(String(b.codigo||""),"pt-BR")),f=ccFiltro();return f&&f!==CC_ESTATISTICO_ID?arr.filter(c=>c.id===f):arr}
function renderPorCentro(linhas,cols,corpo){const conteudo=modoConteudo();if((conteudo==="completa"||conteudo==="estatisticas")&&(!ccFiltro()||ccFiltro()===CC_ESTATISTICO_ID))renderEstatisticas(linhas,cols,corpo);if(conteudo==="estatisticas"||ccFiltro()===CC_ESTATISTICO_ID)return;const ccs=centrosFinanceiros();for(const[gid,glabel]of GRUPOS){const folhasGrupo=plano.filter(c=>contaAtivaNoExercicio(c,periodoAno())&&contaDre(c)&&!contaEstatistica(c)&&contaAnalitica(c)&&grupoEfetivo(c)===gid);if(!folhasGrupo.length)continue;const permitidasGrupo=new Set();for(const cc of ccs){const ids=new Set(Array.isArray(cc.contasPermitidas)?cc.contasPermitidas:[]);folhasGrupo.forEach(c=>{if(ids.has(c.id))permitidasGrupo.add(c.id)})}if(!permitidasGrupo.size)continue;const valsGrupo=somaVetores([...permitidasGrupo].map(id=>{const c=plano.find(x=>x.id===id);return valoresNo(c,new Set([id]),linhas,null)}));corpo.push(linhaTitulo(glabel,valsGrupo,cols,"dre-v7-grupo"));for(const cc of ccs){const permitidas=new Set((Array.isArray(cc.contasPermitidas)?cc.contasPermitidas:[]).filter(id=>folhasGrupo.some(c=>c.id===id)));if(!permitidas.size)continue;const valsCc=somaVetores([...permitidas].map(id=>{const c=plano.find(x=>x.id===id);return valoresNo(c,new Set([id]),linhas,cc.id)}));corpo.push(linhaTitulo(`${cc.codigo||""} · ${cc.nome||"Centro"}`,valsCc,cols,"dre-v7-cc"));const arv=arvoreParaFolhas(plano,permitidas,{estatistica:false}),prefix=`cc:${cc.id}:${gid}`;for(const item of arvoreVisivel(arv,prefix))corpo.push(rowConta(item.conta,item.nivel,prefix,permitidas,linhas,cc.id,false))}}}
function renderConsolidada(linhas,cols,corpo){for(const[gid,glabel]of GRUPOS){const folhas=plano.filter(c=>contaAtivaNoExercicio(c,periodoAno())&&contaDre(c)&&!contaEstatistica(c)&&contaAnalitica(c)&&grupoEfetivo(c)===gid).map(c=>c.id),permitidas=new Set(folhas);if(!permitidas.size)continue;const vals=somaVetores(folhas.map(id=>{const c=plano.find(x=>x.id===id);return valoresNo(c,new Set([id]),linhas,null)}));corpo.push(linhaTitulo(glabel,vals,cols,"dre-v7-grupo"));const arv=arvoreParaFolhas(plano,permitidas,{estatistica:false}),prefix=`cons:${gid}`;for(const item of arvoreVisivel(arv,prefix))corpo.push(rowConta(item.conta,item.nivel,prefix,permitidas,linhas,null,false))}}
function resultadoFinanceiro(linhas){const f=ccFiltro();return somaVetores(linhas.filter(l=>!l.estatistica&&(!f||f===CC_ESTATISTICO_ID?f!==CC_ESTATISTICO_ID:l.ccId===f)).map(l=>l.valores))}
function render(){const t=$("tabelaDreV7");if(!t)return;ajustarFiltros();const cols=colunas(),linhas=linhasBase(),corpo=[];if(visao()==="consolidada")renderConsolidada(linhas,cols,corpo);else renderPorCentro(linhas,cols,corpo);if(modoConteudo()!=="estatisticas"&&ccFiltro()!==CC_ESTATISTICO_ID){const res=resultadoFinanceiro(linhas);corpo.push(`<tr class="dre-v7-resultado"><td>RESULTADO / SALDO DO PERÍODO</td>${cols.map(c=>`<td class="numero"><strong>${moeda(valorFinanceiro(res,c))}</strong></td>`).join("")}</tr>`)}t.innerHTML=`<thead><tr><th>Grupo / Centro / Conta</th>${cols.map(c=>`<th>${esc(c.label)}</th>`).join("")}</tr></thead><tbody>${corpo.join("")||`<tr><td colspan="${cols.length+1}">Nenhuma informação encontrada para este contexto.</td></tr>`}</tbody>`;$("dreV7Contexto").textContent=contextoTexto();$("dreV7Titulo").textContent=`DRE · ${cenario()==="realizado"?"Realizado":cenario()==="budget"?"Budget":"Forecast"}`;$("dreV7Legenda").textContent=contextoTexto();t.querySelectorAll("[data-dre-v7-toggle]").forEach(b=>b.addEventListener("click",()=>{const k=b.dataset.dreV7Toggle;expandidas.has(k)?expandidas.delete(k):expandidas.add(k);render()}))}
function expandirTudo(){const prefixos=new Set();if(visao()==="consolidada")GRUPOS.forEach(([g])=>prefixos.add(`cons:${g}`));else{prefixos.add("estat");centrosFinanceiros().forEach(cc=>GRUPOS.forEach(([g])=>prefixos.add(`cc:${cc.id}:${g}`)))}for(const p of prefixos)plano.filter(c=>contaAtivaNoExercicio(c,periodoAno())&&contaSintetica(c)).forEach(c=>expandidas.add(chaveExp(p,c.id)));render()}
function recolherTudo(){expandidas.clear();render()}
async function carregar(){criarPagina();if(carregando)return;const ids=empresasSelecionadasIds();if(!ids.length){$("tabelaDreV7").innerHTML='<tbody><tr><td>Selecione ao menos uma empresa.</td></tr></tbody>';return}const b=$("btnAtualizarDreV7");carregando=true;if(b){b.disabled=true;b.textContent="Atualizando..."}try{const cen=cenario(),col=cen==="realizado"?"realizadoMensal":cen==="budget"?"budgetLinhas":"forecastLinhas";[plano,centros,docs,realizados]=await Promise.all([listarDocumentos("planoContasGerencial"),listarDocumentos("centrosCusto"),listarDocumentos(col),cen==="forecast"?listarDocumentos("realizadoMensal"):Promise.resolve([])]);preencherCentros();limparAviso();render()}catch(e){console.error("DRE V7:",e);const a=$("dreV7Aviso");if(a){a.classList.remove("hidden");a.textContent="Não foi possível carregar a DRE."}}finally{carregando=false;if(b){b.disabled=false;b.textContent="Atualizar"}}}
function exportarExcel(){const t=$("tabelaDreV7");if(!t)return;exportarTabelaXls(t,{nome:`dre_${cenario()}_${periodoAno()}_${periodoChave()}`,titulo:$("dreV7Titulo")?.textContent||"DRE Gerencial",meta:[contextoTexto()]})}
async function imprimir(){const t=$("tabelaDreV7");if(!t)return;await exportarTabelaPdf(t,{nome:`dre_${cenario()}_${periodoAno()}_${periodoChave()}`,titulo:$("dreV7Titulo")?.textContent||"DRE Gerencial",meta:[contextoTexto()]})}
export function abrir(){criarPagina();abrirPagina("ctrl-dre-v7");const t=$("tituloPagina");if(t)t.textContent="DRE Gerencial";carregar()}
export{carregar};
criarPagina();window.addEventListener("sig:periodo-changed",()=>{if(visivel())marcarSujo("Período alterado no cabeçalho.")});window.addEventListener("sig:empresa-changed",()=>{if(visivel())marcarSujo("Empresa alterada no cabeçalho.")});
