import { abrirPagina, state, db, admin } from "./core.js";
import { $, esc, msg, permite, moeda, listarDocumentos, empresaUnicaSelecionadaId, grupoAtualId, periodoAno, nomeEmpresa } from "./shared.js";
import { writeBatch, doc, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";

const MESES=[["jan","Jan"],["fev","Fev"],["mar","Mar"],["abr","Abr"],["mai","Mai"],["jun","Jun"],["jul","Jul"],["ago","Ago"],["set","Set"],["out","Out"],["nov","Nov"],["dez","Dez"]];
let plano=[],centros=[],premissas=[],realizados=[],budgets=[],detalhes=[],busy=false,expandidas=new Set(),drafts=new Map(),detailDrafts=new Map();
const n=v=>{const x=Number(v||0);return Number.isFinite(x)?x:0};const stamp=x=>n(x?.atualizadoEm?.seconds||x?.criadoEm?.seconds||0);const vazio=()=>Object.fromEntries(MESES.map(([m])=>[m,0]));const total=v=>MESES.reduce((s,[m])=>s+n(v?.[m]),0);const pagina=()=>$("pagina-ctrl-budget");const podeEditar=()=>admin()||permite("controladoria","editar")||permite("controladoria","budget");
function idSeguro(v){return String(v||"sem").replace(/[^a-zA-Z0-9_-]/g,"_")}function budgetId(emp,ano,vers,cc,conta){return `b_${idSeguro(emp)}_${ano}_${idSeguro(vers)}_${idSeguro(cc)}_${idSeguro(conta)}`}
function contexto(){const emp=empresaUnicaSelecionadaId(),ano=Number($("budgetV2Ano")?.value||periodoAno()),vers=$("budgetV2Versao")?.value.trim()||`Budget ${ano} - V1`,cc=$("budgetV2Centro")?.value||"";return{emp,ano,vers,cc}}
function valoresA1(contaId,cc,ano){const out=vazio();realizados.filter(x=>x.contaId===contaId&&(x.centroCustoId||"")===cc&&Number(x.exercicio)===ano-1).forEach(x=>MESES.forEach(([m])=>out[m]+=n(x.valores?.[m])));return out}
function docsBudget(contaId,cc,ano,vers){return budgets.filter(x=>x.contaId===contaId&&(x.centroCustoId||"")===cc&&Number(x.exercicio)===ano&&x.versao===vers).sort((a,b)=>stamp(b)-stamp(a))}
function valoresBudget(contaId,cc,ano,vers){const d=docsBudget(contaId,cc,ano,vers)[0];return{...vazio(),...(d?.valores||{})}}
function detalhesConta(contaId,cc,ano,vers){const base=detalhes.filter(x=>x.status!=="inativo"&&x.cenario==="budget"&&x.contaId===contaId&&(x.centroCustoId||"")===cc&&Number(x.exercicio)===ano&&x.versao===vers);const extras=[...detailDrafts.values()].filter(x=>x._novo&&x.contaId===contaId&&x.centroCustoId===cc&&x.exercicio===ano&&x.versao===vers&&!x._removido);return [...base.filter(x=>!detailDrafts.get(x.id)?._removido).map(x=>detailDrafts.get(x.id)||x),...extras]}
function premissasConta(contaId,cc){return premissas.filter(x=>x.ativo!==false&&x.contaGerencialId===contaId&&(!(x.centroCustoId||"")||(x.centroCustoId||"")===cc)}
function pct(a,b){if(!b)return a?null:0;return(a-b)/Math.abs(b)*100}function pctHtml(a,b){const p=pct(a,b);return p===null?'<span class="fpa-var neutra">—</span>':`<span class="fpa-var ${p>0?"positiva":p<0?"negativa":"neutra"}">${p>0?"+":""}${p.toLocaleString("pt-BR",{maximumFractionDigits:1})}%</span>`}
function contasCentro(cc){const centro=centros.find(x=>x.id===cc);if(!centro)return[];const ids=new Set(Array.isArray(centro.contasPermitidas)?centro.contasPermitidas:[]);return plano.filter(x=>x.status!=="inativo"&&ids.has(x.id)).sort((a,b)=>n(a.ordem)-n(b.ordem)||String(a.codigo||"").localeCompare(String(b.codigo||""),"pt-BR"))}
function criarPagina(){if(pagina())return;const main=document.querySelector("main.conteudo");if(!main)return;const s=document.createElement("section");s.id="pagina-ctrl-budget";s.className="pagina hidden";s.innerHTML=`
<div class="pagina-cabecalho"><div><span class="eyebrow">CONTROLADORIA & FP&A</span><h2>Budget</h2><p>Budget por centro de custo, conta e memória de cálculo, com histórico A‑1 e detalhamento inline.</p></div><div class="acoes-cabecalho"><button id="btnAplicarPremissasV2" class="btn-secundario" type="button">Aplicar premissas</button><button id="btnSalvarBudgetV2" class="btn-primario" type="button">Salvar Budget</button></div></div>
<div id="budgetV2Aviso" class="modulo-aviso">Selecione um centro de custo. Somente contas autorizadas na matriz Centro × Conta serão exibidas.</div>
<div class="fpa-toolbar"><div class="campo"><label for="budgetV2Ano">Exercício do Budget</label><input id="budgetV2Ano" type="number" min="2021" max="2100"></div><div class="campo"><label for="budgetV2Versao">Versão</label><input id="budgetV2Versao"></div><div class="campo"><label for="budgetV2Centro">Centro de custo</label><select id="budgetV2Centro"><option value="">Selecione...</option></select></div><button id="btnAtualizarBudgetV2" class="btn-secundario" type="button">Atualizar</button><span id="mensagemBudgetV2" class="mensagem-form"></span></div>
<section class="lista-card"><div class="lista-cabecalho"><div><h3>Matriz de Budget</h3><p id="budgetV2Legenda">A‑1 × Budget × variação.</p></div><span id="budgetV2Resumo"></span></div><div class="fpa-grid-wrap"><table id="tabelaBudgetV2" class="fpa-grid fpa-grid-budget"><tbody><tr><td>Carregando...</td></tr></tbody></table></div></section>`;main.appendChild(s);$("budgetV2Ano").value=periodoAno();$("budgetV2Versao").value=`Budget ${periodoAno()} - V1`;$("btnAtualizarBudgetV2")?.addEventListener("click",carregar);$("budgetV2Centro")?.addEventListener("change",render);$("budgetV2Ano")?.addEventListener("change",()=>{$("budgetV2Versao").value=`Budget ${$("budgetV2Ano").value} - V1`;render()});$("budgetV2Versao")?.addEventListener("change",render);$("btnAplicarPremissasV2")?.addEventListener("click",aplicarTodas);$("btnSalvarBudgetV2")?.addEventListener("click",salvar)}
function preencherCentros(){const s=$("budgetV2Centro"),atual=s?.value||"";if(!s)return;s.innerHTML='<option value="">Selecione o centro...</option>'+centros.filter(x=>x.status!=="inativo").sort((a,b)=>String(a.codigo||"").localeCompare(String(b.codigo||""),"pt-BR")).map(x=>`<option value="${esc(x.id)}">${esc(x.codigo||"")} · ${esc(x.nome||"")}</option>`).join("");if(atual&&[...s.options].some(o=>o.value===atual))s.value=atual}
function draftConta(contaId){const cx=contexto();if(drafts.has(contaId))return drafts.get(contaId);const v=valoresBudget(contaId,cx.cc,cx.ano,cx.vers);drafts.set(contaId,v);return v}
function somaDetalhes(contaId){const cx=contexto(),arr=detalhesConta(contaId,cx.cc,cx.ano,cx.vers),out=vazio();arr.forEach(d=>MESES.forEach(([m])=>out[m]+=n(d.valores?.[m])));return{arr,valores:out}}
function linhaPrincipal(c){const cx=contexto(),a1=valoresA1(c.id,cx.cc,cx.ano),det=somaDetalhes(c.id),temDetalhe=det.arr.length>0,v=temDetalhe?det.valores:draftConta(c.id),ps=premissasConta(c.id,cx.cc);if(temDetalhe)drafts.set(c.id,{...v});return`<tr data-budget-v2="${c.id}"><td class="sticky-col conta-col"><button class="btn-mini" data-budget-expand="${c.id}" type="button">${expandidas.has(c.id)?"▾":"▸"}</button> <strong>${esc(c.codigo||"")}</strong><span>${esc(c.nome||"")}</span><small>${temDetalhe?`${det.arr.length} sublinha(s) · soma automática`:"Lançamento direto"}</small></td><td class="sticky-col premissa-col">${ps.length?ps.map(p=>`<span class="status-ativo">${esc(p.nome)}</span>`).join(" "):"—"}</td>${MESES.map(([m])=>`<td class="fpa-readonly" data-a1="${m}">${n(a1[m]).toLocaleString("pt-BR",{maximumFractionDigits:2})}</td><td><input data-budget-mes="${m}" type="number" step="0.01" value="${n(v[m])}" ${temDetalhe?"disabled":""}></td><td data-budget-var="${m}">${pctHtml(v[m],a1[m])}</td>`).join("")}<td class="fpa-total" data-total-a1>${moeda(total(a1))}</td><td class="fpa-total" data-total-b>${moeda(total(v))}</td><td class="fpa-total" data-total-var>${pctHtml(total(v),total(a1))}</td></tr>${expandidas.has(c.id)?linhaDetalhes(c,det.arr):""}`}
function linhaDetalhes(c,arr){const cx=contexto();return`<tr class="budget-detail-row"><td colspan="41"><div class="budget-inline"><div class="lista-cabecalho"><div><strong>Memória de cálculo · ${esc(c.codigo||"")} · ${esc(c.nome||"")}</strong><p>Centro: ${esc(centros.find(x=>x.id===cx.cc)?.nome||"")} · as sublinhas somam automaticamente a linha principal.</p></div><button class="btn-secundario" data-add-detail="${c.id}" type="button">+ Sublinha</button></div><div class="tabela-container"><table class="tabela"><thead><tr><th>Descrição / memória</th>${MESES.map(([,nm])=>`<th>${nm}</th>`).join("")}<th>Total</th><th>Ação</th></tr></thead><tbody>${arr.length?arr.map(d=>linhaDetalhe(c.id,d)).join(""):'<tr><td colspan="15">Sem sublinhas. Clique em + Sublinha para detalhar.</td></tr>'}</tbody></table></div></div></td></tr>`}
function linhaDetalhe(contaId,d){const v={...vazio(),...(d.valores||{})};return`<tr data-detail="${esc(d.id)}" data-conta="${esc(contaId)}"><td><input data-detail-desc type="text" value="${esc(d.descricao||"")}" placeholder="Descrição"><small>${esc(d.comentario||"")}</small></td>${MESES.map(([m])=>`<td><input data-detail-mes="${m}" type="number" step="0.01" value="${n(v[m])}"></td>`).join("")}<td data-detail-total>${moeda(total(v))}</td><td><button class="btn-acao" data-rem-detail="${esc(d.id)}" type="button">Remover</button></td></tr>`}
function render(){const t=$("tabelaBudgetV2");if(!t)return;const cx=contexto();if(!cx.emp){t.innerHTML='<tbody><tr><td>Selecione uma única empresa no cabeçalho.</td></tr></tbody>';return}if(!cx.cc){t.innerHTML='<tbody><tr><td>Selecione um centro de custo. Isso evita Budget sem amarração gerencial.</td></tr></tbody>';$("budgetV2Aviso").textContent="O Centro de Custo é obrigatório para edição do Budget.";return}const contas=contasCentro(cx.cc);$("budgetV2Legenda").textContent=`Realizado ${cx.ano-1} (A‑1) × Budget ${cx.ano} · ${cx.vers}`;$("budgetV2Resumo").textContent=`${nomeEmpresa(cx.emp)} · ${centros.find(x=>x.id===cx.cc)?.nome||"Centro"} · ${contas.length} conta(s)`;const cab=MESES.map(([,nm])=>`<th colspan="3">${nm}</th>`).join(""),sub=MESES.map(()=>'<th>R A‑1</th><th>Budget</th><th>Δ%</th>').join("");t.innerHTML=`<thead><tr><th rowspan="2" class="sticky-col conta-col">Conta / detalhamento</th><th rowspan="2" class="sticky-col premissa-col">Premissa</th>${cab}<th colspan="3">Total anual</th></tr><tr>${sub}<th>R ${cx.ano-1}</th><th>Budget ${cx.ano}</th><th>Δ%</th></tr></thead><tbody>${contas.length?contas.map(linhaPrincipal).join(""):'<tr><td colspan="41">Nenhuma conta autorizada para este centro. Configure Centro × Conta.</td></tr>'}</tbody>`;bindTabela()}
function bindTabela(){const t=$("tabelaBudgetV2");t?.querySelectorAll("[data-budget-expand]").forEach(b=>b.addEventListener("click",()=>{const id=b.dataset.budgetExpand;if(expandidas.has(id))expandidas.delete(id);else expandidas.add(id);render()}));t?.querySelectorAll("tr[data-budget-v2]").forEach(tr=>tr.querySelectorAll("[data-budget-mes]").forEach(i=>i.addEventListener("input",()=>{const id=tr.dataset.budgetV2,d=draftConta(id);d[i.dataset.budgetMes]=n(i.value);atualizarLinha(tr,id)})));t?.querySelectorAll("[data-add-detail]").forEach(b=>b.addEventListener("click",()=>adicionarDetalhe(b.dataset.addDetail)));t?.querySelectorAll("[data-detail]").forEach(tr=>{tr.querySelectorAll("[data-detail-mes]").forEach(i=>i.addEventListener("input",()=>atualizarDetalhe(tr)));tr.querySelector("[data-detail-desc]")?.addEventListener("input",()=>atualizarDetalhe(tr));tr.querySelector("[data-rem-detail]")?.addEventListener("click",()=>removerDetalhe(tr.dataset.detail,tr.dataset.conta))})}
function atualizarLinha(tr,contaId){const cx=contexto(),v=draftConta(contaId),a1=valoresA1(contaId,cx.cc,cx.ano);MESES.forEach(([m])=>{const el=tr.querySelector(`[data-budget-var="${m}"]`);if(el)el.innerHTML=pctHtml(v[m],a1[m])});tr.querySelector("[data-total-b]").textContent=moeda(total(v));tr.querySelector("[data-total-var]").innerHTML=pctHtml(total(v),total(a1))}
function adicionarDetalhe(contaId){const cx=contexto(),id=`new_${crypto.randomUUID()}`,d={id,_novo:true,cenario:"budget",exercicio:cx.ano,versao:cx.vers,contaId,centroCustoId:cx.cc,origem:"manual",descricao:"",comentario:"",valores:vazio(),status:"ativo"};detailDrafts.set(id,d);expandidas.add(contaId);render()}
function atualizarDetalhe(tr){const id=tr.dataset.detail,base=detailDrafts.get(id)||detalhes.find(x=>x.id===id);if(!base)return;const d={...base,valores:{...vazio(),...(base.valores||{})},descricao:tr.querySelector("[data-detail-desc]")?.value||""};MESES.forEach(([m])=>d.valores[m]=n(tr.querySelector(`[data-detail-mes="${m}"]`)?.value));detailDrafts.set(id,d);tr.querySelector("[data-detail-total]").textContent=moeda(total(d.valores));recalcularPai(tr.dataset.conta)}
function recalcularPai(contaId){const cx=contexto(),s=somaDetalhes(contaId).valores;drafts.set(contaId,{...s});const tr=$("tabelaBudgetV2")?.querySelector(`tr[data-budget-v2="${contaId}"]`);if(!tr)return;MESES.forEach(([m])=>{const i=tr.querySelector(`[data-budget-mes="${m}"]`);if(i)i.value=n(s[m])});atualizarLinha(tr,contaId)}
function removerDetalhe(id,contaId){const base=detailDrafts.get(id)||detalhes.find(x=>x.id===id);if(!base)return;detailDrafts.set(id,{...base,_removido:true});render();recalcularPai(contaId)}
function aplicarPremissa(contaId){const cx=contexto(),ps=premissasConta(contaId,cx.cc);if(!ps.length)return false;if(detalhesConta(contaId,cx.cc,cx.ano,cx.vers).length)return false;const p=ps.find(x=>(x.centroCustoId||"")===cx.cc)||ps[0],a1=valoresA1(contaId,cx.cc,cx.ano),d=draftConta(contaId);MESES.forEach(([m])=>{d[m]=p.tipo==="crescimento"?n(a1[m])*(1+n(p.percentual)/100):p.tipo==="valor_fixo"?n(p.valorFixo):p.tipo==="repetir_realizado"?n(a1[m]):n(d[m])});return true}
function aplicarTodas(){const cx=contexto();if(!cx.cc)return msg($("mensagemBudgetV2"),"Selecione o centro de custo.");let ok=0,skip=0;contasCentro(cx.cc).forEach(c=>aplicarPremissa(c.id)?ok++:skip++);render();msg($("mensagemBudgetV2"),`${ok} conta(s) preenchida(s) por premissa${skip?`; ${skip} sem premissa ou com detalhamento manual`:""}.`,true)}
async function carregar(){criarPagina();if(busy||!empresaUnicaSelecionadaId())return;busy=true;msg($("mensagemBudgetV2"),"Carregando Budget...");try{[plano,centros,premissas,realizados,budgets,detalhes]=await Promise.all([listarDocumentos("planoContasGerencial"),listarDocumentos("centrosCusto"),listarDocumentos("premissasPlanejamento"),listarDocumentos("realizadoMensal"),listarDocumentos("budgetLinhas"),listarDocumentos("planejamentoDetalhes")]);drafts.clear();detailDrafts.clear();preencherCentros();render();msg($("mensagemBudgetV2"),"")}catch(e){console.error("Budget:",e);msg($("mensagemBudgetV2"),"Não foi possível carregar o Budget.")}finally{busy=false}}
async function salvar(){if(!podeEditar())return;const cx=contexto();if(!cx.emp||!cx.cc)return msg($("mensagemBudgetV2"),"Selecione uma empresa e um centro de custo.");const b=$("btnSalvarBudgetV2");b.disabled=true;b.textContent="Salvando...";try{const batch=writeBatch(db),grupoId=grupoAtualId();for(const c of contasCentro(cx.cc)){const vals=draftConta(c.id),ds=docsBudget(c.id,cx.cc,cx.ano,cx.vers),ref=ds.length?doc(db,"budgetLinhas",ds[0].id):doc(db,"budgetLinhas",budgetId(cx.emp,cx.ano,cx.vers,cx.cc,c.id)),dados={grupoId,empresaId:cx.emp,contaId:c.id,centroCustoId:cx.cc,exercicio:cx.ano,versao:cx.vers,valores:{...vals},status:"rascunho",atualizadoEm:serverTimestamp()};if(ds.length)batch.update(ref,dados);else batch.set(ref,{...dados,criadoPor:state.usuario.id,criadoEm:serverTimestamp()});for(const dup of ds.slice(1))batch.update(doc(db,"budgetLinhas",dup.id),{valores:vazio(),normalizadoPor:state.usuario.id,atualizadoEm:serverTimestamp()})}
  for(const d of detailDrafts.values()){if(d._novo&&d._removido)continue;const ref=doc(db,"planejamentoDetalhes",d._novo?idSeguro(d.id):d.id),dados={grupoId,empresaId:cx.emp,cenario:"budget",exercicio:cx.ano,versao:cx.vers,contaId:d.contaId,centroCustoId:cx.cc,origem:d.origem||"manual",descricao:d.descricao||"",comentario:d.comentario||"",valores:{...vazio(),...(d.valores||{})},status:d._removido?"inativo":"ativo",atualizadoEm:serverTimestamp()};if(d._novo)batch.set(ref,{...dados,criadoPor:state.usuario.id,criadoEm:serverTimestamp()});else batch.update(ref,dados)}await batch.commit();msg($("mensagemBudgetV2"),"Budget salvo. Linhas principais e sublinhas conciliadas.",true);await carregar()}catch(e){console.error(e);msg($("mensagemBudgetV2"),"Não foi possível salvar o Budget.")}finally{b.disabled=false;b.textContent="Salvar Budget"}}
export function abrir(){criarPagina();abrirPagina("ctrl-budget");const t=$("tituloPagina");if(t)t.textContent="Budget";carregar()}
criarPagina();window.addEventListener("sig:empresa-changed",()=>{if(pagina()&&!pagina().classList.contains("hidden"))msg($("mensagemBudgetV2"),"Empresa alterada. Clique em Atualizar.")});
