import { $, esc, permite, moeda, diasAte, competenciaAtual, listarDocumentos } from "./shared.js";
let carregando=false;
function set(id,v){const e=$(id);if(e)e.textContent=v}
export async function carregarDashboard(){if(carregando||!permite("dashboard"))return;carregando=true;try{
 const tarefas={};if(permite("contratos"))tarefas.contratos=listarDocumentos("contratos");if(permite("frota"))tarefas.frota=listarDocumentos("veiculos");if(permite("almoxarifado"))tarefas.estoque=listarDocumentos("itensAlmoxarifado");if(permite("cotacoes"))tarefas.cotacoes=listarDocumentos("cotacoes");if(permite("prestadores"))tarefas.prestadores=listarDocumentos("prestadores");if(permite("controladoria"))tarefas.ctrl=listarDocumentos("planejamentoMensal");
 const chaves=Object.keys(tarefas),result=await Promise.all(Object.values(tarefas)),d={};chaves.forEach((k,i)=>d[k]=result[i]);
 const contratos=d.contratos||[],ativos=contratos.filter(x=>x.status==="ativo"&&((diasAte(x.fim)??1)>=0)),vencer=ativos.filter(x=>{const a=diasAte(x.fim);return a!==null&&a<=60});set("dashContratosAtivos",ativos.length);set("dashContratosVencer",`${vencer.length} a vencer em 60 dias`);
 const frota=d.frota||[];set("dashFrotaAtiva",frota.filter(x=>x.status==="ativo").length);set("dashFrotaManutencao",`${frota.filter(x=>x.status==="manutencao").length} em manutenção`);
 const estoque=d.estoque||[],criticos=estoque.filter(x=>x.status!=="inativo"&&Number(x.estoqueAtual||0)<=Number(x.estoqueMinimo||0));set("dashEstoqueCritico",criticos.length);
 const cot=d.cotacoes||[],pend=cot.filter(x=>!["finalizada","reprovada"].includes(x.status));set("dashCotacoesPendentes",pend.length);set("dashCotacoesAprovacao",`${cot.filter(x=>x.status==="aguardando_aprovacao").length} em aprovação`);
 const prest=d.prestadores||[];set("dashPrestadoresAtivos",prest.filter(x=>x.status!=="inativo").length);
 const ctrl=(d.ctrl||[]).filter(x=>x.competencia===competenciaAtual()),ass=x=>x.natureza==="receita"?1:-1,real=ctrl.reduce((s,x)=>s+ass(x)*Number(x.realizado||0),0),budget=ctrl.reduce((s,x)=>s+ass(x)*Number(x.orcado||0),0),pct=budget?((real-budget)/Math.abs(budget))*100:0;set("dashResultadoGerencial",moeda(real));set("dashVariacaoBudget",`${pct>0?"+":""}${pct.toLocaleString("pt-BR",{maximumFractionDigits:1})}% vs. budget`);
 const prioridades=[];vencer.sort((a,b)=>(diasAte(a.fim)||999)-(diasAte(b.fim)||999)).slice(0,4).forEach(x=>prioridades.push({titulo:`Contrato ${x.numero||x.fornecedor}`,sub:`vence em ${diasAte(x.fim)} dia(s)`,tag:"Contrato"}));criticos.slice(0,4).forEach(x=>prioridades.push({titulo:x.descricao||x.codigo,sub:`saldo ${Number(x.estoqueAtual||0).toLocaleString("pt-BR")} · mínimo ${Number(x.estoqueMinimo||0).toLocaleString("pt-BR")}`,tag:"Estoque"}));cot.filter(x=>x.status==="aguardando_aprovacao").slice(0,4).forEach(x=>prioridades.push({titulo:x.titulo,sub:`${x.fornecedor||"Fornecedor"} · ${x.valorProposto?moeda(x.valorProposto):"sem valor"}`,tag:"Aprovação"}));frota.filter(x=>x.status==="manutencao").slice(0,3).forEach(x=>prioridades.push({titulo:`${x.placa} · ${x.modelo}`,sub:"veículo em manutenção",tag:"Frota"}));
 const area=$("dashPendencias");if(area)area.innerHTML=prioridades.length?prioridades.slice(0,10).map(p=>`<div class="pendencia-item"><div class="pendencia-info"><strong>${esc(p.titulo)}</strong><span>${esc(p.sub)}</span></div><span class="pendencia-tag">${esc(p.tag)}</span></div>`).join(""):'<div class="empty-state">Nenhuma pendência crítica nos módulos liberados.</div>';
 set("dashAtualizadoEm",`Atualizado às ${new Date().toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}`);
 }catch(e){console.error("Dashboard:",e);const a=$("dashPendencias");if(a)a.innerHTML='<div class="empty-state">Não foi possível consolidar os indicadores.</div>'}finally{carregando=false}}
window.addEventListener("sig:ready",carregarDashboard);window.addEventListener("sig:data-changed",carregarDashboard);window.addEventListener("sig:page",e=>{if(e.detail?.pagina==="dashboard")carregarDashboard()});
