import { $, esc, permite, admin, moeda, listarDocumentos, periodoAno, periodoChave, empresasSelecionadasIds, state, db } from "./shared.js";
import { doc, getDoc, setDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";
import { construirLinhasFinanceiras, resumirDre, linhasPorCodigo } from "./financial-reporting.js";
import { calcularConsorcio, statusConsorcioAtivo } from "./consortium-calculations.js";
import { contaAnalitica } from "./account-tree.js";
import { raizConta, multiplicadorApresentacao } from "./account-mask.js";
import { contaAtivaNoExercicio } from "./account-validity.js";
import { contaBalanco, CC_BALANCO_ID } from "./balance-center.js";
import { mapaImobilizadoBalanco } from "./asset-depreciation.js";

const MESES=["Jan","Fev","Mar","Abr","Mai","Jun","Jul","Ago","Set","Out","Nov","Dez"];
const CHAVES=["jan","fev","mar","abr","mai","jun","jul","ago","set","out","nov","dez"];
const PERIODOS={total:[0,1,2,3,4,5,6,7,8,9,10,11],t1:[0,1,2],t2:[3,4,5],t3:[6,7,8],t4:[9,10,11]};
for(let i=0;i<12;i++)PERIODOS[`m${String(i+1).padStart(2,"0")}`]=[i];
const ORDEM_PADRAO=["executivo","evolucao","balanco","caixa","inadimplencia","consorcios","permutas","vendas","desvios"];
let carregando=false,preferencia={ordem:[...ORDEM_PADRAO],ocultos:[]};
const n=v=>{const x=Number(v||0);return Number.isFinite(x)?x:0};
const pct=(a,b)=>Math.abs(b)>0.000001?(a-b)/Math.abs(b)*100:null;
const pctFmt=v=>v==null?"—":`${v>0?"+":""}${v.toLocaleString("pt-BR",{maximumFractionDigits:1})}%`;
const visivel=()=>!!$("pagina-dashboard")&&!$("pagina-dashboard").classList.contains("hidden");
const podeCtrl=()=>admin()||permite("controladoria","visualizar");
const podeInad=()=>admin()||permite("controladoria","inadimplencia")||permite("controladoria","inadimplenciaEditar")||permite("controladoria","editar");
const podeCons=()=>admin()||permite("consorcios","visualizar")||permite("consorcios","editar")||permite("controladoria","consorciosVisualizar")||permite("controladoria","consorciosEditar")||permite("controladoria","editar");
const podePerm=()=>admin()||["visualizar","cadastrar","editar","movimentar","estornar","fechar","inativar"].some(a=>permite("permutas",a));
const podeVendas=()=>admin()||["visualizar","lancar","editar","vendedores","comissoes"].some(a=>permite("vendas",a));

const WIDGETS={
  executivo:{nome:"Resumo executivo",perm:podeCtrl},
  evolucao:{nome:"Evolução de resultado",perm:podeCtrl},
  balanco:{nome:"Análise patrimonial",perm:podeCtrl},
  caixa:{nome:"Posição e projeção de caixa",perm:podeCtrl},
  inadimplencia:{nome:"Inadimplência & Aging",perm:podeInad},
  consorcios:{nome:"Posição de consórcios",perm:podeCons},
  permutas:{nome:"Posição de permutas",perm:podePerm},
  vendas:{nome:"Vendas & Comissões",perm:podeVendas},
  desvios:{nome:"Maiores desvios vs Budget",perm:podeCtrl}
};

function periodoIndices(){return PERIODOS[periodoChave()]||PERIODOS.total}
function mesFechamento(){const p=periodoChave(),ano=periodoAno();if(/^m\d{2}$/.test(p))return Math.max(0,Math.min(11,Number(p.slice(1))-1));if(/^t[1-4]$/.test(p))return Number(p.slice(1))*3-1;if(ano===new Date().getFullYear())return new Date().getMonth();return 11}
function contexto(){const ids=empresasSelecionadasIds();return `${ids.length>1?`${ids.length} empresas consolidadas`:"Empresa selecionada"} · ${periodoAno()}`}
function disponiveis(){return ORDEM_PADRAO.filter(id=>WIDGETS[id]?.perm?.())}
function normalizarPreferencia(p={}){const d=disponiveis(),ordem=[...(Array.isArray(p.ordem)?p.ordem:[])].filter(x=>d.includes(x));d.forEach(x=>{if(!ordem.includes(x))ordem.push(x)});return{ordem,ocultos:[...(Array.isArray(p.ocultos)?p.ocultos:[])].filter(x=>d.includes(x))}}

function css(){if($("dashboard-v2-css"))return;const l=document.createElement("link");l.id="dashboard-v2-css";l.rel="stylesheet";l.href="dashboard-v2.css?v=1";document.head.appendChild(l)}
function montar(){
  const p=$("pagina-dashboard");if(!p||p.dataset.dashboardV2==="1")return;css();p.dataset.dashboardV2="1";p.dataset.gerencial="1";
  p.innerHTML=`
  <div class="welcome modulo-hero dash-v2-hero"><div><span class="eyebrow">COCKPIT GERENCIAL</span><h2>Visão Executiva</h2><p>Resultado, patrimônio, liquidez e posições operacionais em uma leitura integrada.</p></div><div class="dash-v2-head"><span id="dashV2Contexto" class="hero-meta">—</span><button id="btnDashV2Config" class="btn-secundario" type="button">Configurar dashboard</button></div></div>
  <div id="dashV2Aviso" class="modulo-aviso hidden"></div>
  <div id="dashV2Widgets" class="dash-v2-widgets">
    <section class="lista-card dash-v2-widget" data-widget="executivo"><div class="lista-cabecalho"><div><h3>Resumo executivo</h3><p>Indicador, referência e distância para o plano.</p></div><span class="dash-v2-tag">FINANCEIRO</span></div><div class="kpi-grid kpi-grid-6 dash-v2-kpis"><button class="kpi-card dash-v2-click" data-open="dre"><span>Receita realizada</span><strong id="dvReceita">—</strong><small id="dvReceitaSub">—</small></button><button class="kpi-card dash-v2-click" data-open="dre"><span>OPEX realizado</span><strong id="dvOpex">—</strong><small id="dvOpexSub">—</small></button><button class="kpi-card dash-v2-click" data-open="dre"><span>Resultado</span><strong id="dvResultado">—</strong><small id="dvResultadoSub">—</small></button><button class="kpi-card dash-v2-click" data-open="dre"><span>Margem</span><strong id="dvMargem">—</strong><small>Resultado ÷ Receita</small></button><button class="kpi-card dash-v2-click" data-open="caixa"><span>Caixa hoje</span><strong id="dvCaixa">—</strong><small id="dvCaixaSub">posição liquidada</small></button><button class="kpi-card dash-v2-click" data-open="inadimplencia"><span>Inadimplência</span><strong id="dvInad">—</strong><small id="dvInadSub">vencido ÷ carteira</small></button></div></section>
    <section class="lista-card dash-v2-widget" data-widget="evolucao"><div class="lista-cabecalho"><div><h3>Evolução de resultado</h3><p>Receita, OPEX e resultado mês a mês. Clique para abrir a DRE.</p></div><span class="dash-v2-tag">12 MESES</span></div><div id="dvGraficoResultado" class="dash-v2-chart dash-v2-click" data-open="dre"></div></section>
    <section class="lista-card dash-v2-widget" data-widget="balanco"><div class="lista-cabecalho"><div><h3>Análise patrimonial</h3><p id="dvBalancoRef">Posição de fechamento e comparação com o mesmo mês do ano anterior.</p></div><button class="btn-secundario dash-v2-open" data-open="balanco" type="button">Abrir Balanço</button></div><div class="kpi-grid kpi-grid-4"><div class="kpi-card"><span>Ativo</span><strong id="dvAtivo">—</strong><small id="dvAtivoSub">—</small></div><div class="kpi-card"><span>Passivo + PL</span><strong id="dvPassivo">—</strong><small id="dvPassivoSub">—</small></div><div class="kpi-card"><span>Equação patrimonial</span><strong id="dvEquacao">—</strong><small id="dvEquacaoSub">Ativo − Passivo/PL</small></div><div class="kpi-card"><span>Variação do Ativo</span><strong id="dvAtivoVar">—</strong><small>vs mesmo mês do ano anterior</small></div></div><div class="dash-v2-split"><div><h4>Evolução patrimonial</h4><div id="dvGraficoBalanco" class="dash-v2-chart"></div></div><div><h4>Maiores movimentos patrimoniais</h4><div id="dvMovPatrimoniais" class="dash-v2-list"></div></div></div></section>
    <section class="lista-card dash-v2-widget" data-widget="caixa"><div class="lista-cabecalho"><div><h3>Posição e projeção de caixa</h3><p>Liquidado hoje e curva projetada até D+90.</p></div><button class="btn-secundario dash-v2-open" data-open="caixa" type="button">Abrir Caixa</button></div><div class="kpi-grid kpi-grid-4"><div class="kpi-card"><span>Hoje</span><strong id="dvCx0">—</strong></div><div class="kpi-card"><span>D+30</span><strong id="dvCx30">—</strong></div><div class="kpi-card"><span>D+60</span><strong id="dvCx60">—</strong></div><div class="kpi-card"><span>D+90</span><strong id="dvCx90">—</strong></div></div><div id="dvGraficoCaixa" class="dash-v2-chart"></div></section>
    <section class="lista-card dash-v2-widget" data-widget="inadimplencia"><div class="lista-cabecalho"><div><h3>Inadimplência & Aging</h3><p>Exposição atual da carteira por faixa de atraso.</p></div><button class="btn-secundario dash-v2-open" data-open="inadimplencia" type="button">Abrir Aging</button></div><div class="kpi-grid kpi-grid-4"><div class="kpi-card"><span>Carteira em aberto</span><strong id="dvInadCarteira">—</strong></div><div class="kpi-card"><span>Vencido</span><strong id="dvInadVencido">—</strong></div><div class="kpi-card"><span>Índice</span><strong id="dvInadIndice">—</strong></div><div class="kpi-card"><span>Acima de 90 dias</span><strong id="dvInad90">—</strong></div></div><div id="dvAging" class="dash-v2-bars"></div></section>
    <section class="lista-card dash-v2-widget" data-widget="consorcios"><div class="lista-cabecalho"><div><h3>Posição de consórcios</h3><p>Carteira ativa, crédito, parcela e saldo teórico.</p></div><button class="btn-secundario dash-v2-open" data-open="consorcios" type="button">Abrir Consórcios</button></div><div class="kpi-grid kpi-grid-4"><div class="kpi-card"><span>Planos ativos</span><strong id="dvConsAtivos">—</strong></div><div class="kpi-card"><span>Crédito atual</span><strong id="dvConsCredito">—</strong></div><div class="kpi-card"><span>Parcela mensal</span><strong id="dvConsParcela">—</strong></div><div class="kpi-card"><span>Saldo teórico</span><strong id="dvConsSaldo">—</strong></div></div></section>
    <section class="lista-card dash-v2-widget" data-widget="permutas"><div class="lista-cabecalho"><div><h3>Posição de permutas</h3><p>Saldo líquido e exposição operacional das permutas ativas.</p></div><button class="btn-secundario dash-v2-open" data-open="permutas" type="button">Abrir Permutas</button></div><div class="kpi-grid kpi-grid-4"><div class="kpi-card"><span>Permutas ativas</span><strong id="dvPermAtivas">—</strong></div><div class="kpi-card"><span>Valor acordado</span><strong id="dvPermAcordado">—</strong></div><div class="kpi-card"><span>Saldo líquido</span><strong id="dvPermSaldo">—</strong></div><div class="kpi-card"><span>Exposição absoluta</span><strong id="dvPermExposicao">—</strong></div></div></section>
    <section class="lista-card dash-v2-widget" data-widget="vendas"><div class="lista-cabecalho"><div><h3>Vendas & Comissões</h3><p>Faturamento comercial, atingimento de meta e comissão provisionada.</p></div><button class="btn-secundario dash-v2-open" data-open="vendas" type="button">Abrir Vendas</button></div><div class="kpi-grid kpi-grid-4"><div class="kpi-card"><span>Vendas no período</span><strong id="dvVendas">—</strong></div><div class="kpi-card"><span>Meta</span><strong id="dvMeta">—</strong></div><div class="kpi-card"><span>Atingimento</span><strong id="dvAtingimento">—</strong></div><div class="kpi-card"><span>Comissão provisionada</span><strong id="dvComissao">—</strong></div></div><div id="dvGraficoVendas" class="dash-v2-chart"></div></section>
    <section class="lista-card dash-v2-widget" data-widget="desvios"><div class="lista-cabecalho"><div><h3>Maiores desvios vs Budget</h3><p>Top impactos gerenciais do período. Clique na conta para aprofundar na DRE.</p></div><span class="dash-v2-tag">EXCEÇÕES</span></div><div id="dvDesvios" class="dash-v2-list"></div></section>
  </div>
  <div id="dashV2Config" class="dash-v2-modal hidden"><div class="dash-v2-modal-card"><div class="lista-cabecalho"><div><h3>Configurar dashboard</h3><p>Escolha os blocos e a ordem. A preferência fica salva para seu usuário.</p></div><button id="btnDashV2Fechar" class="btn-secundario" type="button">Fechar</button></div><div id="dashV2ConfigLista" class="dash-v2-config-list"></div><div class="form-acoes"><button id="btnDashV2Padrao" class="btn-secundario" type="button">Restaurar padrão</button><button id="btnDashV2Salvar" class="btn-primario" type="button">Salvar configuração</button></div></div></div>`;
  $("btnDashV2Config")?.addEventListener("click",abrirConfig);$("btnDashV2Fechar")?.addEventListener("click",()=>$("dashV2Config")?.classList.add("hidden"));$("btnDashV2Padrao")?.addEventListener("click",()=>{preferencia=normalizarPreferencia({});renderConfig();aplicarPreferencia()});$("btnDashV2Salvar")?.addEventListener("click",salvarPreferencia);
  p.addEventListener("click",e=>{const b=e.target.closest?.("[data-open]");if(!b)return;const k=b.dataset.open;if(k)window.SIG_ABRIR_CTRL?.(k)});
}

async function carregarPreferencia(){try{const r=await getDoc(doc(db,"dashboardPreferencias",state.usuario.id));preferencia=normalizarPreferencia(r.exists()?r.data():{})}catch(e){console.warn("Dashboard: preferência indisponível",e);preferencia=normalizarPreferencia({})}aplicarPreferencia()}
function aplicarPreferencia(){const box=$("dashV2Widgets");if(!box)return;const p=normalizarPreferencia(preferencia);preferencia=p;p.ordem.forEach(id=>{const el=box.querySelector(`[data-widget="${id}"]`);if(el)box.appendChild(el)});box.querySelectorAll("[data-widget]").forEach(el=>{const id=el.dataset.widget,permitido=!!WIDGETS[id]?.perm?.(),oculto=p.ocultos.includes(id);el.classList.toggle("hidden",!permitido||oculto)})}
function renderConfig(){const box=$("dashV2ConfigLista");if(!box)return;const p=normalizarPreferencia(preferencia);preferencia=p;box.innerHTML=p.ordem.map((id,i)=>`<div class="dash-v2-config-row" data-config-id="${id}"><label><input type="checkbox" ${p.ocultos.includes(id)?"":"checked"}> <span>${esc(WIDGETS[id].nome)}</span></label><div><button class="btn-acao" data-move="up" ${i===0?"disabled":""} type="button">↑</button><button class="btn-acao" data-move="down" ${i===p.ordem.length-1?"disabled":""} type="button">↓</button></div></div>`).join("");box.querySelectorAll("input").forEach(c=>c.addEventListener("change",()=>{const id=c.closest("[data-config-id]").dataset.configId;preferencia.ocultos=c.checked?preferencia.ocultos.filter(x=>x!==id):[...new Set([...preferencia.ocultos,id])];aplicarPreferencia()}));box.querySelectorAll("[data-move]").forEach(b=>b.addEventListener("click",()=>{const id=b.closest("[data-config-id]").dataset.configId,i=preferencia.ordem.indexOf(id),j=b.dataset.move==="up"?i-1:i+1;if(j<0||j>=preferencia.ordem.length)return;[preferencia.ordem[i],preferencia.ordem[j]]=[preferencia.ordem[j],preferencia.ordem[i]];renderConfig();aplicarPreferencia()}))}
function abrirConfig(){renderConfig();$("dashV2Config")?.classList.remove("hidden")}
async function salvarPreferencia(){try{preferencia=normalizarPreferencia(preferencia);await setDoc(doc(db,"dashboardPreferencias",state.usuario.id),{usuarioId:state.usuario.id,grupoId:state.usuario.grupoId,ordem:preferencia.ordem,ocultos:preferencia.ocultos,atualizadoEm:serverTimestamp()},{merge:true});$("dashV2Config")?.classList.add("hidden")}catch(e){console.error(e);alert("Não foi possível salvar a configuração do dashboard.")}}

function set(id,v){if($(id))$(id).textContent=v}
function lineChart(id,series,{money=true}={}){const el=$(id);if(!el)return;const todos=series.flatMap(s=>s.valores.map(n)).filter(Number.isFinite),min=Math.min(0,...todos),max=Math.max(0,...todos),span=max-min||1,w=920,h=245,pad=34,x=i=>pad+i*((w-pad*2)/11),y=v=>h-pad-(v-min)/span*(h-pad*2);const grid=[0,.25,.5,.75,1].map(t=>{const v=min+span*t,yy=y(v);return`<line x1="${pad}" y1="${yy}" x2="${w-pad}" y2="${yy}" class="dv-grid"/><text x="4" y="${yy+4}" class="dv-axis">${money?compact(v):v.toFixed(1)}</text>`}).join("");const paths=series.map((s,si)=>`<polyline class="dv-line s${si}" points="${s.valores.map((v,i)=>`${x(i)},${y(n(v))}`).join(" ")}"/>`).join("");const labels=MESES.map((m,i)=>`<text x="${x(i)}" y="${h-7}" text-anchor="middle" class="dv-axis">${m}</text>`).join("");el.innerHTML=`<div class="dash-v2-legend">${series.map((s,i)=>`<span class="s${i}"><i></i>${esc(s.nome)}</span>`).join("")}</div><svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Gráfico de evolução">${grid}${paths}${labels}</svg>`}
function compact(v){const a=Math.abs(v);if(a>=1e6)return`${(v/1e6).toLocaleString("pt-BR",{maximumFractionDigits:1})} mi`;if(a>=1e3)return`${(v/1e3).toLocaleString("pt-BR",{maximumFractionDigits:0})} mil`;return n(v).toLocaleString("pt-BR",{maximumFractionDigits:0})}
function bars(id,itens){const el=$(id);if(!el)return;const max=Math.max(1,...itens.map(x=>n(x.valor)));el.innerHTML=itens.map(x=>`<div class="dv-bar-row"><span>${esc(x.nome)}</span><div><i style="width:${Math.max(1,n(x.valor)/max*100)}%"></i></div><strong>${moeda(x.valor)}</strong></div>`).join("")}
function addDias(iso,dias){const d=new Date(`${iso}T12:00:00`);d.setDate(d.getDate()+dias);return d.toISOString().slice(0,10)}

function caixaResumo(contas,lanc){const hoje=new Date().toISOString().slice(0,10),base=contas.filter(x=>x.status!=="inativo").reduce((s,x)=>s+n(x.saldoAbertura),0),validos=lanc.filter(x=>x.status!=="cancelado"),saldoAte=(data,soLiquidado=false)=>base+validos.filter(x=>String(x.data||"")<=data&&(!soLiquidado||x.status==="liquidado")).reduce((s,x)=>s+(x.natureza==="entrada"?1:-1)*n(x.valor),0);return{hoje:saldoAte(hoje,true),d30:saldoAte(addDias(hoje,30)),d60:saldoAte(addDias(hoje,60)),d90:saldoAte(addDias(hoje,90))}}
function inadResumo(titulos){const hoje=new Date().toISOString().slice(0,10),abertos=titulos.filter(t=>t.status!=="cancelado"&&t.status!=="recebido").map(t=>({...t,saldo:Math.max(0,n(t.valorOriginal)-n(t.valorRecebido))})).filter(t=>t.saldo>0),venc=abertos.filter(t=>t.vencimento&&t.vencimento<hoje),dias=t=>Math.max(0,Math.floor((new Date(`${hoje}T12:00:00`)-new Date(`${t.vencimento}T12:00:00`))/86400000)),bucket={av:0,d30:0,d60:0,d90:0,m90:0};for(const t of abertos){if(!t.vencimento||t.vencimento>=hoje)bucket.av+=t.saldo;else{const d=dias(t);if(d<=30)bucket.d30+=t.saldo;else if(d<=60)bucket.d60+=t.saldo;else if(d<=90)bucket.d90+=t.saldo;else bucket.m90+=t.saldo}}const carteira=abertos.reduce((s,t)=>s+t.saldo,0),vencido=venc.reduce((s,t)=>s+t.saldo,0);return{carteira,vencido,indice:carteira?vencido/carteira*100:0,bucket}}

function stamp(x){return n(x?.atualizadoEm?.seconds||x?.criadoEm?.seconds||0)}
function ativoDoc(x){return x?.legadoArquivado!==true&&x?.duplicadoArquivado!==true}
function idSeguro(v){return String(v||"sem").replace(/[^a-zA-Z0-9_-]/g,"_")}
function docBalanco(conta,ano,realizados){const ds=realizados.filter(d=>ativoDoc(d)&&d.contaId===conta.id&&(d.centroCustoId||"")===CC_BALANCO_ID&&Number(d.exercicio)===Number(ano));if(!ds.length)return null;const canon=`r_${idSeguro(conta.empresaId)}_${ano}_${idSeguro(CC_BALANCO_ID)}_${idSeguro(conta.id)}`;return ds.find(d=>d.id===canon)||[...ds].sort((a,b)=>stamp(b)-stamp(a))[0]}
function mapaAuto(bens,empresa,ano,mes){const comp=`${ano}-${String(mes+1).padStart(2,"0")}`;return mapaImobilizadoBalanco(bens.filter(b=>b.empresaId===empresa&&b.integrarBalanco===true&&b.status!=="cancelado"&&b.status!=="inativo"),comp)}
function balancoMes(plano,realizados,bens,ano,mes,empresas){const ids=new Set(empresas),autos=new Map(empresas.map(e=>[e,mapaAuto(bens,e,ano,mes)])),porCodigo=new Map();let ativo=0,passivo=0;for(const c of plano){if(!ids.has(c.empresaId)||!contaBalanco(c)||!contaAnalitica(c)||!contaAtivaNoExercicio(c,ano))continue;const a=autos.get(c.empresaId),isAuto=a?.bruto?.has(c.id)||a?.acumulada?.has(c.id);let bruto;if(isAuto)bruto=a.bruto.has(c.id)?n(a.bruto.get(c.id)):n(a.acumulada.get(c.id));else bruto=n(docBalanco(c,ano,realizados)?.valores?.[CHAVES[mes]]);const v=bruto*multiplicadorApresentacao(c),raiz=raizConta(c);if(raiz==="1")ativo+=v;if(raiz==="2")passivo+=v;const k=c.codigo||c.id,at=porCodigo.get(k)||{codigo:c.codigo||"",nome:c.nome||"Conta",valor:0};at.valor+=v;porCodigo.set(k,at)}return{ativo,passivo,porCodigo}}

function renderFinanceiro({plano,realizados,budgets,forecasts,bens}){const ano=periodoAno(),emp=empresasSelecionadasIds(),idx=periodoIndices(),realBase=construirLinhasFinanceiras({cenario:"realizado",documentos:realizados,plano,ano,empresasIds:emp}),budBase=construirLinhasFinanceiras({cenario:"budget",documentos:budgets,plano,imobilizados:bens,ano,empresasIds:emp}),foreBase=construirLinhasFinanceiras({cenario:"forecast",documentos:forecasts,realizados,plano,imobilizados:bens,ano,empresasIds:emp}),real=resumirDre(realBase.linhas,idx),bud=resumirDre(budBase.linhas,idx),fore=resumirDre(foreBase.linhas,idx),margem=real.receita?real.resultado/Math.abs(real.receita)*100:0;set("dvReceita",moeda(real.receita));set("dvReceitaSub",`${pctFmt(pct(real.receita,bud.receita))} vs Budget`);set("dvOpex",moeda(real.opex));set("dvOpexSub",`${pctFmt(pct(real.opex,bud.opex))} vs Budget`);set("dvResultado",moeda(real.resultado));set("dvResultadoSub",`${pctFmt(pct(real.resultado,bud.resultado))} vs Budget · Forecast ${moeda(fore.resultado)}`);set("dvMargem",`${margem.toLocaleString("pt-BR",{maximumFractionDigits:1})}%`);const rmes=Array.from({length:12},(_,i)=>resumirDre(realBase.linhas,[i]));lineChart("dvGraficoResultado",[{nome:"Receita",valores:rmes.map(x=>x.receita)},{nome:"OPEX",valores:rmes.map(x=>x.opex)},{nome:"Resultado",valores:rmes.map(x=>x.resultado)}]);const rmap=new Map(linhasPorCodigo(realBase.linhas,idx).map(x=>[x.chave,x])),bmap=new Map(linhasPorCodigo(budBase.linhas,idx).map(x=>[x.chave,x])),desv=[];for(const k of new Set([...rmap.keys(),...bmap.keys()])){const r=rmap.get(k),b=bmap.get(k),base=r||b;if(!base)continue;const rv=r?.efeito||0,bv=b?.efeito||0,impacto=rv-bv;if(Math.abs(rv)+Math.abs(bv)<.001)continue;desv.push({...base,real:rv,budget:bv,impacto})}desv.sort((a,b)=>Math.abs(b.impacto)-Math.abs(a.impacto));const box=$("dvDesvios");if(box)box.innerHTML=desv.slice(0,6).map(x=>`<button class="dash-v2-list-row" data-open="dre" type="button"><span><strong>${esc(x.codigo)} · ${esc(x.nome)}</strong><small>${esc(x.grupoDre||"DRE")}</small></span><span>Budget<strong>${moeda(x.budget)}</strong></span><span>Real<strong>${moeda(x.real)}</strong></span><b class="${x.impacto>=0?"bom":"ruim"}">${x.impacto>0?"+":""}${moeda(x.impacto)}</b></button>`).join("")||'<div class="empty-state">Sem desvios comparáveis.</div>'}

function renderBalanco({plano,realizados,bens}){const ano=periodoAno(),mes=mesFechamento(),emp=empresasSelecionadasIds(),at=balancoMes(plano,realizados,bens,ano,mes,emp),ly=balancoMes(plano,realizados,bens,ano-1,mes,emp),dif=at.ativo-at.passivo;set("dvBalancoRef",`Posição ${MESES[mes]}/${ano} · comparação com ${MESES[mes]}/${ano-1}.`);set("dvAtivo",moeda(at.ativo));set("dvAtivoSub",`${pctFmt(pct(at.ativo,ly.ativo))} vs LY`);set("dvPassivo",moeda(at.passivo));set("dvPassivoSub",`${pctFmt(pct(at.passivo,ly.passivo))} vs LY`);set("dvEquacao",moeda(dif));set("dvEquacaoSub",Math.abs(dif)<.01?"Balanço conciliado":"Revisar diferença patrimonial");set("dvAtivoVar",pctFmt(pct(at.ativo,ly.ativo)));const meses=Array.from({length:12},(_,i)=>balancoMes(plano,realizados,bens,ano,i,emp));lineChart("dvGraficoBalanco",[{nome:"Ativo",valores:meses.map(x=>x.ativo)},{nome:"Passivo + PL",valores:meses.map(x=>x.passivo)}]);const mov=[];for(const k of new Set([...at.porCodigo.keys(),...ly.porCodigo.keys()])){const a=at.porCodigo.get(k),l=ly.porCodigo.get(k),base=a||l,v=n(a?.valor)-n(l?.valor);if(Math.abs(v)>.005)mov.push({codigo:base.codigo,nome:base.nome,valor:v})}mov.sort((a,b)=>Math.abs(b.valor)-Math.abs(a.valor));const box=$("dvMovPatrimoniais");if(box)box.innerHTML=mov.slice(0,6).map(x=>`<button class="dash-v2-list-row simples" data-open="balanco" type="button"><span><strong>${esc(x.codigo)} · ${esc(x.nome)}</strong><small>Variação vs LY</small></span><b class="${x.valor>=0?"bom":"ruim"}">${x.valor>0?"+":""}${moeda(x.valor)}</b></button>`).join("")||'<div class="empty-state">Sem movimentos patrimoniais comparáveis.</div>'}

function renderCaixaDados(contas,lanc){const c=caixaResumo(contas,lanc);set("dvCaixa",moeda(c.hoje));set("dvCx0",moeda(c.hoje));set("dvCx30",moeda(c.d30));set("dvCx60",moeda(c.d60));set("dvCx90",moeda(c.d90));set("dvCaixaSub",`D+90 ${moeda(c.d90)}`);lineChart("dvGraficoCaixa",[{nome:"Projeção",valores:[c.hoje,c.hoje,c.hoje,c.d30,c.d30,c.d30,c.d60,c.d60,c.d60,c.d90,c.d90,c.d90]}])}
function renderInad(titulos){const r=inadResumo(titulos);set("dvInad",`${r.indice.toLocaleString("pt-BR",{maximumFractionDigits:1})}%`);set("dvInadSub",`${moeda(r.vencido)} vencido`);set("dvInadCarteira",moeda(r.carteira));set("dvInadVencido",moeda(r.vencido));set("dvInadIndice",`${r.indice.toLocaleString("pt-BR",{maximumFractionDigits:1})}%`);set("dvInad90",moeda(r.bucket.m90));bars("dvAging",[{nome:"A vencer",valor:r.bucket.av},{nome:"1–30",valor:r.bucket.d30},{nome:"31–60",valor:r.bucket.d60},{nome:"61–90",valor:r.bucket.d90},{nome:">90 dias",valor:r.bucket.m90}])}
function renderCons(cons){const ativos=cons.filter(statusConsorcioAtivo),calcs=ativos.map(calcularConsorcio);set("dvConsAtivos",ativos.length);set("dvConsCredito",moeda(calcs.reduce((s,c)=>s+c.baseCredito,0)));set("dvConsParcela",moeda(calcs.reduce((s,c)=>s+c.parcelaReferencia,0)));set("dvConsSaldo",moeda(calcs.reduce((s,c)=>s+c.saldoTeorico,0)))}
function renderPerm(perms,movs){const at=perms.filter(p=>!["inativo","finalizada","encerrado","cancelado"].includes(p.status||"ativo")),ids=new Set(at.map(x=>x.id)),valid=movs.filter(m=>ids.has(m.permutaId)&&m.estornado!==true),sinal=m=>["credito","ajuste_credito"].includes(m.tipo)?1:-1,map=new Map();for(const m of valid)map.set(m.permutaId,(map.get(m.permutaId)||0)+sinal(m)*n(m.valorPermuta));set("dvPermAtivas",at.length);set("dvPermAcordado",moeda(at.reduce((s,p)=>s+n(p.valorAcordado),0)));set("dvPermSaldo",moeda([...map.values()].reduce((s,v)=>s+v,0)));set("dvPermExposicao",moeda([...map.values()].reduce((s,v)=>s+Math.abs(v),0)))}
function renderVendas(vendas,vendedores){const ano=periodoAno(),idx=periodoIndices(),valid=vendas.filter(v=>v.status!=="cancelada"&&String(v.data||"").startsWith(`${ano}-`)),mesVals=Array(12).fill(0),mesCom=Array(12).fill(0);valid.forEach(v=>{const m=Number(String(v.data||"").slice(5,7))-1;if(m>=0&&m<12){mesVals[m]+=n(v.valor);mesCom[m]+=n(v.comissaoValor)}});const total=idx.reduce((s,i)=>s+mesVals[i],0),com=idx.reduce((s,i)=>s+mesCom[i],0),ativos=vendedores.filter(v=>v.status!=="inativo"),meta=ativos.reduce((s,v)=>s+n(v.metaMensal)*idx.length,0);set("dvVendas",moeda(total));set("dvMeta",moeda(meta));set("dvAtingimento",meta?`${(total/meta*100).toLocaleString("pt-BR",{maximumFractionDigits:1})}%`:"—");set("dvComissao",moeda(com));const metaMes=Array(12).fill(ativos.reduce((s,v)=>s+n(v.metaMensal),0));lineChart("dvGraficoVendas",[{nome:"Vendas",valores:mesVals},{nome:"Meta",valores:metaMes}])}

async function carregar(){montar();if(!visivel()||carregando||!permite("dashboard"))return;carregando=true;set("dashV2Contexto",contexto());const aviso=$("dashV2Aviso");if(aviso)aviso.classList.add("hidden");try{
  const ocultos=new Set(preferencia.ocultos||[]),need=id=>WIDGETS[id]?.perm?.()&&!ocultos.has(id),dados={};
  if(podeCtrl()&&["executivo","evolucao","balanco","caixa","desvios"].some(need)){
    const [plano,realizados,budgets,forecasts,bens,contas,lanc]=await Promise.all([listarDocumentos("planoContasGerencial"),listarDocumentos("realizadoMensal"),listarDocumentos("budgetLinhas"),listarDocumentos("forecastLinhas"),listarDocumentos("imobilizados"),listarDocumentos("contasBancarias"),listarDocumentos("fluxoCaixaLancamentos")]);Object.assign(dados,{plano,realizados,budgets,forecasts,bens,contas,lanc});if(["executivo","evolucao","desvios"].some(need))renderFinanceiro(dados);if(need("balanco"))renderBalanco(dados);if(need("caixa")||need("executivo"))renderCaixaDados(contas,lanc)
  }
  if(podeInad()&&(need("inadimplencia")||need("executivo"))){const t=await listarDocumentos("inadimplenciaTitulos");renderInad(t)}else{set("dvInad","—");set("dvInadSub","sem acesso à carteira")}
  if(podeCons()&&need("consorcios"))renderCons(await listarDocumentos("consorcios"));
  if(podePerm()&&need("permutas")){const [p,m]=await Promise.all([listarDocumentos("permutas"),listarDocumentos("permutaMovimentos")]);renderPerm(p,m)}
  if(podeVendas()&&need("vendas")){const [v,ve]=await Promise.all([listarDocumentos("vendas"),listarDocumentos("vendedores")]);renderVendas(v,ve)}
}catch(e){console.error("Dashboard v2:",e);if(aviso){aviso.textContent="Alguns indicadores não puderam ser carregados. Verifique permissões e disponibilidade das coleções.";aviso.classList.remove("hidden")}}finally{carregando=false}}

montar();
window.addEventListener("sig:ready",async()=>{montar();await carregarPreferencia();carregar()});
window.addEventListener("sig:empresa-changed",carregar);window.addEventListener("sig:periodo-changed",carregar);window.addEventListener("sig:data-changed",carregar);window.addEventListener("sig:page",e=>{if(e.detail?.pagina==="dashboard")setTimeout(carregar,50)});
