import { abrirPagina, admin } from "./core.js";
import { $, esc, msg, permite, state, listarDocumentos, criarDocumento, atualizarDocumento, empresaUnicaSelecionadaId, dataBr, emitirAlteracao } from "./shared.js";
import { confirmarAcaoAdministrativa, atualizarComAuditoria } from "./admin-actions.js";

const COLECAO="descarteLancamentos";
const MAQUINAS=["MAQ.1","MAQ.2","LAJE"];
const RESPONSAVEIS=["ARTUR","GIL","PAULO"];
let registros=[],editId=null,carregando=false;
const ver=()=>admin()||["visualizar","lancar","editar"].some(a=>permite("descarte",a));
const lancar=()=>admin()||permite("descarte","lancar");
const editar=()=>admin()||permite("descarte","editar");
const num=v=>Number(v||0);
const fmt=v=>num(v).toLocaleString("pt-BR",{maximumFractionDigits:2});
const lista=()=>{
  const ano=$("descarteAno")?.value||"",mes=$("descarteMes")?.value||"",maq=$("descarteFiltroMaquina")?.value||"";
  return registros.filter(x=>(!ano||x.data?.startsWith(ano))&&(!mes||x.data?.slice(5,7)===mes)&&(!maq||x.maquina===maq));
};
function montar(){
  if($("pagina-descarte"))return;
  const main=document.querySelector("main.conteudo");if(!main)return;
  const s=document.createElement("section");s.id="pagina-descarte";s.className="pagina hidden production-page";
  s.innerHTML=`<div class="pagina-cabecalho production-head"><div><span class="eyebrow">OPERAÇÃO</span><h2>Descarte</h2><p>Quantidade descartada por máquina e responsável pelo recolhimento.</p></div><div class="acoes-cabecalho"><button id="descarteNovo" class="btn-primario" type="button">+ Novo descarte</button><button id="descarteAtualizar" class="btn-secundario" type="button">Atualizar</button></div></div>
  <div id="descarteAviso" class="modulo-aviso hidden"></div>
  <div class="production-kpis"><div class="kpi-card"><span>Total descartado</span><strong id="descarteKpiTotal">—</strong><small>unidades no filtro</small></div><div class="kpi-card"><span>Lançamentos</span><strong id="descarteKpiRegistros">—</strong><small>registros ativos</small></div><div class="kpi-card"><span>Máquina com maior descarte</span><strong id="descarteKpiMaquina">—</strong><small>no filtro</small></div></div>
  <section class="form-card hidden" id="descarteFormBox"><div class="form-card-titulo"><h3 id="descarteFormTitulo">Novo descarte</h3></div><form id="descarteForm"><div class="form-grid form-grid-3"><div class="campo"><label for="descarteData">Data</label><input id="descarteData" type="date" required></div><div class="campo"><label for="descarteQuantidade">Quantidade</label><input id="descarteQuantidade" type="number" min="0" step="any" required></div><div class="campo"><label for="descarteMaquina">Máquina</label><select id="descarteMaquina" required><option value="">Selecione...</option>${MAQUINAS.map(v=>`<option>${v}</option>`).join("")}</select></div><div class="campo"><label for="descarteResponsavel">Responsável pelo recolhimento</label><select id="descarteResponsavel" required><option value="">Selecione...</option>${RESPONSAVEIS.map(v=>`<option>${v}</option>`).join("")}</select></div></div><div class="form-acoes"><button id="descarteCancelar" class="btn-secundario" type="button">Cancelar</button><button class="btn-primario" type="submit">Salvar descarte</button></div><p id="descarteMensagem" class="mensagem-form"></p></form></section>
  <section class="lista-card"><div class="lista-cabecalho production-toolbar"><div><h3>Análise do descarte</h3><p>Somente lançamentos ativos entram nos totais.</p></div><div class="production-filtros"><select id="descarteAno" aria-label="Ano"><option value="${new Date().getFullYear()}">${new Date().getFullYear()}</option></select><select id="descarteMes" aria-label="Mês"><option value="">Ano inteiro</option>${Array.from({length:12},(_,i)=>`<option value="${String(i+1).padStart(2,"0")}">${new Date(2026,i,1).toLocaleString("pt-BR",{month:"long"})}</option>`).join("")}</select><select id="descarteFiltroMaquina" aria-label="Máquina"><option value="">Todas as máquinas</option>${MAQUINAS.map(v=>`<option>${v}</option>`).join("")}</select></div></div><div class="production-charts"><div class="production-card"><h4>Quantidade por máquina</h4><div id="descartePorMaquina" class="production-bars"></div></div><div class="production-card"><h4>Quantidade por responsável</h4><div id="descartePorResponsavel" class="production-bars"></div></div></div></section>
  <section class="lista-card"><div class="lista-cabecalho"><div><h3>Histórico de descartes</h3><p id="descarteContagem">—</p></div><span class="production-history-note">Estornos permanecem visíveis.</span></div><div class="tabela-container"><table class="tabela"><thead><tr><th>Data</th><th>Máquina</th><th>Quantidade</th><th>Responsável</th><th>Situação</th><th>Ações</th></tr></thead><tbody id="descarteLista"></tbody></table></div></section>`;
  main.appendChild(s);
  $("descarteNovo").addEventListener("click",novo);$("descarteAtualizar").addEventListener("click",carregar);
  $("descarteCancelar").addEventListener("click",()=>{$("descarteFormBox").classList.add("hidden");limpar()});
  $("descarteForm").addEventListener("submit",salvar);
  ["descarteAno","descarteMes","descarteFiltroMaquina"].forEach(id=>$(id).addEventListener("change",render));
}
function menu(){const nav=document.querySelector(".sidebar-menu");if(!nav)return;let b=$("menuDescarte");if(!b){b=document.createElement("button");b.id="menuDescarte";b.className="menu-item hidden";b.dataset.pagina="descarte";b.type="button";b.textContent="Descarte";nav.appendChild(b);b.addEventListener("click",e=>{e.preventDefault();e.stopImmediatePropagation();if(!ver())return;abrirPagina("descarte");carregar()},true)}b.classList.toggle("hidden",!ver())}
function limpar(){editId=null;$("descarteForm").reset();$("descarteData").value=new Date().toLocaleDateString("en-CA");$("descarteFormTitulo").textContent="Novo descarte";msg($("descarteMensagem"),"")}
function novo(){if(!lancar())return;if(!empresaUnicaSelecionadaId())return alert("Selecione apenas uma empresa no cabeçalho.");limpar();$("descarteFormBox").classList.remove("hidden");$("descarteFormBox").scrollIntoView({behavior:"smooth",block:"start"})}
function abrirEdicao(id){if(!editar())return;const x=registros.find(v=>v.id===id);if(!x||x.status!=="ativo"||x.empresaId!==empresaUnicaSelecionadaId())return alert("Selecione a empresa deste registro para editar.");editId=id;$("descarteData").value=x.data;$("descarteQuantidade").value=x.quantidade;$("descarteMaquina").value=x.maquina;$("descarteResponsavel").value=x.responsavel;$("descarteFormTitulo").textContent="Editar descarte";$("descarteFormBox").classList.remove("hidden");$("descarteFormBox").scrollIntoView({behavior:"smooth",block:"start"})}
function barras(id,values){const target=$(id),max=Math.max(1,...values.map(x=>x[1]));target.innerHTML=values.length?values.map(([k,v])=>`<div class="production-bar-row"><span>${esc(k)}</span><div><i style="width:${Math.max(2,v/max*100)}%"></i></div><strong>${fmt(v)}</strong></div>`).join(""):'<p class="production-empty">Sem dados no filtro selecionado.</p>'}
function render(){const historico=lista(),ativos=historico.filter(x=>x.status!=="estornado"),total=ativos.reduce((s,x)=>s+num(x.quantidade),0),maquinas={},responsaveis={};ativos.forEach(x=>{maquinas[x.maquina]=(maquinas[x.maquina]||0)+num(x.quantidade);responsaveis[x.responsavel]=(responsaveis[x.responsavel]||0)+num(x.quantidade)});const maq=Object.entries(maquinas).sort((a,b)=>b[1]-a[1]);$("descarteKpiTotal").textContent=fmt(total);$("descarteKpiRegistros").textContent=String(ativos.length);$("descarteKpiMaquina").textContent=maq[0]?.[0]||"—";$("descarteContagem").textContent=`${historico.length} lançamento(s) no filtro`;
  barras("descartePorMaquina",maq);barras("descartePorResponsavel",Object.entries(responsaveis).sort((a,b)=>b[1]-a[1]));
  $("descarteLista").innerHTML=historico.sort((a,b)=>String(b.data).localeCompare(String(a.data))).map(x=>`<tr class="${x.status==="estornado"?"sig-admin-estornado":""}"><td>${dataBr(x.data)}</td><td>${esc(x.maquina)}</td><td>${fmt(x.quantidade)}</td><td>${esc(x.responsavel)}</td><td>${x.status==="estornado"?"Estornado":"Ativo"}</td><td><div class="acoes-tabela">${x.status!=="estornado"&&editar()?`<button type="button" class="btn-acao destaque" data-descarte-edit="${esc(x.id)}">Editar</button>`:""}${x.status!=="estornado"&&admin()?`<button type="button" class="btn-acao perigo" data-descarte-estorno="${esc(x.id)}">Estornar ADM</button>`:""}</div></td></tr>`).join("")||'<tr><td colspan="6">Nenhum descarte encontrado.</td></tr>';
  document.querySelectorAll("[data-descarte-edit]").forEach(b=>b.addEventListener("click",()=>abrirEdicao(b.dataset.descarteEdit)));
  document.querySelectorAll("[data-descarte-estorno]").forEach(b=>b.addEventListener("click",()=>estornar(b.dataset.descarteEstorno)));
}
async function carregar(){if(carregando||!ver())return;carregando=true;try{registros=await listarDocumentos(COLECAO);const s=$("descarteAno"),atual=s.value||String(new Date().getFullYear()),anos=[...new Set([new Date().getFullYear(),...registros.map(x=>Number(String(x.data||"").slice(0,4))).filter(Boolean)])].sort((a,b)=>b-a);s.innerHTML=anos.map(a=>`<option value="${a}">${a}</option>`).join("");if(anos.map(String).includes(atual))s.value=atual;render();$("descarteAviso").classList.add("hidden")}catch(e){console.error(e);registros=[];render();$("descarteAviso").textContent="Não foi possível consultar descartes. Confira as permissões e as Rules publicadas no Firebase.";$("descarteAviso").classList.remove("hidden")}finally{carregando=false}}
async function salvar(e){e.preventDefault();const empresaId=empresaUnicaSelecionadaId();if(!empresaId)return alert("Selecione apenas uma empresa no cabeçalho.");const quantidade=Number($("descarteQuantidade").value),dados={data:$("descarteData").value,quantidade,maquina:$("descarteMaquina").value,responsavel:$("descarteResponsavel").value};if(!/^\d{4}-\d{2}-\d{2}$/.test(dados.data)||!Number.isFinite(quantidade)||quantidade<0||!MAQUINAS.includes(dados.maquina)||!RESPONSAVEIS.includes(dados.responsavel))return msg($("descarteMensagem"),"Revise os campos do lançamento.");try{msg($("descarteMensagem"),"Salvando...");if(editId){const atual=registros.find(x=>x.id===editId);if(!editar()||!atual||atual.empresaId!==empresaId||atual.status!=="ativo")throw new Error("Edição não permitida neste contexto.");await atualizarDocumento(COLECAO,editId,dados)}else{if(!lancar())throw new Error("Sem permissão.");await criarDocumento(COLECAO,{...dados,empresaId,status:"ativo",origem:"sig",atualizadoPor:state.usuario?.id||""})}$("descarteFormBox").classList.add("hidden");limpar();emitirAlteracao("descarte");await carregar()}catch(err){console.error(err);msg($("descarteMensagem"),err.message||"Não foi possível salvar.")}}
async function estornar(id){if(!admin())return;const x=registros.find(v=>v.id===id);if(!x||x.status!=="ativo")return;const ok=await confirmarAcaoAdministrativa({titulo:"Estornar descarte",descricao:`O descarte de ${fmt(x.quantidade)} unidades em ${dataBr(x.data)} deixará de compor os indicadores.`,motivoLabel:"Motivo obrigatório do estorno",confirmarTexto:"Estornar descarte",perigosa:true});if(!ok)return;try{await atualizarComAuditoria({colecao:COLECAO,id,empresaId:x.empresaId,modulo:"descarte",acao:"estorno",motivo:ok.motivo,resumo:`Estorno de descarte em ${x.data}`,snapshotAntes:x,alteracoes:{status:"estornado",motivoEstorno:ok.motivo,estornadoPor:state.usuario?.id||"",estornadoEm:new Date().toISOString()}});emitirAlteracao("descarte");await carregar()}catch(e){console.error(e);alert("Não foi possível estornar o descarte.")}}
function instalar(){if(!document.querySelector('link[href^="production.css"]')){const l=document.createElement("link");l.rel="stylesheet";l.href="production.css?v=1";document.head.appendChild(l)}montar();menu();$("descarteNovo")?.classList.toggle("hidden",!lancar())}
instalar();window.addEventListener("sig:ready",()=>{instalar();if(ver())carregar()});window.addEventListener("sig:empresa-contexto",()=>{if(!$("pagina-descarte")?.classList.contains("hidden"))carregar()});window.addEventListener("sig:data-changed",e=>{if(e.detail?.modulo==="descarte"&&!$("pagina-descarte")?.classList.contains("hidden"))carregar()});
