import { $, on, esc, norm, msg, permite, state, dataBr, diasAte, preencherEmpresaSelect, nomeEmpresa, listarDocumentos, criarDocumento, atualizarDocumento, excluirDocumento, emitirAlteracao, abrirBox, fecharBox, confirmar } from "./shared.js";
let dados=[],editId=null;
const box=$("formVeiculoContainer"),form=$("formVeiculo"),titulo=$("tituloFormVeiculo"),mensagem=$("mensagemVeiculo"),lista=$("listaVeiculos"),busca=$("buscaVeiculo"),qtd=$("quantidadeVeiculos"),empresa=$("veiculoEmpresa"),placa=$("veiculoPlaca"),status=$("veiculoStatus"),marca=$("veiculoMarca"),modelo=$("veiculoModelo"),ano=$("veiculoAno"),km=$("veiculoKm"),revisaoKm=$("veiculoRevisaoKm"),seguro=$("veiculoSeguro"),licenciamento=$("veiculoLicenciamento"),obs=$("veiculoObservacoes");
function limpar(){editId=null;form?.reset();if(titulo)titulo.textContent="Novo veículo";msg(mensagem,"")}
async function abrir(item=null){limpar();await preencherEmpresaSelect(empresa,{valorAtual:item?.empresaId||state.usuario?.empresaId});if(item){editId=item.id;titulo.textContent="Editar veículo";empresa.value=item.empresaId||"";placa.value=item.placa||"";status.value=item.status||"ativo";marca.value=item.marca||"";modelo.value=item.modelo||"";ano.value=item.ano||"";km.value=Number(item.kmAtual||0);revisaoKm.value=Number(item.proximaRevisaoKm||0);seguro.value=item.vencimentoSeguro||"";licenciamento.value=item.vencimentoLicenciamento||"";obs.value=item.observacoes||""}abrirBox(box,placa);box?.scrollIntoView({behavior:"smooth",block:"start"})}
function revisaoProxima(x){return Number(x.proximaRevisaoKm||0)>0&&Number(x.kmAtual||0)>=Number(x.proximaRevisaoKm||0)-1000}
function docProximo(x){return [x.vencimentoSeguro,x.vencimentoLicenciamento].some(v=>{const d=diasAte(v);return d!==null&&d>=0&&d<=45})}
function render(f=""){const t=norm(f),arr=dados.filter(x=>!t||[x.placa,x.marca,x.modelo].some(v=>norm(v).includes(t))).sort((a,b)=>String(a.placa||"").localeCompare(String(b.placa||""),"pt-BR"));$("frotaAtivos").textContent=dados.filter(x=>x.status==="ativo").length;$("frotaManutencao").textContent=dados.filter(x=>x.status==="manutencao").length;$("frotaRevisao").textContent=dados.filter(revisaoProxima).length;$("frotaDocumentos").textContent=dados.filter(docProximo).length;if(qtd)qtd.textContent=`${dados.length} veículo(s) cadastrado(s)`;if(!lista)return;if(!arr.length){lista.innerHTML='<tr><td colspan="6">Nenhum veículo encontrado.</td></tr>';return}lista.innerHTML=arr.map(x=>`<tr><td class="celula-principal"><strong>${esc(x.placa)}</strong><span>${esc([x.marca,x.modelo,x.ano].filter(Boolean).join(" "))}</span></td><td>${esc(nomeEmpresa(x.empresaId))}</td><td>${Number(x.kmAtual||0).toLocaleString("pt-BR")} km</td><td>${x.proximaRevisaoKm?`${Number(x.proximaRevisaoKm).toLocaleString("pt-BR")} km`:"-"}${revisaoProxima(x)?'<br><span class="status-aviso">Próxima</span>':""}</td><td><span class="${x.status==="ativo"?"status-ativo":x.status==="manutencao"?"status-aviso":"status-inativo"}">${x.status==="ativo"?"Ativo":x.status==="manutencao"?"Manutenção":"Inativo"}</span></td><td><div class="acoes-tabela">${permite("frota","editar")?`<button class="btn-acao destaque" data-fro-edit="${x.id}" type="button">Editar</button>`:""}${permite("frota","excluir")?`<button class="btn-acao perigo" data-fro-del="${x.id}" type="button">Excluir</button>`:""}</div></td></tr>`).join("");document.querySelectorAll("[data-fro-edit]").forEach(b=>on(b,"click",()=>abrir(dados.find(x=>x.id===b.dataset.froEdit))));document.querySelectorAll("[data-fro-del]").forEach(b=>on(b,"click",()=>remover(b.dataset.froDel)))}
export async function carregarFrota(){if(!permite("frota"))return;try{await preencherEmpresaSelect(empresa);dados=await listarDocumentos("veiculos");render(busca?.value||"")}catch(e){console.error(e);if(lista)lista.innerHTML='<tr><td colspan="6">Não foi possível carregar a frota.</td></tr>'}}
async function remover(id){const x=dados.find(a=>a.id===id);if(!x||!confirmar(`Excluir o veículo ${x.placa}?`))return;try{await excluirDocumento("veiculos",id);await carregarFrota();emitirAlteracao("frota")}catch(e){console.error(e);alert("Não foi possível excluir o veículo.")}}
on($("btnNovoVeiculo"),"click",()=>abrir());on($("btnCancelarVeiculo"),"click",()=>{limpar();box?.classList.add("hidden")});on(placa,"input",()=>{placa.value=placa.value.toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,7)});on(busca,"input",()=>render(busca.value));on(form,"submit",async ev=>{ev.preventDefault();const d={empresaId:empresa.value,placa:placa.value.trim().toUpperCase(),status:status.value,marca:marca.value.trim(),modelo:modelo.value.trim(),ano:Number(ano.value||0),kmAtual:Number(km.value||0),proximaRevisaoKm:Number(revisaoKm.value||0),vencimentoSeguro:seguro.value,vencimentoLicenciamento:licenciamento.value,observacoes:obs.value.trim()};if(!d.empresaId||!d.placa||!d.modelo)return msg(mensagem,"Informe empresa, placa e modelo.");if(dados.some(x=>x.id!==editId&&norm(x.placa)===norm(d.placa)))return msg(mensagem,"Já existe um veículo com esta placa.");try{msg(mensagem,"Salvando...");if(editId)await atualizarDocumento("veiculos",editId,d);else await criarDocumento("veiculos",d);msg(mensagem,"Veículo salvo com sucesso.",true);await carregarFrota();emitirAlteracao("frota");setTimeout(()=>fecharBox(box,form,mensagem),500)}catch(e){console.error(e);msg(mensagem,"Não foi possível salvar o veículo.")}});window.addEventListener("sig:page",e=>{if(e.detail?.pagina==="frota")carregarFrota()});
