import { $, esc, listarDocumentos, empresaUnicaSelecionadaId, dataBr, moeda } from './shared.js';
import { colaboradoresPorFuncao } from './hr-role-registry.js?v=6';
import { periodoAtual } from './company-context.js';

let veiculos=[],manutencoes=[],abastecimentos=[],custosDiesel=[],motoristas=[],busy=false,timer=0,observer=null,veiculoSelecionado='';
const num=v=>Number.isFinite(Number(v))?Number(v):0;
const emp=()=>empresaUnicaSelecionadaId();
const agora=()=>new Date();
const diasDesde=s=>{if(!s)return null;const d=new Date(`${String(s).slice(0,10)}T12:00:00`);return Number.isNaN(d.getTime())?null:Math.floor((agora()-d)/86400000)};
const diasAte=s=>{if(!s)return null;const d=new Date(`${s}T12:00:00`);return Number.isNaN(d.getTime())?null:Math.ceil((d-agora())/86400000)};
const em12m=s=>{const d=diasDesde(s);return d!=null&&d>=0&&d<=366};
const periodoInfo=()=>{const p=periodoAtual(),meses=new Set(p.indices.map(i=>String(i+1).padStart(2,'0')));return{...p,meses}};
const emPeriodo=s=>{if(!s)return false;const p=periodoInfo(),str=String(s);return str.slice(0,4)===String(p.ano)&&p.meses.has(str.slice(5,7))};
const obr=v=>Array.isArray(v?.obrigacoes)?v.obrigacoes:[];
const movCons=id=>abastecimentos.filter(x=>x.status!=='estornado'&&x.tipo==='consumo'&&x.veiculoId===id&&num(x.quantidade)>0);
const kml=x=>x.kmAtual!=null&&x.kmAnterior!=null&&num(x.kmAtual)>num(x.kmAnterior)?(num(x.kmAtual)-num(x.kmAnterior))/num(x.quantidade):null;
const media=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:0;
const classificacao=s=>s>=90?'Excelente':s>=75?'Saudável':s>=60?'Atenção':s>=40?'Crítico':'Urgente';

function css(){if(document.querySelector('link[href^="fleet-central.css"]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='fleet-central.css?v=1';document.head.appendChild(l)}
async function lerSeguro(c){try{return await listarDocumentos(c)}catch(e){console.warn(`Frota: ${c} indisponível`,e);return[]}}
async function carregar(){if(busy||!emp())return;busy=true;try{const [v,m,a,c,mo]=await Promise.all([lerSeguro('veiculos'),lerSeguro('manutencoesFrota'),lerSeguro('abastecimentosFrota'),lerSeguro('custosDiesel'),colaboradoresPorFuncao('MOTORISTA').catch(()=>[])]);veiculos=v.filter(x=>x.empresaId===emp());manutencoes=m.filter(x=>x.empresaId===emp());abastecimentos=a.filter(x=>x.empresaId===emp());custosDiesel=c.filter(x=>x.empresaId===emp());motoristas=mo.filter(x=>x.empresaId===emp());decorar();renderSaude();if(veiculoSelecionado&&!$('fleetFichaCentral')?.classList.contains('hidden'))renderFicha(veiculoSelecionado)}finally{busy=false}}

function selectMotorista(input,placeholder){
  if(!input)return;
  const valor=String(input.value||'').trim(),eraSelect=input.tagName==='SELECT';
  let s=input;
  if(!eraSelect){
    s=document.createElement('select');
    [...input.attributes].forEach(a=>{if(!['type','placeholder','value'].includes(a.name))s.setAttribute(a.name,a.value)});
    s.id=input.id;s.required=input.required;input.replaceWith(s);
  }
  s.innerHTML=`<option value="">${placeholder}</option>`+motoristas.map(p=>`<option value="${esc(p.nome)}">${esc(p.nome)} · ${esc(p.cargoNome||'MOTORISTA')}</option>`).join('');
  if(valor&&![...s.options].some(o=>o.value===valor))s.add(new Option(`${valor} · vínculo anterior`,valor));
  s.value=valor;
}
function decorarFormularios(){selectMotorista($('veiculoResponsavel'),'Selecione o motorista...');selectMotorista($('fuelMotorista'),'Selecione o motorista...');selectMotorista($('obrigCondutor'),'Sem condutor vinculado');$('veiculoCentro')?.closest('.campo')?.remove();const t=$('manutTipo');if(t){[['pecas','Peças / componentes'],['servicos','Serviços / mão de obra']].forEach(([v,n])=>{if(![...t.options].some(o=>o.value===v))t.add(new Option(n,v))})}}

function vencida(o){return !['pago','cancelado','em_recurso'].includes(o.status)&&o.vencimento&&(diasAte(o.vencimento)??0)<0}
function manutVencida(m,v){if(['concluida','cancelada'].includes(m.status))return false;const d=diasAte(m.dataPrevista),km=num(m.kmPrevisto)-num(v.quilometragemAtual);return (d!=null&&d<0)||(num(m.kmPrevisto)>0&&km<=0)}
function manutProxima(m,v){if(['concluida','cancelada'].includes(m.status))return false;const d=diasAte(m.dataPrevista),km=num(m.kmPrevisto)-num(v.quilometragemAtual);return (d!=null&&d>=0&&d<=30)||(num(m.kmPrevisto)>0&&km>0&&km<=1000)}
function precoLitro(filtro=em12m){const compras=custosDiesel.filter(x=>x.status!=='estornado'&&filtro(x.data)),custo=compras.reduce((s,x)=>s+num(x.valorTotal??x.valor),0),litros=compras.reduce((s,x)=>s+num(x.quantidade),0);return litros?custo/litros:0}
function custoComFiltro(v,filtro){const ms=manutencoes.filter(x=>x.veiculoId===v.id&&x.status==='concluida'&&filtro(x.dataRealizada||x.dataPrevista)).reduce((s,x)=>s+num(x.custoReal),0),docs=obr(v).filter(x=>x.status==='pago'&&filtro(x.dataPagamento||x.vencimento)).reduce((s,x)=>s+num(x.valor),0),mov=movCons(v.id).filter(x=>filtro(x.data)),litros=mov.reduce((s,x)=>s+num(x.quantidade),0),km=mov.reduce((s,x)=>s+(x.kmAtual!=null&&x.kmAnterior!=null?Math.max(0,num(x.kmAtual)-num(x.kmAnterior)):0),0),fuel=litros*precoLitro(filtro),total=ms+docs+fuel;return{manutencao:ms,documentacao:docs,combustivel:fuel,total,litros,km,kml:litros&&km?km/litros:null,custoKm:km?total/km:null}}
function custo(v){return custoComFiltro(v,em12m)}
function custoPeriodo(v){return custoComFiltro(v,emPeriodo)}
function medianaCustoKm(){const a=veiculos.filter(v=>v.status==='ativo').map(custo).map(x=>x.custoKm).filter(x=>x&&Number.isFinite(x)).sort((a,b)=>a-b);if(!a.length)return 0;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2}
function criterios(v){const out=[];const os=obr(v),consultado=!!v.ultimaConsultaOficialEm;if(os.length||consultado){const ven=os.filter(vencida).length,prox=os.filter(o=>{const d=diasAte(o.vencimento);return !['pago','cancelado'].includes(o.status)&&d!=null&&d>=0&&d<=30}).length;out.push({nome:'Documentação e regularidade',peso:25,pontos:Math.max(0,25-ven*8-prox*3),texto:ven?`${ven} obrigação(ões) vencida(s)`:prox?`${prox} obrigação(ões) vencendo em até 30 dias`:'Sem pendências conhecidas'})}const ms=manutencoes.filter(x=>x.veiculoId===v.id);if(ms.length){const ven=ms.filter(x=>manutVencida(x,v)).length,prox=ms.filter(x=>manutProxima(x,v)).length;out.push({nome:'Manutenção',peso:30,pontos:Math.max(0,30-ven*15-prox*5),texto:ven?`${ven} manutenção(ões) vencida(s)`:prox?`${prox} manutenção(ões) próxima(s)`:'Plano sem atraso conhecido'})}const vals=movCons(v.id).map(x=>({data:x.data,k:kml(x)})).filter(x=>x.k&&x.k>0).sort((a,b)=>String(a.data).localeCompare(String(b.data)));if(vals.length>=3){const rec=media(vals.slice(-3).map(x=>x.k)),ant=vals.slice(-6,-3),base=ant.length?media(ant.map(x=>x.k)):media(vals.map(x=>x.k)),queda=base?(base-rec)/base:0;let p=20;if(queda>.30)p=5;else if(queda>.20)p=10;else if(queda>.10)p=15;out.push({nome:'Consumo',peso:20,pontos:p,texto:`${rec.toFixed(2)} km/l${queda>.10?` · queda de ${(queda*100).toFixed(0)}% versus histórico`:' · estável versus histórico'}`})}const cv=custo(v),med=medianaCustoKm();if(cv.custoKm&&med){const r=cv.custoKm/med;let p=15;if(r>1.75)p=4;else if(r>1.40)p=8;else if(r>1.15)p=12;out.push({nome:'Custo operacional',peso:15,pontos:p,texto:`${moeda(cv.custoKm)}/km · ${r>1.15?`${((r-1)*100).toFixed(0)}% acima da mediana`:'dentro da faixa da frota'}`})}if(num(v.quilometragemAtual)>0){const datas=movCons(v.id).map(x=>x.data).concat(ms.map(x=>x.dataRealizada||x.dataPrevista)).filter(Boolean).sort();if(datas.length){const d=diasDesde(datas.at(-1));let p=10;if(d>180)p=1;else if(d>90)p=4;else if(d>45)p=7;out.push({nome:'Utilização / KM',peso:10,pontos:p,texto:`Última evidência de KM há ${d} dia(s)`})}}return out}
function saude(v){const c=criterios(v),peso=c.reduce((s,x)=>s+x.peso,0),pts=c.reduce((s,x)=>s+x.pontos,0),score=peso?Math.round(pts/peso*100):null;return{v,c,score,cobertura:c.length,classe:score==null?'Dados insuficientes':classificacao(score)}}
function renderSaude(){const alvo=$('frotaSaude');if(!alvo)return;const itens=veiculos.filter(v=>v.status==='ativo').map(saude),validos=itens.filter(x=>x.score!=null),score=validos.length?Math.round(media(validos.map(x=>x.score))):null,falt=['Documentação e regularidade','Manutenção','Consumo','Custo operacional','Utilização / KM'];const html=`<div class="fleet-central-health"><div class="fleet-central-score"><strong>${score==null?'—':score}</strong><span>${score==null?'Dados insuficientes':classificacao(score)}</span><small>${score==null?'Ainda não há base suficiente para uma nota.':'Critérios sem dados são excluídos do cálculo e não penalizam a nota.'}</small></div><div class="fleet-health-method"><strong>Composição</strong><span>Documentação 25 · Manutenção 30 · Consumo 20 · Custo 15 · Utilização 10</span></div>${itens.sort((a,b)=>(a.score??999)-(b.score??999)).map(x=>`<details class="fleet-health-vehicle"><summary><span>${esc(x.v.placa||'—')} · ${esc(x.v.modelo||x.v.marca||'Veículo')}</span><strong>${x.score==null?'Dados insuficientes':`${x.score}/100 · ${esc(x.classe)}`}</strong></summary><div class="fleet-health-breakdown">${x.c.map(c=>`<div><span>${esc(c.nome)} <small>${c.pontos}/${c.peso}</small></span><p>${esc(c.texto)}</p></div>`).join('')}${falt.filter(n=>!x.c.some(c=>c.nome===n)).map(n=>`<div class="missing"><span>${esc(n)} <small>sem nota</small></span><p>Dados insuficientes; este critério não reduz a nota.</p></div>`).join('')}</div><small>Nota baseada em ${x.cobertura} de 5 critérios.</small></details>`).join('')||'<div class="fleet-empty">Nenhum veículo ativo.</div>'}</div>`;if(alvo.innerHTML!==html)alvo.innerHTML=html;const k=$('frotaKpiSaude');if(k)k.textContent=score==null?'—':`${score}/100`;const sm=k?.closest('.fleet-kpi')?.querySelector('small');if(sm)sm.textContent=score==null?'dados insuficientes':classificacao(score)}

function garantirIntegracoes(){const p=document.querySelector('[data-fleet-panel="visao"]');if(!p||$('fleetIntegracoesOficiais'))return;const s=document.createElement('section');s.id='fleetIntegracoesOficiais';s.className='fleet-card';s.innerHTML='<div class="fleet-toolbar"><div><h3>Integrações oficiais</h3><p>Fontes definidas para automação segura.</p></div></div><div class="fleet-integration-grid"><div><strong>SENATRAN / SERPRO</strong><span>Multas, infrações e penalidades</span><small>Aguardando backend e credenciais. Consulta manual permanece como contingência.</small></div><div><strong>Detran-ES</strong><span>IPVA e licenciamento</span><small>Aguardando backend e credenciais. Consulta manual permanece como contingência.</small></div></div>';p.appendChild(s)}
function garantirFicha(){const p=document.querySelector('[data-fleet-panel="visao"]');if(!p||$('fleetFichaCentral'))return;const s=document.createElement('section');s.id='fleetFichaCentral';s.className='fleet-card hidden';const alvo=p.querySelector('.fleet-card:last-child');if(alvo)alvo.before(s);else p.appendChild(s)}
function renderFicha(id){
  garantirFicha();const v=veiculos.find(x=>x.id===id),b=$('fleetFichaCentral');if(!v||!b)return;
  veiculoSelecionado=id;
  const c12=custo(v),cp=custoPeriodo(v),p=periodoInfo();
  const fuel=movCons(id).filter(x=>em12m(x.data)).sort((a,b)=>String(b.data).localeCompare(String(a.data)));
  const ms=manutencoes.filter(x=>x.veiculoId===id).sort((a,b)=>String(b.dataRealizada||b.dataPrevista).localeCompare(String(a.dataRealizada||a.dataPrevista)));
  const os=[...obr(v)].sort((a,b)=>String(b.vencimento).localeCompare(String(a.vencimento)));
  const sv=saude(v);
  const timeline=[
    ...fuel.map(x=>({data:x.data,tipo:'Abastecimento',descricao:`${fmtLitros(x.quantidade)} L · ${x.motorista||'motorista não informado'}`,valor:num(x.quantidade)*precoLitro(em12m)})),
    ...ms.map(x=>({data:x.dataRealizada||x.dataPrevista,tipo:'Manutenção',descricao:x.descricao||x.tipo||'Manutenção',valor:num(x.custoReal)||num(x.custoPrevisto)})),
    ...os.map(x=>({data:x.dataPagamento||x.vencimento,tipo:'Obrigação',descricao:x.exercicio||x.auto||x.descricao||x.tipo||'Obrigação',valor:num(x.valor)}))
  ].filter(x=>x.data).sort((a,b)=>String(b.data).localeCompare(String(a.data)));
  b.innerHTML=`<div class="fleet-toolbar"><div><h3>${esc(v.placa||'—')} · ${esc(v.marca||'')} ${esc(v.modelo||'')}</h3><p>Ficha consolidada · motorista ${esc(v.responsavel||'não definido')}</p></div><button id="fleetFecharFicha" class="btn-secundario" type="button">Fechar</button></div>
  <div class="fleet-central-tabs"><button class="ativo" data-fsec="resumo">Resumo</button><button data-fsec="historico">Histórico geral</button><button data-fsec="custos">Custos</button><button data-fsec="combustivel">Abastecimento/consumo</button><button data-fsec="manutencao">Manutenções</button><button data-fsec="documentos">Documentação/infrações</button></div>
  <div data-fpanel="resumo"><div class="fleet-central-kpis">
    <div><span>Saúde</span><strong>${sv.score==null?'—':`${sv.score}/100`}</strong><small>${esc(sv.classe)} · ${sv.cobertura}/5 critérios</small></div>
    <div><span>Custo 12 meses</span><strong>${moeda(c12.total)}</strong><small>combustível + manutenção + obrigações</small></div>
    <div><span>Custo · ${esc(p.label)} ${p.ano}</span><strong>${moeda(cp.total)}</strong><small>período do filtro geral</small></div>
    <div><span>Consumo 12m</span><strong>${c12.kml?`${c12.kml.toFixed(2)} km/l`:'—'}</strong><small>${c12.litros.toLocaleString('pt-BR',{maximumFractionDigits:1})} L</small></div>
    <div><span>Custo por KM · período</span><strong>${cp.custoKm?moeda(cp.custoKm):'—'}</strong><small>${cp.km.toLocaleString('pt-BR')} km medidos</small></div>
  </div></div>
  <div data-fpanel="historico" class="hidden"><div class="tabela-container"><table class="tabela"><thead><tr><th>Data</th><th>Evento</th><th>Descrição</th><th>Valor / custo estimado</th></tr></thead><tbody>${timeline.map(x=>`<tr><td>${dataBr(x.data)}</td><td>${esc(x.tipo)}</td><td>${esc(x.descricao)}</td><td>${moeda(x.valor)}</td></tr>`).join('')||'<tr><td colspan="4">Sem histórico registrado.</td></tr>'}</tbody></table></div></div>
  <div data-fpanel="custos" class="hidden"><div class="fleet-cost-grid">
    <div><span>Combustível 12m</span><strong>${moeda(c12.combustivel)}</strong></div><div><span>Combustível · período</span><strong>${moeda(cp.combustivel)}</strong></div>
    <div><span>Manutenção 12m</span><strong>${moeda(c12.manutencao)}</strong></div><div><span>Manutenção · período</span><strong>${moeda(cp.manutencao)}</strong></div>
    <div><span>Obrigações 12m</span><strong>${moeda(c12.documentacao)}</strong></div><div><span>Obrigações · período</span><strong>${moeda(cp.documentacao)}</strong></div>
    <div><span>Total 12m</span><strong>${moeda(c12.total)}</strong></div><div><span>Total · ${esc(p.label)} ${p.ano}</span><strong>${moeda(cp.total)}</strong></div>
  </div></div>
  <div data-fpanel="combustivel" class="hidden"><div class="tabela-container"><table class="tabela"><thead><tr><th>Data</th><th>Motorista</th><th>Litros</th><th>KM</th><th>KM/L</th></tr></thead><tbody>${fuel.map(x=>`<tr><td>${dataBr(x.data)}</td><td>${esc(x.motorista||'—')}</td><td>${num(x.quantidade).toLocaleString('pt-BR')}</td><td>${x.kmAtual!=null&&x.kmAnterior!=null?(num(x.kmAtual)-num(x.kmAnterior)).toLocaleString('pt-BR'):'—'}</td><td>${kml(x)?.toFixed(2)||'—'}</td></tr>`).join('')||'<tr><td colspan="5">Sem abastecimentos no período.</td></tr>'}</tbody></table></div></div>
  <div data-fpanel="manutencao" class="hidden"><div class="tabela-container"><table class="tabela"><thead><tr><th>Data</th><th>Tipo</th><th>Descrição</th><th>Fornecedor</th><th>Custo</th></tr></thead><tbody>${ms.map(x=>`<tr><td>${dataBr(x.dataRealizada||x.dataPrevista)}</td><td>${esc(x.tipo||'—')}</td><td>${esc(x.descricao||'—')}</td><td>${esc(x.oficina||'—')}</td><td>${moeda(num(x.custoReal)||num(x.custoPrevisto))}</td></tr>`).join('')||'<tr><td colspan="5">Sem registros.</td></tr>'}</tbody></table></div></div>
  <div data-fpanel="documentos" class="hidden"><div class="tabela-container"><table class="tabela"><thead><tr><th>Tipo</th><th>Referência</th><th>Vencimento</th><th>Status</th><th>Valor</th></tr></thead><tbody>${os.map(x=>`<tr><td>${esc(x.tipo||'—')}</td><td>${esc(x.exercicio||x.auto||x.descricao||'—')}</td><td>${dataBr(x.vencimento)}</td><td>${vencida(x)?'Vencido':esc(x.status||'aberto')}</td><td>${moeda(num(x.valor))}</td></tr>`).join('')||'<tr><td colspan="5">Sem obrigações registradas.</td></tr>'}</tbody></table></div></div>`;
  b.classList.remove('hidden');
  $('fleetFecharFicha').onclick=()=>b.classList.add('hidden');
  b.querySelectorAll('[data-fsec]').forEach(bt=>bt.onclick=()=>{b.querySelectorAll('[data-fsec]').forEach(x=>x.classList.toggle('ativo',x===bt));b.querySelectorAll('[data-fpanel]').forEach(x=>x.classList.toggle('hidden',x.dataset.fpanel!==bt.dataset.fsec))});
  b.scrollIntoView({behavior:'smooth',block:'start'})
}
function fmtLitros(v){return num(v).toLocaleString('pt-BR',{maximumFractionDigits:2})}
function decorarLinhas(){document.querySelectorAll('#listaVeiculos tr').forEach(tr=>{if(tr.dataset.ficha==='1')return;const placa=String(tr.cells?.[0]?.innerText||'').trim().split(' ')[0],v=veiculos.find(x=>x.placa===placa);if(!v)return;tr.dataset.ficha='1';const ac=tr.cells?.[6]?.querySelector('.acoes-tabela');if(ac){const b=document.createElement('button');b.className='btn-acao';b.type='button';b.textContent='Ficha';b.onclick=()=>{document.querySelector('[data-fleet-tab="visao"]')?.click();setTimeout(()=>renderFicha(v.id),40)};ac.prepend(b)}});decorarResumoLinhas()}
function decorarResumoLinhas(){const tb=$('frotaResumoVeiculos'),table=tb?.closest('table');if(!tb||!table)return;const head=table.querySelector('thead tr');if(head&&head.children.length===7){const th=document.createElement('th');th.textContent='Custo período';head.insertBefore(th,head.children[6])}const p=periodoInfo();tb.querySelectorAll('tr').forEach(tr=>{const placa=String(tr.cells?.[0]?.innerText||'').trim().split(' ')[0],v=veiculos.find(x=>x.placa===placa);if(!v)return;const c12=custo(v),cp=custoPeriodo(v);if(tr.cells[5])tr.cells[5].textContent=moeda(c12.total);if(tr.cells.length===7){const td=document.createElement('td');tr.insertBefore(td,tr.cells[6])}if(tr.cells[6]){tr.cells[6].innerHTML=`<strong>${moeda(cp.total)}</strong><br><small>${esc(p.label)} ${p.ano}</small>`}tr.style.cursor='pointer';tr.title='Clique para abrir histórico e detalhamento do veículo';tr.onclick=e=>{if(e.target.closest('button,a,input,select'))return;renderFicha(v.id)}})}

function filtrar(sel,pred){document.querySelectorAll(sel).forEach(tr=>{tr.style.display=pred(tr)?'':'none'})}
function cardAcao(id){if(id==='frotaKpiAtivos'){document.querySelector('[data-fleet-tab="veiculos"]')?.click();setTimeout(()=>filtrar('#listaVeiculos tr',tr=>/\bativo\b/i.test(tr.innerText)),60)}else if(id==='frotaKpiVencidas'){document.querySelector('[data-fleet-tab="obrigacoes"]')?.click();setTimeout(()=>filtrar('#listaObrigacoes tr',tr=>/vencido/i.test(tr.innerText)),60)}else if(id==='frotaKpi30'){document.querySelector('[data-fleet-tab="visao"]')?.click();$('frotaAlertas')?.scrollIntoView({behavior:'smooth',block:'center'})}else if(id==='frotaKpiManut'){document.querySelector('[data-fleet-tab="manutencoes"]')?.click();setTimeout(()=>filtrar('#listaManutencoes tr',tr=>!/concluída|concluida|cancelada/i.test(tr.innerText)),60)}else if(id==='frotaKpiCusto'){document.querySelector('[data-fleet-tab="visao"]')?.click();$('frotaResumoVeiculos')?.closest('.fleet-card')?.scrollIntoView({behavior:'smooth',block:'start'})}else if(id==='frotaKpiSaude'){document.querySelector('[data-fleet-tab="visao"]')?.click();renderSaude();$('frotaSaude')?.scrollIntoView({behavior:'smooth',block:'center'})}}
function cards(){document.querySelectorAll('#pagina-frota .fleet-kpi').forEach(c=>{if(c.dataset.click==='1')return;c.dataset.click='1';c.classList.add('fleet-kpi-clickable');c.tabIndex=0;c.setAttribute('role','button');const id=c.querySelector('strong')?.id,go=()=>cardAcao(id);c.addEventListener('click',go);c.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go()}})})}
function decorar(){css();decorarFormularios();garantirIntegracoes();garantirFicha();cards();decorarLinhas();decorarResumoLinhas()}
function agenda(){clearTimeout(timer);timer=setTimeout(carregar,100)}
function instalar(){if(observer)return;observer=new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(()=>{decorarFormularios();cards();decorarLinhas()},60)});observer.observe(document.body,{childList:true,subtree:true});agenda()}
window.addEventListener('sig:ready',agenda);window.addEventListener('sig:empresa-contexto',agenda);window.addEventListener('sig:periodo-changed',()=>{decorarResumoLinhas();if(veiculoSelecionado&&!$('fleetFichaCentral')?.classList.contains('hidden'))renderFicha(veiculoSelecionado)});window.addEventListener('sig:data-changed',e=>{if(['frota','combustivel','rh'].includes(e.detail?.modulo))agenda()});window.addEventListener('sig:page',e=>{if(['frota','combustivel'].includes(e.detail?.pagina))agenda()});
instalar();
