import { $, esc, msg, permite, abrirPagina, admin, state } from "./core.js";
import { listarDocumentos, criarDocumento, atualizarDocumento, empresaUnicaSelecionadaId, nomeEmpresa } from "./shared.js";

let configs=[],planos=[],busy=false,configDisponivel=true,planosDisponiveis=true;
let programaEditId=null,cicloAtualId=null,checklistDraft=[];
const pagina=()=>$("pagina-governanca");
const podeConfig=()=>admin()||permite("governanca","configurar");
const podeAuditar=()=>admin()||permite("governanca","auditar")||permite("governanca","configurar");
const podePlano=()=>admin()||permite("governanca","planoAcao")||permite("planosAcao","cadastrar");
const hoje=()=>new Date().toISOString().slice(0,10);
const agora=()=>new Date().toISOString();
const n=v=>{const x=Number(v||0);return Number.isFinite(x)?x:0};
const uid=()=>crypto.randomUUID?.()||`${Date.now()}_${Math.random().toString(36).slice(2)}`;
const AREAS=["Controladoria & Financeiro","Fiscal & Tributário","Contábil","RH & Trabalhista","SST","LGPD & Privacidade","Societário","Qualidade & Processos"];
const PERIODICIDADES=["Mensal","Trimestral","Semestral","Anual","Bienal","Eventual"];

function config(){return configs.find(x=>x.empresaId===empresaUnicaSelecionadaId())||null}
function obrigacoes(){return Array.isArray(config()?.complianceObrigacoes)?config().complianceObrigacoes:[]}
function riscos(){return Array.isArray(config()?.complianceRiscos)?config().complianceRiscos:[]}
function programas(){return Array.isArray(config()?.complianceProgramasAuditoria)?config().complianceProgramasAuditoria:[]}
function ciclos(){return Array.isArray(config()?.complianceCiclosAuditoria)?config().complianceCiclosAuditoria:[]}
function cicloAtual(){return ciclos().find(x=>x.id===cicloAtualId)||null}
function programaPorId(id){return programas().find(x=>x.id===id)||null}

function montarMenu(){
  if($("menuGovernanca"))return;const sep=document.querySelector(".sidebar-menu .menu-separador");if(!sep)return;
  const b=document.createElement("button");b.id="menuGovernanca";b.className="menu-item hidden";b.dataset.pagina="governanca";b.type="button";b.textContent="Governança & Compliance";sep.before(b);
  b.addEventListener("click",()=>{if(!permite("governanca"))return;abrirPagina("governanca");if($("tituloPagina"))$("tituloPagina").textContent="Governança & Compliance";carregar()})
}
function css(){if($("gov-auditoria-css"))return;const s=document.createElement("style");s.id="gov-auditoria-css";s.textContent=`
.gov-audit-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.gov-audit-card{border:1px solid #e3e8ef;border-radius:12px;background:#fff;padding:14px}.gov-audit-card h4{margin:0 0 5px}.gov-audit-meta{display:flex;gap:6px;flex-wrap:wrap;margin-top:7px}.gov-audit-actions{display:flex;gap:6px;flex-wrap:wrap;margin-top:10px}.gov-check-item{display:grid;grid-template-columns:1.2fr 1.6fr 1.3fr auto;gap:8px;align-items:center;padding:7px 0;border-bottom:1px solid #eef2f6}.gov-cycle-progress{height:7px;background:#e9eef3;border-radius:99px;overflow:hidden;margin-top:7px}.gov-cycle-progress span{display:block;height:100%;background:#10b8aa}.gov-audit-detail{margin-top:14px}.gov-audit-toolbar{display:flex;gap:8px;align-items:end;flex-wrap:wrap}.gov-audit-toolbar .campo{min-width:160px}.gov-achado-critico{border-left:4px solid #b42318}.gov-achado-alto{border-left:4px solid #e16b21}.gov-achado-medio{border-left:4px solid #d6a800}.gov-achado-baixo{border-left:4px solid #10b8aa}.gov-audit-test textarea{min-width:220px;min-height:52px}.gov-audit-test input[type=url]{min-width:220px}@media(max-width:900px){.gov-audit-grid{grid-template-columns:1fr}.gov-check-item{grid-template-columns:1fr}.gov-audit-test textarea,.gov-audit-test input[type=url]{min-width:140px;width:100%}}
`;document.head.appendChild(s)}

function montarPagina(){
  if(pagina())return;css();const main=document.querySelector("main.conteudo");if(!main)return;const s=document.createElement("section");s.id="pagina-governanca";s.className="pagina hidden";s.innerHTML=`
<div class="pagina-cabecalho"><div><span class="eyebrow">GOVERNANÇA & COMPLIANCE</span><h2>Governança & Compliance</h2><p>Obrigações, riscos, controles, auditorias e planos de ação no mesmo ambiente.</p></div><button id="btnAtualizarGovernanca" class="btn-secundario" type="button">Atualizar</button></div>
<div id="governancaAviso" class="modulo-aviso">Selecione uma empresa para visualizar e parametrizar a matriz de compliance.</div>
<div class="kpi-grid kpi-grid-4"><div class="kpi-card"><span>Índice de conformidade</span><strong id="govConformidade">—</strong><small>obrigações em dia</small></div><div class="kpi-card"><span>Obrigações vencidas</span><strong id="govVencidas">—</strong><small>ação imediata</small></div><div class="kpi-card"><span>Riscos críticos</span><strong id="govRiscosCriticos">—</strong><small>probabilidade × impacto</small></div><div class="kpi-card"><span>Planos vencidos</span><strong id="govPlanosVencidos">—</strong><small>Minha Mesa / Planos de Ação</small></div></div>
<nav class="fpa-tabs gov-tabs"><button class="fpa-tab ativo" data-gov-tab="obrigacoes" type="button">Obrigações</button><button class="fpa-tab" data-gov-tab="riscos" type="button">Riscos & Controles</button><button class="fpa-tab" data-gov-tab="acoes" type="button">Planos de Ação</button><button class="fpa-tab" data-gov-tab="auditoria" type="button">Programas de Auditoria</button></nav>
<section class="gov-view" data-gov-view="obrigacoes"><div class="pagina-cabecalho interno"><div><h3>Calendário de Obrigações</h3><p>Controle de vencimento, responsável e evidência de cumprimento.</p></div><button id="btnNovaObrigacao" class="btn-primario" type="button">+ Nova obrigação</button></div><section id="formObrigacaoBox" class="form-card hidden"><form id="formObrigacao"><div class="form-grid form-grid-3"><div class="campo"><label for="govObrigTitulo">Obrigação</label><input id="govObrigTitulo" required></div><div class="campo"><label for="govObrigArea">Área</label><select id="govObrigArea">${AREAS.map(a=>`<option>${a}</option>`).join("")}</select></div><div class="campo"><label for="govObrigVenc">Próximo vencimento</label><input id="govObrigVenc" type="date" required></div><div class="campo"><label for="govObrigPeriodicidade">Periodicidade</label><select id="govObrigPeriodicidade"><option>Mensal</option><option>Trimestral</option><option>Semestral</option><option>Anual</option><option>Eventual</option></select></div><div class="campo"><label for="govObrigResp">Responsável / área</label><input id="govObrigResp"></div><div class="campo"><label for="govObrigStatus">Status</label><select id="govObrigStatus"><option value="pendente">Pendente</option><option value="concluido">Concluído</option><option value="dispensado">Dispensado</option></select></div></div><div class="form-acoes"><button id="btnCancelarObrigacao" class="btn-secundario" type="button">Cancelar</button><button class="btn-primario" type="submit">Salvar obrigação</button></div></form></section><section class="lista-card"><div class="tabela-container"><table class="tabela"><thead><tr><th>Obrigação</th><th>Área</th><th>Vencimento</th><th>Periodicidade</th><th>Responsável</th><th>Status</th></tr></thead><tbody id="listaGovObrigacoes"></tbody></table></div></section></section>
<section class="gov-view hidden" data-gov-view="riscos"><div class="pagina-cabecalho interno"><div><h3>Matriz de Riscos & Controles</h3><p>Risco inerente, controle existente e acompanhamento de criticidade.</p></div><button id="btnNovoRisco" class="btn-primario" type="button">+ Novo risco</button></div><section id="formRiscoBox" class="form-card hidden"><form id="formRisco"><div class="form-grid form-grid-3"><div class="campo"><label for="govRiscoTitulo">Risco</label><input id="govRiscoTitulo" required></div><div class="campo"><label for="govRiscoArea">Área</label><select id="govRiscoArea">${AREAS.map(a=>`<option>${a}</option>`).join("")}</select></div><div class="campo"><label for="govRiscoResp">Responsável</label><input id="govRiscoResp"></div><div class="campo"><label for="govRiscoProb">Probabilidade (1–5)</label><input id="govRiscoProb" type="number" min="1" max="5" value="3"></div><div class="campo"><label for="govRiscoImpacto">Impacto (1–5)</label><input id="govRiscoImpacto" type="number" min="1" max="5" value="3"></div><div class="campo"><label for="govRiscoStatus">Status</label><select id="govRiscoStatus"><option value="aberto">Aberto</option><option value="monitorado">Monitorado</option><option value="mitigado">Mitigado</option></select></div><div class="campo campo-span-3"><label for="govRiscoControle">Controle / resposta</label><input id="govRiscoControle" placeholder="Controle existente ou ação de mitigação"></div></div><div class="form-acoes"><button id="btnCancelarRisco" class="btn-secundario" type="button">Cancelar</button><button class="btn-primario" type="submit">Salvar risco</button></div></form></section><section class="lista-card"><div class="tabela-container"><table class="tabela"><thead><tr><th>Risco</th><th>Área</th><th>P</th><th>I</th><th>Score</th><th>Controle</th><th>Status</th></tr></thead><tbody id="listaGovRiscos"></tbody></table></div></section></section>
<section class="gov-view hidden" data-gov-view="acoes"><section class="lista-card"><div class="lista-cabecalho"><div><h3>Planos de Ação</h3><p>Ações da empresa conectadas à Minha Mesa.</p></div></div><div class="tabela-container"><table class="tabela"><thead><tr><th>Plano</th><th>Responsável</th><th>Prazo</th><th>Status</th><th>Origem</th></tr></thead><tbody id="listaGovAcoes"></tbody></table></div></section></section>
<section class="gov-view hidden" data-gov-view="auditoria">
  <div class="pagina-cabecalho interno"><div><h3>Programas & Ciclos de Auditoria</h3><p>Planejamento, testes, evidências, achados, conclusão e plano de ação em uma única trilha.</p></div><button id="btnNovoProgramaAuditoria" class="btn-primario" type="button">+ Novo programa</button></div>
  <div class="kpi-grid kpi-grid-4"><div class="kpi-card"><span>Programas ativos</span><strong id="audProgramasAtivos">—</strong><small>matrizes vigentes</small></div><div class="kpi-card"><span>Ciclos em andamento</span><strong id="audCiclosAbertos">—</strong><small>auditorias abertas</small></div><div class="kpi-card"><span>Achados abertos</span><strong id="audAchadosAbertos">—</strong><small>não conformidades / observações</small></div><div class="kpi-card"><span>Conformidade dos testes</span><strong id="audConformidade">—</strong><small>testes concluídos</small></div></div>
  <section id="formProgramaAuditoriaBox" class="form-card hidden"><div class="form-card-titulo"><div><h3 id="tituloProgramaAuditoria">Novo Programa de Auditoria</h3><p>O checklist definido aqui será copiado para cada novo ciclo, preservando o histórico.</p></div></div><form id="formProgramaAuditoria"><div class="form-grid form-grid-3"><div class="campo"><label for="audProgNome">Programa</label><input id="audProgNome" required placeholder="Ex.: Auditoria de Fechamento Financeiro"></div><div class="campo"><label for="audProgArea">Área</label><select id="audProgArea">${AREAS.map(a=>`<option>${a}</option>`).join("")}</select></div><div class="campo"><label for="audProgPeriodicidade">Periodicidade</label><select id="audProgPeriodicidade">${PERIODICIDADES.map(a=>`<option>${a}</option>`).join("")}</select></div><div class="campo"><label for="audProgResponsavel">Responsável pelo programa</label><input id="audProgResponsavel"></div><div class="campo"><label for="audProgStatus">Status</label><select id="audProgStatus"><option value="ativo">Ativo</option><option value="inativo">Inativo</option></select></div><div class="campo"><label for="audProgRisco">Risco prioritário</label><select id="audProgRisco"><option value="baixo">Baixo</option><option value="medio">Médio</option><option value="alto">Alto</option><option value="critico">Crítico</option></select></div><div class="campo campo-span-3"><label for="audProgObjetivo">Objetivo</label><textarea id="audProgObjetivo" rows="2" required></textarea></div><div class="campo campo-span-3"><label for="audProgEscopo">Escopo</label><textarea id="audProgEscopo" rows="2" required></textarea></div></div>
  <div class="lista-cabecalho"><div><h4>Checklist de testes</h4><p>Adicione os procedimentos que serão executados em cada ciclo.</p></div></div><div class="gov-check-item"><input id="audTesteTitulo" placeholder="Teste / requisito"><input id="audTesteProcedimento" placeholder="Procedimento de auditoria"><input id="audTesteEvidencia" placeholder="Evidência esperada"><button id="btnAddTestePrograma" class="btn-secundario" type="button">Adicionar</button></div><div id="listaChecklistPrograma"></div>
  <div class="form-acoes"><button id="btnCancelarProgramaAuditoria" class="btn-secundario" type="button">Cancelar</button><button class="btn-primario" type="submit">Salvar programa</button></div><p id="mensagemProgramaAuditoria" class="mensagem-form"></p></form></section>
  <section id="formCicloAuditoriaBox" class="form-card hidden"><div class="form-card-titulo"><div><h3>Novo Ciclo de Auditoria</h3><p>O ciclo recebe uma cópia do checklist vigente do programa.</p></div></div><form id="formCicloAuditoria"><div class="form-grid form-grid-3"><div class="campo"><label for="audCicloPrograma">Programa</label><select id="audCicloPrograma" required></select></div><div class="campo"><label for="audCicloReferencia">Referência</label><input id="audCicloReferencia" required placeholder="Ex.: 2026 / T3"></div><div class="campo"><label for="audCicloAuditor">Auditor / responsável</label><input id="audCicloAuditor" required></div><div class="campo"><label for="audCicloInicio">Início</label><input id="audCicloInicio" type="date" required></div><div class="campo"><label for="audCicloFim">Previsão de conclusão</label><input id="audCicloFim" type="date" required></div></div><div class="form-acoes"><button id="btnCancelarCicloAuditoria" class="btn-secundario" type="button">Cancelar</button><button class="btn-primario" type="submit">Criar ciclo</button></div><p id="mensagemCicloAuditoria" class="mensagem-form"></p></form></section>
  <div class="gov-audit-grid"><section class="lista-card"><div class="lista-cabecalho"><div><h3>Programas</h3><p>Matrizes permanentes de auditoria.</p></div></div><div id="listaProgramasAuditoria"></div></section><section class="lista-card"><div class="lista-cabecalho"><div><h3>Ciclos</h3><p>Execuções e histórico das auditorias.</p></div></div><div id="listaCiclosAuditoria"></div></section></div>
  <section id="auditoriaCicloDetalhe" class="lista-card gov-audit-detail hidden"></section>
</section>`;main.appendChild(s);
  s.querySelectorAll("[data-gov-tab]").forEach(b=>b.addEventListener("click",()=>{s.querySelectorAll("[data-gov-tab]").forEach(x=>x.classList.toggle("ativo",x===b));s.querySelectorAll("[data-gov-view]").forEach(v=>v.classList.toggle("hidden",v.dataset.govView!==b.dataset.govTab));if(b.dataset.govTab==="auditoria")renderAuditoria()}));
  $("btnAtualizarGovernanca")?.addEventListener("click",carregar);$("btnNovaObrigacao")?.addEventListener("click",()=>$("formObrigacaoBox")?.classList.remove("hidden"));$("btnCancelarObrigacao")?.addEventListener("click",()=>$("formObrigacaoBox")?.classList.add("hidden"));$("btnNovoRisco")?.addEventListener("click",()=>$("formRiscoBox")?.classList.remove("hidden"));$("btnCancelarRisco")?.addEventListener("click",()=>$("formRiscoBox")?.classList.add("hidden"));$("formObrigacao")?.addEventListener("submit",salvarObrigacao);$("formRisco")?.addEventListener("submit",salvarRisco);
  $("btnNovoProgramaAuditoria")?.addEventListener("click",()=>abrirPrograma());$("btnCancelarProgramaAuditoria")?.addEventListener("click",fecharPrograma);$("btnAddTestePrograma")?.addEventListener("click",addTestePrograma);$("formProgramaAuditoria")?.addEventListener("submit",salvarPrograma);$("btnCancelarCicloAuditoria")?.addEventListener("click",()=>$("formCicloAuditoriaBox")?.classList.add("hidden"));$("formCicloAuditoria")?.addEventListener("submit",salvarCiclo)
}

function fmtData(d){return d?String(d).slice(0,10).split("-").reverse().join("/"):"—"}
function score(r){return n(r.probabilidade)*n(r.impacto)}
function classeScore(s){return s>=16?"status-inativo":s>=9?"status-atencao":"status-ativo"}
function statusTxt(s){return({ativo:"Ativo",inativo:"Inativo",em_andamento:"Em andamento",concluido:"Concluído",aberto:"Aberto",resolvido:"Resolvido",conforme:"Conforme",nao_conforme:"Não conforme",nao_aplicavel:"N/A",pendente:"Pendente"})[s]||s||"—"}

function render(){
  const obs=obrigacoes(),rs=riscos(),venc=obs.filter(x=>x.status!=="concluido"&&x.status!=="dispensado"&&x.vencimento&&x.vencimento<hoje()).length,validas=obs.filter(x=>x.status!=="dispensado"),ok=validas.filter(x=>x.status==="concluido"||!x.vencimento||x.vencimento>=hoje()).length,conf=validas.length?Math.round(ok/validas.length*100):100,crit=rs.filter(x=>x.status!=="mitigado"&&score(x)>=16).length,pv=planos.filter(x=>x.status!=="concluido"&&x.prazo&&x.prazo<hoje()).length;
  $("govConformidade").textContent=`${conf}%`;$("govVencidas").textContent=venc;$("govRiscosCriticos").textContent=crit;$("govPlanosVencidos").textContent=pv;$("governancaAviso").innerHTML=`<strong>${esc(nomeEmpresa(empresaUnicaSelecionadaId()||""))}</strong> · ${obs.length} obrigação(ões) · ${rs.length} risco(s) · ${planos.length} plano(s) de ação`;
  $("btnNovaObrigacao").classList.toggle("hidden",!podeConfig()||!configDisponivel);$("btnNovoRisco").classList.toggle("hidden",!podeConfig()||!configDisponivel);$("btnNovoProgramaAuditoria").classList.toggle("hidden",!podeConfig()||!configDisponivel);
  const to=$("listaGovObrigacoes");to.innerHTML=obs.length?obs.sort((a,b)=>String(a.vencimento||"").localeCompare(String(b.vencimento||""))).map(o=>`<tr><td><strong>${esc(o.titulo)}</strong></td><td>${esc(o.area||"-")}</td><td>${fmtData(o.vencimento)}</td><td>${esc(o.periodicidade||"-")}</td><td>${esc(o.responsavel||"-")}</td><td><span class="${o.status==="concluido"?"status-ativo":o.vencimento<hoje()?"status-inativo":"status-atencao"}">${o.status==="concluido"?"Concluído":o.status==="dispensado"?"Dispensado":o.vencimento<hoje()?"Vencido":"Pendente"}</span></td></tr>`).join(""):'<tr><td colspan="6">Nenhuma obrigação parametrizada.</td></tr>';
  const tr=$("listaGovRiscos");tr.innerHTML=rs.length?rs.sort((a,b)=>score(b)-score(a)).map(r=>`<tr><td><strong>${esc(r.titulo)}</strong><small>${esc(r.responsavel||"")}</small></td><td>${esc(r.area||"-")}</td><td>${r.probabilidade}</td><td>${r.impacto}</td><td><span class="${classeScore(score(r))}">${score(r)}</span></td><td>${esc(r.controle||"-")}</td><td>${esc(r.status||"aberto")}</td></tr>`).join(""):'<tr><td colspan="7">Nenhum risco cadastrado.</td></tr>';
  const ta=$("listaGovAcoes");ta.innerHTML=planos.length?planos.sort((a,b)=>String(a.prazo||"").localeCompare(String(b.prazo||""))).map(p=>`<tr><td><strong>${esc(p.titulo||p.descricao||"Plano de ação")}</strong></td><td>${esc(p.responsavelNome||"-")}</td><td>${fmtData(p.prazo)}</td><td>${esc(p.status||"aberto")}</td><td>${esc(p.origem||p.moduloOrigem||"SIG")}</td></tr>`).join(""):'<tr><td colspan="5">Nenhum plano de ação disponível.</td></tr>';
  renderAuditoria()
}

function renderChecklistDraft(){const box=$("listaChecklistPrograma");if(!box)return;box.innerHTML=checklistDraft.length?checklistDraft.map((t,i)=>`<div class="gov-check-item"><span><strong>${esc(t.titulo)}</strong></span><span>${esc(t.procedimento||"-")}</span><span>${esc(t.evidenciaEsperada||"-")}</span><button class="btn-acao" data-aud-rem-teste="${i}" type="button">Remover</button></div>`).join(""):'<div class="empty-state">Nenhum teste no checklist.</div>';box.querySelectorAll("[data-aud-rem-teste]").forEach(b=>b.addEventListener("click",()=>{checklistDraft.splice(Number(b.dataset.audRemTeste),1);renderChecklistDraft()}))}
function abrirPrograma(id=null){if(!podeConfig()||!configDisponivel)return;programaEditId=id;const p=id?programaPorId(id):null;checklistDraft=(p?.checklist||[]).map(x=>({...x}));$("tituloProgramaAuditoria").textContent=p?"Editar Programa de Auditoria":"Novo Programa de Auditoria";$("audProgNome").value=p?.nome||"";$("audProgArea").value=p?.area||AREAS[0];$("audProgPeriodicidade").value=p?.periodicidade||"Anual";$("audProgResponsavel").value=p?.responsavel||"";$("audProgStatus").value=p?.status||"ativo";$("audProgRisco").value=p?.risco||"medio";$("audProgObjetivo").value=p?.objetivo||"";$("audProgEscopo").value=p?.escopo||"";renderChecklistDraft();$("formProgramaAuditoriaBox")?.classList.remove("hidden");$("formProgramaAuditoriaBox")?.scrollIntoView({behavior:"smooth",block:"start"})}
function fecharPrograma(){programaEditId=null;checklistDraft=[];$("formProgramaAuditoria")?.reset();$("formProgramaAuditoriaBox")?.classList.add("hidden")}
function addTestePrograma(){const titulo=$("audTesteTitulo").value.trim();if(!titulo)return;checklistDraft.push({id:`teste_${uid()}`,titulo,procedimento:$("audTesteProcedimento").value.trim(),evidenciaEsperada:$("audTesteEvidencia").value.trim()});$("audTesteTitulo").value="";$("audTesteProcedimento").value="";$("audTesteEvidencia").value="";renderChecklistDraft()}
async function salvarPrograma(e){e.preventDefault();if(!podeConfig()||!configDisponivel)return;if(!checklistDraft.length)return msg($("mensagemProgramaAuditoria"),"Inclua pelo menos um teste no programa.");const arr=[...programas()],base={nome:$("audProgNome").value.trim(),area:$("audProgArea").value,periodicidade:$("audProgPeriodicidade").value,responsavel:$("audProgResponsavel").value.trim(),status:$("audProgStatus").value,risco:$("audProgRisco").value,objetivo:$("audProgObjetivo").value.trim(),escopo:$("audProgEscopo").value.trim(),checklist:checklistDraft.map(x=>({...x})),atualizadoEm:agora()};if(programaEditId){const i=arr.findIndex(x=>x.id===programaEditId);if(i>=0)arr[i]={...arr[i],...base}}else arr.push({id:`prog_${uid()}`,...base,criadoEm:agora()});try{msg($("mensagemProgramaAuditoria"),"Salvando...");await salvarConfig("complianceProgramasAuditoria",arr);fecharPrograma()}catch{}}

function abrirNovoCiclo(programaId){if(!podeAuditar()||!configDisponivel)return;const ativos=programas().filter(x=>x.status!=="inativo");$("audCicloPrograma").innerHTML=ativos.map(p=>`<option value="${esc(p.id)}">${esc(p.nome)}</option>`).join("");$("audCicloPrograma").value=programaId||ativos[0]?.id||"";$("audCicloReferencia").value=String(new Date().getFullYear());$("audCicloAuditor").value=state.usuario?.nome||state.usuario?.email||"";$("audCicloInicio").value=hoje();$("audCicloFim").value="";$("formCicloAuditoriaBox")?.classList.remove("hidden");$("formCicloAuditoriaBox")?.scrollIntoView({behavior:"smooth",block:"start"})}
async function salvarCiclo(e){e.preventDefault();if(!podeAuditar()||!configDisponivel)return;const pid=$("audCicloPrograma").value,p=programaPorId(pid);if(!p)return msg($("mensagemCicloAuditoria"),"Selecione um programa válido.");const ciclo={id:`ciclo_${uid()}`,programaId:p.id,programaNome:p.nome,area:p.area,referencia:$("audCicloReferencia").value.trim(),auditor:$("audCicloAuditor").value.trim(),inicio:$("audCicloInicio").value,previsaoFim:$("audCicloFim").value,status:"em_andamento",testes:(p.checklist||[]).map(t=>({id:t.id,titulo:t.titulo,procedimento:t.procedimento||"",evidenciaEsperada:t.evidenciaEsperada||"",resultado:"pendente",evidenciaUrl:"",observacao:""})),achados:[],criadoEm:agora(),atualizadoEm:agora()};try{msg($("mensagemCicloAuditoria"),"Criando ciclo...");await salvarConfig("complianceCiclosAuditoria",[...ciclos(),ciclo]);cicloAtualId=ciclo.id;$("formCicloAuditoriaBox")?.classList.add("hidden")}catch{}}

function progressoCiclo(c){const t=Array.isArray(c.testes)?c.testes:[],done=t.filter(x=>x.resultado&&x.resultado!=="pendente").length;return{done,total:t.length,pct:t.length?Math.round(done/t.length*100):0}}
function achadosAbertos(c){return(Array.isArray(c.achados)?c.achados:[]).filter(x=>x.status!=="resolvido").length}
function conformidadeAuditoria(){const testes=ciclos().flatMap(c=>c.testes||[]).filter(t=>t.resultado&&t.resultado!=="pendente"&&t.resultado!=="nao_aplicavel");if(!testes.length)return null;return Math.round(testes.filter(t=>t.resultado==="conforme").length/testes.length*100)}
function renderAuditoria(){
  if(!$("listaProgramasAuditoria"))return;const ps=programas(),cs=ciclos(),abertos=cs.filter(x=>x.status!=="concluido").length,ach=cs.reduce((s,c)=>s+achadosAbertos(c),0),conf=conformidadeAuditoria();$("audProgramasAtivos").textContent=ps.filter(x=>x.status!=="inativo").length;$("audCiclosAbertos").textContent=abertos;$("audAchadosAbertos").textContent=ach;$("audConformidade").textContent=conf===null?"—":`${conf}%`;
  const lp=$("listaProgramasAuditoria");lp.innerHTML=ps.length?ps.sort((a,b)=>String(a.nome).localeCompare(String(b.nome),"pt-BR")).map(p=>`<div class="gov-audit-card"><h4>${esc(p.nome)}</h4><p>${esc(p.objetivo||"Sem objetivo definido")}</p><div class="gov-audit-meta"><span class="status-ativo">${esc(p.area||"-")}</span><span class="status-atencao">${esc(p.periodicidade||"-")}</span><span class="${p.status==="inativo"?"status-inativo":"status-ativo"}">${statusTxt(p.status)}</span><span>${(p.checklist||[]).length} teste(s)</span></div><div class="gov-audit-actions">${podeConfig()?`<button class="btn-acao" data-aud-edit-prog="${p.id}" type="button">Editar</button>`:""}${p.status!=="inativo"&&podeAuditar()?`<button class="btn-acao destaque" data-aud-new-cycle="${p.id}" type="button">Novo ciclo</button>`:""}</div></div>`).join(""):'<div class="empty-state">Nenhum programa cadastrado. Crie a matriz de auditoria antes de abrir ciclos.</div>';
  lp.querySelectorAll("[data-aud-edit-prog]").forEach(b=>b.addEventListener("click",()=>abrirPrograma(b.dataset.audEditProg)));lp.querySelectorAll("[data-aud-new-cycle]").forEach(b=>b.addEventListener("click",()=>abrirNovoCiclo(b.dataset.audNewCycle)));
  const lc=$("listaCiclosAuditoria");lc.innerHTML=cs.length?[...cs].sort((a,b)=>String(b.criadoEm||"").localeCompare(String(a.criadoEm||""))).map(c=>{const p=progressoCiclo(c);return`<div class="gov-audit-card"><h4>${esc(c.programaNome||"Auditoria")}</h4><p>${esc(c.referencia||"-")} · ${esc(c.auditor||"-")}</p><div class="gov-audit-meta"><span class="${c.status==="concluido"?"status-ativo":"status-atencao"}">${statusTxt(c.status)}</span><span>${achadosAbertos(c)} achado(s) aberto(s)</span></div><div class="gov-cycle-progress"><span style="width:${p.pct}%"></span></div><small>${p.done}/${p.total} testes executados · ${p.pct}%</small><div class="gov-audit-actions"><button class="btn-acao destaque" data-aud-open-cycle="${c.id}" type="button">Abrir ciclo</button></div></div>`}).join(""):'<div class="empty-state">Nenhum ciclo iniciado.</div>';lc.querySelectorAll("[data-aud-open-cycle]").forEach(b=>b.addEventListener("click",()=>{cicloAtualId=b.dataset.audOpenCycle;renderCicloDetalhe();$("auditoriaCicloDetalhe")?.scrollIntoView({behavior:"smooth",block:"start"})}));renderCicloDetalhe()
}

function renderCicloDetalhe(){const box=$("auditoriaCicloDetalhe"),c=cicloAtual();if(!box)return;if(!c){box.classList.add("hidden");box.innerHTML="";return}box.classList.remove("hidden");const prog=progressoCiclo(c),fechado=c.status==="concluido",ach=Array.isArray(c.achados)?c.achados:[];box.innerHTML=`
<div class="pagina-cabecalho interno"><div><span class="eyebrow">CICLO DE AUDITORIA</span><h3>${esc(c.programaNome||"Auditoria")} · ${esc(c.referencia||"")}</h3><p>${esc(c.area||"-")} · Auditor: ${esc(c.auditor||"-")} · ${fmtData(c.inicio)} a ${fmtData(c.previsaoFim)}</p></div><div class="acoes-cabecalho"><button id="btnSalvarExecAuditoria" class="btn-secundario" type="button">Salvar execução</button><button id="btnConcluirAuditoria" class="btn-primario" type="button">${fechado?"Reabrir auditoria":"Concluir auditoria"}</button></div></div>
<div class="modulo-aviso"><strong>${statusTxt(c.status)}</strong> · ${prog.done}/${prog.total} testes executados · ${achadosAbertos(c)} achado(s) aberto(s).</div>
<h4>Testes e evidências</h4><div class="tabela-container"><table class="tabela"><thead><tr><th>Teste</th><th>Procedimento</th><th>Resultado</th><th>Evidência</th><th>Observação</th></tr></thead><tbody>${(c.testes||[]).map(t=>`<tr class="gov-audit-test" data-aud-test="${esc(t.id)}"><td><strong>${esc(t.titulo)}</strong><small>${esc(t.evidenciaEsperada||"")}</small></td><td>${esc(t.procedimento||"-")}</td><td><select data-aud-test-result ${fechado?"disabled":""}><option value="pendente" ${t.resultado==="pendente"?"selected":""}>Pendente</option><option value="conforme" ${t.resultado==="conforme"?"selected":""}>Conforme</option><option value="nao_conforme" ${t.resultado==="nao_conforme"?"selected":""}>Não conforme</option><option value="nao_aplicavel" ${t.resultado==="nao_aplicavel"?"selected":""}>Não aplicável</option></select></td><td><input data-aud-test-evidence type="url" value="${esc(t.evidenciaUrl||"")}" placeholder="Link da evidência" ${fechado?"disabled":""}></td><td><textarea data-aud-test-obs ${fechado?"disabled":""}>${esc(t.observacao||"")}</textarea></td></tr>`).join("")||'<tr><td colspan="5">Programa sem testes.</td></tr>'}</tbody></table></div>
<div class="pagina-cabecalho interno"><div><h4>Achados / Não conformidades</h4><p>Registre desvios, oportunidades e recomendações. Achados podem gerar Planos de Ação.</p></div><button id="btnNovoAchadoAuditoria" class="btn-secundario" type="button" ${fechado?"disabled":""}>+ Novo achado</button></div>
<section id="formAchadoAuditoriaBox" class="form-card hidden"><form id="formAchadoAuditoria"><div class="form-grid form-grid-3"><div class="campo"><label for="audAchadoTitulo">Achado</label><input id="audAchadoTitulo" required></div><div class="campo"><label for="audAchadoTipo">Classificação</label><select id="audAchadoTipo"><option value="nao_conformidade">Não conformidade</option><option value="observacao">Observação</option><option value="oportunidade">Oportunidade de melhoria</option></select></div><div class="campo"><label for="audAchadoSeveridade">Severidade</label><select id="audAchadoSeveridade"><option value="baixo">Baixa</option><option value="medio">Média</option><option value="alto">Alta</option><option value="critico">Crítica</option></select></div><div class="campo campo-span-3"><label for="audAchadoDescricao">Descrição / evidência do achado</label><textarea id="audAchadoDescricao" rows="2" required></textarea></div><div class="campo campo-span-3"><label for="audAchadoRecomendacao">Recomendação</label><textarea id="audAchadoRecomendacao" rows="2"></textarea></div><div class="campo"><label for="audAchadoPrazo">Prazo recomendado</label><input id="audAchadoPrazo" type="date"></div></div><div class="form-acoes"><button id="btnCancelarAchadoAuditoria" class="btn-secundario" type="button">Cancelar</button><button class="btn-primario" type="submit">Registrar achado</button></div></form></section>
<div id="listaAchadosAuditoria">${ach.length?ach.map(a=>`<div class="gov-audit-card gov-achado-${esc(a.severidade||"medio")}" data-aud-finding="${esc(a.id)}"><h4>${esc(a.titulo)}</h4><p>${esc(a.descricao||"")}</p><div class="gov-audit-meta"><span>${esc(a.tipo==="nao_conformidade"?"Não conformidade":a.tipo==="oportunidade"?"Oportunidade":"Observação")}</span><span>${esc((a.severidade||"medio").toUpperCase())}</span><span>${statusTxt(a.status||"aberto")}</span>${a.prazo?`<span>Prazo ${fmtData(a.prazo)}</span>`:""}${a.planoAcaoId?'<span class="status-ativo">Plano de ação gerado</span>':""}</div>${a.recomendacao?`<p><strong>Recomendação:</strong> ${esc(a.recomendacao)}</p>`:""}<div class="gov-audit-actions">${!fechado&&a.status!=="resolvido"?`<button class="btn-acao" data-aud-resolve-finding="${a.id}" type="button">Marcar resolvido</button>`:""}${!a.planoAcaoId&&podePlano()?`<button class="btn-acao destaque" data-aud-plan-finding="${a.id}" type="button">Gerar plano de ação</button>`:""}</div></div>`).join(""):'<div class="empty-state">Nenhum achado registrado.</div>'}</div>`;
  $("btnSalvarExecAuditoria")?.classList.toggle("hidden",fechado||!podeAuditar());$("btnConcluirAuditoria")?.classList.toggle("hidden",!podeAuditar());$("btnSalvarExecAuditoria")?.addEventListener("click",salvarExecucaoCiclo);$("btnConcluirAuditoria")?.addEventListener("click",alternarConclusaoCiclo);$("btnNovoAchadoAuditoria")?.addEventListener("click",()=>$("formAchadoAuditoriaBox")?.classList.remove("hidden"));$("btnCancelarAchadoAuditoria")?.addEventListener("click",()=>$("formAchadoAuditoriaBox")?.classList.add("hidden"));$("formAchadoAuditoria")?.addEventListener("submit",salvarAchado);box.querySelectorAll("[data-aud-resolve-finding]").forEach(b=>b.addEventListener("click",()=>resolverAchado(b.dataset.audResolveFinding)));box.querySelectorAll("[data-aud-plan-finding]").forEach(b=>b.addEventListener("click",()=>gerarPlanoAchado(b.dataset.audPlanFinding)))
}
async function atualizarCiclo(novo){const arr=ciclos().map(c=>c.id===novo.id?novo:c);await salvarConfig("complianceCiclosAuditoria",arr)}
async function salvarExecucaoCiclo(){const c=cicloAtual();if(!c||c.status==="concluido"||!podeAuditar())return;const testes=(c.testes||[]).map(t=>{const tr=document.querySelector(`[data-aud-test="${CSS.escape(t.id)}"]`);return tr?{...t,resultado:tr.querySelector("[data-aud-test-result]")?.value||"pendente",evidenciaUrl:tr.querySelector("[data-aud-test-evidence]")?.value.trim()||"",observacao:tr.querySelector("[data-aud-test-obs]")?.value.trim()||""}:t});try{await atualizarCiclo({...c,testes,atualizadoEm:agora()})}catch{}}
async function alternarConclusaoCiclo(){const c=cicloAtual();if(!c||!podeAuditar())return;if(c.status!=="concluido"){await salvarExecucaoCiclo();const atualizado=cicloAtual()||c;if((atualizado.testes||[]).some(t=>!t.resultado||t.resultado==="pendente"))return alert("Execute todos os testes antes de concluir a auditoria.");if(!confirm("Concluir este ciclo de auditoria?"))return;await atualizarCiclo({...atualizado,status:"concluido",concluidoEm:agora(),atualizadoEm:agora()})}else{if(!confirm("Reabrir este ciclo de auditoria?"))return;await atualizarCiclo({...c,status:"em_andamento",concluidoEm:null,atualizadoEm:agora()})}}
async function salvarAchado(e){e.preventDefault();const c=cicloAtual();if(!c||c.status==="concluido"||!podeAuditar())return;const a={id:`ach_${uid()}`,titulo:$("audAchadoTitulo").value.trim(),tipo:$("audAchadoTipo").value,severidade:$("audAchadoSeveridade").value,descricao:$("audAchadoDescricao").value.trim(),recomendacao:$("audAchadoRecomendacao").value.trim(),prazo:$("audAchadoPrazo").value,status:"aberto",criadoEm:agora()};try{await atualizarCiclo({...c,achados:[...(c.achados||[]),a],atualizadoEm:agora()});$("formAchadoAuditoria")?.reset();$("formAchadoAuditoriaBox")?.classList.add("hidden")}catch{}}
async function resolverAchado(id){const c=cicloAtual();if(!c||!podeAuditar())return;await atualizarCiclo({...c,achados:(c.achados||[]).map(a=>a.id===id?{...a,status:"resolvido",resolvidoEm:agora()}:a),atualizadoEm:agora()})}
async function gerarPlanoAchado(id){const c=cicloAtual(),a=c?.achados?.find(x=>x.id===id);if(!c||!a||a.planoAcaoId||!podePlano())return;try{const planoId=await criarDocumento("planosAcao",{titulo:`Auditoria · ${a.titulo}`,descricao:[a.descricao,a.recomendacao?`Recomendação: ${a.recomendacao}`:""].filter(Boolean).join("\n\n"),prazo:a.prazo||"",status:"aberto",responsavelId:state.usuario.id,responsavelNome:state.usuario.nome||state.usuario.email||"Usuário",origem:"Auditoria",moduloOrigem:"governanca",referenciaId:c.id});await atualizarCiclo({...c,achados:(c.achados||[]).map(x=>x.id===id?{...x,planoAcaoId:planoId}:x),atualizadoEm:agora()});planos=await listarDocumentos("planosAcao");render()}catch(e){console.error("Plano do achado:",e);alert("Não foi possível gerar o plano de ação. Verifique as permissões de Planos de Ação.")}}

function erroTexto(e){const c=String(e?.code||e?.message||e||"");return c.includes("permission-denied")?"permissão do Firestore":c.includes("failed-precondition")?"índice do Firestore":"consulta ao banco"}
async function carregar(){if(busy||!empresaUnicaSelecionadaId())return;busy=true;msg($("governancaAviso"),"Carregando governança...");try{const[rc,rp]=await Promise.allSettled([listarDocumentos("configuracoesControladoria"),listarDocumentos("planosAcao")]);configDisponivel=rc.status==="fulfilled";planosDisponiveis=rp.status==="fulfilled";configs=configDisponivel?rc.value:[];planos=planosDisponiveis?rp.value:[];if(!configDisponivel)console.error("Governança · configurações:",rc.reason);if(!planosDisponiveis)console.error("Governança · planos de ação:",rp.reason);render();const falhas=[];if(!configDisponivel)falhas.push(`Configurações (${erroTexto(rc.reason)})`);if(!planosDisponiveis)falhas.push(`Planos de Ação (${erroTexto(rp.reason)})`);if(falhas.length)$("governancaAviso").innerHTML=`<strong>Governança carregada parcialmente.</strong> Base indisponível: ${esc(falhas.join("; "))}. As demais áreas continuam funcionando.`}catch(e){console.error("Governança:",e);$("governancaAviso").textContent="Não foi possível montar Governança & Compliance."}finally{busy=false}}
async function salvarConfig(campo,arr){try{const c=config();if(c)await atualizarDocumento("configuracoesControladoria",c.id,{[campo]:arr});else await criarDocumento("configuracoesControladoria",{[campo]:arr});await carregar()}catch(e){console.error("Governança · salvar configuração:",e);$("governancaAviso").innerHTML='<strong>Não foi possível salvar.</strong> A regra de acesso a Configurações da Controladoria precisa estar publicada no Firebase.';throw e}}
async function salvarObrigacao(e){e.preventDefault();if(!podeConfig()||!configDisponivel)return;const arr=[...obrigacoes(),{id:`ob_${Date.now()}`,titulo:$("govObrigTitulo").value.trim(),area:$("govObrigArea").value,vencimento:$("govObrigVenc").value,periodicidade:$("govObrigPeriodicidade").value,responsavel:$("govObrigResp").value.trim(),status:$("govObrigStatus").value}];try{await salvarConfig("complianceObrigacoes",arr);$("formObrigacao")?.reset();$("formObrigacaoBox")?.classList.add("hidden")}catch{}}
async function salvarRisco(e){e.preventDefault();if(!podeConfig()||!configDisponivel)return;const arr=[...riscos(),{id:`ri_${Date.now()}`,titulo:$("govRiscoTitulo").value.trim(),area:$("govRiscoArea").value,responsavel:$("govRiscoResp").value.trim(),probabilidade:n($("govRiscoProb").value),impacto:n($("govRiscoImpacto").value),controle:$("govRiscoControle").value.trim(),status:$("govRiscoStatus").value}];try{await salvarConfig("complianceRiscos",arr);$("formRisco")?.reset();$("formRiscoBox")?.classList.add("hidden")}catch{}}
function acesso(){const b=$("menuGovernanca");if(b)b.classList.toggle("hidden",!permite("governanca"))}
montarMenu();montarPagina();window.addEventListener("sig:ready",acesso);window.addEventListener("sig:empresa-changed",()=>{if(pagina()&&!pagina().classList.contains("hidden"))carregar()});
