import { collection, getDocs, query, where } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";
import { abrirPagina, admin } from './core.js';
import { $, db, esc, msg, permite, state, listarDocumentos, criarDocumento, atualizarDocumento, empresaUnicaSelecionadaId, emitirAlteracao, mensagemErroDados } from './shared.js';
import { confirmarAcaoAdministrativa, atualizarComAuditoria, excluirComAuditoria } from './admin-actions.js';
import { resumoRHPeriodo, fimMes, ativoNaData } from './hr-metrics.js';
import { rankingAbsenteismo, rankingHorasExtras, turnoverPorSetor } from './hr-analytics.js';
import { carregarConfiguracaoModulo, configuracaoModulo, abrirConfiguracaoModulo, registrarModuloConfiguravel } from './module-settings.js';
import { periodoAtual } from './company-context.js';

const SETORES_PADRAO = ['ADM','LAJE','COMERCIAL','LOGISTICA','PRODUÇÃO','MOURÃO','MANUTENÇÃO'];
let configRh={setores:[...SETORES_PADRAO],cargos:[],telas:{}};
const setoresAtivos=()=>{const base=Array.isArray(configRh.setores)?configRh.setores:SETORES_PADRAO;return [...new Set(base.map(x=>String(x||'').trim().toUpperCase()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR'))};
const setoresConhecidos=()=>[...new Set([...setoresAtivos(),...dados.pessoas.map(p=>p.setor).filter(Boolean)])];
const cargosConfig=()=>Array.isArray(configRh.cargos)?configRh.cargos:[];
const cargosAtivos=()=>cargosConfig().filter(c=>c.ativo!==false).sort((a,b)=>String(a.nome||'').localeCompare(String(b.nome||''),'pt-BR'));
const opcoesCargoRh=(valor='')=>'<option value="">Sem cargo definido</option>'+cargosAtivos().map(c=>`<option value="${esc(c.id)}" ${valor===c.id?'selected':''}>${esc(c.nome)}</option>`).join('');
registrarModuloConfiguravel('rh',{titulo:'Configurações · RH',telas:{pessoas:'Colaboradores e quadro',ausencias:'Absenteísmo',extras:'Horas extras',avaliacoes:'Avaliação 360°',acoes:'Ações / Endomarketing'},abrir:()=>abrirConfigRh()});
const COL = { pessoas:'rhColaboradores', ausencias:'rhAusencias', extras:'rhHorasColaboradores' };
const MOD = { pessoas:'rhColaboradores', ausencias:'rhAusencias', extras:'rhHorasColaboradores' };
const TIPOS = ['FALTA','ATESTADO','ATRASO','AFASTAMENTO','OUTROS'];
const perm = (k,a) => admin() || permite(MOD[k],a);
const acesso = () => perm('pessoas','visualizar') || perm('pessoas','lancar') || perm('pessoas','editar');
let dados = { pessoas:[], ausencias:[], extras:[] }, usuarios=[], tab='pessoas', editId='', ocupado=false;
const hoje = () => {const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const contextoPeriodo = () => { const p=periodoAtual(), meses=p.indices.map(i=>`${p.ano}-${String(i+1).padStart(2,'0')}`); return { ...p, inicio:meses[0], fim:meses.at(-1), unico:meses.length===1 }; };
const intervalo=()=>{const p=contextoPeriodo(),min=`${p.inicio}-01`,max=fimMes(p.fim),dataInicio=$('rhDataInicioFiltro')?.value||min,dataFim=$('rhDataFimFiltro')?.value||max;return{...p,dataInicio,dataFim,valido:/^\d{4}-\d{2}-\d{2}$/.test(dataInicio)&&/^\d{4}-\d{2}-\d{2}$/.test(dataFim)&&dataInicio>=min&&dataFim<=max&&dataInicio<=dataFim}};
function sincronizarPeriodo(){const p=contextoPeriodo(),min=`${p.inicio}-01`,max=fimMes(p.fim);$('rhDataInicioFiltro').min=min;$('rhDataInicioFiltro').max=max;$('rhDataFimFiltro').min=min;$('rhDataFimFiltro').max=max;$('rhDataInicioFiltro').value=min;$('rhDataFimFiltro').value=max;render()}
const decimal = v => Number(v||0).toLocaleString('pt-BR',{maximumFractionDigits:2});
const pct = v => `${decimal(v)}%`;
const dataBR = s => s ? String(s).slice(0,10).split('-').reverse().join('/') : '—';
const ativo = x => x.status !== 'estornado';
const pessoa = id => dados.pessoas.find(p => p.id === id && ativo(p));
const nome = id => pessoa(id)?.nome || 'Colaborador não encontrado';
const empresa = () => empresaUnicaSelecionadaId();
function montar(){
  if($('pagina-rh'))return;
  const main=document.querySelector('main.conteudo');if(!main)return;
  const s=document.createElement('section');s.id='pagina-rh';s.className='pagina hidden production-page';
  s.innerHTML=`<div class="rh-module-head"><div class="pagina-cabecalho production-head"><div><span class="eyebrow">PESSOAS</span><h2>RH · Quadro e indicadores</h2><p>Admissões, demissões, ausências e horas extras por colaborador.</p></div><div class="acoes-cabecalho"><button id="rhNovo" class="btn-primario" type="button">+ Novo registro</button><button id="rhConfigurar" class="btn-secundario hidden" type="button">Configurações</button><button id="rhAtualizar" class="btn-secundario" type="button">Atualizar</button></div></div><div class="fleet-tabs"><button class="fleet-tab" data-rh-tab="pessoas" type="button">Colaboradores e quadro</button><button class="fleet-tab" data-rh-tab="ausencias" type="button">Absenteísmo</button><button class="fleet-tab" data-rh-tab="extras" type="button">Horas extras</button></div></div>
  <div id="rhAviso" class="modulo-aviso hidden"></div>
  <section class="lista-card"><div class="lista-cabecalho production-toolbar"><div><h3>Período de análise</h3><p>Use o calendário dentro do período escolhido no topo do SIG.</p></div><div class="rh-filter-bar"><label class="rh-filter-field" for="rhDataInicioFiltro">De <input id="rhDataInicioFiltro" type="date"></label><label class="rh-filter-field" for="rhDataFimFiltro">Até <input id="rhDataFimFiltro" type="date"></label><label class="rh-filter-field" for="rhSetor">Setor <select id="rhSetor"><option value="">Todos os setores</option></select></label><label class="rh-filter-field" for="rhFiltroPessoa">Colaborador <select id="rhFiltroPessoa"><option value="">Todos</option></select></label></div></div></section>
  <div class="production-kpis"><div class="kpi-card"><span id="rhRotuloA">Ativos no fim</span><strong id="rhValorA">—</strong></div><div class="kpi-card"><span id="rhRotuloB">Admissões / demissões</span><strong id="rhValorB">—</strong></div><div class="kpi-card"><span id="rhRotuloC">Turnover</span><strong id="rhValorC">—</strong></div><div class="kpi-card"><span id="rhRotuloD">Absenteísmo</span><strong id="rhValorD">—</strong></div></div>
  <section id="rhFormBox" class="form-card hidden"><div class="form-card-titulo"><h3 id="rhFormTitulo">Novo registro</h3></div><form id="rhForm"><div id="rhCampos" class="form-grid form-grid-3"></div><div class="form-acoes"><button id="rhCancelar" class="btn-secundario" type="button">Cancelar</button><button class="btn-primario" type="submit">Salvar</button></div><p id="rhMensagem" class="mensagem-form"></p></form></section>
  <section class="lista-card"><div class="lista-cabecalho"><div><h3 id="rhTituloLista">Colaboradores</h3><p id="rhNota">Cadastre quem já estava na empresa com a data real de admissão.</p></div></div><div class="tabela-container"><table class="tabela"><thead id="rhCabecalho"></thead><tbody id="rhLista"></tbody></table></div></section>
  <section id="rhSerieBox" class="lista-card"><div class="lista-cabecalho"><h3>Evolução mensal</h3></div><div class="tabela-container"><table class="tabela"><thead id="rhSerieHead"></thead><tbody id="rhSerie"></tbody></table></div></section>
  <section id="rhGraficos" class="lista-card rh-graficos-card"><div class="lista-cabecalho rh-ranking-toolbar"><div><h3>Gráficos e rankings</h3><p>Os gráficos respeitam período, setor e colaborador selecionados acima.</p></div><label class="rh-filter-field" for="rhRankingAgrupamento">Agrupar ranking por<select id="rhRankingAgrupamento"><option value="colaborador">Colaborador</option><option value="setor">Setor</option></select></label></div><div class="rh-analytics-grid"><article class="rh-chart-panel"><div class="lista-cabecalho"><div><h3 id="rhGraficoTituloA">Indicadores</h3><p id="rhGraficoNotaA">Ranking do período selecionado.</p></div></div><div id="rhGraficoA" class="rh-bars"></div></article><article class="rh-chart-panel"><div class="lista-cabecalho"><div><h3 id="rhGraficoTituloB">Comparativo</h3><p id="rhGraficoNotaB">Comparativo do período selecionado.</p></div></div><div id="rhGraficoB" class="rh-bars"></div></article></div></section><section id="rhPorPessoaBox" class="lista-card"><div class="lista-cabecalho"><h3 id="rhPorPessoaTitulo">Por colaborador</h3></div><div class="tabela-container"><table class="tabela"><thead id="rhPorPessoaHead"></thead><tbody id="rhPorPessoa"></tbody></table></div></section><section id="rhPorSetorBox" class="lista-card hidden"><div class="lista-cabecalho"><h3>Total por setor</h3></div><div class="tabela-container"><table class="tabela"><thead id="rhPorSetorHead"></thead><tbody id="rhPorSetor"></tbody></table></div></section>`;
  main.appendChild(s);
  s.querySelectorAll('[data-rh-tab]').forEach(b=>b.addEventListener('click',()=>{trocar(b.dataset.rhTab);carregar()}));
  for(const id of ['rhDataInicioFiltro','rhDataFimFiltro','rhFiltroPessoa']) $(id).addEventListener('change',render);
  $('rhSetor').addEventListener('change',()=>{atualizarFiltroPessoas();render()});
  $('rhNovo').addEventListener('click',novo);$('rhConfigurar').addEventListener('click',abrirConfigRh);$('rhAtualizar').addEventListener('click',carregar);$('rhRankingAgrupamento').addEventListener('change',render);
  $('rhCancelar').addEventListener('click',()=>{$('rhFormBox').classList.add('hidden');editId=''});
  $('rhForm').addEventListener('submit',salvar);
  sincronizarPeriodo();trocar('pessoas');
}
function menu(){const cfg=$('rhConfigurar');if(cfg)cfg.classList.toggle('hidden',!admin());const nav=document.querySelector('.sidebar-menu');if(!nav)return;let b=$('menurh');if(!b){b=document.createElement('button');b.id='menurh';b.className='menu-item hidden';b.dataset.pagina='rh';b.type='button';b.textContent='RH';nav.appendChild(b);b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();if(!acesso())return;abrirPagina('rh');carregar()},true)}b.classList.toggle('hidden',!acesso())}
function telaAtiva(k){return configRh?.telas?.[k]!==false}
function trocar(k){if(!telaAtiva(k)||k!=='pessoas'&&!perm(k,'visualizar')&&!perm(k,'lancar')&&!perm(k,'editar'))k='pessoas';tab=k;editId='';$('rhFormBox')?.classList.add('hidden');document.querySelectorAll('[data-rh-tab]').forEach(b=>{const permitido=telaAtiva(b.dataset.rhTab)&&(b.dataset.rhTab==='pessoas'||perm(b.dataset.rhTab,'visualizar')||perm(b.dataset.rhTab,'lancar')||perm(b.dataset.rhTab,'editar'));b.classList.toggle('ativo',b.dataset.rhTab===k);b.classList.toggle('hidden',!permitido)});const pode=perm(k,'lancar');$('rhNovo')?.classList.toggle('hidden',!pode);$('rhNovo').textContent=k==='pessoas'?'+ Admitir colaborador':'+ Novo registro';const agr=$('rhRankingAgrupamento');if(agr){agr.disabled=k==='pessoas';if(k==='pessoas')agr.value='setor'};render()}
function opcoesPessoa(valor=''){const setor=$('rhSetor')?.value||'';const arr=dados.pessoas.filter(p=>ativo(p)&&(!setor||p.setor===setor)).sort((a,b)=>a.nome.localeCompare(b.nome,'pt-BR'));const html='<option value="">Selecione...</option>'+arr.map(p=>`<option value="${esc(p.id)}">${esc(p.nome)} · ${esc(p.codigo)} · ${esc(p.setor)}</option>`).join('');const s=$('rhColaborador');if(s){s.innerHTML=html;s.value=valor}}
function campos(){if(tab==='pessoas')return `<div class="campo"><label for="rhCodigo">Matrícula / código interno</label><input id="rhCodigo" required maxlength="40"></div><div class="campo"><label for="rhNome">Nome</label><input id="rhNome" required maxlength="120"></div><div class="campo"><label for="rhSetorForm">Setor</label><select id="rhSetorForm" required><option value="">Selecione...</option>${setoresAtivos().map(x=>`<option>${esc(x)}</option>`).join('')}</select></div><div class="campo"><label for="rhCargoForm">Cargo</label><select id="rhCargoForm">${opcoesCargoRh()}</select><small>Base central usada por Frota, Vendas e outros módulos.</small></div><div class="campo"><label for="rhCodigoVendedor">Código do vendedor</label><input id="rhCodigoVendedor" maxlength="40" placeholder="Código do sistema comercial"><small>Opcional. Usado para vincular relatórios de vendas ao colaborador do RH.</small></div><div class="campo"><label for="rhUsuario">Conta SIG (para Minha Mesa)</label><select id="rhUsuario"><option value="">Sem conta vinculada</option>${usuarios.filter(u=>u.empresaId===empresa()||u.acessoGlobal===true||(u.empresasAcesso||[]).includes(empresa())).map(u=>`<option value="${esc(u.id)}">${esc(u.nome||u.email||u.id)}</option>`).join('')}</select></div><div class="campo"><label for="rhAdmissao">Admissão</label><input id="rhAdmissao" type="date" required></div><div class="campo"><label for="rhDemissao">Demissão (quando ocorrer)</label><input id="rhDemissao" type="date"></div><div class="campo"><label for="rhJornada">Jornada prevista no mês (horas)</label><input id="rhJornada" type="number" min="1" max="300" step="0.01" required value="220"></div>`;
  const comum=`<div class="campo"><label for="rhColaborador">Colaborador</label><select id="rhColaborador" required></select></div><div class="campo"><label for="rhData">Data</label><input id="rhData" type="date" required></div>`;
  if(tab==='ausencias')return comum+`<div class="campo"><label for="rhTipo">Tipo</label><select id="rhTipo" required>${TIPOS.map(x=>`<option>${x}</option>`).join('')}</select></div><div class="campo"><label for="rhHoras">Horas ausentes</label><input id="rhHoras" type="number" min="0.01" max="300" step="0.01" required></div><div class="campo"><label for="rhObservacao">Observação operacional (sem dados médicos)</label><input id="rhObservacao" maxlength="200"></div>`;
  return comum+`<div class="campo"><label for="rhHoras50">Horas 50%</label><input id="rhHoras50" type="number" min="0" max="300" step="0.01" value="0" required></div><div class="campo"><label for="rhHoras100">Horas 100%</label><input id="rhHoras100" type="number" min="0" max="300" step="0.01" value="0" required></div>`;
}
function abrir(x=null){if(!empresa())return alert('Selecione apenas uma empresa no cabeçalho.');editId=x?.id||'';$('rhCampos').innerHTML=campos();$('rhForm').reset();$('rhFormTitulo').textContent=`${x?'Atualizar vínculo':'Admitir colaborador'} · ${tab==='pessoas'?'cadastro':tab==='ausencias'?'ausência':'horas extras'}`;msg($('rhMensagem'),'');if(tab==='pessoas'){$('rhCodigo').value=x?.codigo||'';$('rhNome').value=x?.nome||'';$('rhSetorForm').value=x?.setor||'';if($('rhCargoForm'))$('rhCargoForm').value=x?.cargoId||'';if($('rhCodigoVendedor'))$('rhCodigoVendedor').value=x?.codigoVendedor||'';$('rhAdmissao').value=x?.admissao||'';$('rhDemissao').value=x?.demissao||'';$('rhUsuario').value=x?.usuarioId||'';$('rhJornada').value=x?.jornadaMensalHoras??220}else{opcoesPessoa(x?.colaboradorId);$('rhData').value=x?.data||hoje();if(tab==='ausencias'){$('rhTipo').value=x?.tipo||'FALTA';$('rhHoras').value=x?.horas??'';$('rhObservacao').value=x?.observacao||''}else{$('rhHoras50').value=x?.horas50??0;$('rhHoras100').value=x?.horas100??0}}$('rhFormBox').classList.remove('hidden');$('rhFormBox').scrollIntoView({behavior:'smooth',block:'start'})}
function novo(){if(perm(tab,'lancar'))abrir()}
function ler(){const texto=(id,max)=>String($(id).value||'').trim().slice(0,max);const valor=id=>Number($(id).value);if(tab==='pessoas'){const cargoId=$('rhCargoForm')?.value||'',cargo=cargosConfig().find(x=>x.id===cargoId&&x.ativo!==false);const d={codigo:texto('rhCodigo',40).toUpperCase(),nome:texto('rhNome',120).toUpperCase(),setor:$('rhSetorForm').value,cargoId,cargoNome:cargo?.nome||'',codigoVendedor:texto('rhCodigoVendedor',40).toUpperCase(),admissao:$('rhAdmissao').value,demissao:$('rhDemissao').value,jornadaMensalHoras:valor('rhJornada'),usuarioId:$('rhUsuario').value};if(!d.codigo||!d.nome||!setoresConhecidos().includes(d.setor)||(d.cargoId&&!cargo)||!/^\d{4}-\d{2}-\d{2}$/.test(d.admissao)||d.demissao&&d.demissao<d.admissao||!Number.isFinite(d.jornadaMensalHoras)||d.jornadaMensalHoras<=0||d.jornadaMensalHoras>300)throw Error('Revise matrícula, nome, setor, datas e jornada.');if(d.codigoVendedor&&!(cargo?.funcoesSistema||[]).includes('VENDEDOR'))throw Error('O código de vendedor só pode ser vinculado a cargo com função Vendedor / Comercial.');if(d.codigoVendedor&&dados.pessoas.some(p=>p.id!==editId&&ativo(p)&&p.empresaId===empresa()&&String(p.codigoVendedor||'').trim().toUpperCase()===d.codigoVendedor))throw Error('Este código de vendedor já está vinculado a outro colaborador.');if(d.usuarioId&&!usuarios.some(u=>u.id===d.usuarioId&&(u.empresaId===empresa()||u.acessoGlobal===true||(u.empresasAcesso||[]).includes(empresa()))))throw Error('Conta SIG inválida para a empresa.');if(dados.pessoas.some(p=>p.id!==editId&&ativo(p)&&p.empresaId===empresa()&&p.codigo===d.codigo&&(!p.demissao||p.demissao>=d.admissao)))throw Error('Esta matrícula já está em uso na empresa.');const eventos=[...dados.ausencias,...dados.extras].filter(x=>ativo(x)&&x.colaboradorId===editId);if(eventos.some(x=>x.data<d.admissao||d.demissao&&x.data>d.demissao))throw Error('As datas do vínculo conflitam com ausências ou horas extras já registradas.');return d}
  const colaboradorId=$('rhColaborador').value,p=pessoa(colaboradorId),data=$('rhData').value;if(!p||p.empresaId!==empresa()||!/^\d{4}-\d{2}-\d{2}$/.test(data)||!ativoNaData(p,data))throw Error('Escolha um colaborador ativo na data informada.');
  if(tab==='ausencias'){const horas=valor('rhHoras'),tipo=$('rhTipo').value;if(!TIPOS.includes(tipo)||!Number.isFinite(horas)||horas<=0||horas>300)throw Error('Informe tipo e horas ausentes válidas.');return {colaboradorId,data,setor:p.setor,tipo,horas,observacao:texto('rhObservacao',200)}}
  const horas50=valor('rhHoras50'),horas100=valor('rhHoras100');if(!Number.isFinite(horas50)||!Number.isFinite(horas100)||horas50<0||horas100<0||horas50+horas100<=0||horas50+horas100>300)throw Error('Informe horas 50% e/ou 100% válidas.');return {colaboradorId,data,setor:p.setor,horas50,horas100};
}
async function salvar(e){e.preventDefault();if(ocupado)return;const emp=empresa();if(!emp)return alert('Selecione apenas uma empresa no cabeçalho.');try{if(tab==='pessoas'&&editId){[dados.ausencias,dados.extras]=await Promise.all([listarDocumentos(COL.ausencias),listarDocumentos(COL.extras)])}const d=ler(),id=editId;ocupado=true;msg($('rhMensagem'),'Salvando...');if(id){const original=dados[tab].find(x=>x.id===id);if(!original||!ativo(original)||original.empresaId!==emp||!perm(tab,'editar'))throw Error('Edição não autorizada.');await atualizarDocumento(COL[tab],id,d)}else{if(!perm(tab,'lancar'))throw Error('Sem permissão para registrar.');await criarDocumento(COL[tab],{...d,empresaId:emp,status:'ativo',registradoPor:state.usuario.id,origem:'sig'})}$('rhFormBox').classList.add('hidden');editId='';emitirAlteracao('rh');ocupado=false;msg($('rhMensagem'),'Registro salvo.',true);await carregar()}catch(err){console.error(err);msg($('rhMensagem'),err?.code==='permission-denied'?'Gravação negada pelo Firestore. Confira a permissão de cadastro/edição do seu perfil e as Rules ativas.':err.message||'Não foi possível salvar.')}finally{ocupado=false}}
function editar(id){const x=dados[tab].find(v=>v.id===id);if(!x||!perm(tab,'editar')||!ativo(x))return;if(x.empresaId!==empresa())return alert('Selecione a empresa do registro.');abrir(x)}
async function estornar(id){if(!admin())return;const x=dados[tab].find(v=>v.id===id);if(!x||!ativo(x))return;if(tab==='pessoas'&&[...dados.ausencias,...dados.extras].some(v=>ativo(v)&&v.colaboradorId===id))return alert('Este colaborador possui lançamentos. Estorne os registros vinculados antes.');const ok=await confirmarAcaoAdministrativa({titulo:'Estornar registro de RH',descricao:'O registro permanecerá no histórico, fora dos indicadores.',motivoLabel:'Motivo obrigatório',confirmarTexto:'Estornar',perigosa:true});if(!ok)return;try{await atualizarComAuditoria({colecao:COL[tab],id,empresaId:x.empresaId,modulo:MOD[tab],acao:'estorno',motivo:ok.motivo,resumo:`Estorno RH · ${tab}`,snapshotAntes:x,alteracoes:{status:'estornado',motivoEstorno:ok.motivo,estornadoPor:state.usuario.id,estornadoEm:new Date().toISOString()}});emitirAlteracao('rh');await carregar()}catch(e){console.error(e);alert('Não foi possível estornar.')}}
async function excluirAdm(id){if(!admin())return;const x=dados[tab].find(v=>v.id===id);if(!x)return;if(tab==='pessoas'&&[...dados.ausencias,...dados.extras].some(v=>ativo(v)&&v.colaboradorId===id))return alert('Este colaborador possui lançamentos vinculados. Use estorno ou corrija os dependentes antes da exclusão física.');const ok=await confirmarAcaoAdministrativa({titulo:'Excluir fisicamente registro de RH',descricao:'Use somente para cadastro duplicado ou teste. A auditoria será preservada.',motivoLabel:'Motivo obrigatório',confirmarTexto:'Excluir definitivamente',perigosa:true});if(!ok)return;try{await excluirComAuditoria({colecao:COL[tab],id,empresaId:x.empresaId,modulo:MOD[tab],motivo:ok.motivo,resumo:`Exclusão física RH · ${tab}`,snapshotAntes:x});emitirAlteracao('rh');await carregar()}catch(e){console.error(e);alert('Não foi possível excluir. Confira as Rules administrativas.')}}
function tabela(cab,linhas,cols){$('rhCabecalho').innerHTML=`<tr>${cab.map(x=>`<th>${esc(x)}</th>`).join('')}<th>Situação / ações</th></tr>`;$('rhLista').innerHTML=linhas.map(x=>`<tr class="${ativo(x)?'':'sig-admin-estornado'}">${cols(x).map(v=>`<td>${esc(v)}</td>`).join('')}<td>${ativo(x)?'Ativo':'Estornado'} ${ativo(x)&&perm(tab,'editar')?`<button type="button" class="btn-acao destaque" data-rh-edit="${esc(x.id)}">Editar</button>`:''}${ativo(x)&&tab==='pessoas'&&!x.demissao&&perm('pessoas','editar')?`<button type="button" class="btn-acao destaque" data-rh-demissao="${esc(x.id)}">Registrar demissão</button>`:''}${ativo(x)&&admin()?`<button type="button" class="btn-acao perigo" data-rh-estorno="${esc(x.id)}">Estornar ADM</button><button type="button" class="btn-acao perigo" data-rh-excluir="${esc(x.id)}">Excluir ADM</button>`:''}</td></tr>`).join('')||`<tr><td colspan="${cab.length+1}">Nenhum registro no período.</td></tr>`;document.querySelectorAll('[data-rh-edit]').forEach(b=>b.addEventListener('click',()=>editar(b.dataset.rhEdit)));document.querySelectorAll('[data-rh-demissao]').forEach(b=>b.addEventListener('click',()=>{editar(b.dataset.rhDemissao);$('rhDemissao').focus()}));document.querySelectorAll('[data-rh-estorno]').forEach(b=>b.addEventListener('click',()=>estornar(b.dataset.rhEstorno)));document.querySelectorAll('[data-rh-excluir]').forEach(b=>b.addEventListener('click',()=>excluirAdm(b.dataset.rhExcluir)))}
function serie(cab,linhas){$('rhSerieHead').innerHTML=`<tr>${cab.map(x=>`<th>${esc(x)}</th>`).join('')}</tr>`;$('rhSerie').innerHTML=linhas.map(row=>`<tr>${row.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${cab.length}">Sem meses no período.</td></tr>`}
function resumoPessoas(cab,linhas){$('rhPorPessoaHead').innerHTML=`<tr>${cab.map(x=>`<th>${esc(x)}</th>`).join('')}</tr>`;$('rhPorPessoa').innerHTML=linhas.map(row=>`<tr>${row.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${cab.length}">Sem registros.</td></tr>`}
function render(){if(!$('rhLista'))return;const periodo=intervalo(),{inicio,fim,valido,dataInicio,dataFim}=periodo,setor=$('rhSetor').value,id=$('rhFiltroPessoa').value;if(!valido){$('rhAviso').textContent='Escolha dias válidos dentro do mês selecionado.';$('rhAviso').classList.remove('hidden');return}$('rhAviso').classList.add('hidden');const pessoas=dados.pessoas.filter(p=>!setor||p.setor===setor),pessoasRel=id?pessoas.filter(p=>p.id===id):pessoas,ausencias=perm('ausencias','visualizar')||admin()?dados.ausencias:[],extras=perm('extras','visualizar')||admin()?dados.extras:[];const calcular=(col,aus,hrs,set='')=>resumoRHPeriodo(col,aus,hrs,dataInicio,dataFim,set);const rel=calcular(pessoasRel,ausencias,extras);const valores=tab==='pessoas'?[['Ativos no fim',rel.fechamento],['Admissões / demissões',`${rel.admissoes} / ${rel.demissoes}`],['Turnover (desligamentos / quadro médio)',pct(rel.turnover)],['Vínculos cadastrados',pessoas.filter(ativo).length]]:tab==='ausencias'?[['Horas ausentes',decimal(rel.horasAusentes)],['Horas previstas',decimal(rel.previstas)],['Absenteísmo',pct(rel.absenteismo)],['Ativos no fim',rel.fechamento]]:[['Horas 50%',decimal(rel.horas50)],['Horas 100%',decimal(rel.horas100)],['Total de horas',decimal(rel.horas50+rel.horas100)],['Ativos no fim',rel.fechamento]];valores.forEach(([l,v],i)=>{$('rhRotulo'+['A','B','C','D'][i]).textContent=l;$('rhValor'+['A','B','C','D'][i]).textContent=String(v)});
  const selecionados=new Set(pessoasRel.map(p=>p.id));const dentro=x=>x.data>=dataInicio&&x.data<=dataFim&&(!id||x.colaboradorId===id)&&(!setor||x.setor===setor);let registros=tab==='pessoas'?pessoas.filter(p=>!id||p.id===id):dados[tab].filter(x=>dentro(x)&&selecionados.has(x.colaboradorId));registros=[...registros].sort((a,b)=>String(b.data||b.admissao).localeCompare(String(a.data||a.admissao)));
  if(tab==='pessoas'){ $('rhTituloLista').textContent='Colaboradores e vínculos';$('rhNota').textContent='Os ativos são calculados das datas de cada vínculo; não há lançamento mensal isolado.';tabela(['Matrícula','Nome','Setor','Cargo','Cód. vendedor','Admissão','Demissão','Jornada mensal'],registros,x=>[x.codigo,x.nome,x.setor,x.cargoNome||cargosConfig().find(c=>c.id===x.cargoId)?.nome||'—',x.codigoVendedor||'—',dataBR(x.admissao),dataBR(x.demissao),decimal(x.jornadaMensalHoras)]);serie(['Mês','Abertura','Admissões','Demissões','Fechamento','Turnover'],rel.linhas.map(l=>[l.mes,l.abertura,l.admissoes,l.demissoes,l.fechamento,pct(l.turnover)]));$('rhPorPessoaBox').classList.add('hidden');$('rhPorSetorBox').classList.add('hidden')}
  else if(tab==='ausencias'){$('rhTituloLista').textContent='Ocorrências de ausência';$('rhNota').textContent='Somente horas e categoria operacional. Não registre diagnóstico nem CID.';tabela(['Data','Colaborador','Setor','Tipo','Horas'],registros,x=>[dataBR(x.data),nome(x.colaboradorId),x.setor,x.tipo,decimal(x.horas)]);serie(['Mês','Horas ausentes','Horas previstas','Absenteísmo'],rel.linhas.map(l=>[l.mes,decimal(l.horasAusentes),decimal(l.previstas),pct(l.absenteismo)]));$('rhPorPessoaBox').classList.remove('hidden');$('rhPorSetorBox').classList.remove('hidden');$('rhPorPessoaTitulo').textContent='Absenteísmo por colaborador';resumoPessoas(['Colaborador','Setor','Horas ausentes','Horas previstas','Taxa'],pessoasRel.filter(ativo).map(p=>{const v=calcular([p],ausencias,[]);return [p.nome,p.setor,decimal(v.horasAusentes),decimal(v.previstas),pct(v.absenteismo)]}).filter(row=>row[2]!=='0'));setorTabela('ausencias',pessoasRel,calcular,ausencias,extras)}
  else{$('rhTituloLista').textContent='Lançamentos de horas extras';$('rhNota').textContent='Cada lançamento identifica o colaborador e distingue 50% de 100%.';tabela(['Data','Colaborador','Setor','Horas 50%','Horas 100%'],registros,x=>[dataBR(x.data),nome(x.colaboradorId),x.setor,decimal(x.horas50),decimal(x.horas100)]);serie(['Mês','Horas 50%','Horas 100%','Total'],rel.linhas.map(l=>[l.mes,decimal(l.horas50),decimal(l.horas100),decimal(l.horas50+l.horas100)]));$('rhPorPessoaBox').classList.remove('hidden');$('rhPorSetorBox').classList.remove('hidden');$('rhPorPessoaTitulo').textContent='Horas por colaborador e setor';resumoPessoas(['Colaborador','Setor','Horas 50%','Horas 100%','Total'],pessoasRel.filter(ativo).map(p=>{const v=calcular([p],[],extras);return [p.nome,p.setor,decimal(v.horas50),decimal(v.horas100),decimal(v.horas50+v.horas100)]}).filter(row=>row[4]!=='0'));setorTabela('extras',pessoasRel,calcular,ausencias,extras)}
  renderGraficos({pessoas:pessoasRel,ausencias,extras,inicio:dataInicio,fim:dataFim,tabAtual:tab});window.dispatchEvent(new CustomEvent('sig:rh-kpis',{detail:{empresaId:empresa(),inicio:dataInicio,fim:dataFim,tab,rel}}));
}
function atualizarSetoresFiltro(){const s=$('rhSetor'),antes=s.value,lista=setoresConhecidos().sort((a,b)=>a.localeCompare(b,'pt-BR'));s.innerHTML='<option value="">Todos os setores</option>'+lista.map(x=>`<option>${esc(x)}</option>`).join('');if(lista.includes(antes))s.value=antes}
function atualizarFiltroPessoas(){const s=$('rhFiltroPessoa'),setor=$('rhSetor')?.value||'',antes=s.value,arr=dados.pessoas.filter(p=>ativo(p)&&(!setor||p.setor===setor)).sort((a,b)=>a.nome.localeCompare(b.nome,'pt-BR'));s.innerHTML=`<option value="">${setor?'Todos do setor':'Todos'}</option>`+arr.map(p=>`<option value="${esc(p.id)}">${esc(p.nome)} · ${esc(p.codigo)}</option>`).join('');if(arr.some(p=>p.id===antes))s.value=antes}
function barras(id,itens,{valor='valor',rotulo='rotulo',formata=v=>decimal(v),limite=8}={}){const host=$(id),arr=itens.slice(0,limite),max=Math.max(0,...arr.map(x=>Number(x[valor]||0)));host.innerHTML=arr.map(x=>`<div class="rh-bar-row"><div class="rh-bar-label"><strong>${esc(x[rotulo])}</strong><span>${esc(formata(Number(x[valor]||0)))}</span></div><div class="rh-bar-track"><i style="width:${max?Math.max(2,Number(x[valor]||0)/max*100):0}%"></i></div></div>`).join('')||'<div class="rh-empty">Sem dados no período.</div>'}
function renderGraficos({pessoas,ausencias,extras,inicio,fim,tabAtual}){
  const agrup=$('rhRankingAgrupamento')?.value||'colaborador';
  if(tabAtual==='ausencias'){
    const r=rankingAbsenteismo(pessoas,ausencias,inicio,fim,$('rhSetor').value);
    if(agrup==='setor'){
      const setores=[...new Set(pessoas.filter(ativo).map(p=>p.setor))].map(setor=>{const m=resumoRHPeriodo(pessoas,ausencias,[],inicio,fim,setor);const faltas=ausencias.filter(a=>ativo(a)&&a.data>=inicio&&a.data<=fim&&a.tipo==='FALTA'&&a.setor===setor).length;return{rotulo:setor,taxa:m.absenteismo,faltas}}).filter(x=>x.taxa>0||x.faltas>0).sort((a,b)=>b.taxa-a.taxa);
      $('rhGraficoTituloA').textContent='Absenteísmo por setor';$('rhGraficoNotaA').textContent='Índice = horas ausentes ÷ jornada prevista do setor.';barras('rhGraficoA',setores.map(x=>({rotulo:x.rotulo,valor:x.taxa})),{formata:v=>pct(v)});
      $('rhGraficoTituloB').textContent='Faltas por setor';$('rhGraficoNotaB').textContent='Ocorrências classificadas como FALTA.';barras('rhGraficoB',[...setores].sort((a,b)=>b.faltas-a.faltas).map(x=>({rotulo:x.rotulo,valor:x.faltas})),{formata:v=>String(v)});
    }else{
      $('rhGraficoTituloA').textContent='Ranking de absenteísmo por colaborador';$('rhGraficoNotaA').textContent='Índice = horas ausentes ÷ jornada prevista no período.';barras('rhGraficoA',r.map(x=>({rotulo:`${x.nome} · ${x.setor}`,valor:x.taxa})),{formata:v=>pct(v)});
      $('rhGraficoTituloB').textContent='Ranking de faltas por colaborador';$('rhGraficoNotaB').textContent='Quantidade de ocorrências classificadas como FALTA.';barras('rhGraficoB',[...r].sort((a,b)=>b.faltas-a.faltas).map(x=>({rotulo:`${x.nome} · ${x.setor}`,valor:x.faltas})),{formata:v=>String(v)});
    }
  }else if(tabAtual==='extras'){
    const r=rankingHorasExtras(pessoas,extras,inicio,fim,$('rhSetor').value);
    if(agrup==='setor'){
      const setores=[...new Set(pessoas.filter(ativo).map(p=>p.setor))].map(setor=>{const m=resumoRHPeriodo(pessoas,[],extras,inicio,fim,setor);return{rotulo:setor,h50:m.horas50,h100:m.horas100,total:m.horas50+m.horas100}}).filter(x=>x.total>0).sort((a,b)=>b.total-a.total);
      $('rhGraficoTituloA').textContent='Horas extras por setor';$('rhGraficoNotaA').textContent='Total de horas 50% + 100% por setor.';barras('rhGraficoA',setores.map(x=>({rotulo:x.rotulo,valor:x.total})));
      $('rhGraficoTituloB').textContent='Horas 100% por setor';$('rhGraficoNotaB').textContent='Concentração das horas com adicional de 100%.';barras('rhGraficoB',setores.map(x=>({rotulo:x.rotulo,valor:x.h100})));
    }else{
      $('rhGraficoTituloA').textContent='Horas extras por colaborador';$('rhGraficoNotaA').textContent='Total de horas 50% + 100%.';barras('rhGraficoA',r.map(x=>({rotulo:`${x.nome} · ${x.setor}`,valor:x.total})));
      $('rhGraficoTituloB').textContent='Horas 100% por colaborador';$('rhGraficoNotaB').textContent='Ranking das horas com adicional de 100%.';barras('rhGraficoB',r.map(x=>({rotulo:`${x.nome} · ${x.setor}`,valor:x.h100})));
    }
  }else{
    const r=turnoverPorSetor(pessoas,ausencias,extras,inicio,fim);$('rhGraficoTituloA').textContent='Turnover por setor';$('rhGraficoNotaA').textContent='Desligamentos ÷ quadro médio no período.';barras('rhGraficoA',r.map(x=>({rotulo:x.setor,valor:x.turnover})),{formata:v=>pct(v)});$('rhGraficoTituloB').textContent='Desligamentos por setor';$('rhGraficoNotaB').textContent='Volume absoluto de desligamentos.';barras('rhGraficoB',r.map(x=>({rotulo:x.setor,valor:x.demissoes})),{formata:v=>String(v)})
  }
}
async function abrirConfigRh(){
  const emp=empresa();if(!emp)return alert('Selecione apenas uma empresa no cabeçalho.');
  const cfg=await carregarConfiguracaoModulo('rh',emp),setores=Array.isArray(cfg.setores)&&cfg.setores.length?cfg.setores:SETORES_PADRAO;
  let cargos=Array.isArray(cfg.cargos)?cfg.cargos.map(c=>({...c,funcoesSistema:Array.isArray(c.funcoesSistema)?c.funcoesSistema:[]})):[];
  if(!cargos.length){
    try{
      const legados=await listarDocumentos('configuracoesModulos'),legado=legados.find(x=>x.modulo==='rhCargosCentral'&&x.empresaId===emp);
      if(Array.isArray(legado?.cargos))cargos=legado.cargos.map(c=>({...c,funcoesSistema:Array.isArray(c.funcoesSistema)?c.funcoesSistema:[]}));
    }catch{}
  }
  const extraHtml=`<div class="rh-config-block"><label style="display:block;font-weight:700;margin-bottom:6px">Setores ativos</label><p style="margin:0 0 8px;color:#667085;font-size:12px">Um setor por linha. Nomes existentes no histórico continuam visíveis mesmo após alteração.</p><textarea id="rhConfigSetores" style="width:100%;min-height:120px;border:1px solid #d0d5dd;border-radius:10px;padding:10px">${esc(setores.join('\n'))}</textarea></div>
  <div class="rh-config-block" style="margin-top:20px;border-top:1px solid #e5e7eb;padding-top:18px">
    <div style="display:flex;justify-content:space-between;gap:12px;align-items:end;flex-wrap:wrap"><div><strong>Cargos e funções do SIG</strong><p style="margin:4px 0 0;color:#667085;font-size:12px">Cadastre os cargos aqui e defina em quais módulos eles serão reconhecidos.</p></div></div>
    <div class="form-grid form-grid-2" style="margin-top:12px">
      <div class="campo"><label for="rhConfigCargoNome">Cargo</label><input id="rhConfigCargoNome" maxlength="80" placeholder="Ex.: Motorista de carreta"></div>
      <div class="campo"><label>Funções no SIG</label><div style="display:grid;gap:6px;padding-top:5px"><label><input type="checkbox" data-rh-cargo-funcao value="MOTORISTA"> Motorista / Frota</label><label><input type="checkbox" data-rh-cargo-funcao value="VENDEDOR"> Vendedor / Comercial</label><label><input type="checkbox" data-rh-cargo-funcao value="SUPERVISOR_VENDAS"> Supervisão comercial</label><label><input type="checkbox" data-rh-cargo-funcao value="PRODUCAO"> Produção / Indústria</label></div></div>
    </div>
    <div class="form-acoes" style="margin-top:8px"><button type="button" id="rhConfigCargoCancelarEdicao" class="btn-secundario hidden">Cancelar edição</button><button type="button" id="rhConfigCargoAdicionar" class="btn-primario">Adicionar cargo</button></div>
    <div id="rhConfigCargosLista" class="tabela-container" style="margin-top:14px"></div>
  </div>`;
  let cargosModal=cargos.map(c=>({...c})),editCargoId='';
  const modal=await abrirConfiguracaoModulo('rh',{
    titulo:'Configurações · RH',
    telas:{pessoas:'Tela Colaboradores e quadro',ausencias:'Tela Absenteísmo',extras:'Tela Horas extras',avaliacoes:'Tela Avaliações / feedback',acoes:'Tela Ações / Endomarketing'},
    extraHtml,
    coletarExtra:overlay=>{
      const setores=[...new Set(String(overlay.querySelector('#rhConfigSetores')?.value||'').split(/\r?\n/).map(x=>x.trim().toUpperCase()).filter(Boolean))];
      if(!setores.length)throw new Error('Cadastre ao menos um setor.');
      return{setores,cargos:cargosModal};
    },
    onSaved:novo=>{configRh=novo;atualizarSetoresFiltro();atualizarFiltroPessoas();trocar(tab)}
  });
  if(!modal)return;
  const nomeInput=modal.querySelector('#rhConfigCargoNome'),lista=modal.querySelector('#rhConfigCargosLista'),btn=modal.querySelector('#rhConfigCargoAdicionar'),cancelar=modal.querySelector('#rhConfigCargoCancelarEdicao');
  const funcoes=()=>[...modal.querySelectorAll('[data-rh-cargo-funcao]:checked')].map(x=>x.value);
  const limpar=()=>{editCargoId='';nomeInput.value='';modal.querySelectorAll('[data-rh-cargo-funcao]').forEach(x=>x.checked=false);btn.textContent='Adicionar cargo';cancelar.classList.add('hidden')};
  const renderCargos=()=>{
    lista.innerHTML=`<table class="tabela"><thead><tr><th>Cargo</th><th>Funções no SIG</th><th>Status</th><th>Ações</th></tr></thead><tbody>${cargosModal.map(c=>`<tr><td>${esc(c.nome)}</td><td>${esc((c.funcoesSistema||[]).join(', ')||'Sem função sistêmica')}</td><td>${c.ativo===false?'Inativo':'Ativo'}</td><td><button type="button" class="btn-acao" data-cargo-editar="${esc(c.id)}">Editar</button><button type="button" class="btn-acao" data-cargo-status="${esc(c.id)}">${c.ativo===false?'Reativar':'Inativar'}</button></td></tr>`).join('')||'<tr><td colspan="4">Nenhum cargo cadastrado.</td></tr>'}</tbody></table>`;
    lista.querySelectorAll('[data-cargo-editar]').forEach(b=>b.onclick=()=>{const c=cargosModal.find(x=>x.id===b.dataset.cargoEditar);if(!c)return;editCargoId=c.id;nomeInput.value=c.nome||'';modal.querySelectorAll('[data-rh-cargo-funcao]').forEach(x=>x.checked=(c.funcoesSistema||[]).includes(x.value));btn.textContent='Salvar cargo';cancelar.classList.remove('hidden');nomeInput.focus()});
    lista.querySelectorAll('[data-cargo-status]').forEach(b=>b.onclick=()=>{cargosModal=cargosModal.map(c=>c.id===b.dataset.cargoStatus?{...c,ativo:c.ativo===false}:c);if(editCargoId===b.dataset.cargoStatus)limpar();renderCargos()});
  };
  btn.onclick=()=>{
    const nome=String(nomeInput.value||'').trim().toUpperCase();if(!nome)return alert('Informe o nome do cargo.');
    if(cargosModal.some(c=>c.id!==editCargoId&&c.ativo!==false&&String(c.nome||'').trim().toUpperCase()===nome))return alert('Já existe um cargo ativo com esse nome.');
    if(editCargoId)cargosModal=cargosModal.map(c=>c.id===editCargoId?{...c,nome,funcoesSistema:funcoes()}:c);
    else cargosModal.push({id:globalThis.crypto?.randomUUID?.()||String(Date.now()),nome,funcoesSistema:funcoes(),ativo:true});
    limpar();renderCargos();
  };
  cancelar.onclick=limpar;renderCargos();
}
function setorTabela(k,pessoasRel,calcular,ausencias,extras){const setores=[...new Set(pessoasRel.filter(ativo).map(p=>p.setor))].sort();const colunas=k==='ausencias'?['Setor','Horas ausentes','Horas previstas','Absenteísmo']:['Setor','Horas 50%','Horas 100%','Total'];$('rhPorSetorHead').innerHTML='<tr>'+colunas.map(v=>`<th>${esc(v)}</th>`).join('')+'</tr>';$('rhPorSetor').innerHTML=setores.map(setor=>{const m=calcular(pessoasRel,ausencias,extras,setor);const col=k==='ausencias'?[setor,decimal(m.horasAusentes),decimal(m.previstas),pct(m.absenteismo)]:[setor,decimal(m.horas50),decimal(m.horas100),decimal(m.horas50+m.horas100)];return '<tr>'+col.map(v=>`<td>${esc(v)}</td>`).join('')+'</tr>'}).join('')||'<tr><td colspan="4">Nenhum setor no período.</td></tr>'}
async function carregar(){if(ocupado||!acesso())return;ocupado=true;try{configRh=await carregarConfiguracaoModulo('rh',empresa());if(configRh.ativo===false&&!admin()){ $('rhAviso').textContent='O módulo de RH está desativado nas configurações.';$('rhAviso').classList.remove('hidden');return }if(perm('pessoas','lancar')||perm('pessoas','editar')){const snap=await getDocs(query(collection(db,'usuarios'),where('grupoId','==',state.usuario.grupoId)));usuarios=snap.docs.map(d=>({id:d.id,...d.data()})).filter(u=>u.ativo===true)}const chaves=tab==='pessoas'?['pessoas']:['pessoas',tab];const pares=await Promise.all(chaves.map(async k=>[k,await listarDocumentos(COL[k])]));pares.forEach(([k,arr])=>dados[k]=arr);atualizarSetoresFiltro();atualizarFiltroPessoas();render()}catch(e){console.error(e);$('rhAviso').textContent=mensagemErroDados(e,'os dados de RH');$('rhAviso').classList.remove('hidden')}finally{ocupado=false}}
function instalar(){if(!document.querySelector('link[href^="production.css"]')){const l=document.createElement('link');l.rel='stylesheet';l.href='production.css?v=1';document.head.appendChild(l)}if(!document.querySelector('link[href^="rh.css"]')){const l=document.createElement('link');l.rel='stylesheet';l.href='rh.css?v=3';document.head.appendChild(l)}montar();menu();trocar(tab)}
instalar();window.addEventListener('sig:ready',()=>{instalar();if(acesso()&&!$('pagina-rh')?.classList.contains('hidden'))carregar()});window.addEventListener('sig:empresa-contexto',()=>{if(!$('pagina-rh')?.classList.contains('hidden'))carregar()});window.addEventListener('sig:periodo-changed',()=>{if($('rhDataInicioFiltro'))sincronizarPeriodo()});window.addEventListener('sig:data-changed',e=>{if(e.detail?.modulo==='rh'&&!$('pagina-rh')?.classList.contains('hidden'))carregar()});

window.addEventListener('sig:module-config',e=>{if(e.detail?.modulo==='rh'){configRh={...configRh,...e.detail.config};if(!$('pagina-rh')?.classList.contains('hidden'))carregar()}});
