import { collection, getDocs, query, where } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";
import { abrirPagina, admin } from './core.js';
import { $, db, esc, msg, permite, state, listarDocumentos, criarDocumento, atualizarDocumento, empresaUnicaSelecionadaId, emitirAlteracao } from './shared.js';
import { confirmarAcaoAdministrativa, atualizarComAuditoria } from './admin-actions.js';
import { resumoRH, mesDe, ativoNaData } from './hr-metrics.js';

const SETORES = ['ADM','LAJE','COMERCIAL','LOGISTICA','PRODUÇÃO','MOURÃO','MANUTENÇÃO'];
const COL = { pessoas:'rhColaboradores', ausencias:'rhAusencias', extras:'rhHorasColaboradores' };
const MOD = { pessoas:'rhColaboradores', ausencias:'rhAusencias', extras:'rhHorasColaboradores' };
const TIPOS = ['FALTA','ATESTADO','ATRASO','AFASTAMENTO','OUTROS'];
const perm = (k,a) => admin() || permite(MOD[k],a);
const acesso = () => perm('pessoas','visualizar') || perm('pessoas','lancar') || perm('pessoas','editar');
let dados = { pessoas:[], ausencias:[], extras:[] }, usuarios=[], tab='pessoas', editId='', ocupado=false;
const hoje = () => {const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const mesAtual = () => hoje().slice(0,7);
const decimal = v => Number(v||0).toLocaleString('pt-BR',{maximumFractionDigits:2});
const pct = v => `${decimal(v)}%`;
const dataBR = s => s ? String(s).slice(0,10).split('-').reverse().join('/') : '—';
const ativo = x => x.status !== 'estornado';
const pessoa = id => dados.pessoas.find(p => p.id === id && ativo(p));
const nome = id => pessoa(id)?.nome || 'Colaborador não encontrado';
const empresa = () => empresaUnicaSelecionadaId();
function montar(){
  if($('pagina-rh'))return;
  const main=document.querySelector('main.conteudo');if(!main)return;
  const s=document.createElement('section');s.id='pagina-rh';s.className='pagina hidden production-page';
  s.innerHTML=`<div class="pagina-cabecalho production-head"><div><span class="eyebrow">PESSOAS</span><h2>RH · Quadro e indicadores</h2><p>Admissões, demissões, ausências e horas extras por colaborador.</p></div><div class="acoes-cabecalho"><button id="rhNovo" class="btn-primario" type="button">+ Novo registro</button><button id="rhAtualizar" class="btn-secundario" type="button">Atualizar</button></div></div>
  <div id="rhAviso" class="modulo-aviso hidden"></div>
  <div class="fleet-tabs"><button class="fleet-tab" data-rh-tab="pessoas" type="button">Colaboradores e quadro</button><button class="fleet-tab" data-rh-tab="ausencias" type="button">Absenteísmo</button><button class="fleet-tab" data-rh-tab="extras" type="button">Horas extras</button></div>
  <section class="lista-card"><div class="lista-cabecalho production-toolbar"><div><h3>Período de análise</h3><p>Admissão e demissão contam na data informada. O quadro é calculado dos vínculos ativos.</p></div><div class="form-grid"><label>De <input id="rhInicio" type="month"></label><label>Até <input id="rhFim" type="month"></label><label>Setor <select id="rhSetor"><option value="">Todos</option>${SETORES.map(x=>`<option>${esc(x)}</option>`).join('')}</select></label><label>Colaborador <select id="rhFiltroPessoa"><option value="">Todos</option></select></label></div></div></section>
  <div class="production-kpis"><div class="kpi-card"><span id="rhRotuloA">Ativos no fim</span><strong id="rhValorA">—</strong></div><div class="kpi-card"><span id="rhRotuloB">Admissões / demissões</span><strong id="rhValorB">—</strong></div><div class="kpi-card"><span id="rhRotuloC">Turnover</span><strong id="rhValorC">—</strong></div><div class="kpi-card"><span id="rhRotuloD">Absenteísmo</span><strong id="rhValorD">—</strong></div></div>
  <section id="rhFormBox" class="form-card hidden"><div class="form-card-titulo"><h3 id="rhFormTitulo">Novo registro</h3></div><form id="rhForm"><div id="rhCampos" class="form-grid form-grid-3"></div><div class="form-acoes"><button id="rhCancelar" class="btn-secundario" type="button">Cancelar</button><button class="btn-primario" type="submit">Salvar</button></div><p id="rhMensagem" class="mensagem-form"></p></form></section>
  <section class="lista-card"><div class="lista-cabecalho"><div><h3 id="rhTituloLista">Colaboradores</h3><p id="rhNota">Cadastre quem já estava na empresa com a data real de admissão.</p></div></div><div class="tabela-container"><table class="tabela"><thead id="rhCabecalho"></thead><tbody id="rhLista"></tbody></table></div></section>
  <section id="rhSerieBox" class="lista-card"><div class="lista-cabecalho"><h3>Evolução mensal</h3></div><div class="tabela-container"><table class="tabela"><thead id="rhSerieHead"></thead><tbody id="rhSerie"></tbody></table></div></section>
  <section id="rhPorPessoaBox" class="lista-card"><div class="lista-cabecalho"><h3 id="rhPorPessoaTitulo">Por colaborador</h3></div><div class="tabela-container"><table class="tabela"><thead id="rhPorPessoaHead"></thead><tbody id="rhPorPessoa"></tbody></table></div></section><section id="rhPorSetorBox" class="lista-card hidden"><div class="lista-cabecalho"><h3>Total por setor</h3></div><div class="tabela-container"><table class="tabela"><thead id="rhPorSetorHead"></thead><tbody id="rhPorSetor"></tbody></table></div></section>`;
  main.appendChild(s);
  s.querySelectorAll('[data-rh-tab]').forEach(b=>b.addEventListener('click',()=>{trocar(b.dataset.rhTab);carregar()}));
  for(const id of ['rhInicio','rhFim','rhSetor','rhFiltroPessoa']) $(id).addEventListener('change',render);
  $('rhNovo').addEventListener('click',novo);$('rhAtualizar').addEventListener('click',carregar);
  $('rhCancelar').addEventListener('click',()=>{$('rhFormBox').classList.add('hidden');editId=''});
  $('rhForm').addEventListener('submit',salvar);
  $('rhInicio').value=`${new Date().getFullYear()}-01`;$('rhFim').value=mesAtual();trocar('pessoas');
}
function menu(){const nav=document.querySelector('.sidebar-menu');if(!nav)return;let b=$('menurh');if(!b){b=document.createElement('button');b.id='menurh';b.className='menu-item hidden';b.dataset.pagina='rh';b.type='button';b.textContent='RH';nav.appendChild(b);b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();if(!acesso())return;abrirPagina('rh');carregar()},true)}b.classList.toggle('hidden',!acesso())}
function trocar(k){if(k!=='pessoas'&&!perm(k,'visualizar')&&!perm(k,'lancar')&&!perm(k,'editar'))k='pessoas';tab=k;editId='';$('rhFormBox')?.classList.add('hidden');document.querySelectorAll('[data-rh-tab]').forEach(b=>{b.classList.toggle('ativo',b.dataset.rhTab===k);b.classList.toggle('hidden',b.dataset.rhTab!=='pessoas'&&!perm(b.dataset.rhTab,'visualizar')&&!perm(b.dataset.rhTab,'lancar')&&!perm(b.dataset.rhTab,'editar'))});$('rhNovo')?.classList.toggle('hidden',!perm(k,'lancar'));$('rhNovo').textContent=k==='pessoas'?'+ Admitir colaborador':'+ Novo registro';render()}
function opcoesPessoa(valor=''){const arr=dados.pessoas.filter(ativo).sort((a,b)=>a.nome.localeCompare(b.nome,'pt-BR'));const html='<option value="">Selecione...</option>'+arr.map(p=>`<option value="${esc(p.id)}">${esc(p.nome)} · ${esc(p.codigo)} · ${esc(p.setor)}</option>`).join('');const s=$('rhColaborador');if(s){s.innerHTML=html;s.value=valor}}
function campos(){if(tab==='pessoas')return `<div class="campo"><label for="rhCodigo">Matrícula / código interno</label><input id="rhCodigo" required maxlength="40"></div><div class="campo"><label for="rhNome">Nome</label><input id="rhNome" required maxlength="120"></div><div class="campo"><label for="rhSetorForm">Setor</label><select id="rhSetorForm" required><option value="">Selecione...</option>${SETORES.map(x=>`<option>${esc(x)}</option>`).join('')}</select></div><div class="campo"><label for="rhUsuario">Conta SIG (para Minha Mesa)</label><select id="rhUsuario"><option value="">Sem conta vinculada</option>${usuarios.filter(u=>u.empresaId===empresa()||u.acessoGlobal===true||(u.empresasAcesso||[]).includes(empresa())).map(u=>`<option value="${esc(u.id)}">${esc(u.nome||u.email||u.id)}</option>`).join('')}</select></div><div class="campo"><label for="rhAdmissao">Admissão</label><input id="rhAdmissao" type="date" required></div><div class="campo"><label for="rhDemissao">Demissão (quando ocorrer)</label><input id="rhDemissao" type="date"></div><div class="campo"><label for="rhJornada">Jornada prevista no mês (horas)</label><input id="rhJornada" type="number" min="1" max="300" step="0.01" required value="220"></div>`;
  const comum=`<div class="campo"><label for="rhColaborador">Colaborador</label><select id="rhColaborador" required></select></div><div class="campo"><label for="rhData">Data</label><input id="rhData" type="date" required></div>`;
  if(tab==='ausencias')return comum+`<div class="campo"><label for="rhTipo">Tipo</label><select id="rhTipo" required>${TIPOS.map(x=>`<option>${x}</option>`).join('')}</select></div><div class="campo"><label for="rhHoras">Horas ausentes</label><input id="rhHoras" type="number" min="0.01" max="300" step="0.01" required></div><div class="campo"><label for="rhObservacao">Observação operacional (sem dados médicos)</label><input id="rhObservacao" maxlength="200"></div>`;
  return comum+`<div class="campo"><label for="rhHoras50">Horas 50%</label><input id="rhHoras50" type="number" min="0" max="300" step="0.01" value="0" required></div><div class="campo"><label for="rhHoras100">Horas 100%</label><input id="rhHoras100" type="number" min="0" max="300" step="0.01" value="0" required></div>`;
}
function abrir(x=null){if(!empresa())return alert('Selecione apenas uma empresa no cabeçalho.');editId=x?.id||'';$('rhCampos').innerHTML=campos();$('rhForm').reset();$('rhFormTitulo').textContent=`${x?'Atualizar vínculo':'Admitir colaborador'} · ${tab==='pessoas'?'cadastro':tab==='ausencias'?'ausência':'horas extras'}`;msg($('rhMensagem'),'');if(tab==='pessoas'){$('rhCodigo').value=x?.codigo||'';$('rhNome').value=x?.nome||'';$('rhSetorForm').value=x?.setor||'';$('rhAdmissao').value=x?.admissao||'';$('rhDemissao').value=x?.demissao||'';$('rhUsuario').value=x?.usuarioId||'';$('rhJornada').value=x?.jornadaMensalHoras??220}else{opcoesPessoa(x?.colaboradorId);$('rhData').value=x?.data||hoje();if(tab==='ausencias'){$('rhTipo').value=x?.tipo||'FALTA';$('rhHoras').value=x?.horas??'';$('rhObservacao').value=x?.observacao||''}else{$('rhHoras50').value=x?.horas50??0;$('rhHoras100').value=x?.horas100??0}}$('rhFormBox').classList.remove('hidden');$('rhFormBox').scrollIntoView({behavior:'smooth',block:'start'})}
function novo(){if(perm(tab,'lancar'))abrir()}
function ler(){const texto=(id,max)=>String($(id).value||'').trim().slice(0,max);const valor=id=>Number($(id).value);if(tab==='pessoas'){const d={codigo:texto('rhCodigo',40).toUpperCase(),nome:texto('rhNome',120).toUpperCase(),setor:$('rhSetorForm').value,admissao:$('rhAdmissao').value,demissao:$('rhDemissao').value,jornadaMensalHoras:valor('rhJornada'),usuarioId:$('rhUsuario').value};if(!d.codigo||!d.nome||!SETORES.includes(d.setor)||!/^\d{4}-\d{2}-\d{2}$/.test(d.admissao)||d.demissao&&d.demissao<d.admissao||!Number.isFinite(d.jornadaMensalHoras)||d.jornadaMensalHoras<=0||d.jornadaMensalHoras>300)throw Error('Revise matrícula, nome, setor, datas e jornada.');if(d.usuarioId&&!usuarios.some(u=>u.id===d.usuarioId&&(u.empresaId===empresa()||u.acessoGlobal===true||(u.empresasAcesso||[]).includes(empresa()))))throw Error('Conta SIG inválida para a empresa.');if(dados.pessoas.some(p=>p.id!==editId&&ativo(p)&&p.empresaId===empresa()&&p.codigo===d.codigo&&(!p.demissao||p.demissao>=d.admissao)))throw Error('Esta matrícula já está em uso na empresa.');const eventos=[...dados.ausencias,...dados.extras].filter(x=>ativo(x)&&x.colaboradorId===editId);if(eventos.some(x=>x.data<d.admissao||d.demissao&&x.data>d.demissao))throw Error('As datas do vínculo conflitam com ausências ou horas extras já registradas.');return d}
  const colaboradorId=$('rhColaborador').value,p=pessoa(colaboradorId),data=$('rhData').value;if(!p||p.empresaId!==empresa()||!/^\d{4}-\d{2}-\d{2}$/.test(data)||!ativoNaData(p,data))throw Error('Escolha um colaborador ativo na data informada.');
  if(tab==='ausencias'){const horas=valor('rhHoras'),tipo=$('rhTipo').value;if(!TIPOS.includes(tipo)||!Number.isFinite(horas)||horas<=0||horas>300)throw Error('Informe tipo e horas ausentes válidas.');return {colaboradorId,data,setor:p.setor,tipo,horas,observacao:texto('rhObservacao',200)}}
  const horas50=valor('rhHoras50'),horas100=valor('rhHoras100');if(!Number.isFinite(horas50)||!Number.isFinite(horas100)||horas50<0||horas100<0||horas50+horas100<=0||horas50+horas100>300)throw Error('Informe horas 50% e/ou 100% válidas.');return {colaboradorId,data,setor:p.setor,horas50,horas100};
}
async function salvar(e){e.preventDefault();if(ocupado)return;const emp=empresa();if(!emp)return alert('Selecione apenas uma empresa no cabeçalho.');try{if(tab==='pessoas'&&editId){[dados.ausencias,dados.extras]=await Promise.all([listarDocumentos(COL.ausencias),listarDocumentos(COL.extras)])}const d=ler(),id=editId;ocupado=true;msg($('rhMensagem'),'Salvando...');if(id){const original=dados[tab].find(x=>x.id===id);if(!original||!ativo(original)||original.empresaId!==emp||!perm(tab,'editar'))throw Error('Edição não autorizada.');await atualizarDocumento(COL[tab],id,d)}else{if(!perm(tab,'lancar'))throw Error('Sem permissão para registrar.');await criarDocumento(COL[tab],{...d,empresaId:emp,status:'ativo',registradoPor:state.usuario.id,origem:'sig'})}$('rhFormBox').classList.add('hidden');editId='';emitirAlteracao('rh');ocupado=false;await carregar()}catch(err){console.error(err);msg($('rhMensagem'),err.message||'Não foi possível salvar.')}finally{ocupado=false}}
function editar(id){const x=dados[tab].find(v=>v.id===id);if(!x||!perm(tab,'editar')||!ativo(x))return;if(x.empresaId!==empresa())return alert('Selecione a empresa do registro.');abrir(x)}
async function estornar(id){if(!admin())return;const x=dados[tab].find(v=>v.id===id);if(!x||!ativo(x))return;if(tab==='pessoas'&&[...dados.ausencias,...dados.extras].some(v=>ativo(v)&&v.colaboradorId===id))return alert('Este colaborador possui lançamentos. Estorne os registros vinculados antes.');const ok=await confirmarAcaoAdministrativa({titulo:'Estornar registro de RH',descricao:'O registro permanecerá no histórico, fora dos indicadores.',motivoLabel:'Motivo obrigatório',confirmarTexto:'Estornar',perigosa:true});if(!ok)return;try{await atualizarComAuditoria({colecao:COL[tab],id,empresaId:x.empresaId,modulo:MOD[tab],acao:'estorno',motivo:ok.motivo,resumo:`Estorno RH · ${tab}`,snapshotAntes:x,alteracoes:{status:'estornado',motivoEstorno:ok.motivo,estornadoPor:state.usuario.id,estornadoEm:new Date().toISOString()}});emitirAlteracao('rh');await carregar()}catch(e){console.error(e);alert('Não foi possível estornar.')}}
function tabela(cab,linhas,cols){$('rhCabecalho').innerHTML=`<tr>${cab.map(x=>`<th>${esc(x)}</th>`).join('')}<th>Situação / ações</th></tr>`;$('rhLista').innerHTML=linhas.map(x=>`<tr class="${ativo(x)?'':'sig-admin-estornado'}">${cols(x).map(v=>`<td>${esc(v)}</td>`).join('')}<td>${ativo(x)?'Ativo':'Estornado'} ${ativo(x)&&perm(tab,'editar')?`<button type="button" class="btn-acao destaque" data-rh-edit="${esc(x.id)}">Editar</button>`:''}${ativo(x)&&tab==='pessoas'&&!x.demissao&&perm('pessoas','editar')?`<button type="button" class="btn-acao destaque" data-rh-demissao="${esc(x.id)}">Registrar demissão</button>`:''}${ativo(x)&&admin()?`<button type="button" class="btn-acao perigo" data-rh-estorno="${esc(x.id)}">Estornar ADM</button>`:''}</td></tr>`).join('')||`<tr><td colspan="${cab.length+1}">Nenhum registro no período.</td></tr>`;document.querySelectorAll('[data-rh-edit]').forEach(b=>b.addEventListener('click',()=>editar(b.dataset.rhEdit)));document.querySelectorAll('[data-rh-demissao]').forEach(b=>b.addEventListener('click',()=>{editar(b.dataset.rhDemissao);$('rhDemissao').focus()}));document.querySelectorAll('[data-rh-estorno]').forEach(b=>b.addEventListener('click',()=>estornar(b.dataset.rhEstorno)))}
function serie(cab,linhas){$('rhSerieHead').innerHTML=`<tr>${cab.map(x=>`<th>${esc(x)}</th>`).join('')}</tr>`;$('rhSerie').innerHTML=linhas.map(row=>`<tr>${row.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${cab.length}">Sem meses no período.</td></tr>`}
function resumoPessoas(cab,linhas){$('rhPorPessoaHead').innerHTML=`<tr>${cab.map(x=>`<th>${esc(x)}</th>`).join('')}</tr>`;$('rhPorPessoa').innerHTML=linhas.map(row=>`<tr>${row.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${cab.length}">Sem registros.</td></tr>`}
function render(){if(!$('rhLista'))return;const inicio=$('rhInicio').value,fim=$('rhFim').value,setor=$('rhSetor').value,id=$('rhFiltroPessoa').value;const valido=/^\d{4}-\d{2}$/.test(inicio)&&/^\d{4}-\d{2}$/.test(fim)&&inicio<=fim;if(!valido){$('rhAviso').textContent='Escolha um período válido.';$('rhAviso').classList.remove('hidden');return}$('rhAviso').classList.add('hidden');const pessoas=dados.pessoas.filter(p=>!setor||p.setor===setor),pessoasRel=id?pessoas.filter(p=>p.id===id):pessoas,ausencias=perm('ausencias','visualizar')||admin()?dados.ausencias:[],extras=perm('extras','visualizar')||admin()?dados.extras:[];const rel=resumoRH(pessoasRel,ausencias,extras,inicio,fim);const valores=tab==='pessoas'?[['Ativos no fim',rel.fechamento],['Admissões / demissões',`${rel.admissoes} / ${rel.demissoes}`],['Turnover (desligamentos / quadro médio)',pct(rel.turnover)],['Vínculos cadastrados',pessoas.filter(ativo).length]]:tab==='ausencias'?[['Horas ausentes',decimal(rel.horasAusentes)],['Horas previstas',decimal(rel.previstas)],['Absenteísmo',pct(rel.absenteismo)],['Ativos no fim',rel.fechamento]]:[['Horas 50%',decimal(rel.horas50)],['Horas 100%',decimal(rel.horas100)],['Total de horas',decimal(rel.horas50+rel.horas100)],['Ativos no fim',rel.fechamento]];valores.forEach(([l,v],i)=>{$('rhRotulo'+['A','B','C','D'][i]).textContent=l;$('rhValor'+['A','B','C','D'][i]).textContent=String(v)});
  const selecionados=new Set(pessoasRel.map(p=>p.id));const dentro=x=>mesDe(x.data)>=inicio&&mesDe(x.data)<=fim&&(!id||x.colaboradorId===id)&&(!setor||x.setor===setor);let registros=tab==='pessoas'?pessoas.filter(p=>!id||p.id===id):dados[tab].filter(x=>dentro(x)&&selecionados.has(x.colaboradorId));registros=[...registros].sort((a,b)=>String(b.data||b.admissao).localeCompare(String(a.data||a.admissao)));
  if(tab==='pessoas'){ $('rhTituloLista').textContent='Colaboradores e vínculos';$('rhNota').textContent='Os ativos são calculados das datas de cada vínculo; não há lançamento mensal isolado.';tabela(['Matrícula','Nome','Setor','Admissão','Demissão','Jornada mensal'],registros,x=>[x.codigo,x.nome,x.setor,dataBR(x.admissao),dataBR(x.demissao),decimal(x.jornadaMensalHoras)]);serie(['Mês','Abertura','Admissões','Demissões','Fechamento','Turnover'],rel.linhas.map(l=>[l.mes,l.abertura,l.admissoes,l.demissoes,l.fechamento,pct(l.turnover)]));$('rhPorPessoaBox').classList.add('hidden');$('rhPorSetorBox').classList.add('hidden')}
  else if(tab==='ausencias'){$('rhTituloLista').textContent='Ocorrências de ausência';$('rhNota').textContent='Somente horas e categoria operacional. Não registre diagnóstico nem CID.';tabela(['Data','Colaborador','Setor','Tipo','Horas'],registros,x=>[dataBR(x.data),nome(x.colaboradorId),x.setor,x.tipo,decimal(x.horas)]);serie(['Mês','Horas ausentes','Horas previstas','Absenteísmo'],rel.linhas.map(l=>[l.mes,decimal(l.horasAusentes),decimal(l.previstas),pct(l.absenteismo)]));$('rhPorPessoaBox').classList.remove('hidden');$('rhPorSetorBox').classList.remove('hidden');$('rhPorPessoaTitulo').textContent='Absenteísmo por colaborador';resumoPessoas(['Colaborador','Setor','Horas ausentes','Horas previstas','Taxa'],pessoasRel.filter(ativo).map(p=>{const v=resumoRH([p],ausencias,[],inicio,fim);return [p.nome,p.setor,decimal(v.horasAusentes),decimal(v.previstas),pct(v.absenteismo)]}).filter(row=>row[2]!=='0'));setorTabela('ausencias',pessoasRel,ausencias,extras,inicio,fim)}
  else{$('rhTituloLista').textContent='Lançamentos de horas extras';$('rhNota').textContent='Cada lançamento identifica o colaborador e distingue 50% de 100%.';tabela(['Data','Colaborador','Setor','Horas 50%','Horas 100%'],registros,x=>[dataBR(x.data),nome(x.colaboradorId),x.setor,decimal(x.horas50),decimal(x.horas100)]);serie(['Mês','Horas 50%','Horas 100%','Total'],rel.linhas.map(l=>[l.mes,decimal(l.horas50),decimal(l.horas100),decimal(l.horas50+l.horas100)]));$('rhPorPessoaBox').classList.remove('hidden');$('rhPorSetorBox').classList.remove('hidden');$('rhPorPessoaTitulo').textContent='Horas por colaborador e setor';resumoPessoas(['Colaborador','Setor','Horas 50%','Horas 100%','Total'],pessoasRel.filter(ativo).map(p=>{const v=resumoRH([p],[],extras,inicio,fim);return [p.nome,p.setor,decimal(v.horas50),decimal(v.horas100),decimal(v.horas50+v.horas100)]}).filter(row=>row[4]!=='0'));setorTabela('extras',pessoasRel,ausencias,extras,inicio,fim)}
}
function setorTabela(k,pessoasRel,ausencias,extras,inicio,fim){const setores=[...new Set(pessoasRel.filter(ativo).map(p=>p.setor))].sort();const colunas=k==='ausencias'?['Setor','Horas ausentes','Horas previstas','Absenteísmo']:['Setor','Horas 50%','Horas 100%','Total'];$('rhPorSetorHead').innerHTML='<tr>'+colunas.map(v=>`<th>${esc(v)}</th>`).join('')+'</tr>';$('rhPorSetor').innerHTML=setores.map(setor=>{const m=resumoRH(pessoasRel,ausencias,extras,inicio,fim,setor);const col=k==='ausencias'?[setor,decimal(m.horasAusentes),decimal(m.previstas),pct(m.absenteismo)]:[setor,decimal(m.horas50),decimal(m.horas100),decimal(m.horas50+m.horas100)];return '<tr>'+col.map(v=>`<td>${esc(v)}</td>`).join('')+'</tr>'}).join('')||'<tr><td colspan="4">Nenhum setor no período.</td></tr>'}
async function carregar(){if(ocupado||!acesso())return;ocupado=true;try{if(perm('pessoas','lancar')||perm('pessoas','editar')){const snap=await getDocs(query(collection(db,'usuarios'),where('grupoId','==',state.usuario.grupoId)));usuarios=snap.docs.map(d=>({id:d.id,...d.data()})).filter(u=>u.ativo===true)}const chaves=tab==='pessoas'?['pessoas']:['pessoas',tab];const pares=await Promise.all(chaves.map(async k=>[k,await listarDocumentos(COL[k])]));pares.forEach(([k,arr])=>dados[k]=arr);const sel=$('rhFiltroPessoa'),antes=sel.value;sel.innerHTML='<option value="">Todos</option>'+dados.pessoas.filter(ativo).sort((a,b)=>a.nome.localeCompare(b.nome,'pt-BR')).map(p=>`<option value="${esc(p.id)}">${esc(p.nome)} · ${esc(p.codigo)}</option>`).join('');sel.value=antes;render()}catch(e){console.error(e);$('rhAviso').textContent='Não foi possível carregar os dados de RH. Confira o perfil e as Rules publicadas.';$('rhAviso').classList.remove('hidden')}finally{ocupado=false}}
function instalar(){if(!document.querySelector('link[href^="production.css"]')){const l=document.createElement('link');l.rel='stylesheet';l.href='production.css?v=1';document.head.appendChild(l)}montar();menu();trocar(tab)}
instalar();window.addEventListener('sig:ready',()=>{instalar();if(acesso()&&!$('pagina-rh')?.classList.contains('hidden'))carregar()});window.addEventListener('sig:empresa-contexto',()=>{if(!$('pagina-rh')?.classList.contains('hidden'))carregar()});window.addEventListener('sig:data-changed',e=>{if(e.detail?.modulo==='rh'&&!$('pagina-rh')?.classList.contains('hidden'))carregar()});
