import { $, on, esc, norm, msg, permite, state, moeda, numero, preencherEmpresaSelect, nomeEmpresa, listarDocumentos, criarDocumento, atualizarDocumento, excluirDocumento, emitirAlteracao, abrirBox, fecharBox, confirmar, movimentarSaldoItem } from "./shared.js";
let itens=[],movimentos=[],editId=null;
const box=$("formItemContainer"),form=$("formItem"),titulo=$("tituloFormItem"),mensagem=$("mensagemItem"),lista=$("listaItens"),busca=$("buscaItem"),qtd=$("quantidadeItens"),empresa=$("itemEmpresa"),codigo=$("itemCodigo"),descricao=$("itemDescricao"),unidade=$("itemUnidade"),local=$("itemLocal"),custo=$("itemCusto"),saldo=$("itemSaldo"),minimo=$("itemMinimo"),status=$("itemStatus"),movBox=$("formMovimentoContainer"),movForm=$("formMovimento"),movItem=$("movimentoItem"),movTipo=$("movimentoTipo"),movQtd=$("movimentoQuantidade"),movObs=$("movimentoObservacao"),movMensagem=$("mensagemMovimento");
function limpar(){editId=null;form?.reset();saldo.disabled=false;if(titulo)titulo.textContent="Novo item";msg(mensagem,"")}
async function abrir(item=null){limpar();await preencherEmpresaSelect(empresa,{valorAtual:item?.empresaId||state.usuario?.empresaId});if(item){editId=item.id;titulo.textContent="Editar item";empresa.value=item.empresaId||"";codigo.value=item.codigo||"";descricao.value=item.descricao||"";unidade.value=item.unidade||"UN";local.value=item.local||"";custo.value=Number(item.custoMedio||0);saldo.value=Number(item.estoqueAtual||0);minimo.value=Number(item.estoqueMinimo||0);status.value=item.status||"ativo";saldo.disabled=!permite("almoxarifado","ajustar")}abrirBox(box,descricao);box?.scrollIntoView({behavior:"smooth",block:"start"})}
function critico(x){return x.status!=="inativo"&&Number(x.estoqueAtual||0)<=Number(x.estoqueMinimo||0)}
function render(f=""){const t=norm(f),arr=itens.filter(x=>!t||[x.codigo,x.descricao,x.local].some(v=>norm(v).includes(t))).sort((a,b)=>String(a.descricao||"").localeCompare(String(b.descricao||""),"pt-BR"));$("estoqueItens").textContent=itens.filter(x=>x.status!=="inativo").length;$("estoqueCritico").textContent=itens.filter(critico).length;$("estoqueValor").textContent=moeda(itens.reduce((s,x)=>s+Number(x.estoqueAtual||0)*Number(x.custoMedio||0),0));const comp=new Date().toISOString().slice(0,7);$("estoqueMovimentosMes").textContent=movimentos.filter(x=>{const d=x.criadoEm?.toDate?.();return d?d.toISOString().slice(0,7)===comp:true}).length;if(qtd)qtd.textContent=`${itens.length} item(ns) cadastrado(s)`;if(!lista)return;if(!arr.length){lista.innerHTML='<tr><td colspan="6">Nenhum item encontrado.</td></tr>';return}lista.innerHTML=arr.map(x=>`<tr class="${critico(x)?"linha-critica":""}"><td class="celula-principal"><strong>${esc(x.descricao)}</strong><span>${esc(x.codigo)} · ${esc(nomeEmpresa(x.empresaId))}</span></td><td>${esc(x.local||"-")}</td><td class="${critico(x)?"saldo-critico":""}">${numero(x.estoqueAtual)} ${esc(x.unidade||"UN")}</td><td>${numero(x.estoqueMinimo)} ${esc(x.unidade||"UN")}</td><td>${moeda(x.custoMedio)}</td><td><div class="acoes-tabela">${permite("almoxarifado","editar")?`<button class="btn-acao destaque" data-est-edit="${x.id}" type="button">Editar</button>`:""}${permite("almoxarifado","movimentar")?`<button class="btn-acao" data-est-mov="${x.id}" type="button">Movimentar</button>`:""}</div></td></tr>`).join("");document.querySelectorAll("[data-est-edit]").forEach(b=>on(b,"click",()=>abrir(itens.find(x=>x.id===b.dataset.estEdit))));document.querySelectorAll("[data-est-mov]").forEach(b=>on(b,"click",()=>abrirMovimento(b.dataset.estMov)))}
function preencherMovimentos(itemId=""){movItem.innerHTML='<option value="">Selecione...</option>'+itens.filter(x=>x.status!=="inativo").sort((a,b)=>String(a.descricao||"").localeCompare(String(b.descricao||""),"pt-BR")).map(x=>`<option value="${x.id}">${esc(x.codigo)} · ${esc(x.descricao)} (${numero(x.estoqueAtual)} ${esc(x.unidade||"UN")})</option>`).join("");if(itemId)movItem.value=itemId}
function abrirMovimento(itemId=""){movForm?.reset();msg(movMensagem,"");preencherMovimentos(itemId);abrirBox(movBox,movItem);movBox?.scrollIntoView({behavior:"smooth",block:"start"})}
export async function carregarEstoque(){if(!permite("almoxarifado"))return;try{await preencherEmpresaSelect(empresa);[itens,movimentos]=await Promise.all([listarDocumentos("itensAlmoxarifado"),listarDocumentos("movimentacoesEstoque")]);preencherMovimentos();render(busca?.value||"")}catch(e){console.error(e);if(lista)lista.innerHTML='<tr><td colspan="6">Não foi possível carregar o estoque.</td></tr>'}}
on($("btnNovoItem"),"click",()=>abrir());on($("btnCancelarItem"),"click",()=>{limpar();box?.classList.add("hidden")});on($("btnMovimentarEstoque"),"click",()=>abrirMovimento());on($("btnCancelarMovimento"),"click",()=>fecharBox(movBox,movForm,movMensagem));on(busca,"input",()=>render(busca.value));
on(form,"submit",async ev=>{ev.preventDefault();const atual=itens.find(x=>x.id===editId);const d={empresaId:empresa.value,codigo:codigo.value.trim(),descricao:descricao.value.trim(),unidade:unidade.value,local:local.value.trim(),custoMedio:Number(custo.value||0),estoqueAtual:editId&&!permite("almoxarifado","ajustar")?Number(atual?.estoqueAtual||0):Number(saldo.value||0),estoqueMinimo:Number(minimo.value||0),status:status.value};if(!d.empresaId||!d.codigo||!d.descricao)return msg(mensagem,"Informe empresa, código e descrição.");if(itens.some(x=>x.id!==editId&&x.empresaId===d.empresaId&&norm(x.codigo)===norm(d.codigo)))return msg(mensagem,"Já existe um item com este código nesta empresa.");try{msg(mensagem,"Salvando...");if(editId)await atualizarDocumento("itensAlmoxarifado",editId,d);else await criarDocumento("itensAlmoxarifado",d);msg(mensagem,"Item salvo com sucesso.",true);await carregarEstoque();emitirAlteracao("almoxarifado");setTimeout(()=>fecharBox(box,form,mensagem),500)}catch(e){console.error(e);msg(mensagem,"Não foi possível salvar o item.")}});
on(movForm,"submit",async ev=>{ev.preventDefault();if(!movItem.value)return msg(movMensagem,"Selecione o item.");try{msg(movMensagem,"Atualizando saldo...");await movimentarSaldoItem({itemId:movItem.value,tipo:movTipo.value,quantidade:movQtd.value,observacao:movObs.value.trim()});msg(movMensagem,"Movimentação registrada.",true);await carregarEstoque();emitirAlteracao("almoxarifado");setTimeout(()=>fecharBox(movBox,movForm,movMensagem),500)}catch(e){console.error(e);const m={"saldo-insuficiente":"Saldo insuficiente para esta saída.","quantidade-invalida":"Informe uma quantidade válida.","sem-acesso":"Você não tem acesso a este item."};msg(movMensagem,m[e.message]||"Não foi possível registrar a movimentação.")}});
window.addEventListener("sig:page",e=>{if(e.detail?.pagina==="almoxarifado")carregarEstoque()});
