import { collection, getDocs, query, where } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";
import { $, on, esc, msg, state, db, permite, abrirPagina } from "./core.js";
import { moeda, dataBr, diasAte, empresaAtualId, empresasSelecionadasIds, listarDocumentos, criarDocumento, atualizarDocumento, emitirAlteracao } from "./shared.js";

let planos=[],usuarios=[],excecoes=[],busy=false;
const hoje=()=>new Date().toISOString().slice(0,10);
const addDias=(iso,dias)=>{const [a,m,d]=iso.split("-").map(Number),x=new Date(Date.UTC(a,m-1,d));x.setUTCDate(x.getUTCDate()+dias);return x.toISOString().slice(0,10)};
const n=v=>{const x=Number(v||0);return Number.isFinite(x)?x:0};
const critPeso={critica:4,alta:3,media:2,baixa:1};
const paginaPorOrigem={contratos:"contratos",cotacoes:"cotacoes",frota:"frota",almoxarifado:"almoxarifado",controladoria:"controladoria",governanca:"governanca",prestadores:"prestadores"};

function montar(){
  if($("pagina-minhamesa"))return;
  const sep=document.querySelector(".sidebar-menu .menu-separador"),dash=$("menuDashboard");
  if(sep&&!$("menuMinhaMesa")){
    const b=document.createElement("button");b.id="menuMinhaMesa";b.className="menu-item";b.dataset.pagina="minhamesa";b.type="button";b.textContent="Minha Mesa";
    if(dash)dash.before(b);else sep.before(b);
    on(b,"click",()=>{abrirPagina("minhamesa");carregar()});
  }
  const main=document.querySelector("main.conteudo");if(!main)return;
  const p=document.createElement("section");p.id="pagina-minhamesa";p.className="pagina hidden";p.innerHTML=`
    <div class="welcome mesa-hero"><div><span class="eyebrow">EXECUÇÃO</span><h2 id="mesaSaudacao">Minha Mesa</h2><p>Prioridades, exceções, aprovações e planos de ação que precisam de atenção.</p></div><div class="mesa-hero-actions"><button id="btnAtualizarMesa" class="btn-secundario" type="button">Atualizar</button><button id="btnNovoPlanoAcao" class="btn-primario" type="button">+ Plano de ação</button></div></div>
    <div class="kpi-grid kpi-grid-4 mesa-kpis"><div class="kpi-card"><span>Precisam de atenção</span><strong id="mesaQtdExcecoes">—</strong><small>exceções automáticas</small></div><div class="kpi-card"><span>Minhas ações abertas</span><strong id="mesaQtdAcoes">—</strong><small>atribuídas a você</small></div><div class="kpi-card"><span>Ações vencidas</span><strong id="mesaQtdVencidas">—</strong><small>prazo ultrapassado</small></div><div class="kpi-card"><span>Aprovações pendentes</span><strong id="mesaQtdAprovacoes">—</strong><small>cotações aguardando decisão</small></div></div>
    <div class="mesa-grid">
      <section class="lista-card"><div class="lista-cabecalho"><div><h3>Atenção agora</h3><p>Exceções geradas automaticamente pelos módulos aos quais você tem acesso.</p></div><select id="mesaFiltroCriticidade" class="campo-busca"><option value="">Todas</option><option value="critica">Críticas</option><option value="alta">Altas</option><option value="media">Médias</option></select></div><div id="mesaExcecoes" class="mesa-lista"><div class="empty-state">Carregando...</div></div></section>
      <section class="lista-card"><div class="lista-cabecalho"><div><h3>Meus planos de ação</h3><p>Responsabilidades, prazos e andamento.</p></div><select id="mesaFiltroAcoes" class="campo-busca"><option value="abertas">Abertas</option><option value="vencidas">Vencidas</option><option value="concluidas">Concluídas</option><option value="todas">Todas</option></select></div><div id="mesaPlanos" class="mesa-lista"><div class="empty-state">Carregando...</div></div></section>
    </div>
    <section id="mesaTodosPlanosCard" class="lista-card hidden"><div class="lista-cabecalho"><div><h3>Planos de ação da empresa</h3><p>Visão gerencial das ações em andamento.</p></div></div><div id="mesaTodosPlanos" class="mesa-lista"></div></section>
    <section id="formPlanoAcaoContainer" class="form-card hidden"><div class="form-card-titulo"><div><h3 id="tituloPlanoAcao">Novo plano de ação</h3><p id="subPlanoAcao">Transforme uma exceção em responsabilidade com prazo.</p></div></div><form id="formPlanoAcao"><div class="form-grid form-grid-3"><div class="campo campo-span-2"><label for="planoTitulo">Ação</label><input id="planoTitulo" required placeholder="Ex.: renegociar contrato de manutenção"></div><div class="campo"><label for="planoCriticidade">Criticidade</label><select id="planoCriticidade"><option value="media">Média</option><option value="alta">Alta</option><option value="critica">Crítica</option><option value="baixa">Baixa</option></select></div><div class="campo"><label for="planoResponsavel">Responsável</label><select id="planoResponsavel"></select></div><div class="campo"><label for="planoPrazo">Prazo</label><input id="planoPrazo" type="date" required></div><div class="campo"><label for="planoStatus">Status</label><select id="planoStatus"><option value="aberto">Aberto</option><option value="em_andamento">Em andamento</option><option value="concluido">Concluído</option><option value="cancelado">Cancelado</option></select></div><div class="campo campo-span-3"><label for="planoDescricao">Descrição / resultado esperado</label><textarea id="planoDescricao" rows="3"></textarea></div><input id="planoOrigemModulo" type="hidden"><input id="planoOrigemId" type="hidden"></div><div class="form-acoes"><button id="btnCancelarPlano" class="btn-secundario" type="button">Cancelar</button><button class="btn-primario" type="submit">Salvar plano</button></div><p id="mensagemPlanoAcao" class="mensagem-form"></p></form></section>`;
  const dashPage=$("pagina-dashboard");if(dashPage)main.insertBefore(p,dashPage);else main.prepend(p);
  const st=document.createElement("style");st.id="sig-minha-mesa-css";st.textContent=`
.mesa-hero{display:flex;justify-content:space-between;gap:16px;align-items:center}.mesa-hero-actions{display:flex;gap:8px;flex-wrap:wrap}.mesa-grid{display:grid;grid-template-columns:1.15fr .85fr;gap:14px;margin-top:14px}.mesa-lista{display:grid;gap:8px}.mesa-item{border:1px solid #e4e7ec;border-radius:11px;padding:11px;background:#fff;display:grid;grid-template-columns:auto 1fr auto;gap:10px;align-items:start}.mesa-item:hover{border-color:#b7d9d5}.mesa-bolinha{width:9px;height:9px;border-radius:50%;margin-top:5px;background:#98a2b3}.mesa-bolinha.critica{background:#d92d20}.mesa-bolinha.alta{background:#f79009}.mesa-bolinha.media{background:#fdb022}.mesa-bolinha.baixa{background:#12b76a}.mesa-info strong{display:block;color:#0b1f33}.mesa-info span{display:block;color:#667085;font-size:11px;margin-top:3px}.mesa-info small{display:block;color:#98a2b3;font-size:9px;margin-top:5px}.mesa-acoes{display:flex;gap:6px;flex-wrap:wrap;justify-content:flex-end}.mesa-prazo.vencido{color:#b42318;font-weight:850}.mesa-prazo.hoje{color:#b54708;font-weight:850}.mesa-tag{display:inline-flex;padding:3px 7px;border-radius:999px;background:#eef3f5;color:#475467;font-size:8px;font-weight:850;text-transform:uppercase;letter-spacing:.04em}.mesa-progresso{height:5px;background:#eef2f4;border-radius:999px;overflow:hidden;margin-top:7px}.mesa-progresso>i{display:block;height:100%;background:#0c9488}.mesa-empty{padding:18px;color:#667085;text-align:center}.mesa-item.concluido{opacity:.62}.mesa-item.concluido .mesa-info strong{text-decoration:line-through}@media(max-width:900px){.mesa-grid{grid-template-columns:1fr}.mesa-hero{align-items:flex-start;flex-direction:column}.mesa-item{grid-template-columns:auto 1fr}.mesa-acoes{grid-column:2;justify-content:flex-start}}
  `;document.head.appendChild(st);
  on($("btnAtualizarMesa"),"click",carregar);on($("btnNovoPlanoAcao"),"click",()=>abrirPlano());on($("btnCancelarPlano"),"click",fecharPlano);on($("formPlanoAcao"),"submit",salvarPlano);on($("mesaFiltroCriticidade"),"change",renderExcecoes);on($("mesaFiltroAcoes"),"change",renderPlanos);
}

async function carregarUsuarios(){
  if(!(permite("usuarios","visualizar")||permite("planosAcao","reatribuir"))){usuarios=[{id:state.usuario.id,nome:state.usuario.nome||state.usuario.email||"Eu"}];return}
  try{const s=await getDocs(query(collection(db,"usuarios"),where("grupoId","==",state.usuario.grupoId)));usuarios=[];s.forEach(r=>{const d=r.data();if(d.ativo===true)usuarios.push({id:r.id,...d})});}catch{usuarios=[{id:state.usuario.id,nome:state.usuario.nome||state.usuario.email||"Eu"}]}
}

async function carregarPlanos(){
  if(permite("planosAcao","visualizar")){planos=await listarDocumentos("planosAcao");return}
  const empresas=empresasSelecionadasIds();if(!empresas.length){planos=[];return}
  const blocos=await Promise.all(empresas.map(async emp=>{
    const s=await getDocs(query(collection(db,"planosAcao"),where("grupoId","==",state.usuario.grupoId),where("empresaId","==",emp),where("responsavelId","==",state.usuario.id))),arr=[];
    s.forEach(r=>arr.push({id:r.id,...r.data()}));return arr;
  }));
  planos=blocos.flat();
}

function addExc(arr,x){arr.push({criticidade:"media",...x})}
async function montarExcecoes(){
  const arr=[],tarefas=[];
  if(permite("contratos"))tarefas.push(["contratos",listarDocumentos("contratos")]);
  if(permite("cotacoes"))tarefas.push(["cotacoes",listarDocumentos("cotacoes")]);
  if(permite("almoxarifado"))tarefas.push(["estoque",listarDocumentos("itensAlmoxarifado")]);
  if(permite("frota"))tarefas.push(["frota",listarDocumentos("veiculos")]);
  if(permite("controladoria")){tarefas.push(["caixa",listarDocumentos("fluxoCaixaLancamentos")]);tarefas.push(["contas",listarDocumentos("contasBancarias")]);}
  const res=await Promise.all(tarefas.map(x=>x[1].catch(()=>[]))),d={};tarefas.forEach((x,i)=>d[x[0]]=res[i]);
  (d.contratos||[]).forEach(c=>{if(c.status!=="ativo")return;const dias=diasAte(c.fim);if(dias===null)return;if(dias<0)addExc(arr,{id:`ctr-${c.id}`,origem:"contratos",origemId:c.id,criticidade:"critica",titulo:`Contrato vencido · ${c.numero||c.fornecedor}`,sub:`${c.fornecedor||"Fornecedor"} · vencido há ${Math.abs(dias)} dia(s)`,prazo:c.fim});else if(dias<=30)addExc(arr,{id:`ctr-${c.id}`,origem:"contratos",origemId:c.id,criticidade:"alta",titulo:`Contrato vence em ${dias} dia(s)`,sub:`${c.numero||"Contrato"} · ${c.fornecedor||"Fornecedor"}`,prazo:c.fim});else if(dias<=60)addExc(arr,{id:`ctr-${c.id}`,origem:"contratos",origemId:c.id,criticidade:"media",titulo:`Contrato próximo do vencimento`,sub:`${c.numero||"Contrato"} · ${dias} dias restantes`,prazo:c.fim})});
  (d.cotacoes||[]).forEach(c=>{if(c.status==="aguardando_aprovacao"&&permite("cotacoes","aprovar"))addExc(arr,{id:`cot-ap-${c.id}`,origem:"cotacoes",origemId:c.id,criticidade:c.prioridade==="urgente"?"critica":"alta",titulo:`Cotação aguardando sua aprovação`,sub:`${c.titulo||"Solicitação"} · ${c.valorProposto?moeda(c.valorProposto):"valor não informado"}`,prazo:c.prazo});else if(c.status==="solicitada"&&permite("cotacoes","cotacao"))addExc(arr,{id:`cot-in-${c.id}`,origem:"cotacoes",origemId:c.id,criticidade:c.prioridade==="urgente"?"alta":"media",titulo:`Nova solicitação para cotar`,sub:c.titulo||"Solicitação",prazo:c.prazo});if(c.prazo&&c.prazo<hoje()&&!["finalizada","reprovada"].includes(c.status))addExc(arr,{id:`cot-venc-${c.id}`,origem:"cotacoes",origemId:c.id,criticidade:"alta",titulo:`Solicitação com prazo vencido`,sub:c.titulo||"Solicitação",prazo:c.prazo})});
  (d.estoque||[]).forEach(i=>{if(i.status==="inativo")return;if(n(i.estoqueAtual)<=n(i.estoqueMinimo))addExc(arr,{id:`est-${i.id}`,origem:"almoxarifado",origemId:i.id,criticidade:n(i.estoqueAtual)<=0?"alta":"media",titulo:`Estoque crítico · ${i.descricao||i.codigo}`,sub:`Saldo ${n(i.estoqueAtual).toLocaleString("pt-BR")} · mínimo ${n(i.estoqueMinimo).toLocaleString("pt-BR")}`})});
  (d.frota||[]).forEach(v=>{if(v.status==="manutencao")addExc(arr,{id:`fro-man-${v.id}`,origem:"frota",origemId:v.id,criticidade:"media",titulo:`Veículo em manutenção · ${v.placa}`,sub:v.modelo||"Veículo"});const falta=n(v.proximaRevisaoKm)-n(v.kmAtual);if(n(v.proximaRevisaoKm)>0&&falta<=1000)addExc(arr,{id:`fro-rev-${v.id}`,origem:"frota",origemId:v.id,criticidade:falta<=0?"alta":"media",titulo:`Revisão ${falta<=0?"vencida":"próxima"} · ${v.placa}`,sub:falta<=0?`${Math.abs(falta).toLocaleString("pt-BR")} km acima da revisão`:`faltam ${falta.toLocaleString("pt-BR")} km`});[["seguro",v.vencimentoSeguro],["licenciamento",v.vencimentoLicenciamento]].forEach(([nome,data])=>{const dias=diasAte(data);if(dias!==null&&dias<=30)addExc(arr,{id:`fro-${nome}-${v.id}`,origem:"frota",origemId:v.id,criticidade:dias<0?"alta":"media",titulo:`${nome[0].toUpperCase()+nome.slice(1)} ${dias<0?"vencido":"a vencer"} · ${v.placa}`,sub:dias<0?`vencido há ${Math.abs(dias)} dia(s)`:`vence em ${dias} dia(s)`,prazo:data})})});
  (d.caixa||[]).forEach(l=>{if(l.status!=="liquidado"&&l.status!=="cancelado"&&l.data<hoje())addExc(arr,{id:`cx-venc-${l.id}`,origem:"controladoria",origemId:l.id,criticidade:"alta",titulo:`Lançamento financeiro vencido`,sub:`${l.descricao||"Lançamento"} · ${moeda(l.valor)}`,prazo:l.data})});
  if((d.contas||[]).length){const base=d.contas.filter(x=>x.status!=="inativo").reduce((s,x)=>s+n(x.saldoAbertura),0),limite=addDias(hoje(),90),mov=(d.caixa||[]).filter(x=>x.status!=="cancelado"&&x.data<=limite).sort((a,b)=>String(a.data).localeCompare(String(b.data)));let saldo=base,min=base,dataMin=hoje();mov.forEach(x=>{saldo+=(x.natureza==="entrada"?1:-1)*n(x.valor);if(saldo<min){min=saldo;dataMin=x.data}});if(min<0)addExc(arr,{id:"cx-negativo",origem:"controladoria",criticidade:"critica",titulo:"Caixa projetado negativo em D+90",sub:`Menor posição ${moeda(min)} em ${dataBr(dataMin)}`,prazo:dataMin})}
  planos.filter(p=>!["concluido","cancelado"].includes(p.status)&&p.prazo&&p.prazo<hoje()).forEach(p=>addExc(arr,{id:`acao-${p.id}`,origem:"planosAcao",origemId:p.id,criticidade:p.criticidade==="critica"?"critica":"alta",titulo:`Plano de ação vencido · ${p.titulo}`,sub:`Responsável: ${p.responsavelNome||"não informado"}`,prazo:p.prazo}));
  excecoes=arr.sort((a,b)=>(critPeso[b.criticidade]||0)-(critPeso[a.criticidade]||0)||String(a.prazo||"9999").localeCompare(String(b.prazo||"9999")));
}

function renderExcecoes(){const filtro=$("mesaFiltroCriticidade")?.value||"",arr=excecoes.filter(x=>!filtro||x.criticidade===filtro),box=$("mesaExcecoes");if(!box)return;box.innerHTML=arr.length?arr.map(x=>`<div class="mesa-item"><i class="mesa-bolinha ${x.criticidade}"></i><div class="mesa-info"><strong>${esc(x.titulo)}</strong><span>${esc(x.sub||"")}</span><small><span class="mesa-tag">${esc(x.origem)}</span>${x.prazo?` · ${dataBr(x.prazo)}`:""}</small></div><div class="mesa-acoes">${paginaPorOrigem[x.origem]?`<button class="btn-acao" type="button" data-mesa-abrir="${x.origem}">Abrir</button>`:""}<button class="btn-acao destaque" type="button" data-mesa-plano="${x.id}">Criar ação</button></div></div>`).join(""):'<div class="mesa-empty">Nenhuma exceção nesse filtro. Bom sinal.</div>';box.querySelectorAll("[data-mesa-abrir]").forEach(b=>on(b,"click",()=>abrirPagina(paginaPorOrigem[b.dataset.mesaAbrir])));box.querySelectorAll("[data-mesa-plano]").forEach(b=>on(b,"click",()=>abrirPlano(excecoes.find(x=>x.id===b.dataset.mesaPlano))));}
function prazoClasse(p){if(!p)return"";if(p<hoje())return"vencido";if(p===hoje())return"hoje";return""}
function planoHtml(p,gerencial=false){const concluido=p.status==="concluido",prazo=p.prazo?dataBr(p.prazo):"Sem prazo";return`<div class="mesa-item ${concluido?"concluido":""}"><i class="mesa-bolinha ${p.criticidade||"media"}"></i><div class="mesa-info"><strong>${esc(p.titulo)}</strong><span>${esc(p.descricao||"")}</span><small>${gerencial?`${esc(p.responsavelNome||"Sem responsável")} · `:""}<span class="mesa-prazo ${prazoClasse(p.prazo)}">${prazo}</span> · ${esc(p.status||"aberto")}${p.origemModulo?` · ${esc(p.origemModulo)}`:""}</small><div class="mesa-progresso"><i style="width:${p.status==="concluido"?100:p.status==="em_andamento"?50:10}%"></i></div></div><div class="mesa-acoes">${!concluido&&p.responsavelId===state.usuario.id?`<button class="btn-acao" data-plano-andamento="${p.id}" type="button">Em andamento</button><button class="btn-acao destaque" data-plano-concluir="${p.id}" type="button">Concluir</button>`:""}${permite("planosAcao","editar")?`<button class="btn-acao" data-plano-editar="${p.id}" type="button">Editar</button>`:""}</div></div>`}
function bindPlanoAcoes(box){box?.querySelectorAll("[data-plano-andamento]").forEach(b=>on(b,"click",()=>mudarStatus(b.dataset.planoAndamento,"em_andamento")));box?.querySelectorAll("[data-plano-concluir]").forEach(b=>on(b,"click",()=>mudarStatus(b.dataset.planoConcluir,"concluido")));box?.querySelectorAll("[data-plano-editar]").forEach(b=>on(b,"click",()=>abrirPlano(planos.find(x=>x.id===b.dataset.planoEditar),true)));}
function renderPlanos(){
  const modo=$("mesaFiltroAcoes")?.value||"abertas";let arr=planos.filter(p=>p.responsavelId===state.usuario.id);
  if(modo==="abertas")arr=arr.filter(p=>!["concluido","cancelado"].includes(p.status));
  if(modo==="vencidas")arr=arr.filter(p=>!["concluido","cancelado"].includes(p.status)&&p.prazo&&p.prazo<hoje());
  if(modo==="concluidas")arr=arr.filter(p=>p.status==="concluido");
  if(modo==="concluidas")arr.sort((a,b)=>String(b.concluidoEm||b.atualizadoEm?.seconds||"").localeCompare(String(a.concluidoEm||a.atualizadoEm?.seconds||"")));
  else arr.sort((a,b)=>String(a.prazo||"9999").localeCompare(String(b.prazo||"9999")));
  const box=$("mesaPlanos");if(box){box.innerHTML=arr.length?arr.map(p=>planoHtml(p)).join(""):'<div class="mesa-empty">Nenhuma ação nesse filtro.</div>';bindPlanoAcoes(box)}
  const ger=$("mesaTodosPlanosCard"),todos=$("mesaTodosPlanos");ger?.classList.toggle("hidden",!permite("planosAcao","visualizar"));if(todos&&permite("planosAcao","visualizar")){const abertas=planos.filter(p=>!["concluido","cancelado"].includes(p.status)).sort((a,b)=>(critPeso[b.criticidade]||0)-(critPeso[a.criticidade]||0)||String(a.prazo||"9999").localeCompare(String(b.prazo||"9999")));todos.innerHTML=abertas.length?abertas.slice(0,20).map(p=>planoHtml(p,true)).join(""):'<div class="mesa-empty">Nenhum plano de ação aberto nas empresas selecionadas.</div>';bindPlanoAcoes(todos)}
}

function preencherResponsaveis(valor=""){const s=$("planoResponsavel");if(!s)return;const pode=permite("planosAcao","reatribuir");const arr=pode?usuarios:usuarios.filter(u=>u.id===state.usuario.id);s.innerHTML=arr.map(u=>`<option value="${esc(u.id)}">${esc(u.nome||u.email||u.id)}</option>`).join("");s.value=[...s.options].some(o=>o.value===valor)?valor:state.usuario.id;s.disabled=!pode}
function abrirPlano(origem=null,editar=false){const p=editar?origem:null;$("formPlanoAcao")?.reset();$("tituloPlanoAcao").textContent=p?"Editar plano de ação":"Novo plano de ação";$("formPlanoAcaoContainer").dataset.editId=p?.id||"";$("planoTitulo").value=p?.titulo||(!editar&&origem?origem.titulo:"");$("planoDescricao").value=p?.descricao||(!editar&&origem?origem.sub||"":"");$("planoCriticidade").value=p?.criticidade||origem?.criticidade||"media";$("planoPrazo").value=p?.prazo||origem?.prazo||addDias(hoje(),7);$("planoStatus").value=p?.status||"aberto";$("planoOrigemModulo").value=p?.origemModulo||origem?.origem||"manual";$("planoOrigemId").value=p?.origemId||origem?.origemId||"";preencherResponsaveis(p?.responsavelId||state.usuario.id);$("formPlanoAcaoContainer")?.classList.remove("hidden");$("formPlanoAcaoContainer")?.scrollIntoView({behavior:"smooth",block:"start"});$("planoTitulo")?.focus()}
function fecharPlano(){$("formPlanoAcao")?.reset();$("formPlanoAcaoContainer")?.classList.add("hidden");$("formPlanoAcaoContainer").dataset.editId="";msg($("mensagemPlanoAcao"),"")}
async function salvarPlano(e){e.preventDefault();const id=$("formPlanoAcaoContainer")?.dataset.editId||"",respId=$("planoResponsavel").value,u=usuarios.find(x=>x.id===respId)||state.usuario,d={titulo:$("planoTitulo").value.trim(),descricao:$("planoDescricao").value.trim(),criticidade:$("planoCriticidade").value,responsavelId:respId,responsavelNome:u.nome||u.email||respId,prazo:$("planoPrazo").value,status:$("planoStatus").value,origemModulo:$("planoOrigemModulo").value||"manual",origemId:$("planoOrigemId").value||""};if(!d.titulo||!d.responsavelId||!d.prazo)return msg($("mensagemPlanoAcao"),"Informe ação, responsável e prazo.");try{msg($("mensagemPlanoAcao"),"Salvando...");if(id){if(!permite("planosAcao","editar")&&id!==state.usuario.id)throw new Error("sem-permissao");await atualizarDocumento("planosAcao",id,d)}else await criarDocumento("planosAcao",d);fecharPlano();emitirAlteracao("planosAcao");await carregar()}catch(err){console.error(err);msg($("mensagemPlanoAcao"),"Não foi possível salvar o plano de ação.")}}
async function mudarStatus(id,status){try{await atualizarDocumento("planosAcao",id,{status,concluidoEm:status==="concluido"?new Date().toISOString():""});emitirAlteracao("planosAcao");await carregar()}catch(e){console.error(e);alert("Não foi possível atualizar a ação.")}}

function renderResumo(){const minhas=planos.filter(p=>p.responsavelId===state.usuario.id&&!['concluido','cancelado'].includes(p.status)),venc=minhas.filter(p=>p.prazo&&p.prazo<hoje()),ap=excecoes.filter(x=>x.origem==="cotacoes"&&x.titulo.includes("aprovação"));$("mesaQtdExcecoes").textContent=excecoes.length;$("mesaQtdAcoes").textContent=minhas.length;$("mesaQtdVencidas").textContent=venc.length;$("mesaQtdAprovacoes").textContent=ap.length;const nome=String(state.usuario?.nome||"").trim().split(/\s+/)[0];$("mesaSaudacao").textContent=nome?`Olá, ${nome}. O que precisa da sua atenção:`:"Minha Mesa"}
export async function carregar(){if(busy||!state.usuario||!empresaAtualId())return;busy=true;try{await carregarUsuarios();await carregarPlanos();await montarExcecoes();renderResumo();renderExcecoes();renderPlanos()}catch(e){console.error("Minha Mesa:",e);const x=$("mesaExcecoes");if(x)x.innerHTML='<div class="mesa-empty">Não foi possível consolidar a Minha Mesa. Verifique sua conexão ou as permissões de acesso.</div>'}finally{busy=false}}

montar();
window.addEventListener("sig:ready",()=>setTimeout(carregar,60));window.addEventListener("sig:empresa-changed",carregar);window.addEventListener("sig:data-changed",carregar);window.addEventListener("sig:page",e=>{if(e.detail?.pagina==="minhamesa")carregar()});
