import { abrirPagina, admin } from "./core.js";
import { $, esc, msg, permite, state, listarDocumentos, criarDocumento, atualizarDocumento, empresaUnicaSelecionadaId, dataBr, emitirAlteracao } from "./shared.js";
import { confirmarAcaoAdministrativa, atualizarComAuditoria } from "./admin-actions.js";
const TIPOS=["PALLET COM MATERIAL","PALLET VAZIO","ENTRADA DE PALLET","SAIDA DE PALLET","COMPRA DE PALLET"];
const MOD={mov:{colecao:"palletMovimentos",nome:"Entrega e recolhimento",permissao:"palletMovimentos"},inv:{colecao:"palletInventarios",nome:"Inventário de pallets",permissao:"palletInventario"}};
let dados={mov:[],inv:[]},edit={mov:null,inv:null},busy=false,aba="mov";
const pode=(k,acao)=>admin()||permite(MOD[k].permissao,acao);
const ver=k=>["visualizar","lancar","editar"].some(a=>pode(k,a));
const n=v=>Number(v||0);
const fmt=v=>n(v).toLocaleString("pt-BR",{maximumFractionDigits:0});
const localIso=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
const periodo=()=>$("palletAno")?.value||String(new Date().getFullYear());
const docs=k=>dados[k].filter(x=>String(x.data||"").startsWith(periodo())&&x.status!=="estornado");
function montar(){if($("pagina-pallets"))return;const main=document.querySelector("main.conteudo");if(!main)return;const s=document.createElement("section");s.id="pagina-pallets";s.className="pagina hidden production-page";s.innerHTML=`<div class="pagina-cabecalho production-head"><div><span class="eyebrow">LOGÍSTICA</span><h2>Pallets</h2><p>Entregas, recolhimentos e posição do inventário.</p></div><div class="acoes-cabecalho"><select id="palletAno" aria-label="Ano"><option value="${new Date().getFullYear()}">${new Date().getFullYear()}</option></select><button id="palletNovo" class="btn-primario" type="button">+ Novo registro</button><button id="palletAtualizar" class="btn-secundario" type="button">Atualizar</button></div></div><div id="palletAviso" class="modulo-aviso hidden"></div><div class="fleet-tabs"><button class="fleet-tab" id="palletTabMov" type="button">Entregas e recolhimentos</button><button class="fleet-tab" id="palletTabInv" type="button">Inventário e balanço</button></div><div class="production-kpis"><div class="kpi-card"><span id="palletKpiA">Entregues</span><strong id="palletValorA">—</strong></div><div class="kpi-card"><span id="palletKpiB">Recolhidos</span><strong id="palletValorB">—</strong></div><div class="kpi-card"><span id="palletKpiC">Diferença</span><strong id="palletValorC">—</strong></div></div>
  <section class="form-card hidden" id="palletFormBox"><div class="form-card-titulo"><h3 id="palletFormTitulo">Novo registro</h3></div><form id="palletForm"><div class="form-grid form-grid-3"><div class="campo"><label for="palletData">Data</label><input id="palletData" type="date" required></div><div class="campo" data-pallet-mov><label for="palletMotorista">Motorista</label><input id="palletMotorista" list="palletMotoristas" required><datalist id="palletMotoristas">${["CARLOS","CLERISTON","DERCILIO","DIARISTA","FABIO","JOAREZ","JOEL","KRISTIANO","MARCELO","RENATO","RENATO B.","ROBSON","WESLEY","WEVERTON"].map(x=>`<option value="${x}">`).join("")}</datalist></div><div class="campo" data-pallet-mov><label for="palletEntregue">Quantidade entregue</label><input id="palletEntregue" type="number" min="0" step="1" required></div><div class="campo" data-pallet-mov><label for="palletRecolhido">Quantidade recolhida</label><input id="palletRecolhido" type="number" min="0" step="1" required></div><div class="campo" data-pallet-inv><label for="palletTipo">Tipo de movimento / posição</label><select id="palletTipo">${TIPOS.map(t=>`<option>${t}</option>`).join("")}</select></div><div class="campo" data-pallet-inv><label for="palletQuantidade">Quantidade</label><input id="palletQuantidade" type="number" min="0" step="1"></div></div><div class="form-acoes"><button id="palletCancelar" class="btn-secundario" type="button">Cancelar</button><button class="btn-primario" type="submit">Salvar</button></div><p id="palletMensagem" class="mensagem-form"></p></form></section>
  <section id="palletResumoMotoristas" class="lista-card"><div class="lista-cabecalho"><div><h3>Recolhimento por motorista</h3><p>Mais de 500 pallets recolhidos no mês: referência de R$ 120,00 do Script.</p></div><select id="palletMes" aria-label="Mês">${Array.from({length:12},(_,i)=>`<option value="${String(i+1).padStart(2,"0")}">${new Date(2026,i,1).toLocaleString("pt-BR",{month:"long"})}</option>`).join("")}</select></div><div id="palletMotoristasResumo" class="production-master-grid"></div></section>
  <section id="palletBalanco" class="lista-card hidden"><div class="lista-cabecalho"><div><h3>Balanço mensal de pallets</h3><p>Saldo/perda = diferença do estoque físico em relação ao mês anterior, descontadas as compras.</p></div></div><div class="tabela-container"><table class="tabela" id="palletBalancoTabela"></table></div></section>
  <section class="lista-card"><div class="lista-cabecalho"><div><h3 id="palletHistoricoTitulo">Histórico de entregas e recolhimentos</h3><p>Estornos continuam visíveis e não compõem os indicadores.</p></div></div><div class="tabela-container"><table class="tabela"><thead id="palletCabecalho"></thead><tbody id="palletLista"></tbody></table></div></section>`;main.appendChild(s);$("palletTabMov").addEventListener("click",()=>trocar("mov"));$("palletTabInv").addEventListener("click",()=>trocar("inv"));$("palletNovo").addEventListener("click",novo);$("palletAtualizar").addEventListener("click",carregar);$("palletAno").addEventListener("change",render);$("palletMes").addEventListener("change",render);$("palletCancelar").addEventListener("click",()=>{$("palletFormBox").classList.add("hidden");limpar()});$("palletForm").addEventListener("submit",salvar);$("palletMes").value=String(new Date().getMonth()+1).padStart(2,"0");trocar("mov")}
function menu(){const nav=document.querySelector(".sidebar-menu");if(!nav)return;let b=$("menuPallets");if(!b){b=document.createElement("button");b.id="menuPallets";b.className="menu-item hidden";b.dataset.pagina="pallets";b.type="button";b.textContent="Pallets";nav.appendChild(b);b.addEventListener("click",e=>{e.preventDefault();e.stopImmediatePropagation();if(!ver("mov")&&!ver("inv"))return;abrirPagina("pallets");carregar()},true)}b.classList.toggle("hidden",!ver("mov")&&!ver("inv"))}
function trocar(k){if(!ver(k))k=k==="mov"?"inv":"mov";if(!ver(k))return;aba=k;$("palletFormBox")?.classList.add("hidden");$("palletTabMov")?.classList.toggle("ativo",k==="mov");$("palletTabInv")?.classList.toggle("ativo",k==="inv");$("palletTabMov")?.classList.toggle("hidden",!ver("mov"));$("palletTabInv")?.classList.toggle("hidden",!ver("inv"));document.querySelectorAll("[data-pallet-mov]").forEach(x=>{x.classList.toggle("hidden",k!=="mov");x.querySelectorAll("input,select").forEach(i=>i.disabled=k!=="mov")});document.querySelectorAll("[data-pallet-inv]").forEach(x=>{x.classList.toggle("hidden",k!=="inv");x.querySelectorAll("input,select").forEach(i=>i.disabled=k!=="inv")});$("palletNovo")?.classList.toggle("hidden",!pode(k,"lancar"));$("palletResumoMotoristas")?.classList.toggle("hidden",k!=="mov");$("palletBalanco")?.classList.toggle("hidden",k!=="inv");$("palletHistoricoTitulo").textContent=k==="mov"?"Histórico de entregas e recolhimentos":"Histórico de inventário";render()}
function limpar(){edit[aba]=null;$("palletForm").reset();$("palletData").value=localIso();$("palletFormTitulo").textContent=`Novo registro · ${MOD[aba].nome}`;msg($("palletMensagem"),"")}
function novo(){if(!pode(aba,"lancar"))return;if(!empresaUnicaSelecionadaId())return alert("Selecione apenas uma empresa no cabeçalho.");limpar();$("palletFormBox").classList.remove("hidden");$("palletFormBox").scrollIntoView({behavior:"smooth",block:"start"})}
function editarRegistro(id){const x=dados[aba].find(r=>r.id===id);if(!x||x.status!=="ativo"||!pode(aba,"editar"))return;if(x.empresaId!==empresaUnicaSelecionadaId())return alert("Selecione a empresa do registro para editar.");edit[aba]=id;$("palletData").value=x.data;if(aba==="mov"){$("palletMotorista").value=x.motorista;$("palletEntregue").value=x.entregue;$("palletRecolhido").value=x.recolhido}else{$("palletTipo").value=x.tipo;$("palletQuantidade").value=x.quantidade}$("palletFormTitulo").textContent="Editar registro";$("palletFormBox").classList.remove("hidden");$("palletFormBox").scrollIntoView({behavior:"smooth",block:"start"})}
function balanco(){const base=docs("inv"),por=Object.fromEntries(TIPOS.map(t=>[t,Array(12).fill(0)]));for(const x of base){const i=Number(String(x.data).slice(5,7))-1;if(por[x.tipo]&&i>=0&&i<12)por[x.tipo][i]+=n(x.quantidade)}const mat=por[TIPOS[0]],vaz=por[TIPOS[1]],entr=por[TIPOS[2]],sai=por[TIPOS[3]],compra=por[TIPOS[4]],total=mat.map((v,i)=>v+vaz[i]),dif=total.map((v,i)=>i?v-total[i-1]:0),fluxo=entr.map((v,i)=>v-sai[i]),saldo=dif.map((v,i)=>v-compra[i]);const linhas=[["PALLET COM MATERIAL",mat],["PALLET VAZIO",vaz],["TOTAL NO PÁTIO",total],["DIFERENÇA MÊS ANTERIOR",dif],["ENTRADA",entr],["SAÍDA",sai],["DIFERENÇA ENT/SAÍDA",fluxo],["COMPRA",compra],["SALDO / PERDA",saldo]];$("palletBalancoTabela").innerHTML=`<thead><tr><th>Posição / movimento</th>${Array.from({length:12},(_,i)=>`<th>${new Date(2026,i,1).toLocaleString("pt-BR",{month:"short"})}</th>`).join("")}</tr></thead><tbody>${linhas.map(([t,a])=>`<tr><th>${t}</th>${a.map(v=>`<td>${fmt(v)}</td>`).join("")}</tr>`).join("")}</tbody>`;return{total,saldo}}
function render(){if(!$("palletLista"))return;const k=aba,base=docs(k),q=base.reduce((s,x)=>s+n(k==="mov"?x.entregue:x.quantidade),0),r=base.reduce((s,x)=>s+n(x.recolhido),0);if(k==="mov"){$("palletKpiA").textContent="Entregues";$("palletKpiB").textContent="Recolhidos";$("palletKpiC").textContent="Diferença";[$("palletValorA").textContent,$("palletValorB").textContent,$("palletValorC").textContent]=[fmt(q),fmt(r),fmt(q-r)];const mes=$("palletMes").value,totais={};base.filter(x=>x.data?.slice(5,7)===mes).forEach(x=>totais[x.motorista]=(totais[x.motorista]||0)+n(x.recolhido));$("palletMotoristasResumo").innerHTML=Object.entries(totais).sort((a,b)=>b[1]-a[1]).map(([nome,total])=>`<div class="production-master"><h4>${esc(nome)}</h4><strong>${fmt(total)} recolhidos</strong><p>${total>500?"Acima de 500 · referência R$ 120,00":"Até 500"}</p></div>`).join("")||'<p>Sem recolhimentos no mês.</p>'}else{const b=balanco(),mes=Math.max(0,new Date().getMonth());$("palletKpiA").textContent="Registros do ano";$("palletKpiB").textContent="Pallets no pátio (mês atual)";$("palletKpiC").textContent="Saldo/perda (mês atual)";[$("palletValorA").textContent,$("palletValorB").textContent,$("palletValorC").textContent]=[fmt(base.length),fmt(b.total[mes]),fmt(b.saldo[mes])]}
  $("palletCabecalho").innerHTML=k==="mov"?'<tr><th>Data</th><th>Motorista</th><th>Entregues</th><th>Recolhidos</th><th>Situação</th><th>Ações</th></tr>':'<tr><th>Data</th><th>Tipo</th><th>Quantidade</th><th>Situação</th><th>Ações</th></tr>';const todos=dados[k].filter(x=>String(x.data||"").startsWith(periodo()));$("palletLista").innerHTML=todos.sort((a,b)=>String(b.data).localeCompare(String(a.data))).map(x=>`<tr class="${x.status==="estornado"?"sig-admin-estornado":""}"><td>${dataBr(x.data)}</td>${k==="mov"?`<td>${esc(x.motorista)}</td><td>${fmt(x.entregue)}</td><td>${fmt(x.recolhido)}</td>`:`<td>${esc(x.tipo)}</td><td>${fmt(x.quantidade)}</td>`}<td>${x.status==="estornado"?"Estornado":"Ativo"}</td><td>${x.status!=="estornado"&&pode(k,"editar")?`<button class="btn-acao destaque" data-pallet-edit="${esc(x.id)}">Editar</button>`:""}${x.status!=="estornado"&&admin()?`<button class="btn-acao perigo" data-pallet-estorno="${esc(x.id)}">Estornar ADM</button>`:""}</td></tr>`).join("")||`<tr><td colspan="${k==="mov"?6:5}">Nenhum registro encontrado.</td></tr>`;document.querySelectorAll("[data-pallet-edit]").forEach(b=>b.addEventListener("click",()=>editarRegistro(b.dataset.palletEdit)));document.querySelectorAll("[data-pallet-estorno]").forEach(b=>b.addEventListener("click",()=>estornar(b.dataset.palletEstorno)))}
async function carregar(){if(busy||(!ver("mov")&&!ver("inv")))return;busy=true;try{const [m,i]=await Promise.all([ver("mov")?listarDocumentos(MOD.mov.colecao):[],ver("inv")?listarDocumentos(MOD.inv.colecao):[]]);dados={mov:m,inv:i};const s=$("palletAno"),value=s.value||String(new Date().getFullYear()),anos=[...new Set([new Date().getFullYear(),...m.concat(i).map(x=>Number(String(x.data||"").slice(0,4))).filter(Boolean)])].sort((a,b)=>b-a);s.innerHTML=anos.map(y=>`<option value="${y}">${y}</option>`).join("");if(anos.map(String).includes(value))s.value=value;render();$("palletAviso").classList.add("hidden")}catch(e){console.error(e);$("palletAviso").textContent="Não foi possível consultar pallets. Verifique o perfil e as Rules publicadas.";$("palletAviso").classList.remove("hidden")}finally{busy=false}}
async function salvar(e){e.preventDefault();const k=aba,emp=empresaUnicaSelecionadaId();if(!emp)return alert("Selecione apenas uma empresa no cabeçalho.");const data=$("palletData").value,d={data};if(k==="mov"){d.motorista=$("palletMotorista").value.trim().toUpperCase();d.entregue=Number($("palletEntregue").value);d.recolhido=Number($("palletRecolhido").value)}else{d.tipo=$("palletTipo").value;d.quantidade=Number($("palletQuantidade").value)}const nums=k==="mov"?[d.entregue,d.recolhido]:[d.quantidade];if(!/^\d{4}-\d{2}-\d{2}$/.test(data)||nums.some(x=>!Number.isSafeInteger(x)||x<0)||(k==="mov"&&!d.motorista)||(k==="inv"&&!TIPOS.includes(d.tipo)))return msg($("palletMensagem"),"Revise os campos do registro.");try{msg($("palletMensagem"),"Salvando...");if(edit[k]){const atual=dados[k].find(x=>x.id===edit[k]);if(!pode(k,"editar")||!atual||atual.empresaId!==emp||atual.status!=="ativo")throw new Error("Edição não autorizada.");await atualizarDocumento(MOD[k].colecao,edit[k],d)}else{if(!pode(k,"lancar"))throw new Error("Sem permissão.");await criarDocumento(MOD[k].colecao,{...d,empresaId:emp,status:"ativo",origem:"sig",atualizadoPor:state.usuario?.id||""})}$("palletFormBox").classList.add("hidden");limpar();emitirAlteracao("pallets");await carregar()}catch(err){console.error(err);msg($("palletMensagem"),err.message||"Não foi possível salvar.")}}
async function estornar(id){if(!admin())return;const k=aba,x=dados[k].find(y=>y.id===id);if(!x||x.status!=="ativo")return;const ok=await confirmarAcaoAdministrativa({titulo:"Estornar pallet",descricao:`O registro de ${dataBr(x.data)} permanecerá no histórico.`,motivoLabel:"Motivo obrigatório do estorno",confirmarTexto:"Estornar",perigosa:true});if(!ok)return;try{await atualizarComAuditoria({colecao:MOD[k].colecao,id,empresaId:x.empresaId,modulo:MOD[k].permissao,acao:"estorno",motivo:ok.motivo,resumo:`Estorno de pallets em ${x.data}`,snapshotAntes:x,alteracoes:{status:"estornado",motivoEstorno:ok.motivo,estornadoPor:state.usuario?.id||"",estornadoEm:new Date().toISOString()}});emitirAlteracao("pallets");await carregar()}catch(e){console.error(e);alert("Não foi possível estornar.")}}
function instalar(){if(!document.querySelector('link[href^="production.css"]')){const l=document.createElement("link");l.rel="stylesheet";l.href="production.css?v=1";document.head.appendChild(l)}montar();menu();trocar(aba)}
instalar();window.addEventListener("sig:ready",()=>{instalar();if(ver("mov")||ver("inv"))carregar()});window.addEventListener("sig:empresa-contexto",()=>{if(!$("pagina-pallets")?.classList.contains("hidden"))carregar()});window.addEventListener("sig:data-changed",e=>{if(e.detail?.modulo==="pallets"&&!$("pagina-pallets")?.classList.contains("hidden"))carregar()});
