import { admin, permite, moeda, dataBr, diasAte, listarDocumentos } from "./shared.js";

const podeVer=()=>admin()||permite("contasPagar","visualizar")||permite("contasPagar","cadastrar")||permite("contasPagar","editar")||permite("contasPagar","baixar")||permite("contasPagar","estornar");
const aberto=x=>!["pago","estornado","cancelado"].includes(x?.status);
const n=v=>{const x=Number(v||0);return Number.isFinite(x)?x:0};
let busy=false,timer=null;

function montar(){
  const pag=document.getElementById("pagina-minhamesa");if(!pag||document.getElementById("mesaContasPagarCard"))return !!pag;
  const grid=pag.querySelector(".mesa-grid");const card=document.createElement("section");card.id="mesaContasPagarCard";card.className="lista-card mesa-ap-card";card.innerHTML=`<div class="lista-cabecalho"><div><h3>Contas a Pagar</h3><p>Vencidos e próximos vencimentos do cockpit operacional.</p></div><button id="mesaAbrirContasPagar" class="btn-secundario" type="button">Abrir cockpit</button></div><div class="mesa-ap-kpis"><button type="button" data-mesa-ap="vencidos"><span>Vencidos</span><strong id="mesaApVencidos">—</strong><small id="mesaApVencidosValor">—</small></button><button type="button" data-mesa-ap="hoje"><span>Hoje</span><strong id="mesaApHoje">—</strong><small id="mesaApHojeValor">—</small></button><button type="button" data-mesa-ap="7"><span>Próx. 7 dias</span><strong id="mesaAp7">—</strong><small id="mesaAp7Valor">—</small></button></div><div id="mesaApLista" class="mesa-ap-lista"><div class="mesa-empty">Carregando pagamentos...</div></div>`;
  if(grid)pag.insertBefore(card,grid);else pag.appendChild(card);
  if(!document.getElementById("mesa-ap-css")){const s=document.createElement("style");s.id="mesa-ap-css";s.textContent=`.mesa-ap-card{margin-top:14px;border-top:3px solid #0b1f33}.mesa-ap-kpis{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin-bottom:10px}.mesa-ap-kpis button{border:1px solid #e4e7ec;border-radius:10px;background:#f8fafb;padding:9px;text-align:left;cursor:pointer}.mesa-ap-kpis button:hover{border-color:#0c9488}.mesa-ap-kpis span,.mesa-ap-kpis strong,.mesa-ap-kpis small{display:block}.mesa-ap-kpis span{font-size:9px;color:#667085;text-transform:uppercase;font-weight:850}.mesa-ap-kpis strong{margin-top:2px;font-size:18px;color:#0b1f33}.mesa-ap-kpis small{margin-top:2px;color:#667085}.mesa-ap-lista{display:grid;gap:6px}.mesa-ap-item{display:grid;grid-template-columns:auto 1fr auto;gap:9px;align-items:center;border-top:1px solid #f0f2f4;padding:7px 2px}.mesa-ap-item:first-child{border-top:0}.mesa-ap-dot{width:8px;height:8px;border-radius:50%;background:#f79009}.mesa-ap-item.vencido .mesa-ap-dot{background:#d92d20}.mesa-ap-item.hoje .mesa-ap-dot{background:#f79009}.mesa-ap-info strong,.mesa-ap-info small{display:block}.mesa-ap-info strong{font-size:11px;color:#0b1f33}.mesa-ap-info small{font-size:9px;color:#667085;margin-top:2px}.mesa-ap-valor{font-size:11px;font-weight:850;color:#344054}@media(max-width:720px){.mesa-ap-kpis{grid-template-columns:1fr}.mesa-ap-item{grid-template-columns:auto 1fr}.mesa-ap-valor{grid-column:2}}`;document.head.appendChild(s)}
  document.getElementById("mesaAbrirContasPagar")?.addEventListener("click",()=>window.SIG_ABRIR_CONTAS_PAGAR?.());card.querySelectorAll("[data-mesa-ap]").forEach(b=>b.addEventListener("click",()=>window.SIG_ABRIR_CONTAS_PAGAR?.(b.dataset.mesaAp)));return true;
}
function soma(a){return a.reduce((s,x)=>s+n(x.valor),0)}
function classe(x){const d=diasAte(x.vencimento);return d<0?"vencido":d===0?"hoje":""}
async function carregar(){if(!podeVer()||busy)return;if(!montar())return;busy=true;try{const todos=await listarDocumentos("contasPagar"),abertos=todos.filter(aberto),venc=abertos.filter(x=>(diasAte(x.vencimento)??0)<0),hj=abertos.filter(x=>diasAte(x.vencimento)===0),d7=abertos.filter(x=>{const d=diasAte(x.vencimento);return d!==null&&d>=1&&d<=7});[["Vencidos",venc],["Hoje",hj],["7",d7]].forEach(([id,a])=>{document.getElementById(`mesaAp${id}`).textContent=a.length;document.getElementById(`mesaAp${id}Valor`).textContent=moeda(soma(a))});const lista=[...abertos].filter(x=>{const d=diasAte(x.vencimento);return d!==null&&d<=7}).sort((a,b)=>String(a.vencimento||"").localeCompare(String(b.vencimento||""))).slice(0,8),el=document.getElementById("mesaApLista");if(!el)return;if(!lista.length){el.innerHTML='<div class="mesa-empty">Nenhum pagamento vencido ou com vencimento nos próximos 7 dias.</div>';return}el.innerHTML=lista.map(x=>`<div class="mesa-ap-item ${classe(x)}"><i class="mesa-ap-dot"></i><div class="mesa-ap-info"><strong>${String(x.fornecedor||"Fornecedor").replace(/[<>&]/g,"")} · ${String(x.descricao||"").replace(/[<>&]/g,"")}</strong><small>${dataBr(x.vencimento)} · ${x.origem==="contrato"?"Contrato":"Contas a Pagar"}</small></div><span class="mesa-ap-valor">${moeda(x.valor)}</span></div>`).join("")}catch(e){console.warn("Minha Mesa · Contas a Pagar",e);document.getElementById("mesaContasPagarCard")?.classList.add("hidden")}finally{busy=false}}
function agendar(){clearTimeout(timer);timer=setTimeout(carregar,160)}
window.addEventListener("sig:ready",agendar);window.addEventListener("sig:page",e=>{if(e.detail?.pagina==="minhamesa")agendar()});window.addEventListener("sig:empresa-changed",agendar);window.addEventListener("sig:data-changed",e=>{if(["contasPagar","contratos"].includes(e.detail?.modulo))agendar()});
const obs=new MutationObserver(()=>{if(montar())agendar()});obs.observe(document.body,{childList:true,subtree:true});montar();