import { abrirPagina, state, auth } from "./core.js";
import {
  $, esc, msg, permite, admin, moeda, listarDocumentos, criarDocumento,
  grupoAtualId, empresaUnicaSelecionadaId, empresasSelecionadasIds,
  carregarEmpresasModulo, nomeEmpresa, periodoAno, periodoChave, db,
  formatarCpfCnpj, validarCpfCnpj, somenteDigitosDocumento, emitirAlteracao
} from "./shared.js";
import { exportarTabelaPdf, exportarTabelaXls } from "./export-utils.js";
import { EmailAuthProvider, reauthenticateWithCredential } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js";
import { writeBatch, doc, collection, serverTimestamp, updateDoc, getDocs, query, where } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";

const PERIODOS={total:[1,12],t1:[1,3],t2:[4,6],t3:[7,9],t4:[10,12]};
for(let i=1;i<=12;i++)PERIODOS[`m${String(i).padStart(2,"0")}`]=[i,i];
let permutas=[],movimentos=[],fechamentos=[],centros=[],plano=[],carregando=false,apoio=false,detalheId="",fechamentoId="",editId="",deleteCtx=null;
const n=v=>{const x=Number(v||0);return Number.isFinite(x)?x:0};
const pagina=()=>$("pagina-permutas");
const hoje=()=>new Date().toISOString().slice(0,10);
const pode=a=>admin()||permite("permutas",a);
const podeVer=()=>admin()||["visualizar","cadastrar","editar","movimentar","estornar","fechar","inativar"].some(a=>permite("permutas",a));
const ativo=p=>!["inativo","finalizada","encerrado","cancelado"].includes(p?.status||"ativo");
const valido=m=>m?.estornado!==true;
const sinal=m=>["credito","ajuste_credito"].includes(m?.tipo)?1:-1;
const nome=p=>p?.contraparteNome||p?.descricao||"Permuta";
const fmt=v=>v?String(v).slice(0,10).split("-").reverse().join("/"):"-";
const tipo=t=>({credito:"Entrada / crédito",consumo:"Saída / consumo",ajuste_credito:"Ajuste credor",ajuste_debito:"Ajuste devedor"})[t]||t||"-";
const st=s=>({ativo:"Ativa",inativo:"Inativa",finalizada:"Finalizada",encerrado:"Encerrada",cancelado:"Cancelada"})[s||"ativo"]||s||"Ativa";
const diaSeguinte=iso=>{const d=new Date(`${iso}T12:00:00`);d.setDate(d.getDate()+1);return d.toISOString().slice(0,10)};
const leitura=s=>s>0?"Contraparte nos deve":s<0?"Temos obrigação a entregar":"Conciliada";
function periodoCab(){const a=periodoAno(),[m1,m2]=PERIODOS[periodoChave()]||PERIODOS.total,d=new Date(a,m2,0).getDate();return{inicio:`${a}-${String(m1).padStart(2,"0")}-01`,fim:`${a}-${String(m2).padStart(2,"0")}-${String(d).padStart(2,"0")}`}}
function noIntervalo(m,i=$("permutaDataInicio")?.value||"",f=$("permutaDataFim")?.value||""){const d=String(m?.data||"");return(!i||d>=i)&&(!f||d<=f)}
function movs(id,{inicio="",fim="",estornados=true}={}){return movimentos.filter(m=>m.permutaId===id&&(!inicio||String(m.data||"")>=inicio)&&(!fim||String(m.data||"")<=fim)&&(estornados||valido(m))).sort((a,b)=>String(a.data||"").localeCompare(String(b.data||""))||String(a.id).localeCompare(String(b.id)))}
function saldo(id){return movs(id,{estornados:false}).reduce((s,m)=>s+sinal(m)*n(m.valorPermuta),0)}
function saldoAntes(id,data){return movimentos.filter(m=>m.permutaId===id&&valido(m)&&String(m.data||"")<data).reduce((s,m)=>s+sinal(m)*n(m.valorPermuta),0)}
function metaRel(){return[`${fmt($("permutaDataInicio")?.value)} a ${fmt($("permutaDataFim")?.value)}`,empresasSelecionadasIds().length>1?`${empresasSelecionadasIds().length} empresas`:"Empresa selecionada","Estornos fora dos totais"]}

function css(){if($("permutas-v2-css"))return;const s=document.createElement("style");s.id="permutas-v2-css";s.textContent=`
.permuta-filtros,.permuta-acoes{display:flex;gap:8px;align-items:end;flex-wrap:wrap}.permuta-filtros .campo{min-width:145px}.permuta-click{cursor:pointer}.permuta-click:hover td{background:#f5fbfa}.permuta-inativa{opacity:.67}.permuta-estornada td:not(.nao-exportar){text-decoration:line-through;color:#98a2b3;background:#fff7f7}.permuta-estorno-info{display:block;text-decoration:none!important;color:#b42318;font-size:9px;margin-top:3px}.permuta-meta,.permuta-fecha-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin:12px 0}.permuta-meta div,.permuta-fecha-kpis div{border:1px solid #e4e7ec;border-radius:9px;padding:9px;background:#fafbfc}.permuta-meta span,.permuta-fecha-kpis span{display:block;color:#667085;font-size:9px}.permuta-meta strong,.permuta-fecha-kpis strong{display:block;margin-top:3px}.permuta-ciclo{padding:9px 11px;border-left:3px solid #0c9488;background:#f5fbfa;margin:10px 0}.permuta-modal{position:fixed;inset:0;z-index:9999;background:rgba(15,23,42,.55);display:flex;align-items:center;justify-content:center;padding:16px}.permuta-modal.hidden{display:none}.permuta-modal-card{width:min(520px,100%);background:#fff;border-radius:14px;padding:18px;box-shadow:0 20px 60px rgba(0,0,0,.25)}@media(max-width:820px){.permuta-meta,.permuta-fecha-kpis{grid-template-columns:1fr 1fr}}@media(max-width:520px){.permuta-meta,.permuta-fecha-kpis{grid-template-columns:1fr}}
`;document.head.appendChild(s)}

function criarPagina(){if(pagina())return;css();const main=document.querySelector("main.conteudo");if(!main)return;const s=document.createElement("section");s.id="pagina-permutas";s.className="pagina hidden";s.innerHTML=`
<div class="pagina-cabecalho"><div><span class="eyebrow">OPERAÇÕES</span><h2>Permutas</h2><p>Gestão operacional, conta-corrente, estornos, conciliação e fechamentos.</p></div><div class="acoes-cabecalho"><button id="btnAtualizarPermutas" class="btn-secundario" type="button">Atualizar</button><button id="btnNovaPermuta" class="btn-secundario" type="button">+ Nova permuta</button><button id="btnNovoMovPermuta" class="btn-primario" type="button">+ Movimentação</button></div></div>
<div id="permutaAviso" class="modulo-aviso hidden"></div>
<div class="kpi-grid kpi-grid-4"><div class="kpi-card"><span>Saldo atual</span><strong id="permutaSaldo">—</strong><small>movimentos válidos</small></div><div class="kpi-card"><span>Entradas no intervalo</span><strong id="permutaEntradas">—</strong><small>estornos desconsiderados</small></div><div class="kpi-card"><span>Saídas no intervalo</span><strong id="permutaSaidas">—</strong><small>estornos desconsiderados</small></div><div class="kpi-card"><span>Resultado econômico</span><strong id="permutaEconomico">—</strong><small>mercado recebido − custo entregue</small></div></div>
<section class="lista-card"><div class="lista-cabecalho"><div><h3>Filtros e relatórios</h3><p>Intervalo exato de dias.</p></div><div class="permuta-acoes"><button id="btnPeriodoCab" class="btn-secundario" type="button">Usar período do cabeçalho</button><button id="btnPdfPermutas" class="btn-secundario" type="button">PDF</button><button id="btnXlsPermutas" class="btn-secundario" type="button">Excel</button></div></div><div class="permuta-filtros"><div class="campo"><label for="permutaDataInicio">De</label><input id="permutaDataInicio" type="date"></div><div class="campo"><label for="permutaDataFim">Até</label><input id="permutaDataFim" type="date"></div><div class="campo"><label for="permutaFiltroStatus">Status</label><select id="permutaFiltroStatus"><option value="ativas">Ativas</option><option value="inativas">Inativas</option><option value="finalizadas">Finalizadas</option><option value="todas">Todas</option></select></div><button id="btnAplicarPermuta" class="btn-primario" type="button">Aplicar</button></div></section>
<section id="formPermutaContainer" class="form-card hidden"><div class="form-card-titulo"><div><h3 id="tituloFormPermuta">Nova permuta</h3><p>CPF/CNPJ segue a máscara padrão do SIG.</p></div></div><form id="formPermuta"><div class="form-grid form-grid-3"><div class="campo"><label for="permutaDocumento">CPF/CNPJ do cliente/fornecedor</label><input id="permutaDocumento" maxlength="18" inputmode="numeric" placeholder="000.000.000-00 ou 00.000.000/0000-00"></div><div class="campo"><label for="permutaTipoContraparte">Contraparte</label><select id="permutaTipoContraparte"><option value="cliente">Cliente</option><option value="fornecedor">Fornecedor</option><option value="empresa_grupo">Empresa do grupo</option></select></div><div id="campoPermutaEmpresaGrupo" class="campo hidden"><label for="permutaEmpresaGrupo">Empresa do grupo</label><select id="permutaEmpresaGrupo"></select></div><div id="campoPermutaNome" class="campo"><label for="permutaNome">Nome / razão social</label><input id="permutaNome" required></div><div class="campo"><label for="permutaInicio">Início</label><input id="permutaInicio" type="date" required></div><div class="campo"><label for="permutaFim">Fim previsto</label><input id="permutaFim" type="date"></div><div class="campo"><label for="permutaValorAcordado">Valor acordado</label><input id="permutaValorAcordado" type="number" min="0" step="0.01"></div><div class="campo campo-span-2"><label for="permutaDescricao">Objeto / descrição</label><input id="permutaDescricao" required></div><div class="campo campo-span-3"><label for="permutaObservacao">Observação</label><input id="permutaObservacao"></div></div><div class="form-acoes"><button id="btnCancelarPermuta" class="btn-secundario" type="button">Cancelar</button><button class="btn-primario" type="submit">Salvar permuta</button></div><p id="mensagemPermuta" class="mensagem-form"></p></form></section>
<section id="formMovPermutaContainer" class="form-card hidden"><div class="form-card-titulo"><div><h3>Movimentação</h3><p>Somente permutas ativas aceitam lançamentos.</p></div></div><form id="formMovPermuta"><div class="form-grid form-grid-3"><div class="campo"><label for="movPermutaId">Permuta</label><select id="movPermutaId" required></select></div><div class="campo"><label for="movPermutaData">Data</label><input id="movPermutaData" type="date" required></div><div class="campo"><label for="movPermutaTipo">Movimento</label><select id="movPermutaTipo"><option value="credito">Entrada · gera crédito</option><option value="consumo">Saída · consome crédito</option><option value="ajuste_credito">Ajuste credor</option><option value="ajuste_debito">Ajuste devedor</option></select></div><div class="campo campo-span-2"><label for="movPermutaDescricao">Descrição</label><input id="movPermutaDescricao" required></div><div class="campo"><label for="movPermutaDocumento">NF / documento</label><input id="movPermutaDocumento"></div><div class="campo"><label for="movPermutaValor">Valor</label><input id="movPermutaValor" type="number" min="0" step="0.01" required></div><div class="campo"><label for="movPermutaCusto">Custo interno</label><input id="movPermutaCusto" type="number" min="0" step="0.01"></div><div class="campo"><label for="movPermutaMercado">Valor de mercado recebido</label><input id="movPermutaMercado" type="number" min="0" step="0.01"></div><div class="campo"><label for="movPermutaCentro">Centro de custo</label><select id="movPermutaCentro"></select></div><div class="campo"><label for="movPermutaConta">Conta gerencial</label><select id="movPermutaConta"></select></div><div class="campo"><label for="movPermutaObservacao">Observação</label><input id="movPermutaObservacao"></div></div><div class="form-acoes"><button id="btnCancelarMovPermuta" class="btn-secundario" type="button">Cancelar</button><button class="btn-primario" type="submit">Salvar movimentação</button></div><p id="mensagemMovPermuta" class="mensagem-form"></p></form></section>
<section class="lista-card"><div class="lista-cabecalho"><div><h3>Permutas cadastradas</h3><p id="permutaContexto">—</p></div></div><div class="tabela-container"><table id="tabelaPermutas" class="tabela"><thead><tr><th>Contraparte</th><th>CPF/CNPJ</th><th>Acordado</th><th>Entradas</th><th>Saídas</th><th>Saldo</th><th>Status</th><th class="nao-exportar">Ações</th></tr></thead><tbody id="listaPermutas"></tbody></table></div></section>
<section id="permutaDetalhe" class="lista-card hidden"><div class="lista-cabecalho"><div><h3 id="permutaDetalheTitulo">Detalhe</h3><p id="permutaDetalheSub">—</p></div><div class="permuta-acoes"><button id="btnPdfDetalhePermuta" class="btn-secundario" type="button">PDF ficha</button><button id="btnXlsDetalhePermuta" class="btn-secundario" type="button">Excel movimentos</button><button id="btnFecharDetalhePermuta" class="btn-primario" type="button">Fechar período</button></div></div><div id="permutaDetalheMeta" class="permuta-meta"></div><div id="permutaCiclo" class="permuta-ciclo"></div><div class="tabela-container"><table id="tabelaPermutaDetalhe" class="tabela"><thead><tr><th>Data</th><th>Documento</th><th>Descrição</th><th>Tipo</th><th>Valor</th><th>Saldo</th><th>Status</th><th class="nao-exportar">Ação</th></tr></thead><tbody id="listaPermutaDetalhe"></tbody></table></div><h4>Fechamentos</h4><div class="tabela-container"><table class="tabela"><thead><tr><th>Data</th><th>Período</th><th>Entradas</th><th>Saídas</th><th>Saldo antes</th><th>Zerador</th><th>Saldo seguinte</th><th>Situação</th></tr></thead><tbody id="listaPermutaFechamentos"></tbody></table></div></section>
<section id="permutaFechamento" class="form-card hidden"><div class="form-card-titulo"><div><h3>Fechamento da permuta</h3><p>Movimentos estornados ficam fora do demonstrativo.</p></div></div><form id="formFechamentoPermuta"><div class="form-grid form-grid-3"><div class="campo"><label for="fechamentoData">Fechar até</label><input id="fechamentoData" type="date" required></div><label class="driver-switch"><input id="fechamentoZerar" type="checkbox"><span>Gerar lançamento zerador</span></label><label class="driver-switch"><input id="fechamentoFinalizar" type="checkbox"><span>Finalizar a permuta</span></label><div class="campo campo-span-3"><label for="fechamentoObservacao">Observação</label><input id="fechamentoObservacao"></div></div><div id="fechamentoKpis" class="permuta-fecha-kpis"></div><div class="tabela-container"><table id="tabelaFechamentoPermuta" class="tabela"><thead><tr><th>Data</th><th>Documento</th><th>Descrição</th><th>Tipo</th><th>Valor</th></tr></thead><tbody id="listaFechamentoMovimentos"></tbody></table></div><div class="form-acoes"><button id="btnCancelarFechamento" class="btn-secundario" type="button">Cancelar</button><button class="btn-primario" type="submit">Confirmar fechamento</button></div><p id="mensagemFechamento" class="mensagem-form"></p></form></section>
<section class="lista-card"><div class="lista-cabecalho"><div><h3>Razão do intervalo</h3><p>Estornos continuam visíveis e riscados para auditoria.</p></div></div><div class="tabela-container"><table id="tabelaPermutaMovimentos" class="tabela"><thead><tr><th>Data</th><th>Contraparte</th><th>Documento</th><th>Descrição</th><th>Tipo</th><th>Valor</th><th>Saldo após</th><th>Status</th><th class="nao-exportar">Ação</th></tr></thead><tbody id="listaPermutaMovimentos"></tbody></table></div></section>
<div id="modalExcluirPermuta" class="permuta-modal hidden"><div class="permuta-modal-card"><h3 id="tituloExcluirPermuta">Exclusão administrativa</h3><p id="textoExcluirPermuta"></p><div class="campo"><label for="senhaExcluirPermuta">Senha do Administrador</label><input id="senhaExcluirPermuta" type="password" autocomplete="current-password"></div><div class="form-acoes"><button id="btnCancelarExcluirPermuta" class="btn-secundario" type="button">Cancelar</button><button id="btnConfirmarExcluirPermuta" class="btn-primario" type="button">Confirmar exclusão</button></div><p id="mensagemExcluirPermuta" class="mensagem-form"></p></div></div>`;main.appendChild(s);bind();usarPeriodo(false)}

function bind(){
  $("btnAtualizarPermutas")?.addEventListener("click",carregar);$("btnNovaPermuta")?.addEventListener("click",()=>abrirForm());$("btnNovoMovPermuta")?.addEventListener("click",abrirMov);$("btnCancelarPermuta")?.addEventListener("click",()=>$("formPermutaContainer")?.classList.add("hidden"));$("btnCancelarMovPermuta")?.addEventListener("click",()=>$("formMovPermutaContainer")?.classList.add("hidden"));$("formPermuta")?.addEventListener("submit",salvarPermuta);$("formMovPermuta")?.addEventListener("submit",salvarMov);$("permutaTipoContraparte")?.addEventListener("change",alternarContraparte);$("permutaDocumento")?.addEventListener("input",e=>e.target.value=formatarCpfCnpj(e.target.value));
  $("btnAplicarPermuta")?.addEventListener("click",render);$("permutaFiltroStatus")?.addEventListener("change",render);$("btnPeriodoCab")?.addEventListener("click",()=>usarPeriodo(true));$("btnPdfPermutas")?.addEventListener("click",()=>exportarTabelaPdf($("tabelaPermutaMovimentos"),{nome:"permutas_periodo",titulo:"Permutas · Razão do período",meta:metaRel()}));$("btnXlsPermutas")?.addEventListener("click",()=>exportarTabelaXls($("tabelaPermutaMovimentos"),{nome:"permutas_periodo",titulo:"Permutas · Razão do período",meta:metaRel()}));
  $("btnPdfDetalhePermuta")?.addEventListener("click",()=>exportarDetalhe("pdf"));$("btnXlsDetalhePermuta")?.addEventListener("click",()=>exportarDetalhe("xls"));$("btnFecharDetalhePermuta")?.addEventListener("click",()=>detalheId&&abrirFechamento(detalheId));$("fechamentoData")?.addEventListener("change",renderFechamento);$("fechamentoZerar")?.addEventListener("change",renderFechamento);$("fechamentoFinalizar")?.addEventListener("change",renderFechamento);$("btnCancelarFechamento")?.addEventListener("click",()=>$("permutaFechamento")?.classList.add("hidden"));$("formFechamentoPermuta")?.addEventListener("submit",salvarFechamento);
  $("btnCancelarExcluirPermuta")?.addEventListener("click",fecharExclusao);$("btnConfirmarExcluirPermuta")?.addEventListener("click",confirmarExclusao);$("modalExcluirPermuta")?.addEventListener("click",e=>{if(e.target===$("modalExcluirPermuta"))fecharExclusao()})
}
function usarPeriodo(r=true){const p=periodoCab();if($("permutaDataInicio"))$("permutaDataInicio").value=p.inicio;if($("permutaDataFim"))$("permutaDataFim").value=p.fim;if(r)render()}
function filtroPermutas(){const f=$("permutaFiltroStatus")?.value||"ativas";return permutas.filter(p=>f==="todas"||f==="ativas"&&ativo(p)||f==="inativas"&&p.status==="inativo"||f==="finalizadas"&&["finalizada","encerrado"].includes(p.status))}
function movFiltro(){return movimentos.filter(m=>noIntervalo(m)).sort((a,b)=>String(a.data||"").localeCompare(String(b.data||""))||String(a.id).localeCompare(String(b.id)))}

function render(){if(!pagina())return;const ps=filtroPermutas(),arr=movFiltro(),v=arr.filter(valido),ent=v.filter(m=>sinal(m)>0).reduce((s,m)=>s+n(m.valorPermuta),0),sai=v.filter(m=>sinal(m)<0).reduce((s,m)=>s+n(m.valorPermuta),0),eco=v.filter(m=>m.tipo==="consumo").reduce((s,m)=>s+n(m.valorMercado),0)-v.filter(m=>m.tipo==="credito").reduce((s,m)=>s+n(m.custoInterno),0);$("permutaSaldo").textContent=moeda(ps.reduce((s,p)=>s+saldo(p.id),0));$("permutaEntradas").textContent=moeda(ent);$("permutaSaidas").textContent=moeda(sai);$("permutaEconomico").textContent=moeda(eco);$("permutaContexto").textContent=`${ps.length} permuta(s) · ${fmt($("permutaDataInicio")?.value)} a ${fmt($("permutaDataFim")?.value)}`;$("btnNovaPermuta")?.classList.toggle("hidden",!pode("cadastrar")&&!pode("editar"));$("btnNovoMovPermuta")?.classList.toggle("hidden",!pode("movimentar"));
  $("listaPermutas").innerHTML=ps.length?ps.sort((a,b)=>String(nome(a)).localeCompare(String(nome(b)),"pt-BR")).map(p=>{const ms=movs(p.id,{estornados:false}),e=ms.filter(m=>sinal(m)>0).reduce((s,m)=>s+n(m.valorPermuta),0),x=ms.filter(m=>sinal(m)<0).reduce((s,m)=>s+n(m.valorPermuta),0),sl=e-x;return`<tr class="permuta-click ${ativo(p)?"":"permuta-inativa"}" data-detalhe="${p.id}"><td><strong>${esc(nome(p))}</strong><small>${esc(p.tipoContraparte||"")}</small></td><td>${esc(p.contraparteDocumento||"-")}</td><td>${moeda(p.valorAcordado)}</td><td>${moeda(e)}</td><td>${moeda(x)}</td><td><strong>${moeda(sl)}</strong><small>${esc(leitura(sl))}</small></td><td><span class="${ativo(p)?"status-ativo":"status-inativo"}">${esc(st(p.status))}</span></td><td class="nao-exportar"><div class="permuta-acoes"><button class="btn-acao destaque" data-ver="${p.id}" type="button">Detalhes</button>${pode("editar")?`<button class="btn-acao" data-editar="${p.id}" type="button">Editar</button>`:""}${pode("inativar")&&!['finalizada','encerrado'].includes(p.status)?`<button class="btn-acao" data-status="${p.id}" type="button">${p.status==="inativo"?"Reativar":"Inativar"}</button>`:""}${pode("fechar")&&ativo(p)?`<button class="btn-acao" data-fechar="${p.id}" type="button">Fechar</button>`:""}${admin()?`<button class="btn-acao perigo" data-del-permuta="${p.id}" type="button">Excluir</button>`:""}</div></td></tr>`}).join(""):'<tr><td colspan="8">Nenhuma permuta encontrada.</td></tr>';bindTabela();renderRazao(arr);if(detalheId)renderDetalhe(detalheId);if(fechamentoId)renderFechamento()}
function bindTabela(){document.querySelectorAll("[data-detalhe]").forEach(tr=>tr.addEventListener("click",e=>{if(!e.target.closest("button"))abrirDetalhe(tr.dataset.detalhe)}));document.querySelectorAll("[data-ver]").forEach(b=>b.addEventListener("click",()=>abrirDetalhe(b.dataset.ver)));document.querySelectorAll("[data-editar]").forEach(b=>b.addEventListener("click",()=>abrirForm(b.dataset.editar)));document.querySelectorAll("[data-status]").forEach(b=>b.addEventListener("click",()=>statusPermuta(b.dataset.status)));document.querySelectorAll("[data-fechar]").forEach(b=>b.addEventListener("click",()=>abrirFechamento(b.dataset.fechar)));document.querySelectorAll("[data-del-permuta]").forEach(b=>b.addEventListener("click",()=>abrirExclusao("permuta",b.dataset.delPermuta)))}
function renderRazao(arr){const saldos=new Map(),inicio=$("permutaDataInicio")?.value||"";permutas.forEach(p=>saldos.set(p.id,inicio?saldoAntes(p.id,inicio):0));$("listaPermutaMovimentos").innerHTML=arr.length?arr.map(m=>{let sl=saldos.get(m.permutaId)||0;if(valido(m))sl+=sinal(m)*n(m.valorPermuta);saldos.set(m.permutaId,sl);const p=permutas.find(x=>x.id===m.permutaId),est=!valido(m);return`<tr class="${est?"permuta-estornada":""}"><td>${fmt(m.data)}</td><td>${esc(nome(p))}</td><td>${esc(m.documento||"-")}</td><td>${esc(m.descricao||"")}${est?`<span class="permuta-estorno-info">Estornado: ${esc(m.motivoEstorno||"-")} · ${esc(m.estornadoPorNome||m.estornadoPor||"")}</span>`:""}</td><td>${esc(tipo(m.tipo))}</td><td>${moeda(m.valorPermuta)}</td><td>${moeda(sl)}</td><td>${est?"Estornado":"Válido"}</td><td class="nao-exportar">${!est&&pode("estornar")?`<button class="btn-acao perigo" data-estornar="${m.id}" type="button">Estornar</button>`:""}${admin()?`<button class="btn-acao perigo" data-del-mov="${m.id}" type="button">Excluir</button>`:""}</td></tr>`}).join(""):'<tr><td colspan="9">Sem movimentações no intervalo.</td></tr>';document.querySelectorAll("[data-estornar]").forEach(b=>b.addEventListener("click",()=>estornar(b.dataset.estornar)));document.querySelectorAll("[data-del-mov]").forEach(b=>b.addEventListener("click",()=>abrirExclusao("movimento",b.dataset.delMov)))}

function abrirDetalhe(id){detalheId=id;renderDetalhe(id);$("permutaDetalhe")?.classList.remove("hidden");$("permutaDetalhe")?.scrollIntoView({behavior:"smooth",block:"start"})}
function renderDetalhe(id){const p=permutas.find(x=>x.id===id);if(!p)return;const ms=movs(id),vv=ms.filter(valido),e=vv.filter(m=>sinal(m)>0).reduce((s,m)=>s+n(m.valorPermuta),0),x=vv.filter(m=>sinal(m)<0).reduce((s,m)=>s+n(m.valorPermuta),0);$("permutaDetalheTitulo").textContent=nome(p);$("permutaDetalheSub").textContent=`${p.contraparteDocumento||"Sem CPF/CNPJ"} · ${st(p.status)} · ${nomeEmpresa(p.empresaId)}`;$("permutaDetalheMeta").innerHTML=`<div><span>Valor acordado</span><strong>${moeda(p.valorAcordado)}</strong></div><div><span>Entradas válidas</span><strong>${moeda(e)}</strong></div><div><span>Saídas válidas</span><strong>${moeda(x)}</strong></div><div><span>Saldo atual</span><strong>${moeda(e-x)}</strong></div><div><span>Início</span><strong>${fmt(p.dataInicio)}</strong></div><div><span>Fim previsto</span><strong>${fmt(p.dataFim)}</strong></div><div><span>Objeto</span><strong>${esc(p.descricao||"-")}</strong></div><div><span>Observação</span><strong>${esc(p.observacao||"-")}</strong></div>`;$("permutaCiclo").innerHTML=`<strong>Ciclo atual:</strong> ${fmt(p.cicloInicio||p.dataInicio)} em diante · saldo de abertura ${moeda(p.saldoAberturaCiclo||0)} · último fechamento ${fmt(p.ultimoFechamentoData)}`;
  let sl=0;$("listaPermutaDetalhe").innerHTML=ms.length?ms.map(m=>{if(valido(m))sl+=sinal(m)*n(m.valorPermuta);const est=!valido(m);return`<tr class="${est?"permuta-estornada":""}"><td>${fmt(m.data)}</td><td>${esc(m.documento||"-")}</td><td>${esc(m.descricao||"")}${est?`<span class="permuta-estorno-info">Motivo: ${esc(m.motivoEstorno||"-")} · ${esc(m.estornadoPorNome||m.estornadoPor||"")}</span>`:""}</td><td>${esc(tipo(m.tipo))}</td><td>${moeda(m.valorPermuta)}</td><td>${moeda(sl)}</td><td>${est?"Estornado":"Válido"}</td><td class="nao-exportar">${!est&&pode("estornar")?`<button class="btn-acao perigo" data-estornar-det="${m.id}" type="button">Estornar</button>`:""}${admin()?`<button class="btn-acao perigo" data-del-mov-det="${m.id}" type="button">Excluir</button>`:""}</td></tr>`}).join(""):'<tr><td colspan="8">Sem movimentos.</td></tr>';document.querySelectorAll("[data-estornar-det]").forEach(b=>b.addEventListener("click",()=>estornar(b.dataset.estornarDet)));document.querySelectorAll("[data-del-mov-det]").forEach(b=>b.addEventListener("click",()=>abrirExclusao("movimento",b.dataset.delMovDet)));
  const fs=fechamentos.filter(f=>f.permutaId===id).sort((a,b)=>String(b.dataFim||"").localeCompare(String(a.dataFim||"")));$("listaPermutaFechamentos").innerHTML=fs.length?fs.map(f=>`<tr><td>${fmt(f.dataFechamento||f.dataFim)}</td><td>${fmt(f.dataInicio)} a ${fmt(f.dataFim)}</td><td>${moeda(f.entradas)}</td><td>${moeda(f.saidas)}</td><td>${moeda(f.saldoAntes)}</td><td>${f.gerouZerador?moeda(f.valorZerador):"Não"}</td><td>${moeda(f.saldoDepois)}</td><td>${f.finalizou?"Finalizada":"Novo ciclo"}</td></tr>`).join(""):'<tr><td colspan="8">Nenhum fechamento.</td></tr>';$("btnFecharDetalhePermuta")?.classList.toggle("hidden",!pode("fechar")||!ativo(p))}
function exportarDetalhe(formato){const p=permutas.find(x=>x.id===detalheId);if(!p)return;const op={nome:`permuta_${nome(p)}`,titulo:`Permuta · ${nome(p)}`,meta:[p.contraparteDocumento||"",`Saldo ${moeda(saldo(p.id))}`,st(p.status)]};return formato==="pdf"?exportarTabelaPdf($("tabelaPermutaDetalhe"),op):exportarTabelaXls($("tabelaPermutaDetalhe"),op)}

async function abrirForm(id=""){if(!pode("cadastrar")&&!pode("editar"))return aviso("Seu perfil não pode cadastrar/editar permutas.");if(!empresaUnicaSelecionadaId())return aviso("Selecione apenas uma empresa no cabeçalho.");editId=id;$("formPermuta")?.reset();await preencherGrupo();const p=permutas.find(x=>x.id===id);$("tituloFormPermuta").textContent=p?"Editar permuta":"Nova permuta";$("permutaInicio").value=p?.dataInicio||hoje();$("permutaFim").value=p?.dataFim||"";$("permutaTipoContraparte").value=p?.tipoContraparte||"cliente";$("permutaNome").value=p?.contraparteNome||"";$("permutaDocumento").value=formatarCpfCnpj(p?.contraparteDocumento||"");$("permutaValorAcordado").value=p?.valorAcordado||"";$("permutaDescricao").value=p?.descricao||"";$("permutaObservacao").value=p?.observacao||"";if(p?.contraparteEmpresaId)$("permutaEmpresaGrupo").value=p.contraparteEmpresaId;alternarContraparte();$("formPermutaContainer")?.classList.remove("hidden");$("permutaDocumento")?.focus()}
function alternarContraparte(){const inter=$("permutaTipoContraparte")?.value==="empresa_grupo";$("campoPermutaEmpresaGrupo")?.classList.toggle("hidden",!inter);$("campoPermutaNome")?.classList.toggle("hidden",inter);$("permutaDocumento")?.closest(".campo")?.classList.toggle("hidden",inter);$("permutaNome").required=!inter;$("permutaDocumento").required=!inter}
async function preencherGrupo(){const mapa=await carregarEmpresasModulo(),origem=empresaUnicaSelecionadaId(),s=$("permutaEmpresaGrupo");if(!s)return;s.innerHTML='<option value="">Selecione...</option>'+[...mapa.values()].filter(x=>x.id!==origem).map(x=>`<option value="${esc(x.id)}">${esc(x.nomeFantasia||x.razaoSocial||x.id)}</option>`).join("")}
async function salvarPermuta(ev){ev.preventDefault();const empresaId=empresaUnicaSelecionadaId(),tipoC=$("permutaTipoContraparte").value,contraId=tipoC==="empresa_grupo"?$("permutaEmpresaGrupo").value:"",nm=tipoC==="empresa_grupo"?nomeEmpresa(contraId):$("permutaNome").value.trim(),df=formatarCpfCnpj($("permutaDocumento").value);if(!empresaId)return msg($("mensagemPermuta"),"Selecione uma empresa.");if(!nm||tipoC==="empresa_grupo"&&!contraId)return msg($("mensagemPermuta"),"Informe a contraparte.");if(tipoC!=="empresa_grupo"&&!validarCpfCnpj(df))return msg($("mensagemPermuta"),"Informe CPF ou CNPJ válido.");const d={tipoContraparte:tipoC,contraparteNome:nm,contraparteDocumento:tipoC==="empresa_grupo"?"":df,contraparteDocumentoNumeros:tipoC==="empresa_grupo"?"":somenteDigitosDocumento(df),contraparteEmpresaId:contraId,descricao:$("permutaDescricao").value.trim(),valorAcordado:n($("permutaValorAcordado").value),dataInicio:$("permutaInicio").value,dataFim:$("permutaFim").value,observacao:$("permutaObservacao").value.trim()};try{msg($("mensagemPermuta"),"Salvando...");if(editId){const p=permutas.find(x=>x.id===editId);if(p?.tipoContraparte==="empresa_grupo")return msg($("mensagemPermuta"),"Permutas entre empresas não são editáveis nesta versão; use inativação e novo cadastro.");await updateDoc(doc(db,"permutas",editId),{...d,atualizadoEm:serverTimestamp()})}else if(tipoC!=="empresa_grupo"){await criarDocumento("permutas",{...d,status:"ativo",cicloInicio:d.dataInicio,saldoAberturaCiclo:0})}else{const lote=writeBatch(db),grupoId=grupoAtualId(),a=doc(collection(db,"permutas")),b=doc(collection(db,"permutas")),gid=crypto.randomUUID(),base={grupoId,permutaGrupoId:gid,descricao:d.descricao,valorAcordado:d.valorAcordado,dataInicio:d.dataInicio,dataFim:d.dataFim,status:"ativo",cicloInicio:d.dataInicio,saldoAberturaCiclo:0,observacao:d.observacao,tipoContraparte:"empresa_grupo",criadoPor:state.usuario.id,criadoEm:serverTimestamp(),atualizadoEm:serverTimestamp()};lote.set(a,{...base,empresaId,contraparteEmpresaId:contraId,contraparteNome:nomeEmpresa(contraId),espelhoPermutaId:b.id});lote.set(b,{...base,empresaId:contraId,contraparteEmpresaId:empresaId,contraparteNome:nomeEmpresa(empresaId),espelhoPermutaId:a.id});await lote.commit()}$("formPermutaContainer")?.classList.add("hidden");editId="";msg($("mensagemPermuta"),"Permuta salva.",true);await carregar();emitirAlteracao("permutas")}catch(e){console.error(e);msg($("mensagemPermuta"),"Não foi possível salvar.")}}

async function carregarApoio(){if(apoio)return;[centros,plano]=await Promise.all([listarDocumentos("centrosCusto"),listarDocumentos("planoContasGerencial")]);apoio=true}
async function abrirMov(){if(!pode("movimentar"))return aviso("Seu perfil não pode movimentar permutas.");const emp=empresaUnicaSelecionadaId();if(!emp)return aviso("Selecione apenas uma empresa.");await carregarApoio();const ps=permutas.filter(p=>p.empresaId===emp&&ativo(p));$("movPermutaId").innerHTML='<option value="">Selecione...</option>'+ps.map(p=>`<option value="${p.id}">${esc(nome(p))}</option>`).join("");$("movPermutaCentro").innerHTML='<option value="">Sem centro específico</option>'+centros.filter(x=>x.status!=="inativo").map(x=>`<option value="${x.id}">${esc(x.codigo||"")} · ${esc(x.nome||"")}</option>`).join("");$("movPermutaConta").innerHTML='<option value="">Sem conta específica</option>'+plano.filter(x=>x.status!=="inativo"&&x.tipo==="analitica").map(x=>`<option value="${x.id}">${esc(x.codigo||"")} · ${esc(x.nome||"")}</option>`).join("");$("formMovPermuta")?.reset();$("movPermutaData").value=hoje();$("formMovPermutaContainer")?.classList.remove("hidden")}
async function salvarMov(ev){ev.preventDefault();const empresaId=empresaUnicaSelecionadaId(),p=permutas.find(x=>x.id===$("movPermutaId").value);if(!empresaId||!p||!ativo(p))return msg($("mensagemMovPermuta"),"Selecione uma permuta ativa.");const d={permutaId:p.id,data:$("movPermutaData").value,tipo:$("movPermutaTipo").value,descricao:$("movPermutaDescricao").value.trim(),documento:$("movPermutaDocumento").value.trim(),valorPermuta:n($("movPermutaValor").value),custoInterno:n($("movPermutaCusto").value),valorMercado:n($("movPermutaMercado").value),centroCustoId:$("movPermutaCentro").value,contaGerencialId:$("movPermutaConta").value,observacao:$("movPermutaObservacao").value.trim()};if(!d.valorPermuta)return msg($("mensagemMovPermuta"),"Informe o valor.");try{msg($("mensagemMovPermuta"),"Salvando...");if(p.tipoContraparte!=="empresa_grupo"||!p.espelhoPermutaId)await criarDocumento("permutaMovimentos",d);else{const lote=writeBatch(db),grupoId=grupoAtualId(),a=doc(collection(db,"permutaMovimentos")),b=doc(collection(db,"permutaMovimentos")),gid=crypto.randomUUID(),op=d.tipo==="credito"?"consumo":d.tipo==="consumo"?"credito":d.tipo==="ajuste_credito"?"ajuste_debito":"ajuste_credito",base={grupoId,movimentoGrupoId:gid,data:d.data,descricao:d.descricao,documento:d.documento,valorPermuta:d.valorPermuta,observacao:d.observacao,criadoPor:state.usuario.id,criadoEm:serverTimestamp(),atualizadoEm:serverTimestamp(),estornado:false};lote.set(a,{...base,empresaId,permutaId:p.id,tipo:d.tipo,custoInterno:d.custoInterno,valorMercado:d.valorMercado,centroCustoId:d.centroCustoId,contaGerencialId:d.contaGerencialId,espelhoMovimentoId:b.id});lote.set(b,{...base,empresaId:p.contraparteEmpresaId,permutaId:p.espelhoPermutaId,tipo:op,custoInterno:0,valorMercado:0,centroCustoId:"",contaGerencialId:"",espelhoMovimentoId:a.id});await lote.commit()}$("formMovPermutaContainer")?.classList.add("hidden");msg($("mensagemMovPermuta"),"Movimentação registrada.",true);await carregar();emitirAlteracao("permutas")}catch(e){console.error(e);msg($("mensagemMovPermuta"),"Não foi possível registrar.")}}

async function estornar(id){if(!pode("estornar"))return;const m=movimentos.find(x=>x.id===id);if(!m||!valido(m))return;const motivo=prompt("Informe obrigatoriamente o motivo do estorno:","")?.trim();if(!motivo)return alert("O motivo do estorno é obrigatório.");if(!confirm(`Estornar o lançamento de ${moeda(m.valorPermuta)} em ${fmt(m.data)}?`))return;try{const dados={estornado:true,motivoEstorno:motivo,estornadoPor:state.usuario.id,estornadoPorNome:state.usuario.nome||state.usuario.email||"Usuário",estornadoEm:serverTimestamp(),atualizadoEm:serverTimestamp()};if(m.espelhoMovimentoId){const lote=writeBatch(db);lote.update(doc(db,"permutaMovimentos",m.id),dados);lote.update(doc(db,"permutaMovimentos",m.espelhoMovimentoId),dados);await lote.commit()}else await updateDoc(doc(db,"permutaMovimentos",m.id),dados);await carregar();emitirAlteracao("permutas")}catch(e){console.error(e);alert("Não foi possível estornar o lançamento.")}}
async function statusPermuta(id){if(!pode("inativar"))return;const p=permutas.find(x=>x.id===id);if(!p)return;const novo=p.status==="inativo"?"ativo":"inativo";if(!confirm(`${novo==="ativo"?"Reativar":"Inativar"} ${nome(p)}? ${novo==="inativo"?"Novos lançamentos serão bloqueados.":""}`))return;try{if(p.espelhoPermutaId){const lote=writeBatch(db);lote.update(doc(db,"permutas",p.id),{status:novo,atualizadoEm:serverTimestamp()});lote.update(doc(db,"permutas",p.espelhoPermutaId),{status:novo,atualizadoEm:serverTimestamp()});await lote.commit()}else await updateDoc(doc(db,"permutas",p.id),{status:novo,atualizadoEm:serverTimestamp()});await carregar()}catch(e){console.error(e);alert("Não foi possível alterar o status.")}}

function dadosFechamento(){const p=permutas.find(x=>x.id===fechamentoId);if(!p)return null;const inicio=p.cicloInicio||p.dataInicio||"0000-01-01",fim=$("fechamentoData")?.value||hoje(),abertura=n(p.saldoAberturaCiclo)||saldoAntes(p.id,inicio),ms=movs(p.id,{inicio,fim,estornados:false}).filter(m=>m.origem!=="fechamento_zerador"),entradas=ms.filter(m=>sinal(m)>0).reduce((s,m)=>s+n(m.valorPermuta),0),saidas=ms.filter(m=>sinal(m)<0).reduce((s,m)=>s+n(m.valorPermuta),0),antes=abertura+entradas-saidas,zerar=$("fechamentoZerar")?.checked===true,finalizar=$("fechamentoFinalizar")?.checked===true,depois=zerar?0:antes;return{p,inicio,fim,abertura,ms,entradas,saidas,antes,zerar,finalizar,depois}}
function abrirFechamento(id){if(!pode("fechar"))return aviso("Seu perfil não pode fechar permutas.");const p=permutas.find(x=>x.id===id);if(!p||!ativo(p))return;fechamentoId=id;$("formFechamentoPermuta")?.reset();$("fechamentoData").value=hoje();$("permutaFechamento")?.classList.remove("hidden");renderFechamento();$("permutaFechamento")?.scrollIntoView({behavior:"smooth",block:"start"})}
function renderFechamento(){const d=dadosFechamento();if(!d)return;$("fechamentoKpis").innerHTML=`<div><span>Saldo abertura</span><strong>${moeda(d.abertura)}</strong></div><div><span>Entradas válidas</span><strong>${moeda(d.entradas)}</strong></div><div><span>Saídas válidas</span><strong>${moeda(d.saidas)}</strong></div><div><span>Saldo antes do fechamento</span><strong>${moeda(d.antes)}</strong></div>`;$("listaFechamentoMovimentos").innerHTML=d.ms.length?d.ms.map(m=>`<tr><td>${fmt(m.data)}</td><td>${esc(m.documento||"-")}</td><td>${esc(m.descricao||"")}</td><td>${esc(tipo(m.tipo))}</td><td>${moeda(m.valorPermuta)}</td></tr>`).join(""):'<tr><td colspan="5">Nenhum movimento válido neste ciclo.</td></tr>'}
async function salvarFechamento(ev){ev.preventDefault();const d=dadosFechamento();if(!d)return;if(d.fim<d.inicio)return msg($("mensagemFechamento"),"A data final não pode ser anterior ao início do ciclo.");if(!confirm(`Confirmar fechamento de ${fmt(d.inicio)} a ${fmt(d.fim)} com saldo ${moeda(d.antes)}?`))return;try{msg($("mensagemFechamento"),"Fechando...");const lote=writeBatch(db),f=doc(collection(db,"permutaFechamentos")),novaData=diaSeguinte(d.fim),baseF={grupoId:grupoAtualId(),empresaId:d.p.empresaId,permutaId:d.p.id,dataInicio:d.inicio,dataFim:d.fim,dataFechamento:hoje(),saldoAbertura:d.abertura,entradas:d.entradas,saidas:d.saidas,saldoAntes:d.antes,gerouZerador:d.zerar,valorZerador:d.zerar?Math.abs(d.antes):0,saldoDepois:d.depois,finalizou:d.finalizar,observacao:$("fechamentoObservacao").value.trim(),fechadoPor:state.usuario.id,fechadoPorNome:state.usuario.nome||state.usuario.email||"Usuário",criadoEm:serverTimestamp(),atualizadoEm:serverTimestamp()};lote.set(f,baseF);if(d.zerar&&d.antes!==0){const z=doc(collection(db,"permutaMovimentos")),zt=d.antes>0?"ajuste_debito":"ajuste_credito",zb={grupoId:grupoAtualId(),empresaId:d.p.empresaId,permutaId:d.p.id,data:d.fim,tipo:zt,descricao:`Zerador do fechamento ${fmt(d.fim)}`,documento:"FECHAMENTO",valorPermuta:Math.abs(d.antes),custoInterno:0,valorMercado:0,centroCustoId:"",contaGerencialId:"",observacao:"Lançamento automático de fechamento",origem:"fechamento_zerador",fechamentoId:f.id,estornado:false,criadoPor:state.usuario.id,criadoEm:serverTimestamp(),atualizadoEm:serverTimestamp()};lote.set(z,zb);if(d.p.espelhoPermutaId){const z2=doc(collection(db,"permutaMovimentos"));lote.set(z2,{...zb,empresaId:d.p.contraparteEmpresaId,permutaId:d.p.espelhoPermutaId,tipo:zt==="ajuste_debito"?"ajuste_credito":"ajuste_debito",espelhoMovimentoId:z.id});lote.update(z,{espelhoMovimentoId:z2.id})}}
  const upd={status:d.finalizar?"finalizada":"ativo",ultimoFechamentoData:d.fim,cicloInicio:novaData,saldoAberturaCiclo:d.depois,atualizadoEm:serverTimestamp()};lote.update(doc(db,"permutas",d.p.id),upd);if(d.p.espelhoPermutaId)lote.update(doc(db,"permutas",d.p.espelhoPermutaId),{...upd,saldoAberturaCiclo:-d.depois});await lote.commit();$("permutaFechamento")?.classList.add("hidden");fechamentoId="";msg($("mensagemFechamento"),"Fechamento concluído.",true);await carregar();emitirAlteracao("permutas")}catch(e){console.error(e);msg($("mensagemFechamento"),"Não foi possível concluir o fechamento.")}}

function abrirExclusao(tipoEx,id){if(!admin())return alert("Exclusão física é exclusiva do Administrador.");deleteCtx={tipo:tipoEx,id};const item=tipoEx==="permuta"?permutas.find(x=>x.id===id):movimentos.find(x=>x.id===id);$("tituloExcluirPermuta").textContent=tipoEx==="permuta"?"Excluir permuta definitivamente":"Excluir lançamento definitivamente";$("textoExcluirPermuta").textContent=tipoEx==="permuta"?`Esta ação excluirá ${nome(item)} e todos os lançamentos/fechamentos vinculados. Prefira inativar ou estornar quando houver histórico real.`:`Esta ação apagará o lançamento de ${moeda(item?.valorPermuta)}. Prefira Estornar quando o registro fizer parte do histórico real.`;$("senhaExcluirPermuta").value="";msg($("mensagemExcluirPermuta"),"");$("modalExcluirPermuta")?.classList.remove("hidden");$("senhaExcluirPermuta")?.focus()}
function fecharExclusao(){deleteCtx=null;$("modalExcluirPermuta")?.classList.add("hidden");if($("senhaExcluirPermuta"))$("senhaExcluirPermuta").value="";msg($("mensagemExcluirPermuta"),"")}
async function refsRelacionadasPermuta(p){const ids=[p.id,...(p.espelhoPermutaId?[p.espelhoPermutaId]:[])],refs=[];for(const pid of ids){for(const col of ["permutaMovimentos","permutaFechamentos"]){const s=await getDocs(query(collection(db,col),where("grupoId","==",grupoAtualId()),where("permutaId","==",pid)));s.forEach(x=>refs.push(x.ref))}refs.push(doc(db,"permutas",pid))}return refs}
async function apagarRefs(refs){for(let i=0;i<refs.length;i+=400){const lote=writeBatch(db);refs.slice(i,i+400).forEach(r=>lote.delete(r));await lote.commit()}}
function sincronizarExclusaoLocal(ctx){
  if(ctx.tipo==="movimento"){
    const m=movimentos.find(x=>x.id===ctx.id),ids=new Set([ctx.id,...(m?.espelhoMovimentoId?[m.espelhoMovimentoId]:[])]);
    movimentos=movimentos.filter(x=>!ids.has(x.id));
  }else{
    const p=permutas.find(x=>x.id===ctx.id);if(!p)return;
    const ids=new Set([p.id,...(p.espelhoPermutaId?[p.espelhoPermutaId]:[])]);
    permutas=permutas.filter(x=>!ids.has(x.id));
    movimentos=movimentos.filter(x=>!ids.has(x.permutaId));
    fechamentos=fechamentos.filter(x=>!ids.has(x.permutaId));
    if(ids.has(detalheId)){detalheId="";$("permutaDetalhe")?.classList.add("hidden")}
    if(ids.has(fechamentoId)){fechamentoId="";$("permutaFechamento")?.classList.add("hidden")}
    if(ids.has(editId)){editId="";$("formPermutaContainer")?.classList.add("hidden")}
  }
  render();
}
async function confirmarExclusao(){if(!deleteCtx||!admin())return;const ctx={...deleteCtx},senha=$("senhaExcluirPermuta")?.value||"";if(!senha)return msg($("mensagemExcluirPermuta"),"Informe a senha do Administrador.");try{msg($("mensagemExcluirPermuta"),"Validando Administrador...");if(!auth.currentUser?.email)throw new Error("usuario-sem-email");await reauthenticateWithCredential(auth.currentUser,EmailAuthProvider.credential(auth.currentUser.email,senha));if(ctx.tipo==="movimento"){const m=movimentos.find(x=>x.id===ctx.id),refs=[doc(db,"permutaMovimentos",ctx.id)];if(m?.espelhoMovimentoId)refs.push(doc(db,"permutaMovimentos",m.espelhoMovimentoId));await apagarRefs(refs)}else{const p=permutas.find(x=>x.id===ctx.id);if(!p)throw new Error("permuta-nao-encontrada");await apagarRefs(await refsRelacionadasPermuta(p))}sincronizarExclusaoLocal(ctx);fecharExclusao();await carregar();emitirAlteracao("permutas")}catch(e){console.error(e);msg($("mensagemExcluirPermuta"),["auth/invalid-credential","auth/wrong-password"].includes(e.code)?"Senha incorreta.":"Não foi possível concluir a exclusão.")}}

async function carregar(){criarPagina();if(carregando||!podeVer())return;carregando=true;const b=$("btnAtualizarPermutas");if(b){b.disabled=true;b.textContent="Atualizando..."}try{[permutas,movimentos,fechamentos]=await Promise.all([listarDocumentos("permutas"),listarDocumentos("permutaMovimentos"),listarDocumentos("permutaFechamentos")]);$("permutaAviso")?.classList.add("hidden");render()}catch(e){console.error("Permutas v2:",e);aviso(`Não foi possível carregar Permutas. ${e?.code||e?.message||"Verifique as regras do Firestore."}`)}finally{carregando=false;if(b){b.disabled=false;b.textContent="Atualizar"}}}
function aviso(t){const a=$("permutaAviso");if(a){a.classList.remove("hidden");a.textContent=t}}
function marcarSujo(){if(!pagina()||pagina().classList.contains("hidden"))return;aviso("Contexto do cabeçalho alterado. Clique em Atualizar para recarregar Permutas.")}
export function abrir(){criarPagina();abrirPagina("permutas");const t=$("tituloPagina");if(t)t.textContent="Permutas";carregar()}
criarPagina();window.addEventListener("sig:periodo-changed",marcarSujo);window.addEventListener("sig:empresa-changed",()=>{apoio=false;marcarSujo()});