import { abrirPagina, state } from "./core.js";
import { $, esc, msg, permite, moeda, listarDocumentos, criarDocumento, grupoAtualId, empresaUnicaSelecionadaId, empresasSelecionadasIds, carregarEmpresasModulo, nomeEmpresa, periodoAno, periodoChave, db } from "./shared.js";
import { writeBatch, doc, collection, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";

const MESES=["jan","fev","mar","abr","mai","jun","jul","ago","set","out","nov","dez"];
const PERIODOS={total:[0,1,2,3,4,5,6,7,8,9,10,11],t1:[0,1,2],t2:[3,4,5],t3:[6,7,8],t4:[9,10,11]};
for(let i=0;i<12;i++)PERIODOS[`m${String(i+1).padStart(2,"0")}`]=[i];
let permutas=[],movimentos=[],centros=[],plano=[],apoioCarregado=false,carregando=false,sujo=false;
const n=v=>{const x=Number(v||0);return Number.isFinite(x)?x:0};
const pagina=()=>$("pagina-permutas");const visivel=()=>pagina()&&!pagina().classList.contains("hidden");
const dataHoje=()=>new Date().toISOString().slice(0,10);

function criarPagina(){
  if(pagina())return;const main=document.querySelector("main.conteudo");if(!main)return;const s=document.createElement("section");s.id="pagina-permutas";s.className="pagina hidden";s.innerHTML=`
    <div class="pagina-cabecalho"><div><span class="eyebrow">CONTROLADORIA & FP&A</span><h2>Permutas</h2><p>Conta-corrente, conciliação, histórico e resultado econômico das permutas.</p></div><div class="acoes-cabecalho"><button id="btnAtualizarPermutas" class="btn-secundario" type="button">Atualizar</button><button id="btnNovaPermuta" class="btn-secundario" type="button">+ Nova permuta</button><button id="btnNovoMovPermuta" class="btn-primario" type="button">+ Movimentação</button></div></div>
    <div id="permutaAviso" class="modulo-aviso hidden"></div>
    <div class="kpi-grid kpi-grid-4"><div class="kpi-card"><span>Saldo contratual</span><strong id="permutaSaldo">—</strong><small>positivo = contraparte nos deve</small></div><div class="kpi-card"><span>Entregue no período</span><strong id="permutaCreditos">—</strong><small>créditos de permuta</small></div><div class="kpi-card"><span>Recebido no período</span><strong id="permutaConsumos">—</strong><small>consumo de crédito</small></div><div class="kpi-card"><span>Resultado econômico</span><strong id="permutaEconomico">—</strong><small>valor de mercado recebido − custo entregue</small></div></div>
    <section id="formPermutaContainer" class="form-card hidden"><div class="form-card-titulo"><div><h3>Nova permuta</h3><p>Cadastre o acordo que será controlado em conta-corrente.</p></div></div><form id="formPermuta"><div class="form-grid form-grid-3">
      <div class="campo"><label for="permutaTipoContraparte">Contraparte</label><select id="permutaTipoContraparte"><option value="cliente">Cliente</option><option value="fornecedor">Fornecedor</option><option value="empresa_grupo">Empresa do grupo</option></select></div>
      <div id="campoPermutaEmpresaGrupo" class="campo hidden"><label for="permutaEmpresaGrupo">Empresa do grupo</label><select id="permutaEmpresaGrupo"></select></div>
      <div id="campoPermutaNome" class="campo"><label for="permutaNome">Nome / razão social</label><input id="permutaNome" required></div>
      <div class="campo"><label for="permutaDocumento">CPF/CNPJ / referência</label><input id="permutaDocumento"></div><div class="campo"><label for="permutaInicio">Início</label><input id="permutaInicio" type="date" required></div><div class="campo"><label for="permutaFim">Fim previsto</label><input id="permutaFim" type="date"></div>
      <div class="campo"><label for="permutaValorAcordado">Valor acordado</label><input id="permutaValorAcordado" type="number" min="0" step="0.01"></div><div class="campo campo-span-2"><label for="permutaDescricao">Objeto / descrição</label><input id="permutaDescricao" required></div><div class="campo campo-span-3"><label for="permutaObservacao">Observação</label><input id="permutaObservacao"></div>
    </div><div class="form-acoes"><button id="btnCancelarPermuta" class="btn-secundario" type="button">Cancelar</button><button class="btn-primario" type="submit">Salvar permuta</button></div><p id="mensagemPermuta" class="mensagem-form"></p></form></section>
    <section id="formMovPermutaContainer" class="form-card hidden"><div class="form-card-titulo"><div><h3>Movimentação de permuta</h3><p>Entregas geram crédito; bens ou serviços recebidos consomem crédito.</p></div></div><form id="formMovPermuta"><div class="form-grid form-grid-3">
      <div class="campo"><label for="movPermutaId">Permuta</label><select id="movPermutaId" required></select></div><div class="campo"><label for="movPermutaData">Data</label><input id="movPermutaData" type="date" required></div><div class="campo"><label for="movPermutaTipo">Movimento</label><select id="movPermutaTipo"><option value="credito">Entregamos · gera crédito</option><option value="consumo">Recebemos · consome crédito</option><option value="ajuste_credito">Ajuste credor</option><option value="ajuste_debito">Ajuste devedor</option></select></div>
      <div class="campo campo-span-2"><label for="movPermutaDescricao">Descrição</label><input id="movPermutaDescricao" required></div><div class="campo"><label for="movPermutaDocumento">NF / documento</label><input id="movPermutaDocumento"></div>
      <div class="campo"><label for="movPermutaValor">Valor da permuta</label><input id="movPermutaValor" type="number" min="0" step="0.01" required></div><div class="campo"><label for="movPermutaCusto">Custo interno do que entregamos</label><input id="movPermutaCusto" type="number" min="0" step="0.01"></div><div class="campo"><label for="movPermutaMercado">Valor de mercado do que recebemos</label><input id="movPermutaMercado" type="number" min="0" step="0.01"></div>
      <div class="campo"><label for="movPermutaCentro">Centro de custo</label><select id="movPermutaCentro"></select></div><div class="campo"><label for="movPermutaConta">Conta gerencial</label><select id="movPermutaConta"></select></div><div class="campo"><label for="movPermutaObservacao">Observação</label><input id="movPermutaObservacao"></div>
    </div><div class="form-acoes"><button id="btnCancelarMovPermuta" class="btn-secundario" type="button">Cancelar</button><button class="btn-primario" type="submit">Salvar movimentação</button></div><p id="mensagemMovPermuta" class="mensagem-form"></p></form></section>
    <div class="fpa-tabs permuta-tabs"><button type="button" class="fpa-tab ativo" data-permuta-view="visao">Visão geral</button><button type="button" class="fpa-tab" data-permuta-view="extrato">Conta-corrente</button><button type="button" class="fpa-tab" data-permuta-view="conciliacao">Conciliação</button><button type="button" class="fpa-tab" data-permuta-view="economico">Análise econômica</button></div>
    <section class="lista-card permuta-view" data-permuta-panel="visao"><div class="lista-cabecalho"><div><h3>Permutas ativas</h3><p id="permutaContexto">—</p></div></div><div class="tabela-container"><table class="tabela"><thead><tr><th>Contraparte</th><th>Acordado</th><th>Entregue</th><th>Recebido</th><th>Saldo</th><th>Último movimento</th><th>Status</th></tr></thead><tbody id="listaPermutas"></tbody></table></div></section>
    <section class="lista-card permuta-view hidden" data-permuta-panel="extrato"><div class="lista-cabecalho"><div><h3>Razão de permutas</h3><p>Histórico do período selecionado no cabeçalho.</p></div></div><div class="tabela-container"><table class="tabela"><thead><tr><th>Data</th><th>Contraparte</th><th>Documento</th><th>Descrição</th><th>Tipo</th><th>Valor</th><th>Saldo após movimento</th></tr></thead><tbody id="listaPermutaMovimentos"></tbody></table></div></section>
    <section class="lista-card permuta-view hidden" data-permuta-panel="conciliacao"><div class="lista-cabecalho"><div><h3>Conciliação</h3><p>Saldos, movimentações e alertas de permutas paradas.</p></div></div><div id="listaPermutaConciliacao"></div></section>
    <section class="lista-card permuta-view hidden" data-permuta-panel="economico"><div class="lista-cabecalho"><div><h3>Resultado econômico</h3><p>Compara custo interno do que entregamos com valor de mercado do que recebemos.</p></div></div><div class="tabela-container"><table class="tabela"><thead><tr><th>Contraparte</th><th>Custo entregue</th><th>Valor recebido</th><th>Resultado econômico</th><th>Leitura</th></tr></thead><tbody id="listaPermutaEconomico"></tbody></table></div></section>`;
  main.appendChild(s);bind();
}

function bind(){
  $("btnAtualizarPermutas")?.addEventListener("click",carregar);$("btnNovaPermuta")?.addEventListener("click",abrirFormPermuta);$("btnNovoMovPermuta")?.addEventListener("click",abrirFormMovimento);$("btnCancelarPermuta")?.addEventListener("click",()=>$("formPermutaContainer")?.classList.add("hidden"));$("btnCancelarMovPermuta")?.addEventListener("click",()=>$("formMovPermutaContainer")?.classList.add("hidden"));
  $("formPermuta")?.addEventListener("submit",salvarPermuta);$("formMovPermuta")?.addEventListener("submit",salvarMovimento);$("permutaTipoContraparte")?.addEventListener("change",alternarContraparte);
  document.querySelectorAll("[data-permuta-view]").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll("[data-permuta-view]").forEach(x=>x.classList.toggle("ativo",x===b));document.querySelectorAll("[data-permuta-panel]").forEach(x=>x.classList.toggle("hidden",x.dataset.permutaPanel!==b.dataset.permutaView))}));
}
function periodoMov(m){const a=Number(String(m.data||"").slice(0,4)),mes=Number(String(m.data||"").slice(5,7))-1;return a===periodoAno()&&(PERIODOS[periodoChave()]||PERIODOS.total).includes(mes)}
function sinal(m){return ["credito","ajuste_credito"].includes(m.tipo)?1:-1}
function movsPermuta(id,filtrarPeriodo=false){return movimentos.filter(x=>x.permutaId===id&&(!filtrarPeriodo||periodoMov(x))).sort((a,b)=>String(a.data||"").localeCompare(String(b.data||"")))}
function saldoPermuta(id){return movsPermuta(id).reduce((s,x)=>s+sinal(x)*n(x.valorPermuta),0)}
function nomePermuta(p){return p.contraparteNome||p.descricao||"Permuta"}
function fmtData(v){return v?String(v).slice(0,10).split("-").reverse().join("/"):"-"}
function leituraSaldo(s){return s>0?"A contraparte ainda nos deve":s<0?"Ainda temos obrigação a entregar":"Conciliada"}

function render(){
  const periodoMovs=movimentos.filter(periodoMov),credito=periodoMovs.filter(x=>sinal(x)>0).reduce((s,x)=>s+n(x.valorPermuta),0),consumo=periodoMovs.filter(x=>sinal(x)<0).reduce((s,x)=>s+n(x.valorPermuta),0),saldo=permutas.reduce((s,p)=>s+saldoPermuta(p.id),0),economico=periodoMovs.filter(x=>x.tipo==="consumo").reduce((s,x)=>s+n(x.valorMercado),0)-periodoMovs.filter(x=>x.tipo==="credito").reduce((s,x)=>s+n(x.custoInterno),0);
  $("permutaSaldo").textContent=moeda(saldo);$("permutaCreditos").textContent=moeda(credito);$("permutaConsumos").textContent=moeda(consumo);$("permutaEconomico").textContent=moeda(economico);$("permutaContexto").textContent=`${empresasSelecionadasIds().length>1?`${empresasSelecionadasIds().length} empresas`:"Empresa selecionada"} · ${periodoChave().toUpperCase()} · ${periodoAno()}`;
  $("listaPermutas").innerHTML=permutas.length?permutas.map(p=>{const ms=movsPermuta(p.id),ent=ms.filter(x=>sinal(x)>0).reduce((s,x)=>s+n(x.valorPermuta),0),rec=ms.filter(x=>sinal(x)<0).reduce((s,x)=>s+n(x.valorPermuta),0),sal=ent-rec,ult=ms.at(-1)?.data;return`<tr><td><strong>${esc(nomePermuta(p))}</strong><small>${esc(p.tipoContraparte==="empresa_grupo"?"Empresa do grupo":p.tipoContraparte||"")}</small></td><td>${moeda(p.valorAcordado)}</td><td>${moeda(ent)}</td><td>${moeda(rec)}</td><td><strong>${moeda(sal)}</strong><small>${esc(leituraSaldo(sal))}</small></td><td>${fmtData(ult)}</td><td>${esc(p.status||"ativo")}</td></tr>`}).join(""):'<tr><td colspan="7">Nenhuma permuta cadastrada.</td></tr>';
  renderExtrato();renderConciliacao();renderEconomico();
}
function renderExtrato(){
  const arr=movimentos.filter(periodoMov).sort((a,b)=>String(a.data||"").localeCompare(String(b.data||""))),saldos=new Map();$("listaPermutaMovimentos").innerHTML=arr.length?arr.map(m=>{const p=permutas.find(x=>x.id===m.permutaId),novo=(saldos.get(m.permutaId)||0)+sinal(m)*n(m.valorPermuta);saldos.set(m.permutaId,novo);return`<tr><td>${fmtData(m.data)}</td><td>${esc(nomePermuta(p||{}))}</td><td>${esc(m.documento||"-")}</td><td>${esc(m.descricao||"")}</td><td>${sinal(m)>0?"Crédito":"Consumo"}</td><td>${moeda(m.valorPermuta)}</td><td><strong>${moeda(novo)}</strong></td></tr>`}).join(""):'<tr><td colspan="7">Sem movimentações no período.</td></tr>';
}
function renderConciliacao(){
  const hoje=new Date(`${dataHoje()}T12:00:00`),diasAlerta=60;$("listaPermutaConciliacao").innerHTML=permutas.length?permutas.map(p=>{const ms=movsPermuta(p.id),ult=ms.at(-1)?.data,sal=saldoPermuta(p.id),dias=ult?Math.floor((hoje-new Date(`${ult}T12:00:00`))/86400000):null,parada=sal!==0&&(dias===null||dias>=diasAlerta);return`<div class="pendencia-item"><div class="pendencia-info"><strong>${esc(nomePermuta(p))}</strong><span>Saldo ${moeda(sal)} · ${ms.length} movimento(s) · último ${fmtData(ult)}</span></div><span class="pendencia-tag ${parada?"alerta":""}">${parada?"Revisar":sal===0?"Conciliada":"Ativa"}</span></div>`}).join(""):'<div class="empty-state">Nenhuma permuta para conciliar.</div>';
}
function renderEconomico(){
  $("listaPermutaEconomico").innerHTML=permutas.length?permutas.map(p=>{const ms=movsPermuta(p.id,true),custo=ms.filter(x=>x.tipo==="credito").reduce((s,x)=>s+n(x.custoInterno),0),mercado=ms.filter(x=>x.tipo==="consumo").reduce((s,x)=>s+n(x.valorMercado),0),res=mercado-custo,leitura=res>0?"Favorável":res<0?"Desfavorável":"Neutra / incompleta";return`<tr><td>${esc(nomePermuta(p))}</td><td>${moeda(custo)}</td><td>${moeda(mercado)}</td><td><strong>${moeda(res)}</strong></td><td>${leitura}</td></tr>`}).join(""):'<tr><td colspan="5">Sem permutas cadastradas.</td></tr>';
}

async function carregar(){
  criarPagina();if(carregando||!permite("controladoria","visualizar")&&!permite("controladoria"))return;carregando=true;const b=$("btnAtualizarPermutas");if(b){b.disabled=true;b.textContent="Atualizando..."}
  try{[permutas,movimentos]=await Promise.all([listarDocumentos("permutas"),listarDocumentos("permutaMovimentos")]);sujo=false;$("permutaAviso")?.classList.add("hidden");render()}catch(e){console.error("Permutas:",e);const a=$("permutaAviso");if(a){a.classList.remove("hidden");a.innerHTML="As coleções de <strong>Permutas</strong> ainda precisam estar liberadas nas regras do Firebase."}}finally{carregando=false;if(b){b.disabled=false;b.textContent="Atualizar"}}
}
async function abrirFormPermuta(){
  if(!empresaUnicaSelecionadaId())return aviso("Para cadastrar uma permuta, selecione apenas uma empresa no cabeçalho.");$("formPermuta")?.reset();$("permutaInicio").value=dataHoje();$("formPermutaContainer")?.classList.remove("hidden");await preencherEmpresasGrupo();alternarContraparte();
}
function alternarContraparte(){const interno=$("permutaTipoContraparte")?.value==="empresa_grupo";$("campoPermutaEmpresaGrupo")?.classList.toggle("hidden",!interno);$("campoPermutaNome")?.classList.toggle("hidden",interno);if($("permutaNome"))$("permutaNome").required=!interno}
async function preencherEmpresasGrupo(){const mapa=await carregarEmpresasModulo(),origem=empresaUnicaSelecionadaId(),s=$("permutaEmpresaGrupo");if(!s)return;s.innerHTML='<option value="">Selecione...</option>'+[...mapa.values()].filter(x=>x.id!==origem).map(x=>`<option value="${esc(x.id)}">${esc(x.nomeFantasia||x.razaoSocial||x.id)}</option>`).join("")}
async function salvarPermuta(e){
  e.preventDefault();const origem=empresaUnicaSelecionadaId();if(!origem)return msg($("mensagemPermuta"),"Selecione uma única empresa.");const tipo=$("permutaTipoContraparte").value,contraparteEmpresaId=tipo==="empresa_grupo"?$("permutaEmpresaGrupo").value:"",contraparteNome=tipo==="empresa_grupo"?nomeEmpresa(contraparteEmpresaId):$("permutaNome").value.trim();if(!contraparteNome||tipo==="empresa_grupo"&&!contraparteEmpresaId)return msg($("mensagemPermuta"),"Informe a contraparte.");
  const base={tipoContraparte:tipo,contraparteNome,contraparteDocumento:$("permutaDocumento").value.trim(),contraparteEmpresaId,descricao:$("permutaDescricao").value.trim(),valorAcordado:n($("permutaValorAcordado").value),dataInicio:$("permutaInicio").value,dataFim:$("permutaFim").value,status:"ativo",observacao:$("permutaObservacao").value.trim()};
  try{msg($("mensagemPermuta"),"Salvando...");if(tipo!=="empresa_grupo"){await criarDocumento("permutas",base)}else{const grupoId=grupoAtualId(),lote=writeBatch(db),a=doc(collection(db,"permutas")),b=doc(collection(db,"permutas")),gid=crypto.randomUUID(),comum={grupoId,permutaGrupoId:gid,descricao:base.descricao,valorAcordado:base.valorAcordado,dataInicio:base.dataInicio,dataFim:base.dataFim,status:"ativo",observacao:base.observacao,criadoPor:state.usuario.id,criadoEm:serverTimestamp(),atualizadoEm:serverTimestamp(),tipoContraparte:"empresa_grupo"};lote.set(a,{...comum,empresaId:origem,contraparteEmpresaId,contraparteNome:nomeEmpresa(contraparteEmpresaId),espelhoPermutaId:b.id});lote.set(b,{...comum,empresaId:contraparteEmpresaId,contraparteEmpresaId:origem,contraparteNome:nomeEmpresa(origem),espelhoPermutaId:a.id});await lote.commit()}$("formPermutaContainer").classList.add("hidden");msg($("mensagemPermuta"),"Permuta cadastrada.",true);await carregar()}catch(err){console.error(err);msg($("mensagemPermuta"),"Não foi possível cadastrar a permuta.")}
}

async function carregarApoio(){if(apoioCarregado)return;[centros,plano]=await Promise.all([listarDocumentos("centrosCusto"),listarDocumentos("planoContasGerencial")]);apoioCarregado=true}
async function abrirFormMovimento(){
  const emp=empresaUnicaSelecionadaId();if(!emp)return aviso("Para movimentar permuta, selecione apenas uma empresa no cabeçalho.");await carregarApoio();const ps=permutas.filter(x=>x.empresaId===emp&&x.status!=="encerrado"),sp=$("movPermutaId");sp.innerHTML='<option value="">Selecione...</option>'+ps.map(x=>`<option value="${x.id}">${esc(nomePermuta(x))}</option>`).join("");$("movPermutaCentro").innerHTML='<option value="">Sem centro específico</option>'+centros.filter(x=>x.status!=="inativo").map(x=>`<option value="${x.id}">${esc(x.codigo||"")} · ${esc(x.nome||"")}</option>`).join("");$("movPermutaConta").innerHTML='<option value="">Sem conta específica</option>'+plano.filter(x=>x.status!=="inativo").map(x=>`<option value="${x.id}">${esc(x.codigo||"")} · ${esc(x.nome||"")}</option>`).join("");$("formMovPermuta")?.reset();$("movPermutaData").value=dataHoje();$("formMovPermutaContainer")?.classList.remove("hidden")
}
async function salvarMovimento(e){
  e.preventDefault();const empresaId=empresaUnicaSelecionadaId(),permuta=permutas.find(x=>x.id===$("movPermutaId").value);if(!empresaId||!permuta)return msg($("mensagemMovPermuta"),"Selecione a permuta.");const tipo=$("movPermutaTipo").value,d={permutaId:permuta.id,data:$("movPermutaData").value,tipo,descricao:$("movPermutaDescricao").value.trim(),documento:$("movPermutaDocumento").value.trim(),valorPermuta:n($("movPermutaValor").value),custoInterno:n($("movPermutaCusto").value),valorMercado:n($("movPermutaMercado").value),centroCustoId:$("movPermutaCentro").value,contaGerencialId:$("movPermutaConta").value,observacao:$("movPermutaObservacao").value.trim()};if(!d.valorPermuta)return msg($("mensagemMovPermuta"),"Informe o valor da permuta.");
  try{msg($("mensagemMovPermuta"),"Salvando...");if(permuta.tipoContraparte!=="empresa_grupo"||!permuta.espelhoPermutaId){await criarDocumento("permutaMovimentos",d)}else{const lote=writeBatch(db),grupoId=grupoAtualId(),a=doc(collection(db,"permutaMovimentos")),b=doc(collection(db,"permutaMovimentos")),gid=crypto.randomUUID(),oposto=tipo==="credito"?"consumo":tipo==="consumo"?"credito":tipo==="ajuste_credito"?"ajuste_debito":"ajuste_credito",comum={grupoId,movimentoGrupoId:gid,data:d.data,descricao:d.descricao,documento:d.documento,valorPermuta:d.valorPermuta,observacao:d.observacao,criadoPor:state.usuario.id,criadoEm:serverTimestamp(),atualizadoEm:serverTimestamp()};lote.set(a,{...comum,empresaId,permutaId:permuta.id,tipo:d.tipo,custoInterno:d.custoInterno,valorMercado:d.valorMercado,centroCustoId:d.centroCustoId,contaGerencialId:d.contaGerencialId,espelhoMovimentoId:b.id});lote.set(b,{...comum,empresaId:permuta.contraparteEmpresaId,permutaId:permuta.espelhoPermutaId,tipo:oposto,custoInterno:0,valorMercado:d.tipo==="credito"?d.valorMercado:0,centroCustoId:"",contaGerencialId:"",espelhoMovimentoId:a.id,economicoPendente:d.tipo!=="credito"});await lote.commit()}$("formMovPermutaContainer").classList.add("hidden");msg($("mensagemMovPermuta"),"Movimentação registrada.",true);await carregar()}catch(err){console.error(err);msg($("mensagemMovPermuta"),"Não foi possível registrar a movimentação.")}
}
function aviso(texto){const a=$("permutaAviso");if(a){a.classList.remove("hidden");a.textContent=texto}}
function marcarSujo(){if(!visivel())return;sujo=true;const a=$("permutaAviso");if(a){a.classList.remove("hidden");a.textContent="Filtros do cabeçalho alterados. Clique em Atualizar para consultar o novo contexto."}}

export function abrir(){criarPagina();abrirPagina("permutas");const t=$("tituloPagina");if(t)t.textContent="Permutas";carregar()}
criarPagina();window.addEventListener("sig:periodo-changed",marcarSujo);window.addEventListener("sig:empresa-changed",()=>{apoioCarregado=false;marcarSujo()});
