import { abrirPagina, admin } from "./core.js";
import { $, esc, msg, permite, state, listarDocumentos, criarDocumento, atualizarDocumento, empresaUnicaSelecionadaId, empresasSelecionadasIds, dataBr, emitirAlteracao } from "./shared.js";
import { confirmarAcaoAdministrativa, atualizarComAuditoria } from "./admin-actions.js";

const LEGADO=Object.freeze({
  recurso:["LAJE","MOURÃO","MAQ.1","MAQ.2"],
  item:["TRELIÇA","PAINEL","PAINEL E TRELIÇA","MOURÃO","COBOGÓ","COMPENSADOR","BANDEJA","NA"],
  concretador:["ALEX","ANDRÉ","ANTÔNIO","GILBERTO","GILVAN","NA"]
});
const TIPOS={recurso:"Recursos / máquinas",item:"Itens produzidos",concretador:"Concretadores"};
let registros=[],cadastros=[],editId=null,busy=false;
const pagina=()=>$("pagina-producao");
const n=v=>{const x=Number(v||0);return Number.isFinite(x)?x:0};
const podeVer=()=>admin()||["visualizar","lancar","editar","cadastros"].some(a=>permite("producao",a));
const podeLancar=()=>admin()||permite("producao","lancar");
const podeEditar=()=>admin()||permite("producao","editar");
const podeCadastros=()=>admin()||permite("producao","cadastros");
const norm=v=>String(v||"").trim().normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase();

function garantirCss(){if(document.querySelector('link[href^="production.css"]'))return;const l=document.createElement("link");l.rel="stylesheet";l.href="production.css?v=1";document.head.appendChild(l)}
function garantirMenu(){
  const nav=document.querySelector(".sidebar-menu");if(!nav)return;
  let b=$("menuProducao");
  if(!b){b=document.createElement("button");b.id="menuProducao";b.className="menu-item hidden";b.dataset.pagina="producao";b.type="button";b.textContent="Produção";const ref=$("menuComercial")||$("menuControladoria")||nav.querySelector(".menu-separador");if(ref)nav.insertBefore(b,ref);else nav.appendChild(b)}
  b.classList.toggle("hidden",!podeVer());
  if(b.dataset.productionBound!=="1"){b.dataset.productionBound="1";b.addEventListener("click",async e=>{e.preventDefault();e.stopImmediatePropagation();if(!podeVer())return;abrirPagina("producao");await carregar()},true)}
}
function criarPagina(){
  if(pagina())return;
  const main=document.querySelector("main.conteudo");if(!main)return;
  const s=document.createElement("section");s.id="pagina-producao";s.className="pagina hidden production-page";s.innerHTML=`
<div class="pagina-cabecalho production-head"><div><span class="eyebrow">OPERAÇÃO</span><h2>Produção</h2><p>Registro diário de produção, horas trabalhadas e produtividade por recurso.</p></div><div class="acoes-cabecalho"><button id="btnProducaoCadastros" class="btn-secundario" type="button">Cadastros</button><button id="btnNovaProducao" class="btn-primario" type="button">+ Novo lançamento</button><button id="btnAtualizarProducao" class="btn-secundario" type="button">Atualizar</button></div></div>
<div id="producaoAviso" class="modulo-aviso hidden"></div>
<div class="production-kpis"><div class="kpi-card"><span>Produção filtrada</span><strong id="prodKpiQtd">—</strong><small>unidades produzidas</small></div><div class="kpi-card"><span>Horas trabalhadas</span><strong id="prodKpiHoras">—</strong><small>horas registradas</small></div><div class="kpi-card"><span>Produtividade média</span><strong id="prodKpiMedia">—</strong><small>quantidade ÷ horas</small></div><div class="kpi-card"><span>Lançamentos</span><strong id="prodKpiRegs">—</strong><small>registros ativos</small></div></div>
<section id="producaoFormBox" class="form-card hidden"><div class="form-card-titulo"><div><h3 id="producaoFormTitulo">Novo lançamento</h3><p>Campos migrados do Gestão Salvador. Produção por hora é calculada automaticamente.</p></div></div><form id="formProducao"><div class="form-grid form-grid-3"><div class="campo"><label for="prodData">Data</label><input id="prodData" type="date" required></div><div class="campo"><label for="prodRecurso">Produção / máquina</label><select id="prodRecurso" required></select></div><div class="campo"><label for="prodQuantidade">Quantidade produzida</label><input id="prodQuantidade" type="number" min="0" step="1" required></div><div class="campo"><label for="prodHoras">Horas trabalhadas</label><input id="prodHoras" type="number" min="0" step="0.01" required></div><div class="campo"><label for="prodMedia">Produção por hora</label><input id="prodMedia" type="text" readonly value="0"></div><div class="campo"><label for="prodItem">Item</label><select id="prodItem"></select></div><div class="campo"><label for="prodConcretador">Concretador</label><select id="prodConcretador"></select></div></div><div class="form-acoes"><button id="btnCancelarProducao" class="btn-secundario" type="button">Cancelar</button><button class="btn-primario" type="submit">Salvar lançamento</button></div><p id="prodFormMsg" class="mensagem-form"></p></form></section>
<section id="producaoCadastrosBox" class="form-card hidden"><div class="form-card-titulo"><div><h3>Cadastros de Produção</h3><p>Listas deixam de ficar presas no código. A base inicial reproduz as opções do Script.</p></div><button id="btnFecharCadastrosProducao" class="btn-secundario" type="button">Fechar</button></div><div class="production-master-grid">${Object.entries(TIPOS).map(([k,l])=>`<div class="production-master"><h4>${l}</h4><div class="production-master-add"><input data-master-input="${k}" placeholder="Novo cadastro"><button class="btn-secundario" data-master-add="${k}" type="button">Adicionar</button></div><div data-master-list="${k}"></div></div>`).join("")}</div><p id="prodMasterMsg" class="mensagem-form"></p></section>
<section class="lista-card"><div class="lista-cabecalho production-toolbar"><div><h3>Análise da produção</h3><p>Filtros e indicadores calculados a partir dos lançamentos ativos.</p></div><div class="production-filtros"><select id="prodFiltroAno"></select><select id="prodFiltroMes"><option value="">Ano inteiro</option>${Array.from({length:12},(_,i)=>`<option value="${String(i+1).padStart(2,"0")}">${new Date(2026,i,1).toLocaleString("pt-BR",{month:"long"})}</option>`).join("")}</select><select id="prodFiltroRecurso"><option value="">Todos os recursos</option></select><select id="prodFiltroItem"><option value="">Todos os itens</option></select></div></div><div class="production-charts"><div class="production-card"><h4>Produção mensal</h4><div id="prodGraficoMensal" class="production-bars"></div></div><div class="production-card"><h4>Total por produção / máquina</h4><div id="prodGraficoRecurso" class="production-bars"></div></div><div class="production-card"><h4>Média por hora</h4><div id="prodGraficoMedia" class="production-bars"></div></div></div></section>
<section class="lista-card"><div class="lista-cabecalho"><div><h3>Histórico de lançamentos</h3><p id="prodQtdRegistros">—</p></div></div><div class="tabela-container"><table class="tabela"><thead><tr><th>Data</th><th>Produção</th><th>Item</th><th>Quantidade</th><th>Horas</th><th>Prod./hora</th><th>Concretador</th><th>Ações</th></tr></thead><tbody id="prodLista"></tbody></table></div></section>`;
  main.appendChild(s);ligarEventos();
}
function opcoes(tipo,{vazio=true}={}){
  const custom=cadastros.filter(x=>x.tipo===tipo&&x.ativo!==false).map(x=>x.nome).filter(Boolean);
  const valores=custom.length?custom:LEGADO[tipo];
  return `${vazio?'<option value="">Selecione...</option>':''}${[...new Set(valores)].sort((a,b)=>a.localeCompare(b,"pt-BR")).map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join("")}`;
}
function atualizarSelects(){
  const r=$("prodRecurso"),i=$("prodItem"),c=$("prodConcretador"),fr=$("prodFiltroRecurso"),fi=$("prodFiltroItem");
  const vr=r?.value,vi=i?.value,vc=c?.value,vfr=fr?.value,vfi=fi?.value;if(r)r.innerHTML=opcoes("recurso");if(i)i.innerHTML=opcoes("item");if(c)c.innerHTML=opcoes("concretador");if(fr)fr.innerHTML='<option value="">Todos os recursos</option>'+opcoes("recurso",{vazio:false});if(fi)fi.innerHTML='<option value="">Todos os itens</option>'+opcoes("item",{vazio:false});if(r&&vr)r.value=vr;if(i&&vi)i.value=vi;if(c&&vc)c.value=vc;if(fr&&vfr)fr.value=vfr;if(fi&&vfi)fi.value=vfi
}
function anosDisponiveis(){const atual=new Date().getFullYear(),set=new Set([atual,...registros.map(x=>Number(String(x.data||"").slice(0,4))).filter(Boolean)]);return [...set].sort((a,b)=>b-a)}
function atualizarFiltroAno(){const s=$("prodFiltroAno"),atual=s?.value||String(new Date().getFullYear());if(!s)return;s.innerHTML=anosDisponiveis().map(a=>`<option value="${a}">${a}</option>`).join("");if([...s.options].some(o=>o.value===atual))s.value=atual}
function filtrados(){const ano=$("prodFiltroAno")?.value||"",mes=$("prodFiltroMes")?.value||"",rec=$("prodFiltroRecurso")?.value||"",item=$("prodFiltroItem")?.value||"";return registros.filter(x=>x.status!=="estornado"&&(!ano||String(x.data||"").startsWith(ano))&&(!mes||String(x.data||"").slice(5,7)===mes)&&(!rec||x.recurso===rec)&&(!item||x.item===item))}
function fmt(v,d=2){return n(v).toLocaleString("pt-BR",{maximumFractionDigits:d})}
function barras(alvo,dados,sufixo="") {const el=$(alvo);if(!el)return;if(!dados.length){el.innerHTML='<p class="production-empty">Sem dados no filtro selecionado.</p>';return}const max=Math.max(...dados.map(x=>n(x.valor)),1);el.innerHTML=dados.map(x=>`<div class="production-bar-row"><span title="${esc(x.label)}">${esc(x.label)}</span><div><i style="width:${Math.max(2,n(x.valor)/max*100)}%"></i></div><strong>${fmt(x.valor)}${sufixo}</strong></div>`).join("")}
function render(){
  const arr=filtrados(),q=arr.reduce((s,x)=>s+n(x.quantidade),0),h=arr.reduce((s,x)=>s+n(x.horasTrabalhadas),0);$("prodKpiQtd").textContent=fmt(q,0);$("prodKpiHoras").textContent=fmt(h);$("prodKpiMedia").textContent=fmt(h?q/h:0);$("prodKpiRegs").textContent=String(arr.length);$("prodQtdRegistros").textContent=`${arr.length} lançamento(s) no filtro`;
  const ano=$("prodFiltroAno")?.value||String(new Date().getFullYear()),meses=Array.from({length:12},(_,i)=>({label:new Date(2026,i,1).toLocaleString("pt-BR",{month:"short"}),valor:arr.filter(x=>String(x.data||"").startsWith(`${ano}-${String(i+1).padStart(2,"0")}`)).reduce((s,x)=>s+n(x.quantidade),0)}));barras("prodGraficoMensal",meses);
  const porRec={};arr.forEach(x=>{const k=x.recurso||"Não informado";porRec[k]??={q:0,h:0};porRec[k].q+=n(x.quantidade);porRec[k].h+=n(x.horasTrabalhadas)});barras("prodGraficoRecurso",Object.entries(porRec).map(([label,v])=>({label,valor:v.q})).sort((a,b)=>b.valor-a.valor));barras("prodGraficoMedia",Object.entries(porRec).map(([label,v])=>({label,valor:v.h?v.q/v.h:0})).sort((a,b)=>b.valor-a.valor));
  const tb=$("prodLista");if(tb)tb.innerHTML=arr.sort((a,b)=>String(b.data||"").localeCompare(String(a.data||""))).map(x=>`<tr class="${x.status==="estornado"?"sig-admin-estornado":""}"><td>${dataBr(x.data)}</td><td><strong>${esc(x.recurso||"-")}</strong></td><td>${esc(x.item||"-")}</td><td>${fmt(x.quantidade,0)}</td><td>${fmt(x.horasTrabalhadas)}</td><td>${fmt(x.producaoPorHora)}</td><td>${esc(x.concretador||"-")}</td><td><div class="acoes-tabela">${podeEditar()?`<button class="btn-acao destaque" data-prod-edit="${x.id}" type="button">Editar</button>`:""}${admin()?`<button class="btn-acao perigo" data-prod-estorno="${x.id}" type="button">Estornar ADM</button>`:""}</div></td></tr>`).join("")||'<tr><td colspan="8">Nenhum lançamento encontrado.</td></tr>';
  document.querySelectorAll("[data-prod-edit]").forEach(b=>b.addEventListener("click",()=>abrirEdicao(b.dataset.prodEdit)));document.querySelectorAll("[data-prod-estorno]").forEach(b=>b.addEventListener("click",()=>estornar(b.dataset.prodEstorno)))
}
function renderCadastros(){Object.keys(TIPOS).forEach(tipo=>{const el=document.querySelector(`[data-master-list="${tipo}"]`);if(!el)return;const custom=cadastros.filter(x=>x.tipo===tipo);const base=custom.length?custom:LEGADO[tipo].map(nome=>({id:"",nome,ativo:true,legado:true}));el.innerHTML=base.sort((a,b)=>a.nome.localeCompare(b.nome,"pt-BR")).map(x=>`<div class="production-master-row"><span>${esc(x.nome)}</span>${x.legado?'<small>base do Script</small>':`<button type="button" data-master-toggle="${x.id}">${x.ativo===false?"Reativar":"Inativar"}</button>`}</div>`).join("")});document.querySelectorAll("[data-master-toggle]").forEach(b=>b.addEventListener("click",()=>toggleCadastro(b.dataset.masterToggle)))}
async function carregar(){
  if(busy||!podeVer())return;busy=true;msg($("producaoAviso"),"");try{const [r,c]=await Promise.all([listarDocumentos("producaoLancamentos"),listarDocumentos("operacaoCadastros")]);registros=r;cadastros=c;atualizarSelects();atualizarFiltroAno();render();renderCadastros();$("producaoAviso")?.classList.add("hidden")}catch(e){console.error(e);const a=$("producaoAviso");if(a){a.classList.remove("hidden");a.textContent="A tela de Produção está em homologação. Para gravar e consultar dados reais, publique as Firestore Rules desta versão."}registros=[];cadastros=[];atualizarSelects();atualizarFiltroAno();render();renderCadastros()}finally{busy=false}}
function calcularMedia(){const q=n($("prodQuantidade")?.value),h=n($("prodHoras")?.value);if($("prodMedia"))$("prodMedia").value=fmt(h?q/h:0)}
function limparForm(){editId=null;$("formProducao")?.reset();if($("prodData"))$("prodData").value=new Date().toISOString().slice(0,10);if($("producaoFormTitulo"))$("producaoFormTitulo").textContent="Novo lançamento";msg($("prodFormMsg"),"");calcularMedia();atualizarSelects()}
function abrirNovo(){if(!podeLancar())return alert("Seu perfil não pode registrar produção.");if(!empresaUnicaSelecionadaId())return alert("Selecione apenas uma empresa no cabeçalho para lançar produção.");limparForm();$("producaoFormBox")?.classList.remove("hidden");$("producaoFormBox")?.scrollIntoView({behavior:"smooth",block:"start"})}
function abrirEdicao(id){if(!podeEditar())return;const x=registros.find(v=>v.id===id);if(!x)return;editId=id;$("prodData").value=x.data||"";$("prodRecurso").value=x.recurso||"";$("prodQuantidade").value=n(x.quantidade);$("prodHoras").value=n(x.horasTrabalhadas);$("prodItem").value=x.item||"";$("prodConcretador").value=x.concretador||"";if($("producaoFormTitulo"))$("producaoFormTitulo").textContent="Editar lançamento";calcularMedia();$("producaoFormBox")?.classList.remove("hidden");$("producaoFormBox")?.scrollIntoView({behavior:"smooth",block:"start"})}
function validar(payload){const p=norm(payload.recurso),item=norm(payload.item);if(!payload.data||!p)throw new Error("Preencha data e produção/máquina.");if(payload.quantidade<0||payload.horasTrabalhadas<0)throw new Error("Quantidade e horas não podem ser negativas.");if(p==="LAJE"&&!['TRELIÇA','PAINEL','PAINEL E TRELIÇA','NA'].includes(item))throw new Error("Para LAJE, selecione TRELIÇA, PAINEL, PAINEL E TRELIÇA ou NA.");if((p==="MAQ.1"||p==="MAQ.2")&&!item)payload.item="BANDEJA";payload.producaoPorHora=payload.horasTrabalhadas?payload.quantidade/payload.horasTrabalhadas:0;return payload}
async function salvar(e){e.preventDefault();const emp=empresaUnicaSelecionadaId();if(!emp)return alert("Selecione apenas uma empresa no cabeçalho.");const payload=validar({empresaId:emp,data:$("prodData").value,recurso:$("prodRecurso").value,quantidade:n($("prodQuantidade").value),horasTrabalhadas:n($("prodHoras").value),item:$("prodItem").value,concretador:$("prodConcretador").value,status:"ativo",origem:"sig",atualizadoPor:state.usuario?.id||""});try{msg($("prodFormMsg"),"Salvando...");if(editId){if(!podeEditar())throw new Error("sem-permissao");await atualizarDocumento("producaoLancamentos",editId,payload)}else{if(!podeLancar())throw new Error("sem-permissao");await criarDocumento("producaoLancamentos",payload)}msg($("prodFormMsg"),"Lançamento salvo.",true);emitirAlteracao("producao");await carregar();setTimeout(()=>{$("producaoFormBox")?.classList.add("hidden");limparForm()},350)}catch(err){console.error(err);msg($("prodFormMsg"),err?.message?.includes("permission")?"As Firestore Rules da Produção ainda não estão publicadas.":(err.message||"Não foi possível salvar."))}}
async function estornar(id){const x=registros.find(v=>v.id===id);if(!x||x.status==="estornado")return;const ok=await confirmarAcaoAdministrativa({titulo:"Estornar lançamento de produção",descricao:`O lançamento de ${x.recurso||"produção"} em ${dataBr(x.data)} deixará de compor indicadores, mas continuará no histórico.`,motivoLabel:"Motivo obrigatório do estorno",confirmarTexto:"Estornar lançamento",perigosa:true});if(!ok)return;try{await atualizarComAuditoria({colecao:"producaoLancamentos",id:x.id,empresaId:x.empresaId,modulo:"producao",acao:"estorno",motivo:ok.motivo,resumo:`Estorno de produção ${x.recurso||""} em ${x.data||""}`,snapshotAntes:x,alteracoes:{status:"estornado",motivoEstorno:ok.motivo,estornadoPor:state.usuario?.id||"",estornadoEm:new Date().toISOString()}});emitirAlteracao("producao");await carregar()}catch(e){console.error(e);alert("Não foi possível estornar o lançamento.")}}
async function adicionarCadastro(tipo){if(!podeCadastros())return;const input=document.querySelector(`[data-master-input="${tipo}"]`),nome=String(input?.value||"").trim();if(!nome)return;const emp=empresaUnicaSelecionadaId();if(!emp)return alert("Selecione apenas uma empresa no cabeçalho.");if(cadastros.some(x=>x.tipo===tipo&&norm(x.nome)===norm(nome)))return msg($("prodMasterMsg"),"Este cadastro já existe.");try{await criarDocumento("operacaoCadastros",{empresaId:emp,tipo,nome,ativo:true,origem:"sig"});if(input)input.value="";msg($("prodMasterMsg"),"Cadastro incluído.",true);await carregar()}catch(e){console.error(e);msg($("prodMasterMsg"),"Não foi possível salvar o cadastro.")}}
async function toggleCadastro(id){if(!podeCadastros())return;const x=cadastros.find(v=>v.id===id);if(!x)return;try{await atualizarDocumento("operacaoCadastros",id,{ativo:x.ativo===false});await carregar()}catch(e){console.error(e);msg($("prodMasterMsg"),"Não foi possível alterar o cadastro.")}}
function ligarEventos(){$("btnNovaProducao")?.addEventListener("click",abrirNovo);$("btnAtualizarProducao")?.addEventListener("click",carregar);$("btnCancelarProducao")?.addEventListener("click",()=>{$("producaoFormBox")?.classList.add("hidden");limparForm()});$("formProducao")?.addEventListener("submit",salvar);["prodQuantidade","prodHoras"].forEach(id=>$(id)?.addEventListener("input",calcularMedia));["prodFiltroAno","prodFiltroMes","prodFiltroRecurso","prodFiltroItem"].forEach(id=>$(id)?.addEventListener("change",render));$("btnProducaoCadastros")?.addEventListener("click",()=>{$("producaoCadastrosBox")?.classList.toggle("hidden");renderCadastros()});$("btnFecharCadastrosProducao")?.addEventListener("click",()=>$("producaoCadastrosBox")?.classList.add("hidden"));document.querySelectorAll("[data-master-add]").forEach(b=>b.addEventListener("click",()=>adicionarCadastro(b.dataset.masterAdd)))}
function atualizarPermissoes(){garantirMenu();$("btnNovaProducao")?.classList.toggle("hidden",!podeLancar());$("btnProducaoCadastros")?.classList.toggle("hidden",!podeCadastros())}
function instalar(){garantirCss();garantirMenu();criarPagina();atualizarPermissoes()}
instalar();window.addEventListener("sig:ready",()=>{instalar();if(podeVer())carregar()});window.addEventListener("sig:empresa-contexto",()=>{if(!pagina()?.classList.contains("hidden"))carregar()});window.addEventListener("sig:data-changed",e=>{if(e.detail?.modulo==="producao"&&!pagina()?.classList.contains("hidden"))carregar()});
