import { collection, addDoc, updateDoc, doc, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";
import { $, on, esc, norm, msg, db, state, abrirPagina, carregarAdmin, atualizarResumo } from "./core.js";

const DEF=[
 ["dashboard","Dashboard",[["visualizar","Visualizar"]]],
 ["contratos","Contratos",[["visualizar","Visualizar"],["cadastrar","Cadastrar"],["editar","Editar"],["anexar","Anexar documentos"],["aprovar","Aprovar"],["excluir","Excluir"]]],
 ["prestadores","Prestadores & Oficinas",[["visualizar","Visualizar"],["cadastrar","Cadastrar"],["editar","Editar"],["avaliar","Avaliar"],["excluir","Excluir"]]],
 ["frota","Frota",[["visualizar","Visualizar"],["cadastrar","Cadastrar"],["editar","Editar"],["manutencao","Registrar manutenção"],["obrigacoes","Gerir IPVA/licenciamento/multas"],["excluir","Excluir"]]],
 ["almoxarifado","Almoxarifado",[["visualizar","Visualizar"],["cadastrar","Cadastrar item"],["solicitar","Solicitar"],["movimentar","Entregar/receber"],["prorrogar","Autorizar prorrogação"],["editar","Editar"],["ajustar","Ajustar saldo"],["excluir","Excluir"]]],
 ["cotacoes","Solicitações & Cotações",[["visualizar","Visualizar"],["solicitar","Solicitar"],["cotacao","Registrar cotação"],["anexar","Anexar proposta"],["aprovar","Aprovar"],["editar","Editar"]]],
 ["controladoria","Controladoria & FP&A",[["visualizar","Visualizar"],["dre","Visualizar DRE Gerencial"],["balanco","Visualizar Balanço Patrimonial"],["realizado","Editar realizado"],["importar","Importar realizado"],["budget","Editar Budget"],["forecast","Editar Forecast"],["premissas","Gerir premissas"],["imobilizado","Gerir Imobilizado & CAPEX"],["consorciosVisualizar","Visualizar consórcios"],["consorciosEditar","Gerir consórcios"],["planoContas","Gerir plano de contas"],["centrosCusto","Gerir centros de custo"],["caixaVisualizar","Visualizar fluxo de caixa"],["caixaLancar","Lançar/editar caixa"],["caixaContas","Gerir contas bancárias"],["caixaFixos","Gerir compromissos fixos"],["fechamento","Gerir régua de fechamento"],["fecharCompetencia","Fechar/reabrir competência"],["prestacao","Gerar prestação de contas"],["prestacaoComentar","Editar comentários da prestação"],["editar","Administração FP&A"]]],
 ["governanca","Governança & Compliance",[["visualizar","Visualizar"],["auditar","Executar auditoria"],["evidencias","Anexar evidências"],["planoAcao","Gerir planos de ação"],["validar","Validar/encerrar auditoria"],["configurar","Configurar programas e indicadores"]]],
 ["planosAcao","Planos de Ação",[["visualizar","Visualizar todos da empresa"],["cadastrar","Criar para outros usuários"],["editar","Editar planos"],["concluir","Concluir planos de terceiros"],["reatribuir","Reatribuir responsável"]]],
 ["administracao","Administração",[["visualizar","Visualizar"]]],
 ["empresas","Empresas",[["visualizar","Visualizar"],["cadastrar","Cadastrar"],["editar","Editar"],["inativar","Inativar"],["excluir","Excluir"]]],
 ["usuarios","Usuários",[["visualizar","Visualizar"],["cadastrar","Cadastrar"],["editar","Editar"],["inativar","Inativar"],["resetarSenha","Redefinir senha"]]],
 ["perfisAcesso","Perfis de Acesso",[["visualizar","Visualizar"],["cadastrar","Cadastrar"],["editar","Editar"],["inativar","Inativar"]]],
 ["grupoEmpresarial","Grupo Empresarial",[["visualizar","Visualizar"],["editar","Editar"]]]
].map(([modulo,nome,acoes])=>({modulo,nome,acoes:acoes.map(([id,n])=>({id,nome:n}))}));

let editId=null;
const grade=$("gradePermissoesPerfil"),form=$("formPerfil"),box=$("formPerfilContainer"),titulo=$("tituloFormPerfil"),nome=$("perfilNome"),desc=$("perfilDescricao"),mensagem=$("mensagemPerfil"),lista=$("listaPerfis"),qtd=$("quantidadePerfis"),busca=$("buscaPerfil");
function gerar(){if(!grade)return;grade.innerHTML=DEF.map(d=>`<div class="permissao-modulo"><div class="permissao-modulo-titulo">${esc(d.nome)}</div><div class="permissao-acoes">${d.acoes.map(a=>`<label class="permissao-opcao"><input type="checkbox" class="checkbox-permissao" data-modulo="${d.modulo}" data-acao="${a.id}"><span>${esc(a.nome)}</span></label>`).join("")}</div></div>`).join("");document.querySelectorAll('.checkbox-permissao:not([data-acao="visualizar"])').forEach(c=>on(c,"change",()=>{if(c.checked){const v=document.querySelector(`.checkbox-permissao[data-modulo="${c.dataset.modulo}"][data-acao="visualizar"]`);if(v)v.checked=true}}));document.querySelectorAll('.checkbox-permissao[data-acao="visualizar"]').forEach(c=>on(c,"change",()=>{if(!c.checked)document.querySelectorAll(`.checkbox-permissao[data-modulo="${c.dataset.modulo}"]`).forEach(x=>x.checked=false)}))}
function limpar(){editId=null;form?.reset();if(titulo)titulo.textContent="Novo perfil";msg(mensagem,"");document.querySelectorAll(".checkbox-permissao").forEach(c=>c.checked=false);const d=document.querySelector('.checkbox-permissao[data-modulo="dashboard"][data-acao="visualizar"]');if(d)d.checked=true}
function coletar(){const p={};DEF.forEach(d=>{p[d.modulo]={};d.acoes.forEach(a=>{const c=document.querySelector(`.checkbox-permissao[data-modulo="${d.modulo}"][data-acao="${a.id}"]`);p[d.modulo][a.id]=c?.checked===true})});return p}
function preencher(p={}){document.querySelectorAll(".checkbox-permissao").forEach(c=>{let valor=p?.[c.dataset.modulo]?.[c.dataset.acao];if(valor===undefined&&c.dataset.modulo==="controladoria"&&["dre","balanco"].includes(c.dataset.acao)&&p?.controladoria?.visualizar===true)valor=true;c.checked=valor===true})}
function contar(p={}){return Object.values(p).reduce((t,a)=>t+(a&&typeof a==="object"?Object.values(a).filter(Boolean).length:0),0)}
function users(id){return[...state.usuarios.values()].filter(u=>u.perfilId===id)}
function abrir(p=null){limpar();if(p){editId=p.id;if(titulo)titulo.textContent="Editar perfil";nome.value=p.nome||"";desc.value=p.descricao||"";preencher(p.permissoes||{})}box?.classList.remove("hidden");nome?.focus()}
export function renderPerfis(filtro=""){const t=norm(filtro);const arr=[...state.perfis.values()].filter(p=>!t||norm(p.nome).includes(t)).sort((a,b)=>a.acessoTotal===true?-1:b.acessoTotal===true?1:String(a.nome||"").localeCompare(String(b.nome||""),"pt-BR"));if(qtd)qtd.textContent=`${state.perfis.size} perfil(is) cadastrado(s)`;if(!lista)return;if(!arr.length){lista.innerHTML='<tr><td colspan="6">Nenhum perfil encontrado.</td></tr>';return}lista.innerHTML=arr.map(p=>{const prot=p.acessoTotal===true||p.id==="administrador";return`<tr><td class="celula-principal"><strong>${esc(p.nome||p.id)}</strong><span>${esc(p.descricao||"Sem descrição")}</span></td><td>${p.acessoTotal===true?'<span class="selo-sistema">Sistema</span>':"Personalizado"}</td><td>${p.acessoTotal===true?"Todas":`${contar(p.permissoes)} ativa(s)`}</td><td>${users(p.id).length}</td><td><span class="${p.ativo===true?"status-ativo":"status-inativo"}">${p.ativo===true?"Ativo":"Inativo"}</span></td><td>${prot?'<span class="acao-propria">Protegido</span>':`<div class="acoes-tabela"><button class="btn-acao destaque" data-pe="${p.id}" type="button">Editar</button><button class="btn-acao" data-ps="${p.id}" type="button">${p.ativo===true?"Inativar":"Reativar"}</button></div>`}</td></tr>`}).join("");document.querySelectorAll("[data-pe]").forEach(b=>on(b,"click",()=>abrir(state.perfis.get(b.dataset.pe))));document.querySelectorAll("[data-ps]").forEach(b=>on(b,"click",()=>statusPerfil(b.dataset.ps)))}
export async function carregarPerfis(){if(lista)lista.innerHTML='<tr><td colspan="6">Carregando perfis...</td></tr>';try{await carregarAdmin();renderPerfis(busca?.value||"")}catch(e){console.error(e);if(lista)lista.innerHTML='<tr><td colspan="6">Não foi possível carregar os perfis.</td></tr>'}}
on($("cardPerfisAcesso"),"click",async()=>{abrirPagina("perfis");await carregarPerfis()});on($("btnNovoPerfil"),"click",()=>abrir());on($("btnCancelarPerfil"),"click",()=>{limpar();box?.classList.add("hidden")});on(busca,"input",()=>renderPerfis(busca.value));
on(form,"submit",async ev=>{ev.preventDefault();const n=nome.value.trim(),d=desc.value.trim(),p=coletar();if([...state.perfis.values()].some(x=>x.id!==editId&&norm(x.nome)===norm(n)))return msg(mensagem,"Já existe um perfil com este nome.");try{msg(mensagem,"Salvando...");if(editId){const atual=state.perfis.get(editId);if(atual?.acessoTotal===true||editId==="administrador")return msg(mensagem,"O perfil Administrador é protegido.");await updateDoc(doc(db,"perfisAcesso",editId),{nome:n,descricao:d,permissoes:p,atualizadoEm:serverTimestamp()});msg(mensagem,"Perfil atualizado com sucesso.",true)}else{await addDoc(collection(db,"perfisAcesso"),{nome:n,descricao:d,grupoId:state.usuario.grupoId,acessoTotal:false,ativo:true,permissoes:p,criadoEm:serverTimestamp()});msg(mensagem,"Perfil criado com sucesso.",true)}await carregarPerfis();await atualizarResumo();setTimeout(()=>{limpar();box?.classList.add("hidden")},600)}catch(e){console.error(e);msg(mensagem,"Não foi possível salvar o perfil.")}});
async function statusPerfil(id){const p=state.perfis.get(id);if(!p||p.acessoTotal===true||id==="administrador")return;const novo=p.ativo!==true;if(!novo&&users(id).some(u=>u.ativo===true))return alert("Este perfil possui usuários ativos. Altere o perfil desses usuários antes de inativá-lo.");if(!confirm(`${novo?"Reativar":"Inativar"} o perfil ${p.nome}?`))return;try{await updateDoc(doc(db,"perfisAcesso",id),{ativo:novo,atualizadoEm:serverTimestamp()});await carregarPerfis();await atualizarResumo()}catch(e){console.error(e);alert("Não foi possível alterar o perfil.")}}
gerar();