import { abrirPagina, admin } from "./core.js";
import { $, esc, msg, permite, state, listarDocumentos, criarDocumento, atualizarDocumento, empresaUnicaSelecionadaId, dataBr, emitirAlteracao } from "./shared.js";
import { confirmarAcaoAdministrativa, atualizarComAuditoria } from "./admin-actions.js";
const TIPOS=["CORRETIVA","MELHORIA","PREVENTIVA"],FUNCOES=["MECÂNICO","ELETRICISTA","OPERADOR","AUTOMAÇÃO"];
const STATUS={aberta:"Aberta",em_execucao:"Em execução",concluida:"Concluída",cancelada:"Cancelada"};
let ordens=[],editId=null,busy=false;
const pode=a=>admin()||permite("ordensServico",a);
const ver=()=>["visualizar","solicitar","executar","supervisionar"].some(pode);
const campo=(id,label,type="text",required=false)=>`<div class="campo"><label for="os${id}">${label}</label><input id="os${id}" type="${type}" ${required?"required":""}></div>`;
const select=(id,label,values,required=false)=>`<div class="campo"><label for="os${id}">${label}</label><select id="os${id}" ${required?"required":""}><option value="">Selecione...</option>${values.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join("")}</select></div>`;
const localIso=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
function montar(){if($("pagina-ordensservico"))return;const main=document.querySelector("main.conteudo");if(!main)return;const s=document.createElement("section");s.id="pagina-ordensservico";s.className="pagina hidden production-page";s.innerHTML=`<div class="pagina-cabecalho production-head"><div><span class="eyebrow">INDÚSTRIA</span><h2>Ordens de Serviço</h2><p>Solicitação, execução e conclusão dos serviços da fábrica.</p></div><div class="acoes-cabecalho"><button class="btn-primario" id="osNova" type="button">+ Solicitar serviço</button><button class="btn-secundario" id="osAtualizar" type="button">Atualizar</button></div></div><div id="osAviso" class="modulo-aviso hidden"></div><div class="production-kpis"><div class="kpi-card"><span>Em aberto</span><strong id="osKpiAbertas">—</strong></div><div class="kpi-card"><span>Em execução</span><strong id="osKpiExecucao">—</strong></div><div class="kpi-card"><span>Concluídas</span><strong id="osKpiConcluidas">—</strong></div><div class="kpi-card"><span>Com parada de produção</span><strong id="osKpiParada">—</strong></div></div>
<section class="form-card hidden" id="osFormBox"><div class="form-card-titulo"><div><h3 id="osFormTitulo">Nova solicitação</h3><p>Campos de execução são preenchidos ao iniciar e concluir o serviço.</p></div></div><form id="osForm"><div class="form-grid form-grid-3">${campo("Numero","Número da OS","text",true)}${select("Tipo","Tipo de serviço",TIPOS,true)}${campo("Solicitante","Solicitante","text",true)}${campo("DataSolicitacao","Data da solicitação","date",true)}${select("Funcao","Função",FUNCOES,true)}${campo("Equipamento","Equipamento","text",true)}<div class="campo"><label for="osDescricao">Serviço solicitado</label><textarea id="osDescricao" required></textarea></div>${campo("Executante","Executante")}${campo("Inicio","Data de início","date")}${campo("Fim","Data de conclusão","date")}<div class="campo"><label for="osRealizado">Serviço realizado</label><textarea id="osRealizado"></textarea></div><div class="campo"><label><input id="osParada" type="checkbox"> Houve parada de produção</label></div><div class="campo"><label><input id="osPeca" type="checkbox"> Houve troca de peça</label></div><div class="campo"><label for="osObservacao">Observação</label><textarea id="osObservacao"></textarea></div></div><div class="form-acoes"><button id="osCancelar" class="btn-secundario" type="button">Cancelar</button><button class="btn-primario" type="submit">Salvar OS</button></div><p id="osMensagem" class="mensagem-form"></p></form></section>
<section class="lista-card"><div class="lista-cabecalho production-toolbar"><div><h3>Acompanhamento das OS</h3><p>O histórico permanece após conclusão ou cancelamento.</p></div><div class="production-filtros"><input id="osBusca" type="search" placeholder="OS, equipamento, solicitante"><select id="osFiltroStatus"><option value="">Todos os status</option>${Object.entries(STATUS).map(([k,v])=>`<option value="${k}">${v}</option>`).join("")}</select></div></div><div class="tabela-container"><table class="tabela"><thead><tr><th>Nº OS</th><th>Solicitação</th><th>Equipamento / serviço</th><th>Tipo</th><th>Status</th><th>Execução</th><th>Ações</th></tr></thead><tbody id="osLista"></tbody></table></div></section>`;main.appendChild(s);$("osNova").addEventListener("click",novo);$("osAtualizar").addEventListener("click",carregar);$("osCancelar").addEventListener("click",()=>{$("osFormBox").classList.add("hidden");limpar()});$("osForm").addEventListener("submit",salvar);$("osBusca").addEventListener("input",render);$("osFiltroStatus").addEventListener("change",render)}
function menu(){const nav=document.querySelector(".sidebar-menu");if(!nav)return;let b=$("menuOrdensServico");if(!b){b=document.createElement("button");b.id="menuOrdensServico";b.className="menu-item hidden";b.dataset.pagina="ordensservico";b.type="button";b.textContent="Ordens de Serviço";nav.appendChild(b);b.addEventListener("click",e=>{e.preventDefault();e.stopImmediatePropagation();if(!ver())return;abrirPagina("ordensservico");carregar()},true)}b.classList.toggle("hidden",!ver())}
function limpar(){editId=null;$("osForm").reset();$("osDataSolicitacao").value=localIso();$("osFormTitulo").textContent="Nova solicitação";msg($("osMensagem"),"")}
function novo(){if(!pode("solicitar"))return;if(!empresaUnicaSelecionadaId())return alert("Selecione apenas uma empresa no cabeçalho.");limpar();$("osFormBox").classList.remove("hidden");$("osFormBox").scrollIntoView({behavior:"smooth",block:"start"})}
function abrirEdicao(id){const x=ordens.find(y=>y.id===id);if(!x||!pode("executar")||x.status==="cancelada"||(!admin()&&x.status==="concluida"))return;if(x.empresaId!==empresaUnicaSelecionadaId())return alert("Selecione a empresa da OS para editar.");editId=id;const campos={Numero:"numero",Tipo:"tipo",Solicitante:"solicitante",DataSolicitacao:"dataSolicitacao",Funcao:"funcao",Equipamento:"equipamento",Descricao:"descricao",Executante:"executante",Inicio:"dataInicio",Fim:"dataFim",Realizado:"realizado",Observacao:"observacao"};Object.entries(campos).forEach(([id,key])=>$("os"+id).value=x[key]||"");$("osParada").checked=x.paradaProducao===true;$("osPeca").checked=x.trocaPeca===true;$("osFormTitulo").textContent=`Executar OS ${x.numero}`;$("osFormBox").classList.remove("hidden");$("osFormBox").scrollIntoView({behavior:"smooth",block:"start"})}
function payload(){const g=id=>String($("os"+id).value||"").trim();return{numero:g("Numero"),tipo:g("Tipo"),solicitante:g("Solicitante"),dataSolicitacao:g("DataSolicitacao"),funcao:g("Funcao"),equipamento:g("Equipamento"),descricao:g("Descricao"),executante:g("Executante"),dataInicio:g("Inicio"),dataFim:g("Fim"),realizado:g("Realizado"),paradaProducao:$("osParada").checked,trocaPeca:$("osPeca").checked,observacao:g("Observacao")}}
function validar(d){if(!d.numero||!TIPOS.includes(d.tipo)||!d.solicitante||!d.dataSolicitacao||!FUNCOES.includes(d.funcao)||!d.equipamento||!d.descricao)throw new Error("Preencha os dados obrigatórios da solicitação.");if(d.dataFim&&!d.dataInicio)throw new Error("Informe o início antes da conclusão.");if(d.dataFim&&d.dataFim<d.dataInicio)throw new Error("A conclusão não pode ser anterior ao início.");if(d.dataInicio&&!d.executante)throw new Error("Informe o executante ao iniciar.");if(d.dataFim&&!d.realizado)throw new Error("Descreva o serviço realizado ao concluir.");d.status=d.dataFim?"concluida":d.dataInicio?"em_execucao":"aberta";return d}
async function salvar(e){e.preventDefault();const emp=empresaUnicaSelecionadaId();if(!emp)return alert("Selecione apenas uma empresa no cabeçalho.");try{const d=validar(payload());if(!editId&&(d.status!=="aberta"||!pode("solicitar")))throw new Error("A solicitação deve começar em aberto.");if(editId){const x=ordens.find(y=>y.id===editId);if(!pode("executar")||!x||x.empresaId!==emp||x.status==="cancelada"||(!admin()&&x.status==="concluida"))throw new Error("Edição não autorizada.");if(d.numero!==x.numero||d.dataSolicitacao!==x.dataSolicitacao)throw new Error("Número e data de solicitação não podem ser alterados.");await atualizarDocumento("ordensServico",editId,d)}else{if(ordens.some(x=>x.empresaId===emp&&x.numero.toUpperCase()===d.numero.toUpperCase()&&x.status!=="cancelada"))throw new Error("Já existe OS com esse número na empresa.");await criarDocumento("ordensServico",{...d,empresaId:emp,origem:"sig",solicitadoPor:state.usuario?.id||""})}$("osFormBox").classList.add("hidden");limpar();emitirAlteracao("ordensservico");await carregar()}catch(err){console.error(err);msg($("osMensagem"),err.message||"Não foi possível salvar.")}}
function render(){if(!$("osLista"))return;const busca=$("osBusca").value.toLocaleLowerCase("pt-BR"),status=$("osFiltroStatus").value,arr=ordens.filter(x=>(!status||x.status===status)&&[x.numero,x.equipamento,x.solicitante,x.descricao].some(v=>String(v||"").toLocaleLowerCase("pt-BR").includes(busca)));$("osKpiAbertas").textContent=String(ordens.filter(x=>x.status==="aberta").length);$("osKpiExecucao").textContent=String(ordens.filter(x=>x.status==="em_execucao").length);$("osKpiConcluidas").textContent=String(ordens.filter(x=>x.status==="concluida").length);$("osKpiParada").textContent=String(ordens.filter(x=>x.status!=="cancelada"&&x.paradaProducao).length);$("osLista").innerHTML=arr.sort((a,b)=>String(b.dataSolicitacao).localeCompare(String(a.dataSolicitacao))).map(x=>`<tr class="${x.status==="cancelada"?"sig-admin-estornado":""}"><td>${esc(x.numero)}</td><td>${dataBr(x.dataSolicitacao)}<small>${esc(x.solicitante)}</small></td><td><strong>${esc(x.equipamento)}</strong><small>${esc(x.descricao)}</small></td><td>${esc(x.tipo)}</td><td>${esc(STATUS[x.status]||x.status)}</td><td>${x.dataInicio?`${dataBr(x.dataInicio)}${x.dataFim?` → ${dataBr(x.dataFim)}`:""}`:"—"}</td><td>${pode("executar")&&!["concluida","cancelada"].includes(x.status)?`<button class="btn-acao destaque" data-os-edit="${esc(x.id)}">${x.status==="aberta"?"Iniciar":"Concluir"}</button>`:""}${admin()&&x.status!=="cancelada"?`<button class="btn-acao perigo" data-os-cancel="${esc(x.id)}">Cancelar ADM</button>`:""}</td></tr>`).join("")||'<tr><td colspan="7">Nenhuma OS encontrada.</td></tr>';document.querySelectorAll("[data-os-edit]").forEach(b=>b.addEventListener("click",()=>abrirEdicao(b.dataset.osEdit)));document.querySelectorAll("[data-os-cancel]").forEach(b=>b.addEventListener("click",()=>cancelar(b.dataset.osCancel)))}
async function carregar(){if(busy||!ver())return;busy=true;try{ordens=await listarDocumentos("ordensServico");render();$("osAviso").classList.add("hidden")}catch(e){console.error(e);$("osAviso").textContent="Não foi possível consultar as OS. Confira permissões e Rules publicadas.";$("osAviso").classList.remove("hidden")}finally{busy=false}}
async function cancelar(id){if(!admin())return;const x=ordens.find(v=>v.id===id);if(!x||x.status==="cancelada")return;const ok=await confirmarAcaoAdministrativa({titulo:"Cancelar Ordem de Serviço",descricao:`OS ${x.numero} permanecerá no histórico.`,motivoLabel:"Motivo obrigatório",confirmarTexto:"Cancelar OS",perigosa:true});if(!ok)return;try{await atualizarComAuditoria({colecao:"ordensServico",id,empresaId:x.empresaId,modulo:"ordensServico",acao:"cancelamento",motivo:ok.motivo,resumo:`Cancelamento OS ${x.numero}`,snapshotAntes:x,alteracoes:{status:"cancelada",motivoCancelamento:ok.motivo,canceladoPor:state.usuario?.id||"",canceladoEm:new Date().toISOString()}});emitirAlteracao("ordensservico");await carregar()}catch(e){console.error(e);alert("Não foi possível cancelar a OS.")}}
function instalar(){if(!document.querySelector('link[href^="production.css"]')){const l=document.createElement("link");l.rel="stylesheet";l.href="production.css?v=1";document.head.appendChild(l)}montar();menu();$("osNova")?.classList.toggle("hidden",!pode("solicitar"))}
instalar();window.addEventListener("sig:ready",()=>{instalar();if(ver())carregar()});window.addEventListener("sig:empresa-contexto",()=>{if(!$("pagina-ordensservico")?.classList.contains("hidden"))carregar()});window.addEventListener("sig:data-changed",e=>{if(e.detail?.modulo==="ordensservico"&&!$("pagina-ordensservico")?.classList.contains("hidden"))carregar()});
