import { initializeApp } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js";
import { getAuth, createUserWithEmailAndPassword, deleteUser, sendPasswordResetEmail, signOut } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js";
import { setDoc, updateDoc, doc, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";
import { $, on, esc, norm, msg, auth, db, state, firebaseConfigPublic, abrirPagina, carregarAdmin, atualizarResumo } from "./core.js";

const appNovo=initializeApp(firebaseConfigPublic,"sig-criacao-usuarios");
const authNovo=getAuth(appNovo);
let editId=null;
const form=$("formUsuario"),box=$("formUsuarioContainer"),titulo=$("tituloFormUsuario"),descricao=$("descricaoFormUsuario"),nome=$("usuarioNome"),email=$("usuarioEmail"),senha=$("usuarioSenha"),campoSenha=$("campoSenhaNovoUsuario"),perfil=$("usuarioPerfil"),empresa=$("usuarioEmpresaPrincipal"),global=$("usuarioAcessoGlobal"),listaEmpresas=$("listaEmpresasAcesso"),mensagem=$("mensagemUsuario"),lista=$("listaUsuarios"),qtd=$("quantidadeUsuarios"),busca=$("buscaUsuario");

const ativosEmpresas=()=>[...state.empresas.values()].filter(e=>e.ativo===true).sort((a,b)=>String(a.nomeFantasia||a.razaoSocial||"").localeCompare(String(b.nomeFantasia||b.razaoSocial||""),"pt-BR"));
const ativosPerfis=()=>[...state.perfis.values()].filter(p=>p.ativo===true).sort((a,b)=>String(a.nome||"").localeCompare(String(b.nome||""),"pt-BR"));
function preencher(){const es=ativosEmpresas(),ps=ativosPerfis();if(empresa)empresa.innerHTML='<option value="">Selecione...</option>'+es.map(e=>`<option value="${e.id}">${esc(e.nomeFantasia||e.razaoSocial)}</option>`).join("");if(perfil)perfil.innerHTML='<option value="">Selecione...</option>'+ps.map(p=>`<option value="${p.id}">${esc(p.nome||p.id)}</option>`).join("");if(listaEmpresas)listaEmpresas.innerHTML=es.map(e=>`<label class="checkbox-card"><input type="checkbox" class="checkbox-empresa-acesso" value="${e.id}"><span>${esc(e.nomeFantasia||e.razaoSocial)}</span></label>`).join("")}
function sinc(){const id=empresa?.value;if(!id)return;const c=document.querySelector(`.checkbox-empresa-acesso[value="${id}"]`);if(c)c.checked=true}
function estadoAcessos(){const g=global?.checked===true;document.querySelectorAll(".checkbox-empresa-acesso").forEach(c=>c.disabled=g);if(listaEmpresas)listaEmpresas.style.opacity=g?".55":"1"}
function limpar(){editId=null;form?.reset();if(email)email.disabled=false;if(senha)senha.required=false;campoSenha?.classList.remove("hidden");if(titulo)titulo.textContent="Novo usuário";if(descricao)descricao.textContent="Crie o acesso e vincule perfil e empresas.";msg(mensagem,"");preencher();estadoAcessos()}
function abrir(u=null){limpar();if(u){editId=u.id;if(titulo)titulo.textContent="Editar usuário";if(descricao)descricao.textContent="A conta de autenticação permanece vinculada ao e-mail atual.";campoSenha?.classList.add("hidden");email.disabled=true;nome.value=u.nome||"";email.value=u.email||"";perfil.value=u.perfilId||"";empresa.value=u.empresaId||"";global.checked=u.acessoGlobal===true;const ac=new Set(Array.isArray(u.empresasAcesso)?u.empresasAcesso:u.empresaId?[u.empresaId]:[]);document.querySelectorAll(".checkbox-empresa-acesso").forEach(c=>c.checked=ac.has(c.value));sinc();estadoAcessos()}else senha.required=true;box?.classList.remove("hidden");nome?.focus()}
const nomeEmpresa=id=>{const e=state.empresas.get(id);return e?.nomeFantasia||e?.razaoSocial||"-"};
const nomePerfil=id=>state.perfis.get(id)?.nome||id||"-";

export function renderUsuarios(filtro=""){const t=norm(filtro);const arr=[...state.usuarios.values()].filter(u=>!t||[u.nome,u.email].some(v=>norm(v).includes(t))).sort((a,b)=>String(a.nome||"").localeCompare(String(b.nome||""),"pt-BR"));if(qtd)qtd.textContent=`${state.usuarios.size} usuário(s) cadastrado(s)`;if(!lista)return;if(!arr.length){lista.innerHTML='<tr><td colspan="6">Nenhum usuário encontrado.</td></tr>';return}lista.innerHTML=arr.map(u=>{const proprio=auth.currentUser?.uid===u.id;const acesso=u.acessoGlobal===true?"Grupo completo":`${new Set([u.empresaId,...(u.empresasAcesso||[])].filter(Boolean)).size} empresa(s)`;return`<tr><td class="celula-principal"><strong>${esc(u.nome)}</strong><span>${esc(u.email)}</span></td><td>${esc(nomeEmpresa(u.empresaId))}</td><td>${esc(nomePerfil(u.perfilId))}</td><td>${esc(acesso)}</td><td><span class="${u.ativo===true?"status-ativo":"status-inativo"}">${u.ativo===true?"Ativo":"Inativo"}</span></td><td><div class="acoes-tabela">${proprio?'<span class="acao-propria">Usuário atual</span>':`<button class="btn-acao destaque" data-ue="${u.id}" type="button">Editar</button><button class="btn-acao" data-us="${u.id}" type="button">${u.ativo===true?"Desativar":"Ativar"}</button>`}<button class="btn-acao" data-ur="${u.id}" type="button">Redefinir senha</button></div></td></tr>`}).join("");document.querySelectorAll("[data-ue]").forEach(b=>on(b,"click",()=>abrir(state.usuarios.get(b.dataset.ue))));document.querySelectorAll("[data-us]").forEach(b=>on(b,"click",()=>status(b.dataset.us)));document.querySelectorAll("[data-ur]").forEach(b=>on(b,"click",()=>reset(b.dataset.ur)))}
export async function carregarUsuarios(){if(lista)lista.innerHTML='<tr><td colspan="6">Carregando usuários...</td></tr>';try{await carregarAdmin();preencher();renderUsuarios(busca?.value||"")}catch(e){console.error(e);if(lista)lista.innerHTML='<tr><td colspan="6">Não foi possível carregar os usuários.</td></tr>'}}

on($("cardUsuarios"),"click",async()=>{abrirPagina("usuarios");await carregarUsuarios()});on($("btnNovoUsuario"),"click",async()=>{await carregarAdmin();abrir()});on($("btnCancelarUsuario"),"click",()=>{limpar();box?.classList.add("hidden")});on(empresa,"change",sinc);on(global,"change",estadoAcessos);on(busca,"input",()=>renderUsuarios(busca.value));
const selecionadas=()=>[...document.querySelectorAll(".checkbox-empresa-acesso:checked")].map(c=>c.value);
on(form,"submit",async ev=>{ev.preventDefault();const n=nome.value.trim(),em=email.value.trim().toLowerCase(),pid=perfil.value,eid=empresa.value,g=global.checked;sinc();const acessos=[...new Set([...selecionadas(),eid].filter(Boolean))];if(!g&&!acessos.length)return msg(mensagem,"Selecione ao menos uma empresa permitida.");if(!pid||!eid)return msg(mensagem,"Selecione o perfil e a empresa principal.");try{if(editId){msg(mensagem,"Salvando alterações...");await updateDoc(doc(db,"usuarios",editId),{nome:n,perfilId:pid,empresaId:eid,acessoGlobal:g,empresasAcesso:acessos,atualizadoEm:serverTimestamp()});msg(mensagem,"Usuário atualizado com sucesso.",true)}else{if((senha.value||"").length<6)return msg(mensagem,"A senha inicial precisa ter pelo menos 6 caracteres.");if([...state.usuarios.values()].some(u=>norm(u.email)===norm(em)))return msg(mensagem,"Já existe um usuário cadastrado com este e-mail.");msg(mensagem,"Criando acesso...");let cred=null;try{cred=await createUserWithEmailAndPassword(authNovo,em,senha.value);await setDoc(doc(db,"usuarios",cred.user.uid),{nome:n,email:em,perfilId:pid,empresaId:eid,empresasAcesso:acessos,acessoGlobal:g,grupoId:state.usuario.grupoId,ativo:true,criadoEm:serverTimestamp()})}catch(e){if(cred?.user){try{await deleteUser(cred.user)}catch{}}throw e}finally{try{await signOut(authNovo)}catch{}}msg(mensagem,"Usuário criado com sucesso.",true)}await carregarUsuarios();await atualizarResumo();setTimeout(()=>{limpar();box?.classList.add("hidden")},700)}catch(e){console.error(e);const m={"auth/email-already-in-use":"Este e-mail já possui uma conta.","auth/invalid-email":"O e-mail informado é inválido.","auth/weak-password":"A senha inicial é muito fraca."};msg(mensagem,m[e.code]||"Não foi possível salvar o usuário.")}});
async function status(id){const u=state.usuarios.get(id);if(!u||auth.currentUser?.uid===id)return;const novo=u.ativo!==true;if(!confirm(`${novo?"Ativar":"Desativar"} ${u.nome||u.email}?`))return;try{await updateDoc(doc(db,"usuarios",id),{ativo:novo,atualizadoEm:serverTimestamp()});await carregarUsuarios();await atualizarResumo()}catch(e){console.error(e);alert("Não foi possível alterar o status do usuário.")}}
async function reset(id){const u=state.usuarios.get(id);if(!u?.email)return;if(!confirm(`Enviar e-mail de redefinição de senha para ${u.email}?`))return;try{await sendPasswordResetEmail(auth,u.email);alert("E-mail de redefinição enviado.")}catch(e){console.error(e);alert("Não foi possível enviar a redefinição de senha.")}}
