import { abrirPagina, admin } from "./core.js";
import { $, esc, msg, permite, state, listarDocumentos, criarDocumento, atualizarDocumento, empresaUnicaSelecionadaId, dataBr, emitirAlteracao } from "./shared.js";
import { confirmarAcaoAdministrativa, atualizarComAuditoria } from "./admin-actions.js";
const SETORES=["ADM","LAJE","COMERCIAL","LOGISTICA","PRODUÇÃO","MOURÃO","MANUTENÇÃO"];
const MOD={
  horas:{area:"rh",titulo:"Horas extras",colecao:"rhHorasExtras",campos:[["data","Data","date",true],["setor","Setor","select",true,["LAJE","MANUTENÇÃO","MOURÃO","LOGISTICA","PRODUÇÃO"]],["horas50","Horas 50%","number",false],["horas100","Horas 100%","number",false],["valor","Valor (R$)","number",false]]},
  quadro:{area:"rh",titulo:"Quadro de funcionários",colecao:"rhQuadro",campos:[["data","Data do registro","date",true],["admissoes","Admissões","integer"],["demissoes","Demissões","integer"],["atestados","Atestados","integer"],["afastamentos","Afastamentos >15 dias","integer"]]},
  setores:{area:"rh",titulo:"Ativos por setor",colecao:"rhAtivosSetor",campos:[["data","Data","date",true],["setor","Setor","select",true,SETORES],["quantidade","Quantidade","integer",true]]},
  ativos:{area:"rh",titulo:"Ativos no mês",colecao:"rhAtivosMes",campos:[["data","Data","date",true],["quantidade","Quantidade","integer",true]]},
  incidentes:{area:"seguranca",titulo:"Ocorrências",colecao:"segurancaOcorrencias",campos:[["data","Data","date",true],["tipo","Tipo","select",true,["ACIDENTE DE TRABALHO","ACIDENTE DE TRAJETO"]],["quantidade","Quantidade","integer",true]]},
  treinamentos:{area:"seguranca",titulo:"Treinamentos",colecao:"segurancaTreinamentos",campos:[["setor","Setor","select",true,["Produção","Comercial","Logistica","Financeiro","RH"]],["tipoTreinamento","Tipo de treinamento","text",true],["data","Data de realização","date",true],["nome","Nome do treinamento","text",true],["local","Local","select",false,["SALVADOR","SERRA"]],["cargaHoraria","Carga horária","number"],["horaInicio","Hora de início","time"],["instrutor","Instrutor / facilitador","text"],["custoTotal","Custo total (R$)","number"],["publico","Público","select",true,["MOTORISTAS","GESTORES","TODOS COLABORADORES","ADMINISTRATIVO","TODOS"]]]}
};
const AREAS={rh:{nome:"RH",chaves:["horas","quadro","setores","ativos"]},seguranca:{nome:"Segurança do Trabalho",chaves:["incidentes","treinamentos"]}};
let ativo={rh:"horas",seguranca:"incidentes"},dados=Object.fromEntries(Object.keys(MOD).map(k=>[k,[]])),edicao=null,busy={rh:false,seguranca:false};
const perm=(k,a)=>admin()||permite("mod"+k,a);
const ver=k=>["visualizar","lancar","editar"].some(a=>perm(k,a));
const localIso=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
const num=v=>Number(v||0);
function campo([id,label,t,required,options=[]]){const tag=t==="select"?`<select id="work${id}" ${required?"required":""}><option value="">Selecione...</option>${options.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join("")}</select>`:`<input id="work${id}" type="${t==="integer"?"number":t}" ${["number","integer"].includes(t)?`min="0" step="${t==="integer"?"1":"any"}"`:""} ${required?"required":""}>`;return `<div class="campo"><label for="work${id}">${label}</label>${tag}</div>`}
function montar(area){if($("pagina-"+area))return;const main=document.querySelector("main.conteudo");if(!main)return;const cfg=AREAS[area],s=document.createElement("section");s.id="pagina-"+area;s.className="pagina hidden production-page";s.innerHTML=`<div class="pagina-cabecalho production-head"><div><span class="eyebrow">PESSOAS E OPERAÇÃO</span><h2>${cfg.nome}</h2><p>${area==="rh"?"Horas, movimentação do quadro e posições de funcionários por competência.":"Ocorrências e treinamentos registrados por data e setor."}</p></div><div class="acoes-cabecalho"><button id="${area}Novo" class="btn-primario" type="button">+ Novo registro</button><button id="${area}Atualizar" class="btn-secundario" type="button">Atualizar</button></div></div><div id="${area}Aviso" class="modulo-aviso hidden"></div><div class="fleet-tabs">${cfg.chaves.map(k=>`<button type="button" class="fleet-tab" data-work-tab="${k}">${MOD[k].titulo}</button>`).join("")}</div><div class="production-kpis"><div class="kpi-card"><span>Registros no ano</span><strong id="${area}KpiRegistros">—</strong></div><div class="kpi-card"><span id="${area}KpiLabel">Total</span><strong id="${area}KpiTotal">—</strong></div></div><section id="${area}FormBox" class="form-card hidden"><div class="form-card-titulo"><h3 id="${area}FormTitulo">Novo registro</h3></div><form id="${area}Form"><div id="${area}Campos" class="form-grid form-grid-3"></div><div class="form-acoes"><button id="${area}Cancelar" class="btn-secundario" type="button">Cancelar</button><button class="btn-primario" type="submit">Salvar</button></div><p id="${area}Mensagem" class="mensagem-form"></p></form></section><section class="lista-card"><div class="lista-cabecalho production-toolbar"><div><h3 id="${area}Historico">Histórico</h3><p>Registros estornados permanecem visíveis e não entram nos totais.</p></div><select id="${area}Ano" aria-label="Ano"></select></div><div class="tabela-container"><table class="tabela"><thead id="${area}Cabecalho"></thead><tbody id="${area}Lista"></tbody></table></div></section>`;main.appendChild(s);s.querySelectorAll("[data-work-tab]").forEach(b=>b.addEventListener("click",()=>trocar(area,b.dataset.workTab)));$(area+"Novo").addEventListener("click",()=>novo(area));$(area+"Atualizar").addEventListener("click",()=>carregar(area));$(area+"Cancelar").addEventListener("click",()=>{$(area+"FormBox").classList.add("hidden");edicao=null});$(area+"Form").addEventListener("submit",e=>salvar(area,e));$(area+"Ano").addEventListener("change",()=>render(area));trocar(area,ativo[area])}
function menu(area){const nav=document.querySelector(".sidebar-menu");if(!nav)return;let b=$("menu"+area);if(!b){b=document.createElement("button");b.id="menu"+area;b.className="menu-item hidden";b.dataset.pagina=area;b.type="button";b.textContent=AREAS[area].nome;nav.appendChild(b);b.addEventListener("click",e=>{e.preventDefault();e.stopImmediatePropagation();if(!AREAS[area].chaves.some(ver))return;abrirPagina(area);carregar(area)},true)}b.classList.toggle("hidden",!AREAS[area].chaves.some(ver))}
function trocar(area,k){if(!ver(k))k=AREAS[area].chaves.find(ver);if(!k)return;ativo[area]=k;edicao=null;$(area+"FormBox")?.classList.add("hidden");$(area+"Campos").innerHTML=MOD[k].campos.map(campo).join("");document.querySelectorAll(`#pagina-${area} [data-work-tab]`).forEach(b=>{b.classList.toggle("ativo",b.dataset.workTab===k);b.classList.toggle("hidden",!ver(b.dataset.workTab))});$(area+"Novo").classList.toggle("hidden",!perm(k,"lancar"));$(area+"Historico").textContent=MOD[k].titulo;render(area)}
function novo(area){const k=ativo[area];if(!perm(k,"lancar"))return;if(!empresaUnicaSelecionadaId())return alert("Selecione apenas uma empresa no cabeçalho.");edicao=null;$(area+"Form").reset();if($("workdata"))$("workdata").value=localIso();$(area+"FormTitulo").textContent=`Novo registro · ${MOD[k].titulo}`;msg($(area+"Mensagem"),"");$(area+"FormBox").classList.remove("hidden");$(area+"FormBox").scrollIntoView({behavior:"smooth",block:"start"})}
function editarRegistro(area,id){const k=ativo[area],x=dados[k].find(y=>y.id===id);if(!x||x.status!=="ativo"||!perm(k,"editar"))return;if(x.empresaId!==empresaUnicaSelecionadaId())return alert("Selecione a empresa do registro.");edicao=id;for(const [key,,t] of MOD[k].campos){const f=$("work"+key);f.value=x[key]??""}$(area+"FormTitulo").textContent=`Editar · ${MOD[k].titulo}`;$(area+"FormBox").classList.remove("hidden");$(area+"FormBox").scrollIntoView({behavior:"smooth",block:"start"})}
function payload(k){const d={};for(const [key,,t,required,options] of MOD[k].campos){const raw=String($("work"+key)?.value||"").trim();if(required&&!raw)throw new Error("Preencha os campos obrigatórios.");if(t==="select"&&raw&&!(options||[]).includes(raw))throw new Error("Opção inválida: "+key);if(t==="number"||t==="integer"){const v=raw?Number(raw):0;if(!Number.isFinite(v)||v<0||(t==="integer"&&!Number.isSafeInteger(v)))throw new Error("Valor inválido: "+key);d[key]=v}else d[key]=raw}return d}
async function salvar(area,e){e.preventDefault();const k=ativo[area],emp=empresaUnicaSelecionadaId();if(!emp)return alert("Selecione apenas uma empresa no cabeçalho.");try{const d=payload(k);msg($(area+"Mensagem"),"Salvando...");if(edicao){const x=dados[k].find(y=>y.id===edicao);if(!x||x.empresaId!==emp||x.status!=="ativo"||!perm(k,"editar"))throw new Error("Edição não autorizada.");await atualizarDocumento(MOD[k].colecao,edicao,d)}else{if(!perm(k,"lancar"))throw new Error("Sem permissão.");await criarDocumento(MOD[k].colecao,{...d,empresaId:emp,status:"ativo",origem:"sig",registradoPor:state.usuario?.id||""})}$(area+"FormBox").classList.add("hidden");edicao=null;emitirAlteracao(area);await carregar(area)}catch(err){console.error(err);msg($(area+"Mensagem"),err.message||"Não foi possível salvar.")}}
function render(area){if(!$(area+"Lista"))return;const k=ativo[area],ano=$(area+"Ano")?.value||String(new Date().getFullYear()),todos=dados[k].filter(x=>String(x.data||"").startsWith(ano)),arr=todos.filter(x=>x.status!=="estornado");let total=0,label="Total";if(k==="horas"){total=arr.reduce((s,x)=>s+num(x.horas50)+num(x.horas100),0);label="Horas extras"}else if(k==="quadro"){total=arr.reduce((s,x)=>s+num(x.admissoes)-num(x.demissoes),0);label="Admissões − demissões"}else if(k==="treinamentos"){total=arr.reduce((s,x)=>s+num(x.cargaHoraria),0);label="Carga horária"}else if(k==="ativos"){const ultimo=[...arr].sort((a,b)=>String(b.data).localeCompare(String(a.data)))[0];total=num(ultimo?.quantidade);label="Ativos na última posição"}else if(k==="setores"){const pos=new Map();[...arr].sort((a,b)=>String(b.data).localeCompare(String(a.data))).forEach(x=>{if(!pos.has(x.setor))pos.set(x.setor,num(x.quantidade))});total=[...pos.values()].reduce((s,v)=>s+v,0);label="Última posição por setor"}else{total=arr.reduce((s,x)=>s+num(x.quantidade),0);label="Quantidade"}$(area+"KpiRegistros").textContent=String(arr.length);$(area+"KpiLabel").textContent=label;$(area+"KpiTotal").textContent=total.toLocaleString("pt-BR",{maximumFractionDigits:2});$(area+"Cabecalho").innerHTML=`<tr>${MOD[k].campos.map(([,l])=>`<th>${esc(l)}</th>`).join("")}<th>Situação</th><th>Ações</th></tr>`;$(area+"Lista").innerHTML=todos.sort((a,b)=>String(b.data).localeCompare(String(a.data))).map(x=>`<tr class="${x.status==="estornado"?"sig-admin-estornado":""}">${MOD[k].campos.map(([key,,t])=>`<td>${t==="date"?dataBr(x[key]):esc(x[key]??"—")}</td>`).join("")}<td>${x.status==="estornado"?"Estornado":"Ativo"}</td><td>${x.status!=="estornado"&&perm(k,"editar")?`<button type="button" class="btn-acao destaque" data-work-edit="${esc(x.id)}">Editar</button>`:""}${x.status!=="estornado"&&admin()?`<button type="button" class="btn-acao perigo" data-work-estorno="${esc(x.id)}">Estornar ADM</button>`:""}</td></tr>`).join("")||`<tr><td colspan="${MOD[k].campos.length+2}">Nenhum registro encontrado.</td></tr>`;document.querySelectorAll(`#pagina-${area} [data-work-edit]`).forEach(b=>b.addEventListener("click",()=>editarRegistro(area,b.dataset.workEdit)));document.querySelectorAll(`#pagina-${area} [data-work-estorno]`).forEach(b=>b.addEventListener("click",()=>estornar(area,b.dataset.workEstorno)))}
async function carregar(area){if(busy[area]||!AREAS[area].chaves.some(ver))return;busy[area]=true;try{const pares=await Promise.all(AREAS[area].chaves.map(async k=>[k,ver(k)?await listarDocumentos(MOD[k].colecao):[]]));pares.forEach(([k,v])=>dados[k]=v);const sel=$(area+"Ano"),anterior=sel.value||String(new Date().getFullYear()),anos=[...new Set([new Date().getFullYear(),...pares.flatMap(([,v])=>v).map(x=>Number(String(x.data||"").slice(0,4))).filter(Boolean)])].sort((a,b)=>b-a);sel.innerHTML=anos.map(a=>`<option value="${a}">${a}</option>`).join("");if(anos.map(String).includes(anterior))sel.value=anterior;render(area);$(area+"Aviso").classList.add("hidden")}catch(e){console.error(e);$(area+"Aviso").textContent="Não foi possível carregar os registros. Confira o perfil e as Rules publicadas.";$(area+"Aviso").classList.remove("hidden")}finally{busy[area]=false}}
async function estornar(area,id){if(!admin())return;const k=ativo[area],x=dados[k].find(y=>y.id===id);if(!x||x.status!=="ativo")return;const ok=await confirmarAcaoAdministrativa({titulo:"Estornar registro",descricao:`O registro de ${MOD[k].titulo} em ${dataBr(x.data)} permanecerá no histórico.`,motivoLabel:"Motivo obrigatório",confirmarTexto:"Estornar",perigosa:true});if(!ok)return;try{await atualizarComAuditoria({colecao:MOD[k].colecao,id,empresaId:x.empresaId,modulo:"mod"+k,acao:"estorno",motivo:ok.motivo,resumo:`Estorno ${MOD[k].titulo}`,snapshotAntes:x,alteracoes:{status:"estornado",motivoEstorno:ok.motivo,estornadoPor:state.usuario?.id||"",estornadoEm:new Date().toISOString()}});emitirAlteracao(area);await carregar(area)}catch(e){console.error(e);alert("Não foi possível estornar.")}}
function instalar(){if(!document.querySelector('link[href^="production.css"]')){const l=document.createElement("link");l.rel="stylesheet";l.href="production.css?v=1";document.head.appendChild(l)}for(const a of Object.keys(AREAS)){montar(a);menu(a);if($(a+"Campos"))trocar(a,ativo[a])}}
instalar();window.addEventListener("sig:ready",()=>{instalar();for(const a of Object.keys(AREAS))if(AREAS[a].chaves.some(ver))carregar(a)});window.addEventListener("sig:empresa-contexto",()=>{for(const a of Object.keys(AREAS))if(!$("pagina-"+a)?.classList.contains("hidden"))carregar(a)});window.addEventListener("sig:data-changed",e=>{const a=e.detail?.modulo;if(AREAS[a]&&!$("pagina-"+a)?.classList.contains("hidden"))carregar(a)});
